isl-org/Open3D

src/Tools/ViewGeometry.cpp

macOS High Serra
clang-900.0.39.2
Python 2.6
Warning message:
```
/Users/qianyizh/Desktop/Open3D/src/Tools/ViewGeometry.cpp:106:3: warning: bool literal returned from 'main' [-Wmain]
return false;
^      ~~~~~
```

Fix warning in compilation by LLVM

---

docs/getting_started.rst
src/Core/Utility/Timer.cpp
src/Core/Utility/Timer.h

Resolves #149.

---

src/Core/Geometry/Image.cpp
src/Core/Geometry/Image.h

Resolves #156.

---

src/Core/Geometry/Image.cpp
src/Core/Geometry/Image.h

Resolves #158.

---

src/Core/Geometry/Image.cpp
src/Core/Geometry/Image.h

Resolves #160.

---

src/Core/Geometry/Image.h

Resolves #162.

---

src/Core/Geometry/PointCloud.cpp
src/Core/Geometry/TriangleMesh.cpp

Resolves #167.

---

src/Core/Geometry/TriangleMesh.cpp

Resolves #170.

---

src/Core/Geometry/EstimateNormals.cpp

Resolves #181.

---

src/Core/Geometry/DownSample.cpp

Resolves #179.

---

src/Core/Geometry/RGBDImage.cpp
src/Core/Geometry/RGBDImage.h

fix typos for RGBDImagePyramid

---

src/Core/Geometry/DownSample.cpp

Fixes #178.
I also went through all Open3D classes, but this is the only inconsistency cases I found.

adding underbar for class member variables

---

src/Core/Geometry/LineSet.cpp
src/Core/Geometry/LineSet.h

Resolves #176 and similar problems like #167.

Resolves #176.

---

src/IO/FileFormat/FilePLY.cpp

add ply_close() to FilePLY.cpp

---

src/Core/Odometry/OdometryOption.h

Resolves #192.

---

README.md

Appveyor Badge Update

---

src/Python/py3d.h

Fix for #199

---

src/Python/Tutorial/Basic/working_with_numpy.py

Fix for #202

---

scripts/install-deps-ubuntu.sh

Fix python dev

---

docs/getting_started.rst
docs/tutorial/Advanced/rgbd_integration.rst
docs/tutorial/ReconstructionSystem/system_overview.rst

This PR relates to #213 and fixes #132 and #206.

Documentation

---

src/External/pybind11/CMakeLists.txt

This fixes potential cmake error. Fixes #228.

Fix pybind11/CMakeLists.txt

---

docs/tutorial/Advanced/colored_pointcloud_registration.rst
src/Core/Registration/ColoredICP.cpp
src/Core/Registration/ColoredICP.h
src/Python/Core/py3d_registration.cpp

expose lambda_geometric in registration_colored_icp

---

src/Python/Tutorial/Advanced/interactive_visualization.py

Minor fix for `src/Python/Tutorial/Advanced/interactive_visualization.py`

Adding copyrights

---

docs/getting_started.rst
docs/tutorial/Basic/file_io.rst
docs/tutorial/Basic/index.rst
src/Python/Tutorial/Basic/file_io.py

adding documents for file IO tutorial

---

scripts/install-deps-ubuntu.sh

adding python-tk

---

docs/tutorial/Advanced/multiway_registration.rst
docs/tutorial/Basic/icp_registration.rst
docs/tutorial/Basic/index.rst
docs/tutorial/Basic/pointcloud.rst
docs/tutorial/Basic/python_interface.rst
docs/tutorial/Basic/rgbd_images/index.rst

minor fix for documentation

---

.appveyor.yml

There is a build failure on AppVeyor CI. This fixes #317.

Removing unnecessary lines in .appveyor.yml

---

.appveyor.yml

Revert "Removing unnecessary lines in .appveyor.yml"

---

src/Core/Registration/Registration.cpp

Resolves #347.
Edit:
This is obvious bug, can be merged immediately.

Bug fix for GetInformationMatrixFromPointClouds #347

---

docs/tutorial/Advanced/non_blocking_visualization.rst
src/Python/Tutorial/Advanced/non_blocking_visualization.py

This is following work of #343.

Polishing non_blocking_visualization

---

src/Core/Registration/FastGlobalRegistration.cpp

Polishing fast global registration #344

---

docs/tutorial/Advanced/rgbd_integration.rst
docs/tutorial/Basic/rgbd_images/nyu.rst
docs/tutorial/Basic/rgbd_images/redwood.rst
docs/tutorial/Basic/rgbd_images/sun.rst
docs/tutorial/Basic/rgbd_images/tum.rst
docs/tutorial/ReconstructionSystem/integrate_scene.rst
docs/tutorial/ReconstructionSystem/make_fragments.rst
src/Core/Camera/PinholeCameraIntrinsic.cpp
src/Core/Camera/PinholeCameraIntrinsic.h
src/Experimental/OdometryRGBD/OdometryRGBD.cpp
src/IO/FileFormat/FileLOG.cpp
src/Python/Core/py3d_camera.cpp
src/Python/Tutorial/Advanced/camera_trajectory.py
src/Python/Tutorial/Advanced/rgbd_integration.py
src/Python/Tutorial/Basic/rgbd_nyu.py
src/Python/Tutorial/Basic/rgbd_redwood.py
src/Python/Tutorial/Basic/rgbd_sun.py
src/Python/Tutorial/Basic/rgbd_tum.py
src/Python/Tutorial/ReconstructionSystem/integrate_scene.py
src/Python/Tutorial/ReconstructionSystem/make_fragments.py
src/Python/Tutorial/ReconstructionSystem/test_pairwise_rgbd_alignment.py

Fix GetPrimeSenseDefault issue #352

---

.appveyor.yml

This PR is to resolve appveyor issue.

Removing numpy install in appveyor

---

src/Core/Registration/GlobalOptimization.cpp

used sparse cholesky decomposition based solver for determining delta.

used sparse eigen solver

---

build.sh
src/CMakeLists.txt
util/pip_package/MANIFEST.in
util/pip_package/README.rst
util/pip_package/open3d/__init__.py
util/pip_package/open3d/win32/32b/__init__.py
util/pip_package/open3d/win32/64b/__init__.py
util/pip_package/open3d/win32/__init__.py

#377 
Added support for 64bit Python 2.7+ and 3.5+ on Windows.

add support for 64bit Python on Windows

---

src/Core/Camera/PinholeCameraIntrinsic.cpp
src/Core/Camera/PinholeCameraIntrinsic.h
src/Python/Core/open3d_camera.cpp
util/scripts/install-deps-osx.sh

Adding another Kinect2 parameters.
Related to #410

Kinect2 param

---

src/Python/Visualization/open3d_visualizer.cpp
src/Test/TestDepthCapture.cpp
src/Test/TestPointCloud.cpp
src/Tools/ManuallyAlignPointCloud/ManuallyAlignPointCloud.cpp
src/Tools/ManuallyCropGeometry.cpp
src/Tools/ViewGeometry.cpp
src/Visualization/Utility/DrawGeometry.cpp
src/Visualization/Visualizer/Visualizer.cpp
src/Visualization/Visualizer/Visualizer.h

This addresses #422 
I also changed the name of ``DestroyWindow()`` so that they are consistent.

fix name conflict of CreateWindow()

---

docs/tutorial/Advanced/color_map_optimization.rst
src/Core/ColorMap/ColorMapOptimization.cpp
src/Core/ColorMap/ColorMapOptimization.h
src/Python/Tutorial/Advanced/color_map_optimization.py

Removes warnings in color map optimization.
Partly resolves #366.

Warning fix

---

docs/tutorial/Advanced/color_map_optimization.rst
docs/tutorial/Advanced/rgbd_integration.rst
docs/tutorial/Basic/rgbd_odometry.rst
docs/tutorial/ReconstructionSystem/make_fragments.rst

- Resolves #454 
- Resolves #424
- Typo fix.

Updating documents

---

docs/tutorial/Advanced/color_map_optimization.rst

Adding a note for color map optimization module.

Adding exceptional case in color_map_optimization.rst

---

src/Visualization/Visualizer/VisualizerRender.cpp

bug fix #467

---

src/Test/TestCameraPoseTrajectory.cpp
src/Test/TestDepthCapture.cpp
src/Test/TestFileDialog.cpp
src/Test/TestFileSystem.cpp
src/Test/TestFlann.cpp
src/Test/TestImage.cpp
src/Test/TestLineSet.cpp
src/Test/TestOpenMP.cpp
src/Test/TestPCDFileFormat.cpp
src/Test/TestPointCloud.cpp
src/Test/TestPoseGraph.cpp
src/Test/TestProgramOptions.cpp
src/Test/TestRealSense.cpp
src/Test/TestRegistrationRANSAC.cpp
src/Test/TestTriangleMesh.cpp
src/Test/TestVisualizer.cpp

This PR replaces tabs to 4spaces in Test/*.* files.
There is no content change in this PR. Please check it through:
https://github.com/IntelVCL/Open3D/compare/master...syncle:test_tab?w=1

tab indent for Test

---

util/pip_package/setup.py.in

removed the opencv dependency of the pip package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/493)

removed the opencv dependency.

---

docs/tutorial/Advanced/fast_global_registration.rst
docs/tutorial/Advanced/headless_rendering.rst
docs/tutorial/Advanced/non_blocking_visualization.rst

Polishing documents.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/506)

Polishing documents

---

src/IO/CMakeLists.txt
src/Visualization/CMakeLists.txt

Resolves #509.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/524)

exclude empty directories from 'make install'

---

examples/Python/Advanced/color_map_optimization.py

in python color_map_optimization example
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/529)

fix PinholeCameraIntrinsic initialization

---

3rdparty/CMakeLists.txt
3rdparty/GLFW/CMakeLists.txt
docs/_static/C++/CMakeLists.txt
src/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/552)

Fix glfw linking issue when built from source

---

.travis.yml

This fixes #557
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/558)

Update .travis.yml to fix #557

---

.travis.yml
CMakeLists.txt

Fixes https://github.com/IntelVCL/Open3D/issues/550 ubuntu default install path. Updated travis to test default installation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/568)

Fix ubuntu default install path

---

src/Python/Visualization/open3d_visualizer.cpp
src/Visualization/Visualizer/Visualizer.cpp
src/Visualization/Visualizer/Visualizer.h

This allows an easy way to create an offscreen window (e.g. for tests).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/580)

Add visible parameter to Visualizer::CreateVisualizerWindow

---

docs/_static/C++/TestVisualizer.cpp
examples/Cpp/CameraPoseTrajectory.cpp
examples/Cpp/DepthCapture.cpp
examples/Cpp/EvaluateFeatureMatch.cpp
examples/Cpp/EvaluatePCDMatch.cpp
examples/Cpp/FileDialog.cpp
examples/Cpp/FileSystem.cpp
examples/Cpp/Flann.cpp
examples/Cpp/Image.cpp
examples/Cpp/IntegrateRGBD.cpp
examples/Cpp/LineSet.cpp
examples/Cpp/OdometryRGBD.cpp
examples/Cpp/OpenMP.cpp
examples/Cpp/PCDFileFormat.cpp
examples/Cpp/PointCloud.cpp
examples/Cpp/PoseGraph.cpp
examples/Cpp/ProgramOptions.cpp
examples/Cpp/RGBDOdometry.cpp
examples/Cpp/RealSense.cpp
examples/Cpp/RegistrationRANSAC.cpp
examples/Cpp/TriangleMesh.cpp
examples/Cpp/TrimMeshBasedOnPointCloud.cpp
examples/Cpp/ViewDistances.cpp
examples/Cpp/ViewPCDMatch.cpp
examples/Cpp/Visualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/590)

Consistent example naming and return code

---

examples/Python/ReconstructionSystem/config/stanford/burghers.json
examples/Python/ReconstructionSystem/config/stanford/cactusgarden.json
examples/Python/ReconstructionSystem/config/stanford/copyroom.json
examples/Python/ReconstructionSystem/config/stanford/lounge.json
examples/Python/ReconstructionSystem/config/stanford/stonewall.json
examples/Python/ReconstructionSystem/config/stanford/totempole.json
examples/Python/ReconstructionSystem/initialize_config.py
examples/Python/ReconstructionSystem/integrate_scene.py
examples/Python/ReconstructionSystem/make_fragments.py
examples/Python/ReconstructionSystem/scripts/download_stanford.sh
examples/Python/Utility/file.py

This PR provides download script of [stanford dataset](http://qianyi.info/scenedata.html) and produces the following result.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/598)

Adding stanford example

---

src/Core/Registration/GlobalOptimization.cpp

https://github.com/IntelVCL/Open3D/issues/600
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/601)

Update pose graph connectivity check

---

docs/tutorial/ReconstructionSystem/capture_your_own_dataset.rst
examples/Python/ReconstructionSystem/config/realsense.json
examples/Python/ReconstructionSystem/sensors/realsense_pcd_visualizer.py
examples/Python/ReconstructionSystem/sensors/realsense_recorder.py
src/Core/Geometry/PointCloudFactory.cpp

This PR resolves #473. It adds the followings
- sensors/realsense_pcd_visualizer.py - that visualizes Realsense RGBD stream as a 3D point cloud in realtime. (Thanks @baptiste-mnh and @LLDavid 👍)
- Chaninging documents
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/622)

RealSense point cloud viewer

---

README.md

Just a simple update of the README.md to reflect our related projects (so far just Open3D-PointNet from my conversation with Jaesik).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/636)

README.md updated to include new Open3D Ecosystem section

---

docs/tutorial/Basic/file_io.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/668)

Add documentation on supported point cloud formats

---

src/Python/Package/open3d/__init__.py

Closes https://github.com/IntelVCL/Open3D/issues/664
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/676)

Promote compiled extension for pycharm autocomplete

---

src/UnitTest/Core/Utility/IJsonConvertible.cpp
src/UnitTest/UnitTest.h

implemented the IJsonConvertible test case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/685)

IJsonConvertible

---

src/UnitTest/UnitTest.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/706)

fixed build after automatic merge duplicated function in UnitTest.h

---

.travis.yml
CMakeLists.txt
src/UnitTest/UnitTest.h
util/scripts/install-deps-osx.sh

Experimenting, do not merge yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/707)

Speed up travis CI OSX build

---

src/Python/Visualization/open3d_visualizer.cpp

This addresses #754
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/759)

fix parameter name of create_window

---

docs/conf.py
docs/python_api/camera.rst
docs/python_api/geometry.rst
docs/python_api/integration.rst
docs/python_api/odometry.rst
docs/python_api/registration.rst
docs/python_api/utility.rst
docs/python_api/visualization.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/779)

Shorter import in docs "open3d.open3d -> open3d"

---

src/Python/Package/open3d/__init__.py

**before:**
**after:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/799)

fix autocomplete for python modules

---

src/Core/Registration/FastGlobalRegistration.h
src/UnitTest/Core/Camera/PinholeCameraIntrinsic.cpp

Fixes #807.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/808)

Adding missing initializers for FGR class

---

docs/contribute.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/816)

update clang-format link to 3rd party

---

examples/Cpp/RegistrationRANSAC.cpp

Resolves #800.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/802)

Fix issues on examples/Cpp/RegistrationRANSAC.cpp

---

src/IO/FileFormat/FileSTL.cpp

Changed 
```cpp
mesh.vertices_[i * 3 + j];
```
to
```cpp
mesh.vertices_[mesh.triangles_[i][j]]
```
This is because it is not guaranteed that the number of vertices is 3 times the number of trianagles after.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/829)

fix STL mesh write vertex index

---

CMakeLists.txt
src/CMakeLists.txt
src/IO/FileFormat/FilePCD.cpp
src/Tools/ManuallyAlignPointCloud/VisualizerForAlignment.cpp
src/Visualization/Visualizer/VisualizerWithEditing.cpp

Also see https://github.com/IntelVCL/Open3D-3rdparty/pull/4.
```
${PACKAGE_PREFIX_DIR}/include/Open3D
${PACKAGE_PREFIX_DIR}/include/Open3D/3rdparty/Eigen
${PACKAGE_PREFIX_DIR}/include/Open3D/3rdparty/flann
${PACKAGE_PREFIX_DIR}/include/Open3D/3rdparty/flann/algorithms
${PACKAGE_PREFIX_DIR}/include/Open3D/3rdparty/flann/nn
${PACKAGE_PREFIX_DIR}/include/Open3D/3rdparty/flann/util
${PACKAGE_PREFIX_DIR}/include/Open3D/3rdparty/glew/include
${PACKAGE_PREFIX_DIR}/include/Open3D/3rdparty/GLFW/include;/usr/include
${PACKAGE_PREFIX_DIR}/include/Open3D/3rdparty/libjpeg
${PACKAGE_PREFIX_DIR}/include/Open3D/3rdparty/jsoncpp/include
${PACKAGE_PREFIX_DIR}/include/Open3D/3rdparty/liblzf
${PACKAGE_PREFIX_DIR}/include/Open3D/3rdparty/libpng
${PACKAGE_PREFIX_DIR}/include/Open3D/3rdparty/rply …
```

Do not install 3rd party header except Eigen and GL

---

docs/conf.py

This is quick fix for handling issue on documentation building.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/845)

fix documentation building

---

src/Open3D/Geometry/TriangleMesh.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/843)

Update adjacency list after mesh operations

---

examples/Cpp/LineSet.cpp
examples/Cpp/TriangleMesh.cpp
examples/Cpp/Visualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/856)

Fix namespace typo in examples

---

docs/index.rst
docs/python_api/color_map.rst
docs/python_api/io.rst
src/Python/camera/camera.cpp
src/Python/geometry/geometry.cpp
src/Python/geometry/geometry.h
src/Python/geometry/image.cpp
src/Python/geometry/lineset.cpp
src/Python/geometry/pointcloud.cpp
src/Python/geometry/trianglemesh.cpp
src/Python/geometry/voxelgrid.cpp
src/Python/io/io.cpp
src/Python/registration/feature.cpp
src/Python/registration/global_optimization.cpp

and etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/859)

Gather IO functions under open3d.io for Python binding

---

docs/compilation.rst
src/Open3D/Geometry/PointCloud.h
src/Python/geometry/pointcloud.cpp
src/Python/visualization/visualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/861)

Fix typos in documentation

---

docs/tutorial/ReconstructionSystem/capture_your_own_dataset.rst
docs/tutorial/ReconstructionSystem/make_fragments.rst
docs/tutorial/ReconstructionSystem/register_fragments.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/862)

Fix typos and formatting in docs (Reconstruction system)

---

src/Open3D/Open3D.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/868)

include HalfEdgeTriangleMesh.h in Open3d.h

---

docs/index.rst
src/Open3D/Geometry/PointCloud.h
src/Open3D/Registration/Registration.h
src/Python/color_map/color_map.cpp
src/Python/docstring.cpp
src/Python/docstring.h
src/Python/geometry/geometry.cpp
src/Python/geometry/halfedgetrianglemesh.cpp
src/Python/geometry/image.cpp
src/Python/geometry/kdtreeflann.cpp
src/Python/geometry/lineset.cpp
src/Python/geometry/pointcloud.cpp
src/Python/geometry/trianglemesh.cpp
src/Python/geometry/voxelgrid.cpp
src/Python/integration/integration.cpp
src/Python/io/io.cpp
src/Python/odometry/odometry.cpp
src/Python/registration/feature.cpp
src/Python/registration/global_optimization.cpp
src/Python/registration/registration.cpp
src/Python/utility/console.cpp
src/Python/utility/eigen.cpp
src/Python/utility/utility.cpp
src/Python/visualization/renderoption.cpp
src/Python/visualization/utility.cpp
src/Python/visualization/viewcontrol.cpp
src/Python/visualization/visualization.cpp
src/Python/visualization/visualizer.cpp

- Improved function pybind docstring parser
- handles special cases like numpy array
- better formatting for listing
- Add docstrings for all functions
- Fix sphinx warnings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/869)

Docstrings for all python functions

---

src/Python/CMakeLists.txt
src/Python/docstring.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/890)

Class method docstring compatible with Python 2 and 3 C API

---

src/Python/geometry/pointcloud.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/899)

fix point cloud dist function docs

---

.gitmodules
CMakeLists.txt
README.md
docs/compilation.rst
docs/contribute.rst
docs/introduction.rst
docs/tutorial/docker/docker-gui.rst
docs/tutorial/docker/docker-test.rst
src/Open3D/Utility/Eigen.h
src/Python/package/README.rst
src/Python/package/js/package.json
util/docker/open3d-test/tools/run.sh
util/docker/open3d-test/tools/test.sh
util/docker/open3d-xvfb/tools/run.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/898)

Rename to ISL

---

src/Python/camera/camera.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/923)

fix doc string of PinholeCameraTrajectory

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/925)

update appveyor build badge to master branch

---

.clang-format

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/930)

remove duplicated sort includes

---

src/Open3D/Geometry/VoxelGrid.cpp
src/Open3D/Geometry/VoxelGrid.h
src/Python/geometry/voxelgrid.cpp
src/UnitTest/Geometry/VoxelGrid.cpp

Voxel grid updates: https://app.asana.com/0/1111336323009173/1116934627207087
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/933)

Voxel grid update

---

src/Open3D/Geometry/VoxelGrid.cpp

Fixes #935
Thanks @WenyinWei
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/952)

Fixes Eigen::floor compiler error issue #935

---

src/Open3D/Geometry/Octree.cpp
src/Open3D/Geometry/Octree.h
src/Python/geometry/geometry.cpp
src/Python/geometry/octree.cpp
src/Python/geometry/octree.h
src/UnitTest/Geometry/Octree.cpp
src/UnitTest/Python/test_octree.py

- All properties and methods except lambdas are bound. 
- Docstrings
- Python unit tests
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/947)

add octree python bindings

---

src/Open3D/Geometry/Octree.cpp
src/Open3D/Geometry/Octree.h
src/UnitTest/Geometry/Octree.cpp

Prototype for octree with generic data
1. OctreeLeafNode needs to be inherited.
2. User needs to provide f_init and f_update for node construction and update. 
3. Comments & suggestions welcomed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/946)

Octree with generic data

---

docs/compilation.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/960)

 fix build docs on make -j

---

src/Open3D/Geometry/Octree.cpp
src/Open3D/Geometry/Octree.h
src/Open3D/Geometry/VoxelGrid.cpp
src/Open3D/Geometry/VoxelGrid.h
src/Python/geometry/octree.cpp
src/Python/geometry/voxelgrid.cpp
src/UnitTest/Python/test_octree.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/983)

Voxel grid to octree

---

docs/compilation.rst
docs/contribute.rst
docs/make.py
docs/tutorial/Advanced/headless_rendering.rst
docs/tutorial/Basic/python_interface.rst
docs/tutorial/ReconstructionSystem/capture_your_own_dataset.rst
docs/tutorial/docker/docker-test.rst
util/scripts/runUnitTests.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/989)

Docs update on unit test and python style

---

src/Python/package/setup.py

fixes #970
fixes #780
fixes #905 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1012)

fix empty bdist_wheel

---

src/Python/visualization/visualizer.cpp

expose Visualizer::CaptureDepthPointCloud to python interface
(#992)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1014)

expose CaptureDepthPointCloud to python interface

---

src/UnitTest/Python/test_open3d_eigen.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1031)

fix python unit test

---

src/Open3D/IO/FileFormat/FilePLY.cpp

Added triangulation by ear clipping to FilePly.cpp based on PR #1060
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1065)

Added triangulation by ear clipping to FilePly.cpp

---

src/Open3D/IO/FileFormat/FilePTS.cpp

"Writinging" -> "Writing"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1088)

correct typo

---

.gitmodules
3rdparty/CMakeLists.txt
3rdparty/README.txt
docs/tutorial/Basic/file_io.rst
src/Open3D/IO/ClassIO/TriangleMeshIO.cpp
src/Open3D/IO/ClassIO/TriangleMeshIO.h
src/Open3D/IO/FileFormat/FileGLTF.cpp
src/UnitTest/IO/FileFormat/FileGLTF.cpp

Added support for [glTF file format](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0).
Support for the alternative GLB file format, which is the binary version of glTF, is also added.
`tinygltf` is added as a submodule, in a similar manner as `tinyobjloader` for obj files.
Currently, only vertices, vertex normals, and vertex colors are supported.
Moreover, only the first mesh given in the glTF file will be read.
The following improvements can be added to a future PR:
- Read all meshes given in a glTF file by combining them into one mesh when reading the file
- Optimized writing of indices (store as `uint16_t` if `number_of_vertices <= 65536`)
--- …

FileGLTF for TriangleMesh

---

examples/Cpp/AzureKinectMKVReader.cpp
examples/Cpp/AzureKinectRecord.cpp
src/Open3D/IO/Sensor/AzureKinect/AzureKinectRecorder.cpp
src/Open3D/IO/Sensor/AzureKinect/AzureKinectRecorder.h
src/Open3D/IO/Sensor/AzureKinect/MKVReader.cpp
src/Open3D/IO/Sensor/AzureKinect/MKVReader.h
src/Open3D/Visualization/Shader/RGBDImageShader.cpp
src/Open3D/Visualization/Shader/RGBDImageShader.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1112)

Fix control flows and improve performance

---

src/Open3D/Registration/Registration.cpp

This PR fixes bug #917
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1128)

Fix bug in GetInformationMatrixFromPointClouds()

---

src/Open3D/IO/FileFormat/FileOFF.cpp
src/Open3D/Utility/Console.h
src/Open3D/Utility/Helper.cpp
src/Open3D/Utility/Helper.h
src/Python/docstring.cpp
src/Python/docstring.h

by trimming white space from the header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1125)

Parsing off files: handling windows line endings

---

3rdparty/libjpeg-turbo/libjpeg-turbo.cmake

fixes #1135
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1136)

auto determine lib or lib64 for 3rdparty_install

---

src/Open3D/ColorMap/ColorMapOptimization.cpp
src/Open3D/ColorMap/ColorMapOptimization.h
src/Open3D/ColorMap/TriangleMeshAndImageUtilities.cpp
src/Open3D/ColorMap/TriangleMeshAndImageUtilities.h
src/Python/color_map/color_map.cpp

before: 
after:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1140)

color map knn interpolate for invisible point

---

CMakeLists.txt
docs/conf.py
src/Open3D/Geometry/TriangleMeshSimplification.cpp
src/Python/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1155)

suppress 3rd-party lib warnings

---

src/Open3D/Registration/Registration.cpp

Fixes #863.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1187)

Warning if no normals in ColoredICP

---

util/scripts/install-deps-ubuntu.sh
util/scripts/setup-linux.sh

Addresses #944.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1191)

Add optional flag to install-deps-ubuntu.sh script

---

docs/tutorial/ReconstructionSystem/make_fragments.rst
examples/Python/ReconstructionSystem/make_fragments.py

Fixes #950.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1192)

Fix read_rgbd_image in make_fragments.py

---

src/Python/package/open3d/j_visualizer.py

fixes https://github.com/intel-isl/Open3D/issues/949
(problem on Python 3.6)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1193)

Update type check for open3d PointCloud

---

src/Open3D/Geometry/TetraMesh.cpp

also print warning on the console if the tetra is invalid
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1212)

fixed maybe-uninitialized warning in TetraMesh.cpp

---

examples/Cpp/Log.cpp
src/Open3D/Utility/Console.cpp
src/Open3D/Utility/Console.h
src/UnitTest/Utility/Console.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1209)

LogFatal to throw exception rather than exit()

---

examples/Python/Advanced/fast_global_registration.py
src/Open3D/Registration/FastGlobalRegistration.cpp

Resolves #1001 
Return registration result from FastGlobalRegistration module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1220)

Fix bugs #1001

---

src/Open3D/Registration/Registration.cpp

Resolves #1117.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1221)

Fix bugs #1117

---

src/Python/open3d_pybind/registration/registration.cpp

Addressing issue #1258.
Using scientific format and fmt::format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1274)

Python registration __repr__

---

src/Open3D/IO/FileFormat/FilePTS.cpp

Change num_of_pts from int to unsigned long long
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1279)

Large PTS File IO 

---

src/Open3D/ColorMap/ColorMapOptimization.h
src/Python/open3d_pybind/color_map/color_map.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1270)

Improve docs for color map

---

src/Open3D/Camera/PinholeCameraIntrinsic.h
src/Open3D/Camera/PinholeCameraParameters.h
src/Open3D/Camera/PinholeCameraTrajectory.h
src/Python/open3d_pybind/camera/camera.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1271)

Improve docs for camera

---

src/Open3D/Geometry/BoundingVolume.h
src/Python/open3d_pybind/geometry/boundingvolume.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1282)

Improve docs on Bounding Boxes for CPP api

---

src/Open3D/Geometry/Geometry.h
src/Open3D/Geometry/Geometry2D.h
src/Open3D/Geometry/Geometry3D.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1284)

Add CPP docs for Geometry base classes

---

docs/compilation.rst
docs/contribute.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1342)

Add script details in docs

---

src/Open3D/Container/SizeVector.h
src/Open3D/Container/Tensor.cpp
src/Open3D/Container/Tensor.h
src/UnitTest/Container/Tensor.cpp

Implements the following functions with PyTorch semantics.
```cpp
Tensor::Permute
Tensor::Transpose
Tensor::T
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1337)

Dimshuffle and transpose

---

src/Open3D/Container/AdvancedIndexing.cpp
src/Open3D/Container/CUDAState.cuh
src/Open3D/Container/CUDAUtils.h
src/Open3D/Container/Device.h
src/Open3D/Container/Indexer.h
src/Open3D/Container/Kernel/CUDALauncher.cuh
src/Open3D/Container/Kernel/IndexGetSet.cpp
src/Open3D/Container/Kernel/IndexGetSetCUDA.cu
src/Open3D/Container/Kernel/UnaryEWCUDA.cu
src/Open3D/Container/MemoryManager.cpp
src/Open3D/Container/MemoryManager.h
src/Open3D/Container/MemoryManagerCUDA.cu
src/Open3D/Container/Tensor.cpp
src/UnitTest/Container/CUDAState.cpp
src/UnitTest/Container/ContainerTest.h
src/UnitTest/Container/Device.cpp
src/UnitTest/Container/Tensor.cpp
src/UnitTest/main.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1396)

Multi-gpu and p2p transfer support 

---

src/Open3D/Container/Blob.h
src/Open3D/Container/CMakeLists.txt
src/Open3D/Container/DLPack/DLPackConverter.cpp
src/Open3D/Container/DLPack/DLPackConverter.h
src/Open3D/Container/DLPack/dlpack.h
src/Open3D/Container/Device.h
src/Open3D/Container/Indexer.h
src/Open3D/Container/Kernel/IndexGetSet.cpp
src/Open3D/Container/Kernel/UnaryEW.cpp
src/Open3D/Container/Kernel/UnaryEWCUDA.cu
src/Open3D/Container/MemoryManager.cpp
src/Open3D/Container/MemoryManager.h
src/Open3D/Container/MemoryManagerCUDA.cu
src/Open3D/Container/Tensor.cpp
src/Open3D/Container/Tensor.h
src/UnitTest/Container/DLPack/DLPackConverter.cpp
src/UnitTest/Container/MemoryManager.cpp
src/UnitTest/Container/Tensor.cpp

Only need to review commit 778b788. 
The rest are from #1396, let's approve and merge #1396 first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1400)

DLPack support

---

src/Open3D/GUI/SceneWidget.cpp
src/Open3D/GUI/SceneWidget.h
src/Open3D/GUI/Widget.cpp
src/Open3D/GUI/Widget.h
src/Open3D/GUI/Window.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1430)

gui: Window now passes key events

---

src/Open3D/GUI/Button.cpp
src/Open3D/GUI/Checkbox.cpp
src/Open3D/GUI/Combobox.cpp
src/Open3D/GUI/Slider.cpp
src/Open3D/GUI/TextEdit.cpp
src/Open3D/GUI/Widget.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1435)

gui: renamed DrawResult::CLICKED to ::REDRAW for clarity

---

3rdparty/SDL2/sdl2.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1442)

Sdl fix for building on Windows systems

---

src/Open3D/Geometry/Geometry.h
src/Open3D/Visualization/Rendering/Filament/FilamentScene.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentScene.h
src/Open3D/Visualization/Rendering/Scene.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1438)

Added string ids for geometry

---

src/Open3D/Container/CMakeLists.txt
src/Open3D/Container/TensorList.cpp
src/Open3D/Container/TensorList.h
src/UnitTest/Container/Tensor.cpp
src/UnitTest/Container/TensorList.cpp

It is a specific and simplified version of std::vector for tensors.
- **Construct**: initialize from a vector of tensors, high dimensional tensors
- **Manipulate**: Resize, Clear, PushBack, Concatenate
- **Access**: [], Slice, IndexGet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1399)

Init TensorList

---

CHANGELOG.md
docs/contribute/contribute.rst
docs/contribute/contribution_recipes.rst
docs/contribute/styleguide.rst
docs/index.rst

* New documentation structure with an update of the contribution guidelines
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1465)

Adding new contribution guidelines

---

.travis.yml
CHANGELOG.md

* Travis migrated to bionic
* Added support for clang-7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1471)

Update travis configuration to support clang-7 and gcc 7.4.

---

util/scripts/install-deps-ubuntu.sh

Dependencies for SDL and Filament added to ubuntu helper scripts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1475)

additional dependecies added

---

src/Open3D/ML/Misc/Detail/FixedRadiusSearch.cuh
src/Open3D/ML/Misc/Detail/FixedRadiusSearch.h
src/Open3D/ML/TensorFlow/Misc/FixedRadiusSearchOpKernel.cpp
src/Open3D/ML/TensorFlow/Misc/FixedRadiusSearchOpKernel.cu
src/Open3D/ML/TensorFlow/Misc/FixedRadiusSearchOpKernel.h
src/Open3D/ML/TensorFlow/Misc/FixedRadiusSearchOps.cpp
src/UnitTest/Python/tf_ops/test_fixed_radius_search.py

This PR adds
- fixed_radius_search op in ml module
- unit test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1461)

fixed radius search tensorflow op

---

docs/compilation.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1477)

Minor typo correction in compilation.rst

---

docs/tutorial/Basic/visualization.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1476)

Typo correction in tutorial/Basic/visualization.rst

---

3rdparty/filament/filament_build.cmake
3rdparty/filament/filament_download.cmake

Added install step for Filament
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1479)

Fixes for CI travis builds on Linux

---

.gitmodules
3rdparty/CMake/Findnanoflann.cmake
3rdparty/README.txt
src/Open3D/ML/Misc/Detail/RadiusSearch.h
src/Open3D/ML/TensorFlow/CMakeLists.txt
src/Open3D/ML/TensorFlow/Misc/RadiusSearchOpKernel.cpp
src/Open3D/ML/TensorFlow/Misc/RadiusSearchOpKernel.h
src/Open3D/ML/TensorFlow/Misc/RadiusSearchOps.cpp
src/UnitTest/Python/tf_ops/test_radius_search.py

This PR adds
- nanoflann as submodule
- radius search op in ml module
- unit test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1464)

radius search tensorflow op

---

src/Python/CMakeLists.txt
src/Python/generate_tf_ops_wrapper.py
src/Python/make_python_package.cmake
src/Python/open3d/ml/tf/ops/__init__.py
src/Python/open3d/ml/tf/python/ops/lib.py
src/Python/open3d/ml/tf/python/ops/ops.py.in

This PR adds code for generating function wrappers in open3d/ml/tf/python/ops/ops.py
to allow
- doc generation
- simplify docstring lookup for IDEs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1485)

tf op function wrapper generation

---

src/Open3D/Registration/GlobalOptimization.cpp

This PR fixes #1497.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1498)

Fix number of edge not showing on error message

---

src/Open3D/Core/AdvancedIndexing.h
src/Open3D/Core/Broadcast.h
src/Open3D/Core/CMakeLists.txt
src/Open3D/Core/Device.h
src/Open3D/Core/Indexer.h
src/Open3D/Core/Kernel/BinaryEW.cpp
src/Open3D/Core/Kernel/BinaryEW.h
src/Open3D/Core/Kernel/BinaryEWCPU.cpp
src/Open3D/Core/Kernel/BinaryEWCUDA.cu
src/Open3D/Core/Kernel/CPULauncher.h
src/Open3D/Core/Kernel/CUDALauncher.cuh
src/Open3D/Core/Kernel/Kernel.h
src/Open3D/Core/Kernel/UnaryEW.cpp
src/Open3D/Core/Kernel/UnaryEWCUDA.cu
src/Open3D/Core/Tensor.cpp
src/Open3D/Core/Tensor.h
src/Open3D/Core/TensorList.cpp
src/Open3D/Core/TensorList.h
src/Python/open3d/core.py
src/Python/open3d_pybind/core/tensor.cpp
src/UnitTest/Container/Tensor.cpp
src/UnitTest/Python/test_core.py

Supports `add, sub, mul, div`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1460)

Binary element-wise ops

---

src/Open3D/ML/Misc/Detail/FixedRadiusSearch.h
src/Open3D/ML/Misc/Detail/KnnSearch.h
src/Open3D/ML/Misc/Detail/NeighborSearchCommon.h
src/Open3D/ML/TensorFlow/Misc/KnnSearchOpKernel.cpp
src/Open3D/ML/TensorFlow/Misc/KnnSearchOpKernel.h
src/Open3D/ML/TensorFlow/Misc/KnnSearchOps.cpp
src/Open3D/ML/TensorFlow/Misc/RadiusSearchOpKernel.cpp
src/UnitTest/Python/tf_ops/test_knn_search.py

This PR adds
- op for knn search in ml module
- new header for common code of search ops
- unit test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1494)

knn search tensorflow op

---

src/Python/open3d_pybind/visualization/visualizer.cpp

Related with #1501
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1518)

Give sensible name for python argument

---

docs/tutorial/ReconstructionSystem/capture_your_own_dataset.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1525)

Fix filename error in tutorial

---

src/Open3D/Visualization/Rendering/Filament/FilamentRenderToBuffer.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentResourceManager.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1527)

fixed problem caused by gcc bug #51242

---

src/Open3D/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1530)

Gui CI fix

---

.appveyor.yml
CHANGELOG.md

* Now appveyor should be able to build all branches
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1534)

Fix for appveyor to build all branches

---

src/Open3D/ML/Misc/Detail/VoxelPooling.h
src/Open3D/ML/TensorFlow/Misc/VoxelPoolingGradOpKernel.cpp
src/Open3D/ML/TensorFlow/Misc/VoxelPoolingGradOpKernel.h
src/Open3D/ML/TensorFlow/Misc/VoxelPoolingOpKernel.cpp
src/Open3D/ML/TensorFlow/Misc/VoxelPoolingOpKernel.h
src/Open3D/ML/TensorFlow/Misc/VoxelPoolingOps.cpp
src/Python/open3d/ml/tf/ops/__init__.py
src/Python/open3d/ml/tf/python/ops/gradients.py
src/Python/open3d/ml/tf/python/ops/lib.py
src/UnitTest/Python/tf_ops/check_gradients.py
src/UnitTest/Python/tf_ops/test_voxel_pooling.py

This PR adds
- voxel pooling op and corresponding gradient op in ml module
- unit test
- functions for checking gradients
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1493)

voxel pooling tensorflow op

---

src/Open3D/GUI/Application.h
src/Open3D/GUI/Layout.h
src/Open3D/GUI/SceneWidget.cpp
src/Open3D/GUI/Widget.h

Add some documentation, fix zoom to work like MeshLab.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1542)

Gui zoomfix

---

src/Open3D/GUI/Materials/defaultLit.mat
src/Open3D/Visualization/Rendering/Filament/FilamentResourceManager.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentScene.cpp
src/Open3D/Visualization/Rendering/Filament/PointCloudBuffers.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1547)

Switched pointclouds to lit material by default

---

docs/tutorial/Advanced/non_blocking_visualization.rst
examples/Python/Advanced/remove_geometry.py
examples/Python/Basic/mesh_properties.py
examples/Python/Basic/transformation.py
examples/Python/ReconstructionSystem/sensors/azure_kinect_mkv_reader.py
examples/Python/ReconstructionSystem/sensors/azure_kinect_recorder.py
examples/Python/ReconstructionSystem/sensors/azure_kinect_viewer.py

Related with #1501, #1528 
To avoid such repetitive commits of such nature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1537)

Fix bug in examples.

---

.gitmodules
3rdparty/CMake/FindCUTLASS.cmake
3rdparty/README.txt

This PR just adds the submodule and enables the include dir for the tf ops
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1551)

added 3rdparty library cutlass

---

src/Open3D/Core/Kernel/BinaryEW.cpp
src/Open3D/Core/Kernel/UnaryEW.cpp
src/Open3D/Core/Kernel/UnaryEW.h
src/Open3D/Core/Kernel/UnaryEWCPU.cpp
src/Open3D/Core/Kernel/UnaryEWCUDA.cu
src/Open3D/Core/Tensor.cpp
src/Open3D/Core/Tensor.h
src/Python/open3d_pybind/core/tensor.cpp
src/UnitTest/Container/Tensor.cpp
src/UnitTest/Python/test_core.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1532)

Unary sqrt, sin, cos, neg, exp ops

---

src/Open3D/Visualization/Rendering/Filament/FilamentScene.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentScene.h
src/Open3D/Visualization/Rendering/Scene.h
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1554)

Entity transform default init. Scene::GetEntityBoundingBox now return world-space AABB

---

src/Open3D/Core/Indexer.h
src/Open3D/Core/Kernel/BinaryEWCPU.cpp
src/Open3D/Core/Kernel/BinaryEWCUDA.cu
src/Open3D/Core/Kernel/CPULauncher.h
src/Open3D/Core/Kernel/CUDALauncher.cuh
src/Open3D/Core/Kernel/IndexGetSetCPU.cpp
src/Open3D/Core/Kernel/IndexGetSetCUDA.cu
src/Open3D/Core/Kernel/UnaryEWCPU.cpp
src/Open3D/Core/Kernel/UnaryEWCUDA.cu
src/Open3D/Core/Tensor.cpp
src/Open3D/Core/Tensor.h
src/Python/open3d/core.py
src/Python/open3d_pybind/core/size_vector.cpp
src/Python/open3d_pybind/core/tensor.cpp
src/UnitTest/Container/Tensor.cpp
src/UnitTest/Python/test_core.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1533)

Tensor::To for type casting

---

src/Open3D/GUI/Materials/defaultUnlit.mat
src/Open3D/GUI/SceneWidget.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentView.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1561)

Tonemapping is switched off

---

.travis.yml
src/Open3D/Visualization/Rendering/Filament/FilamentView.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1562)

Disabled switching of clear color for View

---

src/Open3D/GUI/NumberEdit.cpp
src/Open3D/GUI/NumberEdit.h
src/Open3D/GUI/SceneWidget.cpp
src/Open3D/GUI/SceneWidget.h
src/Open3D/GUI/TextEdit.cpp
src/Open3D/GUI/TextEdit.h
src/Open3D/GUI/VectorEdit.cpp
src/Open3D/GUI/VectorEdit.h
src/Open3D/Visualization/Rendering/CameraInteractor.cpp
src/Open3D/Visualization/Rendering/CameraInteractor.h
src/Open3D/Visualization/Rendering/Filament/FilamentScene.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentScene.h
src/Open3D/Visualization/Rendering/LightDirectionInteractor.cpp
src/Open3D/Visualization/Rendering/LightDirectionInteractor.h
src/Open3D/Visualization/Rendering/MatrixInteractor.cpp
src/Open3D/Visualization/Rendering/MatrixInteractor.h
src/Open3D/Visualization/Rendering/Scene.h
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.h

Adds UI to change sun direction via mouse or by editing numerical values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1565)

Gui lighting UI

---

src/Open3D/Visualization/Rendering/LightDirectionInteractor.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

Also changed the color of the sun back to something yellow, as it was very orange.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1573)

Added UI to change background color

---

examples/Cpp/GuiDemo.cpp
src/Open3D/GUI/Combobox.cpp
src/Open3D/GUI/Combobox.h
src/Open3D/GUI/FileDialog.cpp
src/Open3D/GUI/Materials/defaultLit.mat
src/Open3D/Visualization/Rendering/Filament/FilamentRenderer.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentRenderer.h
src/Open3D/Visualization/Rendering/Filament/FilamentResourceManager.cpp
src/Open3D/Visualization/Rendering/Renderer.h
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

Also reduced materials options count:
* Lit
* Unlit
* Normal map
* Depth
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1569)

Moved materials switch to settings ui

---

examples/Cpp/GuiDemo.cpp
src/Open3D/GUI/Combobox.cpp
src/Open3D/GUI/Combobox.h
src/Open3D/GUI/FileDialog.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1583)

Gui buildfix

---

examples/Cpp/GuiDemo.cpp
src/Open3D/GUI/Combobox.cpp
src/Open3D/GUI/Combobox.h
src/Open3D/GUI/FileDialog.cpp
src/Open3D/GUI/SceneWidget.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1584)

Gui demofix mouse

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1588)

Merge light and material settings into one

---

src/Open3D/GUI/Gui.cpp
src/Open3D/GUI/Gui.h
src/Open3D/GUI/Window.cpp

Fixes camera rotating when dragging in color edit popup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1591)

Fix dragging in color popup also moving camera underneath

---

src/Open3D/GUI/Menu.cpp
src/Open3D/GUI/Menu.h
src/Open3D/GUI/MenuMacOS.mm
src/Open3D/GUI/Window.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1590)

Fix settings and key help underlapping menu on Linux

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1595)

point clouds with vertex colors is always unlit

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1593)

Update help keys HUD

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1596)

option for checking colors of point cloud added

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1602)

Change IBL intensity from 50k to 100k

---

src/Open3D/GUI/Combobox.cpp
src/Open3D/GUI/Combobox.h
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1601)

Add UI to set prefab materials

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1604)

merged back point size changing for depth and normals mode

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1607)

Adds initial lighting profiles

---

src/Open3D/GUI/Layout.cpp
src/Open3D/GUI/Layout.h
src/Open3D/GUI/Widget.h
src/Open3D/GUI/Window.cpp
src/Open3D/GUI/Window.h
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1608)

Refactor settings UI

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1609)

Point clouds are always in smart mode

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1611)

ibl rotaion. added clay material

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

… automatic search help menu item
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1614)

Small fixes for help menu

---

src/Open3D/ML/ContinuousConv/Detail/ContinuousConv.cuh
src/Open3D/ML/ContinuousConv/Detail/ContinuousConvTranspose.cuh
src/Open3D/ML/ContinuousConv/Detail/ContinuousConvTranspose.h
src/Open3D/ML/TensorFlow/ContinuousConv/ContinuousConvTransposeOpKernel.cpp
src/Open3D/ML/TensorFlow/ContinuousConv/ContinuousConvTransposeOpKernel.cu
src/Open3D/ML/TensorFlow/ContinuousConv/ContinuousConvTransposeOpKernel.h
src/Open3D/ML/TensorFlow/ContinuousConv/ContinuousConvTransposeOps.cpp

This PR adds
- implementation of the transpose continuous convolution
- tf op wrapper
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1570)

transpose conv implementation and tf op

---

src/Open3D/ML/ContinuousConv/Detail/ContinuousConvTransposeBackpropFilter.cuh
src/Open3D/ML/ContinuousConv/Detail/ContinuousConvTransposeBackpropFilter.h
src/Open3D/ML/TensorFlow/ContinuousConv/ContinuousConvTransposeBackpropFilterOpKernel.cpp
src/Open3D/ML/TensorFlow/ContinuousConv/ContinuousConvTransposeBackpropFilterOpKernel.cu
src/Open3D/ML/TensorFlow/ContinuousConv/ContinuousConvTransposeBackpropFilterOpKernel.h
src/Open3D/ML/TensorFlow/ContinuousConv/ContinuousConvTransposeBackpropFilterOps.cpp

This PR adds the implementation of the filter backprop and the tf op.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1579)

implementation of filter backprop for transpose conv

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

Added point cloud profile, automatically enable it if all geometries are point clouds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1618)

Added point cloud profile

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1619)

Fixed height of skybox button

---

src/Apps/Open3DViewer/Info.plist.in

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1626)

Set app menu name to "Open3D" for macOS

---

src/Open3D/Visualization/Rendering/Filament/FilamentView.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentView.h
src/Open3D/Visualization/Rendering/View.h
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1627)

App UI fixes

---

src/Open3D/Geometry/PointCloudSegmentation.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1637)

log error in PointCloud::SegmentPlane() if there are less than 3 points

---

src/Python/open3d/ml/tf/__init__.py
src/Python/open3d/ml/tf/layers/__init__.py
src/Python/open3d/ml/tf/python/layers/convolutions.py

This PR adds the layer class for the cconv for tensorflow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1606)

layer class for cconv

---

src/Open3D/ML/TensorFlow/ContinuousConv/ContinuousConvBackpropFilterOps.cpp
src/Open3D/ML/TensorFlow/ContinuousConv/ContinuousConvOps.cpp
src/Open3D/ML/TensorFlow/ContinuousConv/ContinuousConvTransposeBackpropFilterOps.cpp
src/Open3D/ML/TensorFlow/ContinuousConv/ContinuousConvTransposeOps.cpp
src/Python/open3d/ml/tf/python/layers/convolutions.py
src/Python/open3d/ml/tf/python/ops/gradients.py
src/UnitTest/Python/tf_ops/test_cconv.py

This PR adds some unit tests for the continuous convs and fixes some bugs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1648)

cconv unit tests and bugfixes

---

src/Open3D/Core/Kernel/UnaryEW.h
src/Open3D/Core/Kernel/UnaryEWCPU.cpp
src/Open3D/Core/Kernel/UnaryEWCUDA.cu
src/Open3D/Core/Tensor.cpp
src/Open3D/Core/Tensor.h
src/Python/open3d/core.py
src/Python/open3d_pybind/core/tensor.cpp
src/UnitTest/Container/Tensor.cpp
src/UnitTest/Python/test_core.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1620)

add Tensor::Abs and python bindings

---

src/UnitTest/Python/tf_ops/cconv_python.py
src/UnitTest/Python/tf_ops/test_cconv_python.py

This PR adds
- python implementation of cconv
- unit test
in preparation for unit tests of the cpp implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1599)

cconv python implementation

---

.appveyor.yml
3rdparty/libjpeg-turbo/libjpeg-turbo.cmake
CMakeLists.txt

Fixes #1657
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1660)

Enable /bigobj flag for Windows debug build

---

src/Open3D/GUI/SceneWidget.cpp
src/Open3D/Visualization/Rendering/IBLRotationInteractor.cpp
src/Open3D/Visualization/Rendering/IBLRotationInteractor.h
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1670)

Added ability to rotate IBL

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1671)

Minor UI text changes

---

src/Open3D/GUI/SceneWidget.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1674)

Increase FPS movement rate

---

src/Open3D/GUI/SceneWidget.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1676)

FPS mode fixes

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1677)

Point cloud profile uses default IBL and force redraw after loading IBL

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1679)

Add toggleable axes

---

src/Open3D/GUI/SceneWidget.cpp
src/Open3D/GUI/SceneWidget.h
src/Open3D/GUI/Widget.cpp
src/Open3D/GUI/Widget.h
src/Open3D/GUI/Window.cpp
src/Open3D/Visualization/Rendering/IBLRotationInteractor.cpp
src/Open3D/Visualization/Rendering/IBLRotationInteractor.h
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1675)

IBL rotation will always display skybox

---

src/Open3D/Visualization/Rendering/LightDirectionInteractor.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1685)

Fixes axes casting shadows and sun-direction gui

---

src/Open3D/Visualization/Rendering/LightDirectionInteractor.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

Eigen doesn't play well with `auto` and #1685 seems to only accidentally work for me, and only in the directory on my machine I created it in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1686)

Fixes #1684/1685 not working for sun rotation due

---

src/Open3D/GUI/Application.cpp
src/Open3D/GUI/FileDialog.cpp
src/Open3D/GUI/Layout.cpp
src/Open3D/GUI/Layout.h
src/Open3D/Visualization/Rendering/MatrixInteractor.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1694)

Changes for app feedback

---

src/Open3D/Core/Dispatch.h
src/Open3D/Core/Dtype.h
src/Open3D/Core/Indexer.h
src/Open3D/Core/Kernel/BinaryEW.cpp
src/Open3D/Core/Kernel/BinaryEW.h
src/Open3D/Core/Kernel/BinaryEWCPU.cpp
src/Open3D/Core/Kernel/BinaryEWCUDA.cu
src/Open3D/Core/Kernel/UnaryEW.h
src/Open3D/Core/Kernel/UnaryEWCPU.cpp
src/Open3D/Core/Kernel/UnaryEWCUDA.cu
src/Open3D/Core/Tensor.cpp
src/Open3D/Core/Tensor.h
src/Python/open3d/core.py
src/Python/open3d_pybind/core/dtype.cpp
src/Python/open3d_pybind/core/tensor.cpp
src/Python/open3d_pybind/pybind_utils.cpp
src/UnitTest/Container/Tensor.cpp
src/UnitTest/Python/test_core.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1652)

boolean dtype, logical ops, comparision ops

---

.travis.yml
docs/tutorial/Advanced/headless_rendering.rst
src/Tools/GLInfo.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1707)

Travis headless docs build

---

src/Open3D/GUI/SceneWidget.cpp
src/Open3D/GUI/SceneWidget.h
src/Open3D/GUI/Window.cpp
src/Open3D/GUI/Window.h
src/Open3D/Visualization/Rendering/Filament/FilamentView.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentView.h
src/Open3D/Visualization/Rendering/View.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1712)

Make drawing quicker while resizing

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1716)

Fix unlit material prevent unlit objects from being white-on-white

---

src/Benchmark/Geometry/KDTreeFlann.cpp
src/Benchmark/Geometry/SamplePoints.cpp
util/scripts/run-travis.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1710)

Travis: run microbenchmarks

---

src/Open3D/GUI/SceneWidget.cpp
src/Open3D/Visualization/Rendering/ModelInteractor.cpp
src/Open3D/Visualization/Rendering/RotationInteractor.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1717)

Fix problems when model center is far from origin

---

src/Open3D/GUI/Widget.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1720)

User-set color and lighting override automatic settings

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

(I got the logic of the commit message backwards, a mesh with uniform color should load lit)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1721)

Meshes with one uniform color load with lit material now

---

src/Open3D/GUI/SceneWidget.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1727)

Disable MSAA while rotating for smoother action on sluggish models

---

src/Open3D/GUI/Window.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1729)

Fix crash starting GuiDemo

---

src/Open3D/Core/Dispatch.h
src/Open3D/Core/Kernel/BinaryEWCPU.cpp
src/Open3D/Core/Kernel/BinaryEWCUDA.cu

Avoided nested template macro generation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1722)

Speeds up compilation

---

src/Apps/Open3DViewer/Open3DViewer_mac.mm
src/Open3D/GUI/Application.cpp
src/Open3D/GUI/Application.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1735)

Fix crash on macOS when quit from Dock >> right click >> Quit

---

src/Open3D/GUI/Application.cpp
src/Open3D/GUI/Application.h
src/Open3D/GUI/SceneWidget.cpp
src/Open3D/GUI/SceneWidget.h
src/Open3D/GUI/Window.cpp
src/Open3D/GUI/Window.h
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1732)

Draw subsampled version of large point clouds when rotating

---

src/Open3D/IO/FileFormat/FilePLY.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1736)

Return from ReadTriangleMeshFromPLY quicker if it is not a triangle mesh

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

German, could you check that the default lighting looks good to you?  I adjusted it so that it looks good to me and approximately what we had (for Qianyi's models), but I'd like your feedback.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1737)

Set models with no vertex colors to have white vertices, updated default lighting

---

src/Open3D/IO/FileFormat/FilePLY.cpp

Reverts intel-isl/Open3D#1736
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1740)

Revert "Return from ReadTriangleMeshFromPLY quicker if it is not a triangle mesh"

---

Open3DViewerDebug.entitlements
Open3DViewerRelease.entitlements
src/Apps/Open3DViewer/Open3DViewer.entitlements

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1742)

Fix app entitlements on macOS

---

src/Apps/CMakeLists.txt

App name needs to be "Open3D"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1741)

Change app name on Linux to Open3D

---

src/Open3D/Core/AdvancedIndexing.cpp
src/Open3D/Core/Broadcast.cpp
src/Open3D/Core/DLPack/DLPackConverter.cpp
src/Open3D/Core/Kernel/UnaryEWCPU.cpp
src/Open3D/Core/SizeVector.h
src/Open3D/Core/Tensor.cpp
src/Open3D/Core/Tensor.h
src/Python/open3d_pybind/core/tensor.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1739)

fix windows warnings (as errors)

---

src/Open3D/IO/ClassIO/FileFormatIO.cpp
src/Open3D/IO/ClassIO/FileFormatIO.h
src/Open3D/IO/FileFormat/FileGLTF.cpp
src/Open3D/IO/FileFormat/FileOBJ.cpp
src/Open3D/IO/FileFormat/FileOFF.cpp
src/Open3D/IO/FileFormat/FilePCD.cpp
src/Open3D/IO/FileFormat/FilePLY.cpp
src/Open3D/IO/FileFormat/FilePTS.cpp
src/Open3D/IO/FileFormat/FileSTL.cpp
src/Open3D/IO/FileFormat/FileXYZ.cpp
src/Open3D/IO/FileFormat/FileXYZN.cpp
src/Open3D/IO/FileFormat/FileXYZRGB.cpp
src/Open3D/Open3D.h.in
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1749)

Read header of geometry files to determine what geometry it contains

---

src/Open3D/ML/Misc/Detail/FixedRadiusSearch.cuh
src/Open3D/ML/Misc/Detail/FixedRadiusSearch.h
src/Open3D/ML/Misc/Detail/NeighborSearchCommon.h
src/Open3D/ML/TensorFlow/Misc/BuildSpatialHashTableOpKernel.cpp
src/Open3D/ML/TensorFlow/Misc/BuildSpatialHashTableOpKernel.cu
src/Open3D/ML/TensorFlow/Misc/BuildSpatialHashTableOpKernel.h
src/Open3D/ML/TensorFlow/Misc/BuildSpatialHashTableOps.cpp
src/Open3D/ML/TensorFlow/Misc/FixedRadiusSearchOpKernel.cpp
src/Open3D/ML/TensorFlow/Misc/FixedRadiusSearchOpKernel.cu
src/Open3D/ML/TensorFlow/Misc/FixedRadiusSearchOpKernel.h
src/Open3D/ML/TensorFlow/Misc/FixedRadiusSearchOps.cpp
src/Python/open3d/ml/tf/layers/__init__.py
src/Python/open3d/ml/tf/python/layers/convolutions.py
src/Python/open3d/ml/tf/python/layers/neighbor_search.py
src/UnitTest/Python/tf_ops/test_cconv.py
src/UnitTest/Python/tf_ops/test_cconv_python.py
src/UnitTest/Python/tf_ops/test_fixed_radius_search.py

This PR adds
- a separate op for building the acceleration structure to improve efficiency
- a layer for the fixed radius search
- updated dependent code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1723)

split fixed radius search op

---

src/Apps/CMakeLists.txt
src/Apps/Open3DViewer/Open3DViewer.desktop.in
src/Apps/Open3DViewer/Open3DViewer.xml
src/Apps/Open3DViewer/postinstall-linux.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1763)

Implement FreeDesktop menu and file associations

---

src/Open3D/GUI/Application.h
src/Open3D/GUI/Checkbox.h
src/Open3D/GUI/Color.h
src/Open3D/GUI/ColorEdit.h
src/Open3D/GUI/Combobox.h
src/Open3D/GUI/Dialog.h
src/Open3D/GUI/FileDialog.h
src/Open3D/GUI/Label.h
src/Open3D/GUI/Layout.h
src/Open3D/GUI/ListView.h
src/Open3D/GUI/Menu.h
src/Open3D/GUI/SceneWidget.h
src/Open3D/GUI/Slider.cpp
src/Open3D/GUI/Slider.h
src/Open3D/GUI/TextEdit.h
src/Open3D/GUI/VectorEdit.h
src/Open3D/GUI/Widget.h
src/Open3D/GUI/Window.cpp
src/Open3D/GUI/Window.h
src/Open3D/IO/FileFormat/FilePLY.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1776)

Documentation for GUI directory, small consistency improvements

---

examples/Python/ReconstructionSystem/opencv_pose_estimation.py

Fixes #1786
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1799)

fixes get_xyz_from_pts interpolation

---

src/Open3D/Core/Indexer.cpp
src/Open3D/Core/Indexer.h
src/Open3D/Core/Tensor.h

fixes #1793
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1801)

Tensor::Fill explicit specialization, reduce number of outputs

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1807)

Fix so OBJ models with single albedo map default to Unlit material

---

util/scripts/make-documentation.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1806)

fix typo in make docs

---

src/Open3D/GUI/Window.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1808)

Adds camera reset, fixes camera moving in fly mode when changing colors

---

src/Open3D/GUI/SceneWidget.cpp
src/Open3D/GUI/SceneWidget.h
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

To view information go to help menu and select 'Show Camera Info'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1810)

Add small display in lower left corner to show current camera pos and front/left/up vectors

---

src/Open3D/GUI/SceneWidget.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1811)

Added Ctrl+Shift to rotate z

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1824)

Fix warning streaming out to console in Open3DViewer

---

src/Open3D/Geometry/BoundingVolume.cpp
src/Open3D/Geometry/BoundingVolume.h

#1792
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1798)

Fix OrientedBoundingBox GetPointIndicesWithinBoundingBox

---

.github/workflows/ccpp.yml
.gitignore
.travis.yml
src/UnitTest/Utility/FileSystem.cpp
util/scripts/run-travis.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1831)

run macos ci on github actions

---

src/Open3D/GUI/SceneWidget.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1836)

Better far plane distance calculation in SceneWidget

---

.gitignore
src/Open3D/Visualization/Rendering/Filament/PointCloudBuffers.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1839)

Fix filament warnings when displaying point clouds

---

src/Open3D/Core/Kernel/ReductionCPU.cpp
src/Open3D/Core/Kernel/ReductionCUDA.cu
src/UnitTest/Core/Tensor.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1827)

use lowest instead of min for smallest value

---

README.md
docs/compilation.rst
docs/contribute/contribution_recipes.rst
docs/getting_started.rst
docs/introduction.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1848)

Update readme for the release

---

3rdparty/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1855)

CMake: check that updated submodules are present

---

src/Open3D/GUI/Window.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1854)

GUI: fixed x, y arguments to Window constructor

---

docs/index.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1862)

remove dummy cuda doc entry

---

src/Open3D/GUI/Combobox.cpp
src/Open3D/GUI/Combobox.h
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1873)

App: add option to material combobox to restore to original values from file

---

src/Open3D/Geometry/TriangleMesh.h
src/Open3D/Visualization/Rendering/Filament/FilamentResourceManager.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1879)

Fixes Kd value not being properly loaded from .mtl

---

examples/Python/Basic/pointcloud.ipynb

Addressing #1853
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1884)

jupyter tutorial on compute_point_cloud_distance

---

src/Python/open3d/ml/tf/layers/__init__.py
src/Python/open3d/ml/tf/python/layers/convolutions.py
src/UnitTest/Python/tf_ops/test_sparseconv.py

This PR adds
- sparse conv layers based on the cconv implementation
- unit tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1869)

add sparseconv layer

---

examples/Python/open3d_tutorial.py
src/UnitTest/Python/test_color_map.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1897)

test_color_map.py Travis (and OPENMP) FP error fixes

---

examples/Python/Advanced/surface_reconstruction.ipynb
src/Open3D/Geometry/EstimateNormals.cpp
src/Open3D/Geometry/PointCloud.h
src/Python/open3d_pybind/geometry/pointcloud.cpp

Implementing method of Hoppe et al.
Addressing #270, #306, #1507, #1641.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1895)

Orient normals using propagation on MST of Riemannian graph

---

examples/Python/open3d_tutorial.py
src/Open3D/IO/FileFormat/FilePNG.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentResourceManager.cpp
src/UnitTest/Python/test_color_map.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1886)

Add support for PNG with alpha channel

---

src/Benchmark/CMakeLists.txt
src/Benchmark/IO/PointCloudIO.cpp
src/Open3D/IO/ClassIO/PointCloudIO.cpp
src/Open3D/IO/ClassIO/PointCloudIO.h
src/Open3D/IO/FileFormat/FilePCD.cpp
src/Open3D/IO/FileFormat/FilePLY.cpp
src/Open3D/IO/FileFormat/FilePTS.cpp
src/Open3D/Utility/Eigen.cpp
src/Open3D/Utility/Eigen.h
src/UnitTest/IO/ClassIO/PointCloudIO.cpp
src/UnitTest/IO/ClassIO/VoxelGridIO.cpp
src/UnitTest/Utility/Eigen.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1891)

PointCloudIO: UnitTests and Benchmarks

---

.github/workflows/ccpp.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1903)

turn off two mac ci builds on github actions

---

src/Apps/Open3DViewer/Open3DViewer.cpp
src/Apps/Open3DViewer/Open3DViewer.h
src/Apps/Open3DViewer/Open3DViewer_mac.mm
src/Open3D/GUI/Application.cpp
src/Open3D/GUI/Application.h
src/Open3D/GUI/ProgressBar.cpp
src/Open3D/GUI/ProgressBar.h
src/Open3D/GUI/Task.cpp
src/Open3D/GUI/Task.h
src/Open3D/GUI/Window.cpp
src/Open3D/Open3D.h.in
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1896)

GUI: added threading and loading dialog to app

---

examples/Cpp/PCDFileFormat.cpp
src/Benchmark/IO/PointCloudIO.cpp
src/Open3D/IO/ClassIO/PointCloudIO.cpp
src/Open3D/IO/ClassIO/PointCloudIO.h
src/Open3D/IO/FileFormat/FilePCD.cpp
src/Open3D/IO/FileFormat/FilePLY.cpp
src/Open3D/IO/FileFormat/FilePTS.cpp
src/Open3D/IO/FileFormat/FileXYZ.cpp
src/Open3D/IO/FileFormat/FileXYZN.cpp
src/Open3D/IO/FileFormat/FileXYZRGB.cpp
src/Open3D/Utility/FileSystem.cpp
src/Open3D/Utility/FileSystem.h
src/Open3D/Utility/Helper.cpp
src/Open3D/Utility/Helper.h
src/Open3D/Utility/ProgressReporters.h
src/Python/open3d_pybind/io/class_io.cpp
src/Tools/ConvertPointCloud.cpp
src/UnitTest/IO/ClassIO/PointCloudIO.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1907)

update_progress callbacks for ReadPointCloud and WritePointCloud

---

docs/compilation.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1914)

add cmake 3.12+ installation docs

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1913)

Integrates point cloud I/O progress into app loading progress bar

---

docs/make_docs.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1951)

Docs: disable multiprocessing for sphinx-build

---

.travis.yml
3rdparty/CMake/FindPythonExecutable.cmake
CMakeLists.txt
src/Python/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1923)

cmake: pickup python from PYTHON_EXECUTABLE or from PATH

---

src/UnitTest/Visualization/Rendering/MaterialModifier.cpp
src/pybind/geometry/geometry.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1964)

fix master build

---

cpp/benchmark/geometry/KDTreeFlann.cpp
cpp/benchmark/geometry/SamplePoints.cpp
cpp/open3d/geometry/KDTreeFlann.h
cpp/open3d/io/ClassIO/ImageWarpingFieldIO.h
cpp/open3d/io/FileFormat/FilePLY.cpp
cpp/open3d/ml/TensorFlow/Misc/FixedRadiusSearchOpKernel.h
cpp/open3d/ml/TensorFlow/Misc/InvertNeighborsListOpKernel.h
cpp/open3d/ml/TensorFlow/Misc/KnnSearchOpKernel.h
cpp/open3d/ml/TensorFlow/Misc/RadiusSearchOpKernel.h
cpp/open3d/ml/TensorFlow/Misc/ReduceSubarraysSumOpKernel.h
cpp/open3d/ml/TensorFlow/Misc/VoxelPoolingGradOpKernel.h
cpp/open3d/ml/TensorFlow/Misc/VoxelPoolingOpKernel.h
cpp/open3d/pipelines/color_map/EigenHelperForNonRigidOptimization.h
cpp/open3d/utility/Eigen.h
cpp/open3d/utility/IJsonConvertible.h
cpp/open3d/visualization/Rendering/Filament/FilamentCamera.h
cpp/open3d/visualization/Rendering/Filament/FilamentEntitiesMods.h
cpp/open3d/visualization/Rendering/Filament/FilamentRenderToBuffer.h
cpp/open3d/visualization/Rendering/Filament/FilamentRenderer.h
cpp/open3d/visualization/Rendering/Filament/FilamentResourceManager.h
cpp/open3d/visualization/Rendering/Filament/FilamentScene.cpp
cpp/open3d/visualization/Rendering/Filament/FilamentScene.h
cpp/open3d/visualization/Rendering/Filament/FilamentView.h
cpp/open3d/visualization/Rendering/RendererHandle.h
docs/Doxyfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1975)

doxygen: fix for reorg; cleanup namespaces

---

cpp/open3d/ml/Helper.h
cpp/open3d/ml/TensorFlow/CMakeLists.txt
cpp/open3d/ml/TensorFlow/ContinuousConv/ContinuousConvBackpropFilterOpKernel.cu
cpp/open3d/ml/TensorFlow/ContinuousConv/ContinuousConvOpKernel.cu
cpp/open3d/ml/TensorFlow/ContinuousConv/ContinuousConvTransposeBackpropFilterOpKernel.cu
cpp/open3d/ml/TensorFlow/ContinuousConv/ContinuousConvTransposeOpKernel.cu
cpp/open3d/ml/TensorFlow/Misc/BuildSpatialHashTableOpKernel.cu
cpp/open3d/ml/TensorFlow/Misc/FixedRadiusSearchOpKernel.cu
cpp/open3d/ml/TensorFlow/Misc/InvertNeighborsListOpKernel.cu

Linking the main library will cause side effects when using graph mode and cuda.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1981)

do not link main library when building the tf ops lib

---

cpp/apps/Open3DViewer/Info.plist.in

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2001)

Updated Info.plist file to make Open3D default, add .pcd support

---

cpp/open3d/visualization/visualizer/Visualizer.cpp

Addressing #1991
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2008)

std::min of extent in visualizer

---

cpp/open3d/ml/Misc/Detail/VoxelPooling.h
cpp/open3d/ml/TensorFlow/Misc/VoxelPoolingGradOpKernel.h
cpp/open3d/ml/TensorFlow/Misc/VoxelPoolingOpKernel.cpp
cpp/open3d/ml/TensorFlow/Misc/VoxelPoolingOpKernel.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2014)

remove voxel_pooling namespace

---

cpp/open3d/visualization/gui/Button.cpp
cpp/open3d/visualization/gui/Checkbox.cpp
cpp/open3d/visualization/gui/Combobox.cpp
cpp/open3d/visualization/gui/ImageLabel.cpp
cpp/open3d/visualization/gui/Label.cpp
cpp/open3d/visualization/gui/Layout.cpp
cpp/open3d/visualization/gui/NumberEdit.cpp
cpp/open3d/visualization/gui/TextEdit.cpp
cpp/open3d/visualization/gui/Util.cpp
cpp/open3d/visualization/gui/Util.h
cpp/open3d/visualization/gui/VectorEdit.cpp
cpp/open3d/visualization/gui/Window.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2013)

Removed visualization::gui::util namespace

---

CMakeLists.txt
docs/contribute/styleguide.rst
util/scripts/check_cpp_style.cmake
util/scripts/check_style.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2016)

add make check-cpp-style, apply-cpp-style

---

cpp/open3d/geometry/TriangleMeshFactory.cpp
cpp/tests/geometry/TriangleMesh.cpp

Addressing #2010
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2034)

fix coord frame origin bug

---

cpp/open3d/geometry/SurfaceReconstructionPoisson.cpp
cpp/open3d/geometry/TriangleMesh.h
cpp/pybind/geometry/trianglemesh.cpp

Addressing #2027.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2035)

expose poisson rec threads param

---

util/scripts/run-ci.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2048)

fix path in run-ci.sh

---

.appveyor.yml
README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2059)

update CI badges, remove appveyor

---

docs/compilation.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2055)

Docs updated for build with CUDA

---

3rdparty/filament/filament_download.cmake

Use `FetchContent` to download Filament.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2085)

fetch Filament with FetchContent

---

cpp/open3d/visualization/gui/SceneWidget.cpp
cpp/open3d/visualization/gui/SceneWidget.h
cpp/open3d/visualization/rendering/Open3DScene.cpp
cpp/open3d/visualization/visualizer/GuiVisualizer.cpp
cpp/pybind/io/class_io.cpp
cpp/pybind/make_python_package.cmake
cpp/pybind/visualization/gui/gui.cpp
cpp/pybind/visualization/rendering/rendering.cpp
cpp/pybind/visualization/rendering/rendering.h
cpp/pybind/visualization/visualization.cpp
examples/python/GUI/vis-gui.py
python/open3d/visualization/rendering/__init__.py
python/setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2113)

Added pybinds open3d::visualization::rendering and implement Python equivalent of vis app

---

cpp/pybind/core/tensor.cpp
python/open3d/core.py
python/test/core/test_core.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2130)

support Tensor.item() in pybind

---

.github/workflows/windows.yml
3rdparty/find_dependencies.cmake
3rdparty/mkl/mkl.cmake
CMakeLists.txt
cpp/open3d/core/CMakeLists.txt
cpp/open3d/core/kernel/Kernel.cpp
cpp/open3d/core/kernel/Kernel.h
cpp/open3d/ml/PyTorch/Misc/ReduceSubarraysSumOpKernel.cu
cpp/pybind/core/core.h
cpp/pybind/core/kernel.cpp
util/scripts/run-ci.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2128)

MKL integration with tests

---

cpp/open3d/visualization/gui/Window.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2133)

Fixed hidpi on Linux

---

cpp/open3d/visualization/gui/Application.cpp
cpp/open3d/visualization/gui/Native.h
cpp/open3d/visualization/gui/NativeMacOS.mm

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2143)

Tell macOS that Python using GUI on macOS works like an app

---

.travis.yml
docs/builddocs.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2154)

pin python deps version for building docs

---

docs/contribute/styleguide.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2166)

fix macos style guide docs render

---

.github/workflows/windows.yml
CMakeLists.txt
examples/CMakeLists.txt
examples/cpp/CMakeLists.txt
examples/cpp/iterative_build_examples.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2199)

Build examples iteratively on Windows CI

---

cpp/apps/Open3DViewer/Info.plist.in
cpp/apps/Open3DViewer/Open3DViewer.desktop.in
cpp/apps/Open3DViewer/Open3DViewer.xml
cpp/open3d/visualization/visualizer/GuiVisualizer.cpp
examples/python/GUI/vis-gui.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2204)

Added FBX to Open3DViewer dialog

---

cpp/open3d/visualization/gui/NativeMacOS.mm
cpp/pybind/visualization/gui/gui.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2237)

More ml-vis fixes

---

cpp/pybind/tgeometry/geometry.cpp
cpp/pybind/visualization/gui/gui.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2238)

style fix for master

---

.github/workflows/documentation.yml
.github/workflows/style.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2240)

build style/docs on PR or commit on master

---

cpp/open3d/visualization/gui/Materials/defaultLit.mat

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2239)

Enable transparency for lit material

---

util/run_ci.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2242)

verbose TestVisualizer build

---

util/run_ci.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2247)

ci: build with release, rm cuda run file

---

cpp/open3d/io/file_format/FileASSIMP.cpp
cpp/open3d/visualization/gui/Materials/defaultLit.mat
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2243)

Fix rendering anomalies with ao/rough/metal texture

---

cpp/open3d/io/file_format/FileASSIMP.cpp
cpp/open3d/visualization/gui/Materials/defaultLitTransparency.mat
cpp/open3d/visualization/rendering/Material.h
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.h
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2258)

Add shader for materials with transparency

---

.github/workflows/gce-ubuntu-docker.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2262)

Skip GCE CI if secrets are not available (forks)

---

cpp/open3d/io/file_format/FileASSIMP.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2265)

Fix how base color is extracted from Assimp

---

cpp/open3d/core/nns/NearestNeighborSearch.h
cpp/pybind/core/nns/nearest_neighbor_search.cpp

the original pr was merged too soon
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2269)

quick docstring fix for junha/nn_pybind

---

examples/python/GUI/vis-gui.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2273)

Fix vis-gui.py not being able to load any geometry (see 2268)

---

cpp/open3d/visualization/gui/Materials/unlitGradient.mat
cpp/open3d/visualization/rendering/Gradient.cpp
cpp/open3d/visualization/rendering/Gradient.h
cpp/open3d/visualization/rendering/Material.h
cpp/open3d/visualization/rendering/MaterialModifier.cpp
cpp/open3d/visualization/rendering/MaterialModifier.h
cpp/open3d/visualization/rendering/Open3DScene.cpp
cpp/open3d/visualization/rendering/Open3DScene.h
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.h
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/rendering/filament/FilamentScene.h
cpp/open3d/visualization/rendering/filament/PointCloudBuffers.cpp
cpp/pybind/visualization/rendering/rendering.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2263)

Added unlitGradient shader for colormaps and LUT

---

cpp/pybind/core/core.cpp
cpp/pybind/open3d_pybind.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2278)

use pybind11's gil management

---

cpp/pybind/core/core.cpp
cpp/pybind/pybind_utils.cpp
cpp/pybind/pybind_utils.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2277)

fix windows python dtype convert

---

cpp/open3d/visualization/gui/Materials/unlitGradient.mat
cpp/pybind/visualization/rendering/rendering.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2285)

Minor fixes ml/vis fixes

---

examples/python/GUI/vis-gui.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2274)

Fix 'All' option in file dialog in vis-gui.py

---

cpp/open3d/ml/PyTorch/Misc/BuildSpatialHashTableOps.cpp
cpp/open3d/ml/PyTorch/Misc/FixedRadiusSearchOps.cpp
cpp/open3d/ml/PyTorch/Misc/KnnSearchOps.cpp
cpp/open3d/ml/PyTorch/Misc/RadiusSearchOps.cpp
cpp/open3d/ml/TensorFlow/ContinuousConv/ContinuousConvOps.cpp
cpp/open3d/ml/TensorFlow/Misc/BuildSpatialHashTableOps.cpp
cpp/open3d/ml/TensorFlow/Misc/FixedRadiusSearchOps.cpp
cpp/open3d/ml/TensorFlow/Misc/InvertNeighborsListOps.cpp
cpp/open3d/ml/TensorFlow/Misc/KnnSearchOps.cpp
cpp/open3d/ml/TensorFlow/Misc/RadiusSearchOps.cpp
cpp/open3d/ml/TensorFlow/Misc/ReduceSubarraysSumOps.cpp
cpp/open3d/ml/TensorFlow/Misc/VoxelPoolingOps.cpp
cpp/open3d/ml/impl/misc/KnnSearch.h
python/open3d/ml/tf/python/layers/convolutions.py
python/open3d/ml/tf/python/layers/neighbor_search.py
python/open3d/ml/torch/python/layers/convolutions.py
python/open3d/ml/torch/python/layers/neighbor_search.py

This PR
- improves docstrings for layers and ops
- fixes some missing or wrong default args in torch layers/ops
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2296)

improved doc for ml layers and ops

---

.github/workflows/documentation.yml
docs/documented_modules.txt
docs/index.rst
docs/make_docs.py
docs/python_api_in/open3d.ml.tf.layers.ContinuousConv.rst
docs/python_api_in/open3d.ml.torch.nn.ContinuousConv.rst

This PR adds the ml module to the doc system and allows to override generated rst files with custom files in `python_api_in`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2293)

ml doc fix and custom api doc files

---

3rdparty/find_dependencies.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2297)

make 3rdparty_tbb depend on ext_tbb

---

python/open3d/ml/tf/__init__.py
python/open3d/ml/torch/__init__.py

Explicitly import each module from ml3d.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2298)

change ml3d import method

---

cpp/pybind/visualization/gui/gui.cpp
cpp/pybind/visualization/rendering/rendering.cpp
examples/python/GUI/vis-gui.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2299)

vis-gui.py example fixes

---

docs/python_api_in/open3d.ml.tf.layers.FixedRadiusSearch.rst
docs/python_api_in/open3d.ml.tf.layers.KNNSearch.rst
docs/python_api_in/open3d.ml.tf.layers.RadiusSearch.rst
docs/python_api_in/open3d.ml.tf.layers.SparseConv.rst
docs/python_api_in/open3d.ml.tf.layers.SparseConvTranspose.rst
docs/python_api_in/open3d.ml.tf.layers.rst
docs/python_api_in/open3d.ml.tf.ops.rst
docs/python_api_in/open3d.ml.torch.nn.FixedRadiusSearch.rst
docs/python_api_in/open3d.ml.torch.nn.KNNSearch.rst
docs/python_api_in/open3d.ml.torch.nn.RadiusSearch.rst
docs/python_api_in/open3d.ml.torch.nn.SparseConv.rst
docs/python_api_in/open3d.ml.torch.nn.SparseConvTranspose.rst
docs/python_api_in/open3d.ml.torch.nn.functional.rst
docs/python_api_in/open3d.ml.torch.nn.rst
python/open3d/ml/tf/__init__.py
python/open3d/ml/tf/layers/__init__.py
python/open3d/ml/tf/ops/__init__.py
python/open3d/ml/tf/python/layers/convolutions.py
python/open3d/ml/torch/__init__.py
python/open3d/ml/torch/nn/__init__.py
python/open3d/ml/torch/nn/functional/__init__.py

This PR adds
- doc strings for modules
- more custom .rst files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2302)

more ml doc improvements

---

python/test/core/test_core.py
python/test/core/test_torch_integration.py
python/test/open3d_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2304)

list pytorch device correctly for pytest

---

cpp/open3d/io/file_format/FilePNG.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2326)

Fix handling of 4 channel images on PNG export

---

.github/workflows/windows.yml
cpp/pybind/ml/contrib/contrib_subsample.cpp
python/test/ml/test_contrib_subsample.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2321)

fix contrib-subsample unit test order

---

docs/python_api_in/open3d.ml.tf.layers.VoxelPooling.rst
docs/python_api_in/open3d.ml.tf.layers.rst
docs/python_api_in/open3d.ml.torch.nn.VoxelPooling.rst
docs/python_api_in/open3d.ml.torch.nn.rst
python/open3d/ml/tf/layers/__init__.py
python/open3d/ml/tf/python/layers/voxel_pooling.py
python/open3d/ml/torch/nn/__init__.py
python/open3d/ml/torch/python/layers/voxel_pooling.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2322)

Layer interface for voxel_pooling op

---

cpp/open3d/visualization/rendering/Open3DScene.cpp
cpp/open3d/visualization/rendering/Open3DScene.h
cpp/open3d/visualization/rendering/Scene.h
cpp/open3d/visualization/rendering/filament/FilamentGeometryBuffersBuilder.h
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.h
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/rendering/filament/FilamentScene.h
cpp/open3d/visualization/rendering/filament/LineSetBuffers.cpp
cpp/open3d/visualization/rendering/filament/PointCloudBuffers.cpp
cpp/open3d/visualization/rendering/filament/TriangleMeshBuffers.cpp
cpp/pybind/visualization/rendering/rendering.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2318)

Downsample point clouds with by using a different index array

---

3rdparty/find_dependencies.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2334)

Remove looking for X11 on macOS

---

python/open3d/ml/__init__.py
python/open3d/ml/contrib/__init__.py
python/open3d/ml/datasets.py
python/open3d/ml/tf/__init__.py
python/open3d/ml/tf/layers/__init__.py
python/open3d/ml/tf/ops/__init__.py
python/open3d/ml/tf/python/layers/convolutions.py
python/open3d/ml/tf/python/layers/neighbor_search.py
python/open3d/ml/tf/python/layers/voxel_pooling.py
python/open3d/ml/tf/python/ops/gradients.py
python/open3d/ml/tf/python/ops/lib.py
python/open3d/ml/tf/python/ops/ops.py.in
python/open3d/ml/torch/__init__.py
python/open3d/ml/torch/layers/__init__.py
python/open3d/ml/torch/ops/__init__.py
python/open3d/ml/torch/python/layers/convolutions.py
python/open3d/ml/torch/python/layers/neighbor_search.py
python/open3d/ml/torch/python/layers/voxel_pooling.py
python/open3d/ml/torch/python/ops.py.in
python/open3d/ml/torch/python/return_types.py.in

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2333)

added missing license header in ml module py files

---

cpp/open3d/visualization/rendering/filament/FilamentScene.cpp

Prevents duplicate object names
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2339)

Fix crash on Abandoned FBX model

---

cpp/open3d/visualization/gui/Application.cpp
cpp/open3d/visualization/gui/Window.cpp
cpp/open3d/visualization/gui/Window.h
cpp/pybind/visualization/gui/gui.cpp

Also adds pybind that was never uncommented.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2348)

Clean up Filament to avoid crashes.

---

cpp/open3d/visualization/rendering/Open3DScene.cpp
cpp/open3d/visualization/rendering/Open3DScene.h
cpp/pybind/visualization/rendering/rendering.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2349)

Added ability to change downsample threshold in Open3DScene

---

cpp/open3d/visualization/gui/Materials/unlitSolidColor.mat
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.h
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/rendering/filament/FilamentScene.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2352)

Added unlitSolidColor shader

---

cpp/open3d/visualization/rendering/filament/FilamentGeometryBuffersBuilder.h
cpp/open3d/visualization/rendering/filament/PointCloudBuffers.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2355)

Better algorithm for downsampling

---

cpp/open3d/visualization/rendering/filament/PointCloudBuffers.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2363)

Added special name for TPointCloud rendering to create UV arrays from scalar on C++ side

---

cpp/open3d/visualization/rendering/Open3DScene.cpp
cpp/open3d/visualization/rendering/Open3DScene.h
cpp/open3d/visualization/rendering/filament/PointCloudBuffers.cpp

Also fixes a bug with index downsampling
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2371)

Add bounding-box-only mode for rotation.

---

cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/rendering/filament/PointCloudBuffers.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2376)

Add "__visualization_scalar" handling to FilamentScene::UpdateGeometry

---

cpp/pybind/visualization/rendering/rendering.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2383)

Add has_alpha to pybind for Material

---

cpp/open3d/visualization/gui/SceneWidget.cpp
cpp/open3d/visualization/gui/SceneWidget.h
cpp/open3d/visualization/rendering/Open3DScene.cpp
cpp/open3d/visualization/rendering/Renderer.h
cpp/open3d/visualization/rendering/Scene.h
cpp/open3d/visualization/rendering/filament/FilamentRenderer.cpp
cpp/open3d/visualization/rendering/filament/FilamentRenderer.h
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/rendering/filament/FilamentScene.h
cpp/open3d/visualization/visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2384)

Improve UI responsiveness when viewing large models

---

python/open3d/ml/tf/__init__.py
python/open3d/ml/torch/__init__.py

This adds the vis namespace from Open3D-ML
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2394)

add ml vis namespace

---

cpp/open3d/visualization/gui/Materials/defaultLitTransparency.mat
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2396)

Add alpha to baseColor of shader (and simplify some shader calculations)

---

docs/compilation.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2401)

added documentation about the ml build options

---

3rdparty/mkl/tbb.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2431)

Fix for cmake externalproject_add patch_command

---

util/run_ci.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2428)

Ensure C++ and Python units tests always run

---

.github/workflows/openblas.yml
3rdparty/filament/filament_build.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2438)

ubuntu 20.04 build filament from source CI

---

cpp/open3d/visualization/gui/NumberEdit.cpp
cpp/open3d/visualization/gui/NumberEdit.h
cpp/pybind/visualization/gui/gui.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2373)

Added ability to set the preferred with of gui::NumberEdit

---

.github/workflows/openblas.yml
3rdparty/filament/filament_build.cmake
3rdparty/filament/filament_download.cmake
3rdparty/openblas/openblas.cmake
CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2449)

rollback filament to 1.8.1

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2457)

ignore configured .in files for docs

---

.github/workflows/openblas.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2459)

pass filament compile cache

---

cpp/open3d/visualization/rendering/filament/FilamentScene.h

Somehow this got left out of #2452 (although it was committed on my machine, which seems strange).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2463)

Other half of #2452

---

python/open3d/ml/__init__.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2473)

added missing imports to open3d.ml namespace

---

docs/arm.rst
docs/contribute/styleguide.rst
examples/python/geometry/iss_keypoint_detector.ipynb
examples/python/geometry/pointcloud.ipynb
examples/python/geometry/surface_reconstruction.ipynb
examples/python/pipelines/icp_registration.ipynb
examples/python/pipelines/robust_kernels.ipynb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2474)

consistent sidebar lower case

---

docs/versions.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2482)

remove 0.10.1 docs link

---

.github/workflows/documentation.yml
.github/workflows/windows.yml
CMakeLists.txt
docs/make_docs.py

+ Fix for Windows release wheel version (Correct handling of DEVELOPER_BUILD in powershell)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2484)

Documentation build fix (Jupyter + Python visualization.{gui,rendering})

---

README.md
docs/index.rst
docs/open3d_ml.rst

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2486)

ml docs on readme and rst

---

README.md
docs/compilation.rst
examples/python/geometry/python_interface.ipynb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2488)

fix broken links

---

cpp/open3d/visualization/gui/Application.cpp
cpp/open3d/visualization/gui/Application.h
cpp/pybind/visualization/gui/gui.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2499)

Change pybind's run() to not cleanup at the end.

---

cpp/open3d/visualization/gui/Application.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2502)

Fix deadlock with ml3d visualizer on macOS

---

python/open3d/ml/torch/__init__.py
util/ci_utils.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2496)

test import of torch and tensorflow

---

cpp/open3d/geometry/Line3D.h

fixes #2487
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2491)

fix ambiguous transform

---

python/open3d/ml/torch/__init__.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2503)

better error msg for cuda mismatch

---

cpp/open3d/visualization/gui/Materials/unlitGradient.mat

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2512)

Fix z-buffering problem with labels/gradients in ml3d visualizer

---

3rdparty/filament/filament_build.cmake
3rdparty/filament/filament_download.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2517)

Errissa/filament 1.9.5

---

examples/python/gui/add-geometry.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2515)

Added example to add geometry to a scene using the new GUI.

---

cpp/pybind/pipelines/registration/robust_kernels.cpp

Fix https://github.com/intel-isl/Open3D/issues/2505
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2535)

replace the non utf-8 char “” with ""

---

docs/compilation.rst

Some commands in compilation doc can't work, this PR fixes them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2536)

Fix compilation doc

---

3rdparty/assimp/ObjFileData.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2532)

Give sheen a default value (i.e., don't leave it unitialized)

---

cpp/open3d/geometry/TriangleMeshSimplification.cpp

Resolves #2444.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2542)

Change a wrong variable in TriangleMeshSimplification.cpp

---

examples/python/reconstruction_system/initialize_config.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2574)

fix string to boolean

---

cpp/pybind/geometry/trianglemesh.cpp

Solves issue #2089
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2573)

Add pybind for triangle_material_ids

---

cpp/open3d/geometry/PointCloudFactory.cpp

Fixes Issue #2547
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2577)

Add support for 4 channel (RGBA) color images to CreateFromRGBDImage

---

cpp/open3d/io/file_format/FileASSIMP.cpp

Addresses issues #1638 and #2510
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2576)

Update to match material handling of old OBJ file loader

---

cpp/open3d/visualization/visualizer/Visualizer.cpp
cpp/open3d/visualization/visualizer/VisualizerRender.cpp

Addresses issues #1550
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2579)

Log non-fatal GLFW errors as warnings instead of errors

---

python/open3d/ml/torch/python/layers/convolutions.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2590)

automatically cast int extents to the right type

---

cpp/open3d/visualization/rendering/Open3DScene.cpp
cpp/open3d/visualization/rendering/Open3DScene.h
cpp/pybind/visualization/rendering/rendering.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2612)

Add functions to Open3DScene for ML vis changes

---

cpp/open3d/visualization/gui/Materials/depth.mat

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2626)

Modify shader to work with Filament's new inverse z buffer

---

.github/workflows/documentation.yml
.github/workflows/gce-ubuntu-docker.yml
.github/workflows/macos.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
util/docker/open3d-gpu/scripts/gce-ubuntu-docker-run.sh

Update GCE GPU availability zones.
To fix CI failure: https://github.com/intel-isl/Open3D/actions/runs/366842560 reported by @prewettg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2631)

Substitute set-env with environment files

---

examples/python/gui/all-widgets.py
examples/python/gui/render-to-image.py
examples/python/gui/vis-gui.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2629)

Fixes for LGTM warnings

---

cpp/open3d/t/geometry/PointCloud.h
cpp/open3d/t/io/PointCloudIO.cpp
cpp/open3d/t/io/PointCloudIO.h
cpp/open3d/t/io/file_format/FilePLY.cpp
cpp/pybind/t/geometry/pointcloud.cpp
cpp/tests/t/io/PointCloudIO.cpp

Write tensor point cloud with custom attributes support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2594)

write point cloud with custom attributes

---

cpp/open3d/utility/FileSystem.cpp
cpp/open3d/utility/FileSystem.h
cpp/open3d/visualization/gui/Application.cpp
cpp/open3d/visualization/gui/Application.h
cpp/open3d/visualization/gui/Window.cpp
cpp/pybind/visualization/gui/gui.cpp
examples/python/gui/non-english.py

Adds support for international characters in the GUI, see the added `examples/python/non-english.py`.  Fixes issue #2600.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2655)

Added support for international characters in the GUI

---

cpp/open3d/visualization/visualizer/Receiver.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2691)

fix windows warning (as error) on master

---

docs/tutorial/sensor/azure_kinect.rst
python/open3d/__init__.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2718)

remove 16.04 kinect workaround

---

cpp/open3d/t/geometry/PointCloud.cpp
cpp/open3d/t/geometry/PointCloud.h
cpp/tests/t/geometry/PointCloud.cpp
python/test/t/geometry/test_pointcloud.py

It's just to fix the build issues on Master.
The transform function is yet to be revisited for making it more generalized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2725)

[URGENT] Build Fix for Master

---

cpp/open3d/core/nns/FaissIndex.cpp
cpp/open3d/core/nns/FixedRadiusIndex.cpp
cpp/open3d/core/nns/NNSIndex.cpp
cpp/open3d/core/nns/NNSIndex.h
cpp/open3d/core/nns/NanoFlannIndex.cpp
cpp/open3d/core/nns/NanoFlannIndex.h
cpp/open3d/core/nns/NearestNeighborSearch.cpp
cpp/tests/core/NearestNeighborSearch.cpp
python/test/core/test_nn.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2752)

Enable HybridSearch on GPU

---

cpp/open3d/visualization/gui/SceneWidget.cpp
cpp/open3d/visualization/rendering/LightDirectionInteractorLogic.cpp
cpp/open3d/visualization/rendering/Open3DScene.cpp
cpp/open3d/visualization/rendering/Scene.h
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/rendering/filament/FilamentScene.h
cpp/open3d/visualization/visualizer/GuiVisualizer.cpp
cpp/open3d/visualization/visualizer/O3DVisualizer.cpp
cpp/pybind/visualization/rendering/rendering.cpp
examples/python/gui/add-geometry.py
examples/python/gui/render-to-image.py
examples/python/gui/vis-gui.py

* Added sun halo features
* Filled in missing implementation for dynamically changing shadow casting of lights.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2759)

Support multiple non-sun directional lights

---

cpp/open3d/visualization/gui/Materials/defaultUnlitTransparency.mat
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.h
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2760)

Add shader for unlit with transparency

---

cpp/open3d/visualization/rendering/Scene.h
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/rendering/filament/FilamentScene.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2764)

Fix background not being drawn in some camera orientations

---

cpp/open3d/ml/tensorflow/misc/NmsOpKernel.cu

Thanks @Prantl and @benjaminum for debugging the issue.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2770)

fix memcpy issue for nms cuda

---

cpp/open3d/visualization/rendering/filament/FilamentScene.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2771)

Fix punctual lights not being added to scene

---

python/open3d/visualization/_external_visualizer.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2772)

added compatible draw() function for external visualizer

---

cpp/open3d/visualization/rendering/filament/FilamentCamera.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2782)

Make sure projection flags are always properly initialized

---

cpp/open3d/visualization/gui/Materials/unlitBackground.mat

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2783)

Fix aspect ratios of background images for very wide/tall images

---

cpp/pybind/geometry/boundingvolume.cpp
cpp/pybind/io/class_io.cpp
cpp/pybind/visualization/gui/gui.cpp
cpp/pybind/visualization/rendering/rendering.cpp
python/open3d/visualization/draw.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2785)

Added python bindings, improved descriptiveness of __repr__ for bounding boxes, and added BG options to draw()

---

cpp/open3d/visualization/rendering/ColorGrading.cpp
cpp/open3d/visualization/rendering/ColorGrading.h
cpp/pybind/visualization/gui/gui.cpp
cpp/pybind/visualization/rendering/rendering.cpp

* SSR/Refraction material properties
* Color grading
* 3D Labels
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2794)

Add pybinds for new rendering features

---

examples/python/reconstruction_system/tintegrate_scene.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2795)

performance fix for python TSDF integration

---

cpp/pybind/visualization/rendering/rendering.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2802)

Add pybind for adding a TriangleMeshModel to the scene

---

cpp/open3d/visualization/rendering/filament/FilamentView.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2798)

Have temporal anti-aliasing disabled by default

---

cpp/open3d/core/kernel/GeneralEWCPU.cpp
cpp/open3d/core/kernel/GeneralEWCUDA.cu
cpp/open3d/core/kernel/GeneralEWSharedImpl.h
cpp/open3d/t/geometry/TSDFVoxelGrid.cpp
examples/cpp/TIntegrateRGBD.cpp
examples/python/reconstruction_system/tintegrate_scene.py

This PR identifies several memory issues caused by inappropriate parameter setups. Added error messages accordingly:
- Zero block count due to incorrect depth scale.
- Illegal memory access caused by too large `sdf_trunc / block_size`.
- Out-of-memory issues caused by limited memory budget and high resolution / large scale scenes.
It also introduces some improvements in python/cpp examples with more parameter support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2805)

TIntegrateRGBD updates

---

cpp/pybind/CMakeLists.txt
cpp/pybind/docstring.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2810)

add python2 error message

---

.github/workflows/documentation.yml
.github/workflows/windows.yml
CMakeLists.txt
cpp/open3d/core/hashmap/CUDA/InternalNodeManager.h
cpp/open3d/core/nns/MemoryAllocation.h
cpp/open3d/geometry/Keypoint.h
cpp/open3d/pipelines/registration/TransformationEstimation.h
docs/tutorial/sensor/realsense.rst
util/ci_utils.sh

Fix pip version in docs build to prevent policy change
uninstall Open3d before rebuilding with GUI
doxygen typo fixes
Realsense tutorial video
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2808)

Gui Rendering docs build

---

cpp/open3d/visualization/gui/Materials/unlitLine.mat
cpp/open3d/visualization/visualizer/O3DVisualizer.cpp
cpp/open3d/visualization/visualizer/O3DVisualizer.h

* Enables wide lines in Draw example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2809)

Ensure consistent rendering of wide lines in all viewing angles

---

examples/cpp/Draw.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2811)

Add check for selected points before running ICP (to prevent crash)

---

cpp/pybind/visualization/gui/gui.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2816)

Fix crashes on exit due to Window not being destroyed

---

cpp/open3d/visualization/gui/Window.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2817)

Fix dialogs flickering when dismissed on Mac

---

cpp/open3d/visualization/gui/FileDialog.cpp
cpp/open3d/visualization/gui/FileDialog.h
cpp/open3d/visualization/gui/FileDialogNative.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2818)

Automatically add extension to non-native file dialog if none is specified

---

.github/workflows/macos.yml
.github/workflows/windows.yml
README.md
cpp/pybind/CMakeLists.txt
docs/getting_started.rst.in
python/conda_meta/meta.yaml

See: 
https://github.com/intel-isl/Open3D-ML/pull/200
and 
https://github.com/intel-isl/Open3D/issues/2825
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2826)

add ml deps for conda build

---

cpp/open3d/core/Tensor.cpp
cpp/open3d/core/Tensor.h
cpp/open3d/core/kernel/UnaryEW.h
cpp/open3d/core/kernel/UnaryEWCPU.cpp
cpp/open3d/core/kernel/UnaryEWCUDA.cu
cpp/pybind/core/tensor.cpp
cpp/tests/core/Tensor.cpp
python/test/core/test_core.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2848)

Add numerical operations to Tensor

---

cpp/open3d/core/CMakeLists.txt
cpp/open3d/core/Tensor.cpp
cpp/open3d/core/Tensor.h
cpp/open3d/core/kernel/Arange.cpp
cpp/open3d/core/kernel/Arange.h
cpp/open3d/core/kernel/ArangeCPU.cpp
cpp/open3d/core/kernel/ArangeCUDA.cu
cpp/open3d/core/kernel/GeneralEW.h
cpp/open3d/core/kernel/GeneralEWCPU.cpp
cpp/open3d/core/kernel/GeneralEWCUDA.cu
cpp/pybind/core/tensor.cpp
cpp/tests/core/Tensor.cpp
python/conda_meta/meta.yaml
python/requirements.txt
python/test/core/test_core.py
util/ci_utils.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2849)

Implement np style arange for Tensor

---

cpp/open3d/core/CMakeLists.txt
cpp/open3d/core/NumpyIO.cpp
cpp/open3d/core/NumpyIO.h
cpp/open3d/core/ShapeUtil.cpp
cpp/open3d/core/ShapeUtil.h
cpp/open3d/core/Tensor.cpp
cpp/open3d/core/Tensor.h
cpp/open3d/core/hashmap/Hashmap.cpp
cpp/pybind/core/tensor.cpp
cpp/pybind/make_install_pip_package.cmake
cpp/tests/core/Tensor.cpp
examples/cpp/TIntegrateRGBD.cpp
python/test/core/test_core.py

Added:
```cpp
Tensor::Save();
Tensor::Load();
```
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2859)

numpy-compatible tensor IO

---

3rdparty/mkl/mkl.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2882)

update mkl download links

---

3rdparty/CMake/FindCUB.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2913)

fix incompatible CUB include dir with CUDA 11 and later

---

examples/python/gui/textured-model.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2935)

Python example of using a texture on a Material

---

cpp/open3d/visualization/gui/SceneWidget.cpp
cpp/open3d/visualization/gui/SceneWidget.h
cpp/open3d/visualization/rendering/Scene.h
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/rendering/filament/FilamentScene.h
cpp/open3d/visualization/visualizer/GuiSettingsModel.cpp
cpp/open3d/visualization/visualizer/GuiSettingsModel.h
cpp/open3d/visualization/visualizer/GuiSettingsView.cpp
cpp/open3d/visualization/visualizer/GuiSettingsView.h
cpp/open3d/visualization/visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2944)

Mode For Light To Follow Camera

---

cpp/open3d/visualization/gui/SceneWidget.cpp
cpp/open3d/visualization/gui/SceneWidget.h
cpp/open3d/visualization/rendering/filament/FilamentCamera.cpp
cpp/open3d/visualization/visualizer/O3DVisualizer.cpp
cpp/pybind/visualization/gui/gui.cpp
cpp/pybind/visualization/o3dvisualizer.cpp
python/open3d/visualization/draw.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2936)

Added ability to set camera in open3d.visualization.draw()

---

cpp/open3d/visualization/gui/SceneWidget.cpp
cpp/open3d/visualization/gui/SceneWidget.h
cpp/open3d/visualization/rendering/CameraSphereInteractorLogic.cpp
cpp/open3d/visualization/rendering/CameraSphereInteractorLogic.h
cpp/open3d/visualization/visualizer/O3DVisualizer.cpp
cpp/open3d/visualization/visualizer/O3DVisualizer.h
cpp/pybind/visualization/gui/gui.cpp
cpp/pybind/visualization/o3dvisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2962)

Mouse movement by spherical coordinates

---

.github/workflows/openblas.yml
.github/workflows/ubuntu.yml
util/ci_utils.sh

See: https://github.com/intel-isl/Open3D/actions/runs/530363966
https://github.com/easimon/maximize-build-space/blob/master/action.yml
```
Filesystem      Size  Used Avail Use% Mounted on
udev            3.4G     0  3.4G   0% /dev
tmpfs           696M  680K  695M   1% /run
/dev/sdb1        84G   64G   20G  77% /         <- Working directory /home/runner/work/Open3D/Open3D
tmpfs           3.4G  8.0K  3.4G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.4G     0  3.4G   0% /sys/fs/cgroup
/dev/sdb15      105M  3.7M  101M   4% /boot/efi
/dev/sda1        14G  4.1G  9.0G  32% /mnt
```
```
Filesystem      Size  Used Avail Use% Mounted on
udev            3.4G     0  3.4G   0% /dev
tmpfs           696M  680K  695M   1% /run
/dev/sdb1        84G   23G   62G  27% / …
```

free up disk space for ubuntu CI

---

cpp/open3d/visualization/rendering/MatrixInteractorLogic.cpp
cpp/open3d/visualization/rendering/MatrixInteractorLogic.h
cpp/open3d/visualization/rendering/ModelInteractorLogic.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3011)

Mousewheel dollies based on distance from center of rotation rather than size of model

---

cpp/open3d/t/geometry/TSDFVoxelGrid.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3030)

Remove unnecessary include causing unwanted compile dependencies

---

cpp/pybind/visualization/rendering/rendering.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3033)

Added python bindings for rendering::Camera

---

cpp/open3d/core/Dispatch.h
cpp/open3d/core/Dtype.cpp
cpp/open3d/core/Dtype.h
cpp/open3d/core/NumpyIO.cpp
cpp/open3d/core/Scalar.h
cpp/open3d/core/Tensor.cpp
cpp/open3d/t/geometry/TSDFVoxelGrid.cpp
cpp/pybind/core/dtype.cpp
cpp/pybind/core/tensor.cpp
cpp/pybind/pybind_utils.cpp
python/test/core/test_core.py

This was a part of #2972. Some more tests were added and pulled out as a separate PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3035)

add int16 dtype and some tests

---

cpp/open3d/visualization/rendering/filament/FilamentScene.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3048)

Change UpdateGeometry to work on updates where vertex count changes

---

cpp/open3d/visualization/gui/Materials/unlitBackground.mat
cpp/open3d/visualization/gui/SceneWidget.cpp
cpp/open3d/visualization/rendering/Open3DScene.cpp
cpp/open3d/visualization/rendering/Open3DScene.h
cpp/open3d/visualization/rendering/Renderer.h
cpp/open3d/visualization/rendering/RendererHandle.cpp
cpp/open3d/visualization/rendering/RendererHandle.h
cpp/open3d/visualization/rendering/Scene.h
cpp/open3d/visualization/rendering/View.h
cpp/open3d/visualization/rendering/filament/FilamentRenderToBuffer.cpp
cpp/open3d/visualization/rendering/filament/FilamentRenderer.cpp
cpp/open3d/visualization/rendering/filament/FilamentRenderer.h
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.h
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/rendering/filament/FilamentScene.h
cpp/open3d/visualization/rendering/filament/FilamentView.cpp
cpp/open3d/visualization/rendering/filament/FilamentView.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3031)

Use RenderTargets For Scene Caching

---

cpp/pybind/visualization/gui/gui.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3045)

Add init pybind for Label3D

---

cpp/open3d/t/geometry/PointCloud.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3062)

Make sure invalid input triggers LogError instead of prematurely throwing exception

---

cpp/open3d/visualization/rendering/filament/FilamentScene.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3061)

Make sure bounding box is non-empty

---

cpp/pybind/t/geometry/tsdf_voxelgrid.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3058)

Add pybind param names to docstring for 'TSDFVoxelGrid.integrate'

---

.github/workflows/documentation.yml

Error: https://github.com/intel-isl/Open3D/actions/runs/585471938
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3071)

maximize build space for docs

---

cpp/open3d/utility/FileSystem.cpp
cpp/tests/utility/FileSystem.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3070)

[FileSystem] Fix GetPathComponents and unit tests on Windows.

---

util/check_cpp_style.cmake
util/check_style.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3086)

[Fix] Style-guide link update

---

cpp/open3d/visualization/gui/Label3D.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3096)

Fix issue with Label3D position not being set in constructor

---

cpp/pybind/visualization/rendering/rendering.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3104)

Added pybind for Camera::CopyFrom()

---

cpp/open3d/core/kernel/ReductionCUDA.cu
cpp/open3d/core/linalg/InverseCUDA.cpp
cpp/open3d/core/linalg/LeastSquaresCUDA.cpp
cpp/open3d/core/linalg/SVDCUDA.cpp
cpp/open3d/core/linalg/SolveCUDA.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3099)

[CUDA] Fix memory leaks.

---

util/docker/open3d-gpu/scripts/gce-ubuntu-docker-run.sh

Trying to fix (e.g in https://github.com/intel-isl/Open3D/runs/2027032298):
Reference: https://github.com/kyma-project/test-infra/issues/93#issuecomment-457263589
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3110)

Delete GCloud SSH keys to keep the profile small

---

cpp/open3d/visualization/gui/Menu.cpp
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp
cpp/open3d/visualization/rendering/filament/FilamentView.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3114)

Fixed crash when referencing submenus

---

cpp/open3d/visualization/gui/GLFWWindowSystem.cpp

The original changes: https://github.com/intel-isl/Open3D/commit/2ded6fac2895716a7c68e73eac5c51b4d2e34c7f#diff-d6211a57b3abf49ab21596a94e5fdc1dd01af58dca56681e6ef604cdbf22dfec
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3119)

Added the double-click code from Window.cpp in #2905 that got clobbered by the WindowSystem refactor

---

cpp/benchmarks/CMakeLists.txt
examples/cpp/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3124)

benchmark links 3rd-party library

---

util/docker/open3d-gpu/scripts/gce-ubuntu-docker-run.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3169)

gce disk size set to 48GB

---

3rdparty/filament/filament_build.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3179)

Modify Filament build from source to pull specific commit instead of branch

---

cpp/open3d/Open3D.h.in
cpp/open3d/visualization/gui/Application.cpp
cpp/open3d/visualization/gui/CMakeLists.txt
cpp/open3d/visualization/gui/ToggleSwitch.cpp
cpp/open3d/visualization/gui/ToggleSwitch.h
cpp/pybind/visualization/gui/gui.cpp
examples/python/gui/all-widgets.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3182)

Added gui::ToggleSwitch

---

cpp/open3d/core/Device.h
cpp/open3d/io/file_format/FilePCD.cpp
cpp/open3d/io/file_format/FilePTS.cpp
cpp/open3d/io/sensor/azure_kinect/K4aPlugin.cpp
cpp/open3d/utility/Console.cpp
cpp/open3d/utility/Helper.cpp
cpp/open3d/utility/Helper.h
cpp/open3d/visualization/gui/FileDialog.cpp
cpp/open3d/visualization/gui/NativeMacOS.mm
cpp/pybind/docstring.cpp
examples/cpp/IntegrateRGBD.cpp
examples/cpp/ProgramOptions.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3223)

SplitString returns tokens directly

---

.github/workflows/Dockerfile.openblas

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3225)

remove ENV in openblas docker

---

util/ci_utils.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3224)

clean up ci_utils for arm64

---

.github/workflows/Dockerfile.openblas

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3226)

less verbose tar print for arm docker

---

cpp/open3d/visualization/gui/SceneWidget.cpp
cpp/open3d/visualization/gui/SceneWidget.h
cpp/open3d/visualization/visualizer/O3DVisualizer.cpp
cpp/open3d/visualization/visualizer/O3DVisualizer.h
cpp/pybind/visualization/o3dvisualizer.cpp
examples/python/gui/text3d.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3233)

Added 3D labels to O3DVisualizer, added example

---

CHANGELOG.md
cpp/open3d/geometry/LineSet.h
cpp/open3d/geometry/LineSetFactory.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3255)

Added camera visualization to LineSet

---

cpp/open3d/geometry/BoundingVolume.h
cpp/open3d/io/OctreeIO.cpp
cpp/open3d/visualization/gui/Layout.cpp
cpp/open3d/visualization/gui/Layout.h
cpp/pybind/geometry/trianglemesh.cpp
cpp/pybind/visualization/gui/gui.cpp

Also: Fix #3268 error in CreateOctreeFromFile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3286)

get_is_open() for CollapsableVert widget

---

cpp/open3d/visualization/gui/ImageWidget.cpp
cpp/open3d/visualization/gui/ImageWidget.h
cpp/open3d/visualization/gui/UIImage.cpp
cpp/open3d/visualization/gui/UIImage.h
cpp/open3d/visualization/rendering/Renderer.h
cpp/open3d/visualization/rendering/filament/FilamentRenderer.cpp
cpp/open3d/visualization/rendering/filament/FilamentRenderer.h
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.h
cpp/pybind/t/geometry/geometry.cpp
cpp/pybind/t/geometry/image.cpp
cpp/pybind/t/geometry/pointcloud.cpp
cpp/pybind/t/geometry/trianglemesh.cpp
cpp/pybind/visualization/gui/gui.cpp
cpp/pybind/visualization/rendering/rendering.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3277)

Support TGeometry Image At Low Level and In Image Widget

---

python/MANIFEST.in

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3288)

simplify MANIFEST.in with graft

---

cpp/open3d/visualization/gui/PickPointsInteractor.cpp
cpp/open3d/visualization/gui/PickPointsInteractor.h
cpp/open3d/visualization/gui/SceneWidget.cpp
cpp/open3d/visualization/gui/SceneWidget.h
cpp/open3d/visualization/visualizer/O3DVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3252)

Added polygon picking

---

cpp/pybind/geometry/pointcloud.cpp
cpp/pybind/t/geometry/pointcloud.cpp
python/test/t/geometry/test_pointcloud.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3293)

voxel_down_sample pybind for t::pointcloud

---

cpp/open3d/visualization/gui/Button.cpp
cpp/open3d/visualization/gui/Checkbox.cpp
cpp/open3d/visualization/gui/ColorEdit.cpp
cpp/open3d/visualization/gui/ImageWidget.cpp
cpp/open3d/visualization/gui/Label.cpp
cpp/open3d/visualization/gui/NumberEdit.cpp
cpp/open3d/visualization/gui/Slider.cpp
cpp/open3d/visualization/gui/TextEdit.cpp
cpp/open3d/visualization/gui/ToggleSwitch.cpp
cpp/open3d/visualization/gui/VectorEdit.cpp
cpp/open3d/visualization/gui/Widget.cpp
cpp/open3d/visualization/gui/Widget.h
cpp/pybind/visualization/gui/gui.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3334)

Added tooltips

---

cpp/open3d/visualization/gui/Window.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3339)

Fix crash in Open3D Viewer when loading model (regression)

---

cpp/pybind/geometry/voxelgrid.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3292)

Fix error message when no correct arguments are provided

---

cpp/open3d/visualization/gui/Materials/defaultUnlit.mat
cpp/open3d/visualization/rendering/Material.h
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3340)

Add material property for supplying vertex colors in sRGB

---

cpp/open3d/t/geometry/kernel/ImageImpl.h

#3295 and another PR resulted in a merge issue in master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3344)

fix header include

---

examples/python/geometry/mesh.ipynb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3336)

Adjusted odd characters which were giving unicode charmap error

---

cpp/open3d/visualization/gui/VectorEdit.cpp

This fixes #3358
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3360)

Fix multiple VectorEdits in a UI not working

---

cpp/open3d/visualization/gui/Widget.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3348)

Make tooltips prettier

---

cpp/pybind/core/tensor.cpp
cpp/pybind/core/tensor_converter.cpp
cpp/pybind/core/tensor_converter.h
python/test/core/test_core.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3362)

fix scalar boolean handling in pybind

---

cpp/open3d/visualization/gui/Checkbox.cpp
cpp/open3d/visualization/gui/ColorEdit.cpp
cpp/open3d/visualization/gui/Combobox.cpp
cpp/open3d/visualization/gui/Layout.cpp
cpp/open3d/visualization/gui/ListView.cpp
cpp/open3d/visualization/gui/NumberEdit.cpp
cpp/open3d/visualization/gui/Slider.cpp
cpp/open3d/visualization/gui/TabControl.cpp
cpp/open3d/visualization/gui/TextEdit.cpp
cpp/open3d/visualization/gui/ToggleSwitch.cpp
cpp/open3d/visualization/gui/VectorEdit.cpp

Also removed use of std::stringstream in favor of std::to_string()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3369)

Fixed identically named Checkboxes and ToogleSwitches not working

---

cpp/open3d/visualization/gui/BitmapWindowSystem.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3370)

Unqueue dead window events

---

cpp/open3d/visualization/gui/GLFWWindowSystem.cpp
cpp/open3d/visualization/gui/Window.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3374)

Ensure offscreen buffer is properly resized when using BitmapWindowSystem

---

cpp/open3d/visualization/gui/Application.cpp
cpp/open3d/visualization/gui/Application.h
cpp/open3d/visualization/visualizer/O3DVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3385)

Don't add menus in Jupyter that are not meaningful

---

cpp/pybind/geometry/lineset.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3402)

Add pybinds for LineSet::CreateCameraVisualization()

---

cpp/open3d/visualization/utility/Draw.cpp
cpp/open3d/visualization/utility/Draw.h
cpp/open3d/visualization/visualizer/O3DVisualizer.cpp
cpp/open3d/visualization/visualizer/O3DVisualizer.h
cpp/pybind/visualization/o3dvisualizer.cpp
cpp/pybind/visualization/rendering/rendering.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3418)

Add support for TriangleMeshModel to O3DVisualizer and draw

---

cpp/open3d/visualization/visualizer/O3DVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3419)

Redraw when a new selection set is selected in O3DVisualizer

---

examples/cpp/VoxelHashingGUI.cpp

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3424)

Add FPS panel to voxelhashing gui

---

cpp/open3d/t/io/ImageIO.cpp
cpp/open3d/t/io/PointCloudIO.cpp
cpp/open3d/t/io/file_format/FilePLY.cpp
examples/cpp/VoxelHashingGUI.cpp

Convert CUDA pointcloud to CPU for ply write.
+ Support for writing CUDA images.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3436)

added support to write cuda pointcloud

---

3rdparty/webrtc/webrtc_common.cmake
3rdparty/webrtc/webrtc_download.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3446)

remove task queue objs from libwebrtc_extra

---

cpp/open3d/visualization/rendering/filament/FilamentScene.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3459)

Fix memory leak when updating normals with Scene::UpdateGeometry

---

3rdparty/find_dependencies.cmake
3rdparty/webrtc/webrtc_build.cmake
3rdparty/webrtc/webrtc_common.cmake
3rdparty/webrtc/webrtc_download.cmake
CMakeLists.txt
cpp/open3d/visualization/webrtc_server/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3458)

Use is_clang=false for WebRTC build

---

cpp/open3d/visualization/visualizer/O3DVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3460)

Fix crash when TriangleMesh has no material properties

---

cpp/open3d/visualization/gui/SceneWidget.cpp
cpp/open3d/visualization/gui/SceneWidget.h
cpp/open3d/visualization/rendering/IBLRotationInteractorLogic.cpp
cpp/open3d/visualization/rendering/IBLRotationInteractorLogic.h
cpp/open3d/visualization/rendering/Scene.h
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/rendering/filament/FilamentScene.h
cpp/open3d/visualization/visualizer/GuiVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3482)

Fix skybox not showing in O3DVisualizer if already on and then rotated

---

docs/compilation.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3479)

add info about building the open3d pytorch wheels

---

examples/cpp/ColorMapOptimization.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3490)

Fix bug in ColorMapOptimization cpp example

---

cpp/open3d/visualization/visualizer/O3DVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3498)

Set a valid shader name when model is added

---

cpp/open3d/visualization/gui/Window.cpp
cpp/pybind/visualization/gui/gui.cpp
cpp/pybind/visualization/o3dvisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3501)

Export pybind for Window::ShowMenu()

---

cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/rendering/filament/PointCloudBuffers.cpp

* Automatically copies GPU-based T point clouds to CPU but outputs warning
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3507)

Add support for GPU-based tgeometries internally

---

cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3512)

Support GPU tgeometry image and point cloud updates

---

cpp/open3d/visualization/visualizer/O3DVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3513)

Check for redundant change to avoid unecssary state changes

---

docs/tutorial/visualization/web_visualizer.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3518)

add notes on colab

---

docs/compilation.rst
docs/cpp_project.rst
docs/tutorial/visualization/web_visualizer.rst

- optimize title
- add links to source code for webrtc
- fixed some typos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3521)

minor docs change

---

cpp/open3d/visualization/visualizer/O3DVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3528)

Make sure downsampled point cloud material properties update properly

---

CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3536)

disable -S link flag for macos

---

cpp/open3d/Macro.h
cpp/open3d/core/AdvancedIndexing.h
cpp/open3d/core/Indexer.cpp
cpp/open3d/core/Tensor.h
cpp/open3d/core/hashmap/CUDA/SlabHashmap.h
cpp/open3d/core/hashmap/CUDA/SlabNodeManager.h
cpp/open3d/core/kernel/CPULauncher.h
cpp/open3d/core/kernel/ReductionCUDA.cu
cpp/open3d/ml/contrib/Cloud.cpp
cpp/open3d/visualization/gui/Application.cpp
cpp/open3d/visualization/gui/ImguiFilamentBridge.cpp
cpp/open3d/visualization/gui/PickPointsInteractor.cpp
cpp/open3d/visualization/visualizer/O3DVisualizerSelections.cpp
cpp/pybind/ml/contrib/contrib_subsample.cpp
examples/cpp/ColorMapOptimization.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3594)

Migrate assert to OPEN3D_ASSERT

---

cpp/open3d/Open3D.h.in
cpp/open3d/core/SizeVector.h
cpp/open3d/core/kernel/ReductionCUDA.cu
cpp/open3d/t/geometry/TSDFVoxelGrid.cpp
cpp/open3d/utility/CMakeLists.txt
cpp/open3d/utility/Console.cpp
cpp/open3d/utility/Console.h
cpp/open3d/utility/Helper.cpp
cpp/open3d/utility/Helper.h
cpp/open3d/utility/Logging.cpp
cpp/open3d/utility/Logging.h
cpp/open3d/visualization/gui/FileDialog.cpp
cpp/open3d/visualization/visualizer/ViewControlWithCustomAnimation.cpp
cpp/open3d/visualization/visualizer/VisualizerRender.cpp

Follow-up PR for #3622. 
Move console-related code to `Console.h`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3626)

Migrate console functions to Console.h

---

cpp/pybind/utility/CMakeLists.txt
cpp/pybind/utility/logging.cpp
cpp/pybind/utility/utility.cpp
cpp/pybind/utility/utility.h
cpp/tests/utility/CMakeLists.txt
cpp/tests/utility/Logging.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3642)

Console->Logger in pybind and unit test

---

cpp/open3d/t/geometry/PointCloud.cpp

Related: #3613 
FYI: @VladMVLX
Thanks for pointing this out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3661)

Transpose rotation before applying on the right.

---

cpp/open3d/visualization/webrtc_server/WebRTCWindowSystem.cpp
cpp/open3d/visualization/webrtc_server/WebRTCWindowSystem.h
cpp/pybind/visualization/webrtc_server/webrtc_window_system.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3759)

WebRTC data channel callback registration

---

cpp/open3d/Open3D.h.in
cpp/open3d/core/MemoryManagerStatistic.cpp
cpp/open3d/core/MemoryManagerStatistic.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3747)

Print on evey Malloc and Free for debugging

---

cpp/open3d/visualization/webrtc_server/PeerConnectionManager.h
cpp/open3d/visualization/webrtc_server/WebRTCWindowSystem.cpp
cpp/open3d/visualization/webrtc_server/WebRTCWindowSystem.h
cpp/pybind/docstring.cpp
cpp/pybind/visualization/webrtc_server/webrtc_window_system.cpp
docs/documented_modules.txt

Add webrtc to sphinx documented modules
docstring namespace fix - don't replace ::<space> with .<space> since ::<space> is used in rst headings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3764)

Replies for DataChannelCallback

---

cpp/open3d/t/pipelines/kernel/ComputeTransformImpl.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3803)

PointToPlane ICP Bug Fix

---

util/docker/open3d-gpu/scripts/gce-ubuntu-docker-run.sh

Enables multi-gpu unit tests.
For example:
```
n1-standard-8 + 1 Tesla T4: $0.512 hourly
n1-standard-8 + 2 Tesla T4: $0.757 hourly
```
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3847)

Use 2 gpus on for GPU CI

---

3rdparty/README.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3860)

update readme about zeromq fork

---

cpp/open3d/pipelines/registration/Registration.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3861)

fix master style

---

.github/workflows/windows.yml
util/ci_utils.sh

to detect state dependent tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3871)

Randomize C++ and Python unit test order

---

.github/workflows/Dockerfile.openblas

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3885)

Set openblas build ccache size to 1G

---

cpp/pybind/t/geometry/trianglemesh.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3897)

fix property of trianglemesh pybind

---

cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp

Parallelize with OpenMP the initial matching of `FastGlobalRegistration`, plus minor refactoring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3849)

Parallelize FastGlobalRegistration

---

cpp/tests/core/FixedRadiusIndex.cpp

- Refactor unit test for FixedRadiusIndex
- Resolve unit test failure on CUDA 11.0 #3856
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3895)

refactor unit test for FixedRadiusIndex

---

cpp/open3d/utility/Logging.cpp
cpp/open3d/utility/Logging.h

Since it is not used anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3942)

remove console-specific prints

---

cpp/open3d/core/CMakeLists.txt
cpp/open3d/core/EigenConverter.cpp
cpp/open3d/core/Indexer.cpp
cpp/open3d/core/SizeVector.cpp
cpp/open3d/core/SizeVector.h
cpp/open3d/core/Tensor.cpp
cpp/open3d/core/Tensor.h
cpp/open3d/core/kernel/NonZeroCPU.cpp
cpp/open3d/core/nns/FaissIndex.cpp
cpp/open3d/core/nns/FixedRadiusIndex.cpp
cpp/open3d/core/nns/KnnIndex.cpp
cpp/open3d/core/nns/NanoFlannIndex.cpp
cpp/open3d/t/geometry/LineSet.h
cpp/open3d/t/geometry/PointCloud.cpp
cpp/open3d/t/geometry/PointCloud.h
cpp/open3d/t/geometry/RaycastingScene.cpp
cpp/open3d/t/geometry/TriangleMesh.h
cpp/open3d/t/geometry/kernel/Transform.cpp
cpp/open3d/t/io/file_format/FilePTS.cpp
cpp/pybind/ml/contrib/iou.cpp

... by implicit type conversion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3954)

AssertShape() accepts both shape and dynamic shape

---

cpp/open3d/core/nns/FaissIndex.h
cpp/open3d/core/nns/NNSIndex.h
cpp/open3d/core/nns/NanoFlannIndex.h
cpp/open3d/core/nns/NearestNeighborSearch.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3933)

Update NNS docstrings, changing Int64 to Int32

---

cpp/open3d/core/Tensor.cpp
python/test/core/test_core.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4043)

throw exception when slicing a 0-dim tensor

---

cpp/open3d/ml/pytorch/CMakeLists.txt
cpp/open3d/ml/tensorflow/CMakeLists.txt

This PR adds install commands to install the op libraries to allow using them in C++ projects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4069)

install ml ops shared libraries

---

.github/workflows/Dockerfile.openblas
.github/workflows/Dockerfile.ubuntu-cuda

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4092)

silent wget in docker build

---

cpp/pybind/make_install_pip_package.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4089)

uninstall before install-pip-package

---

cpp/open3d/t/geometry/RaycastingScene.cpp
cpp/open3d/t/geometry/RaycastingScene.h
cpp/pybind/t/geometry/raycasting_scene.cpp
python/test/t/geometry/test_raycasting_scene.py

This PR adds another function for testing if a ray has any intersection with the scene.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4095)

Add function for testing ray occlusions to RaycastingScene

---

cpp/open3d/core/TensorCheck.cpp
cpp/open3d/core/TensorCheck.h
cpp/open3d/utility/Helper.cpp
cpp/open3d/utility/Helper.h
cpp/tests/core/TensorCheck.cpp
cpp/tests/utility/Helper.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4098)

check multiple dtypes with AssertTensorDtypes

---

.github/workflows/docker_build.sh

This avoids `sudo` from the host.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4102)

chown inside docker, avoids sudo

---

.github/workflows/Dockerfile.openblas
.github/workflows/Dockerfile.ubuntu-cuda

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4101)

explicitly set max ccache size in docker build

---

.github/workflows/Dockerfile.ubuntu-cuda
cpp/open3d/core/Tensor.cpp
cpp/pybind/make_python_package.cmake

Changes:
- Update `node` version in Docker build
- Add CMake checks for `node` versions
Tested:
- Local build
- Downloaded developer wheel from CI build
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4091)

Fix Jupyter WebRTC

---

cmake/Open3DISPC.cmake
cpp/benchmarks/CMakeLists.txt
cpp/benchmarks/benchmark_utilities/CMakeLists.txt
cpp/benchmarks/benchmark_utilities/Rand.cpp
cpp/benchmarks/benchmark_utilities/Rand.h
cpp/benchmarks/core/BinaryEW.cpp
cpp/benchmarks/core/CMakeLists.txt
cpp/benchmarks/core/UnaryEW.cpp
cpp/open3d/core/CMakeLists.txt
cpp/open3d/core/Indexer.cpp
cpp/open3d/core/Indexer.h
cpp/open3d/core/Indexer.ispc
cpp/open3d/core/Indexer.isph
cpp/open3d/core/ParallelFor.isph
cpp/open3d/core/kernel/BinaryEWCPU.cpp
cpp/open3d/core/kernel/BinaryEWCPU.ispc
cpp/open3d/core/kernel/UnaryEWCPU.cpp
cpp/open3d/core/kernel/UnaryEWCPU.ispc
cpp/tests/core/CMakeLists.txt
cpp/tests/core/Indexer.cpp
cpp/tests/core/Indexer.ispc
cpp/tests/core/Tensor.cpp
cpp/tests/t/io/PointCloudIO.cpp

- Add vectorized ISPC code for all BinaryEW and UnaryEW ops.
- Add benchmarks for all BinaryEW and UnaryEW ops.
- Fix rounding issue in PTS unit test by moving from `0.3 * 255 = 76.5 -> 76 | 77` to `0.4 * 255 = 102 -> 102`.
- Fix rounding issue for `sqrt`, `sin`, `cos`, `exp` which were compared for strict binary representation equality.
- Only test 100, 100k, 100m entries to keep benchmark time modarate.
- Duplicate enums for UnaryEW and BinaryEW ops to avoid coupling with internal kernel API.
<details>
<summary>Scalar Code Path</summary>
```
[Open3D INFO] CPUInfo: 6 cores, 12 threads.
[Open3D INFO] ISAInfo: DISABLED instruction set used in ISPC code.
2021-09-27T12:03:17+02:00
Running ./bin/benchmarks
Run on (12 X 4787.91 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x6)
L1 Instruction 32 KiB …
```

Vectorize BinaryEW and UnaryEW ops

---

cpp/pybind/visualization/rendering/rendering.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4070)

Revert name change of Gradient points attribute

---

cpp/open3d/core/Tensor.cpp
cpp/open3d/core/Tensor.h
cpp/pybind/core/tensor.cpp
cpp/tests/core/EigenConverter.cpp
cpp/tests/core/Tensor.cpp
python/test/core/test_core.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4099)

Tensor iterator

---

.github/workflows/Dockerfile.ubuntu-cuda

https://github.com/nodesource/distributions/issues/1266#issuecomment-932422525
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4121)

add temporary fix for nodejs certificate

---

cpp/open3d/visualization/rendering/filament/PointCloudBuffers.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4217)

Check for empty bounding box to prevent Filament panic

---

cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp
examples/python/t_reconstruction_system/dense_slam_gui.py

Fixes #4203 and related issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4218)

Fix Material API and tracking

---

docs/tutorial/t_reconstruction_system/dense_slam.rst
docs/tutorial/t_reconstruction_system/index.rst

Fix minor phrasing in tutorials and add a citation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4223)

Improve docs

---

.github/workflows/Dockerfile.wheel
.github/workflows/documentation.yml
.github/workflows/gce-ubuntu-docker.yml
.github/workflows/macos.yml
.github/workflows/openblas.yml
.github/workflows/style.yml
.github/workflows/ubuntu-wheel.yml
.github/workflows/ubuntu.yml
.github/workflows/webrtc.yml
.github/workflows/windows.yml
docs/arm.rst
docs/compilation.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4245)

No need for recursive clone and submodules

---

3rdparty/CMake/FindPytorch.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4251)

avoid re-linking MKL in pytorch ops

---

cpp/open3d/Open3D.h.in
cpp/open3d/geometry/PointCloudCluster.cpp
cpp/open3d/io/ModelIO.cpp
cpp/open3d/io/TriangleMeshIO.cpp
cpp/open3d/io/file_format/FileOBJ.cpp
cpp/open3d/io/file_format/FileOFF.cpp
cpp/open3d/io/file_format/FilePLY.cpp
cpp/open3d/io/file_format/FileSTL.cpp
cpp/open3d/utility/CMakeLists.txt
cpp/open3d/utility/Logging.cpp
cpp/open3d/utility/Logging.h
cpp/open3d/utility/ProgressBar.cpp
cpp/open3d/utility/ProgressBar.h
cpp/open3d/utility/ProgressReporters.h
cpp/open3d/visualization/utility/SelectionPolygon.cpp
cpp/open3d/visualization/utility/SelectionPolygonVolume.cpp
cpp/open3d/visualization/visualizer/VisualizerWithCustomAnimation.cpp
examples/cpp/TrimMeshBasedOnPointCloud.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4254)

move ProgressBar to a standalone file

---

python/open3d/visualization/tensorboard_plugin/util.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4255)

Fix function rename.

---

cpp/open3d/geometry/TriangleMesh.cpp
cpp/tests/geometry/TriangleMesh.cpp

#3838 
add an unit test in this condition
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4224)

fix issue#3838, called multiple times may change vertex normal

---

examples/python/gui/demo-scene.py

The demo scene script requires this asset from the `open3d_downloads` project: https://github.com/isl-org/open3d_downloads/releases/download/o3d_demo_scene/demo_scene_assets.tgz
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4243)

Add demo scene example

---

.github/workflows/docker_test.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4273)

daemon reload and restart docker

---

docs/python_api_in/open3d.ml.tf.layers.ContinuousConv.rst
docs/python_api_in/open3d.ml.tf.layers.FixedRadiusSearch.rst
docs/python_api_in/open3d.ml.tf.layers.KNNSearch.rst
docs/python_api_in/open3d.ml.tf.layers.RadiusSearch.rst
docs/python_api_in/open3d.ml.tf.layers.SparseConv.rst
docs/python_api_in/open3d.ml.tf.layers.SparseConvTranspose.rst
docs/python_api_in/open3d.ml.tf.layers.VoxelPooling.rst
docs/python_api_in/open3d.ml.torch.layers.ContinuousConv.rst
docs/python_api_in/open3d.ml.torch.layers.FixedRadiusSearch.rst
docs/python_api_in/open3d.ml.torch.layers.KNNSearch.rst
docs/python_api_in/open3d.ml.torch.layers.RadiusSearch.rst
docs/python_api_in/open3d.ml.torch.layers.SparseConv.rst
docs/python_api_in/open3d.ml.torch.layers.SparseConvTranspose.rst
docs/python_api_in/open3d.ml.torch.layers.VoxelPooling.rst

Following up on https://github.com/isl-org/Open3D/pull/4143#pullrequestreview-775552168
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4149)

remove rst overrides that avoid inherited members

---

.github/workflows/Dockerfile.cuda
.github/workflows/Dockerfile.openblas
.github/workflows/docker_build.sh
.github/workflows/docker_test.sh
.github/workflows/readme.md
.github/workflows/ubuntu-openblas.yml
.github/workflows/windows.yml
util/ci_utils.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4268)

Refactor openblas CI to use docker build and test

---

cpp/open3d/visualization/rendering/filament/TriangleMeshBuffers.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4275)

Convert t geometry triangle mesh indices to int32

---

.github/workflows/ubuntu-openblas.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4277)

upload openblas cache before running test

---

examples/python/geometry/distance_queries.ipynb

Use new way of accessing vertex positions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4299)

Fix distance queries tutorial

---

cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/rendering/filament/PointCloudBuffers.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4308)

Ensure visualization scalar tensor is contiguous before copying data from it

---

cpp/pybind/t/geometry/tensormap.cpp
python/test/t/geometry/test_tensormap.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4309)

fix tensormap return reference

---

examples/python/gui/add-geometry.py
examples/python/gui/draw.py
examples/python/gui/line-width.py
examples/python/gui/mouse-and-point-coord.py
examples/python/gui/multiple-windows.py
examples/python/gui/online-processing.py
examples/python/gui/render-to-image.py
examples/python/gui/text3d.py
examples/python/gui/textured-model.py
examples/python/gui/video.py
examples/python/gui/vis-gui.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4313)

Update Python GUI examples to use MaterialRecord

---

cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4317)

Add caching to prevent redundant creation of textures on GPU

---

cpp/open3d/visualization/visualizer/GuiVisualizer.cpp

Fixes #4322
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4323)

Fix windows macro in guivisualizer

---

cpp/open3d/geometry/PointCloud.cpp

Closes #1381
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4330)

add threads synchronization to RemoveStatisticalOutlier

---

.gitignore
cpp/open3d/visualization/gui/Application.cpp
cpp/open3d/visualization/gui/Application.h
cpp/open3d/visualization/rendering/Camera.h
cpp/open3d/visualization/rendering/Renderer.cpp
cpp/open3d/visualization/rendering/Renderer.h
cpp/open3d/visualization/rendering/filament/FilamentCamera.cpp
cpp/open3d/visualization/rendering/filament/FilamentCamera.h
cpp/pybind/visualization/gui/gui.cpp
cpp/pybind/visualization/gui/gui.h
cpp/pybind/visualization/rendering/rendering.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3751)

Update math for converting depth buffer values to view space Z

---

docs/conf.py.in
docs/make_docs.py
docs/tutorial/visualization/tensorboard_plugin.rst
python/README.rst
python/open3d/web_visualizer.py

Path to Open3D_ML_ROOT is different in CI (inside Open3D) compared to common developer machine (sibling to Open3D).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4343)

Copy tensorboard.md from Open3D_ML_ROOT for docs

---

.gitignore
cpp/pybind/pipelines/registration/registration.cpp
cpp/pybind/t/pipelines/registration/registration.cpp

- Fix #4096
- Fix #1459 
- Add gitignore entry for #4343
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4350)

Fix 4096, 1459, and add gitigonre for 4343

---

cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4356)

Prevent premature texture deletion

---

cpp/pybind/t/geometry/image.cpp
python/test/t/geometry/test_image.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4361)

fix buffer protocol strides of t::G::Image

---

docs/versions.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4363)

point to release instead of 0.14.1

---

.github/workflows/macos.yml

Run only manually. Can be used for release or any branch builds.
Test run with macOS viewer as github actions artifact:
https://github.com/isl-org/Open3D/actions/runs/1526742807
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4364)

Build macOS 10.15 viewer in Github actions

---

cpp/open3d/geometry/TriangleMesh.cpp
cpp/open3d/geometry/TriangleMesh.h
cpp/pybind/geometry/trianglemesh.cpp

Fix Issue #3531
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4379)

Change `lambda` parameter to `lambda_filter`, to avoid conflict with keyword. Fix #3531

---

.github/workflows/documentation.yml
.github/workflows/macos.yml
.github/workflows/ubuntu-cuda.yml
.github/workflows/ubuntu-openblas.yml
.github/workflows/ubuntu-wheel.yml
.github/workflows/windows.yml

Fix master wheel upload issue.
See: https://github.com/google-github-actions/setup-gcloud/issues/418#issuecomment-986770201
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4381)

pin setup-gcloud to v0.2.1

---

cpp/open3d/geometry/PointCloud.cpp

Fixes #4390.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4391)

pass print_progress to OMPProgressBar

---

cpp/open3d/geometry/TriangleMesh.h
cpp/pybind/geometry/trianglemesh.cpp

This PR addresses https://github.com/isl-org/Open3D/issues/3176
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4392)

improve docstrings for remove_duplicated_triangles()

---

README.md

Updated Forum Links
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4407)

Update forum link in README.md

---

3rdparty/stdgpu/stdgpu.cmake

Fixed #4410.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4411)

Fixed build error on Fedora.

---

python/open3d/visualization/async_event_loop.py
python/open3d/visualization/tensorboard_plugin/colormap.py
python/open3d/visualization/tensorboard_plugin/labellut.py
python/open3d/visualization/tensorboard_plugin/summary.py
python/open3d/visualization/tensorboard_plugin/util.py
python/test/visualization/test_tensorboard_plugin.py

Resolves #4384
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4402)

Remove unused import to allow async_event_loop to work without Open3D-ML

---

cpp/open3d/visualization/gui/TabControl.cpp
cpp/open3d/visualization/gui/TabControl.h
cpp/pybind/visualization/gui/gui.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4449)

add get/set TabControl index

---

docs/Doxyfile.in
docs/_static/google_analytics_header.html
docs/conf.py.in

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4473)

Add google analytics js to every page from sphinx and doxygen

---

cpp/pybind/core/dtype.cpp
cpp/pybind/core/hashmap.cpp
cpp/pybind/core/tensor_type_caster.h
cpp/pybind/open3d_pybind.h
cpp/pybind/pipelines/registration/robust_kernels.cpp
cpp/pybind/visualization/gui/gui.cpp

- Fixes pybind-related compilation error following https://github.com/microsoft/onnxruntime/pull/9794
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4478)

Fix VS 2022 compilation issue

---

cpp/open3d/visualization/rendering/filament/FilamentCamera.cpp
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/rendering/filament/FilamentScene.h

Fixes issue #4480.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4513)

Fix memory leak when destroying PyOffscreenRenderer

---

cpp/open3d/t/geometry/PointCloud.cpp

- Fix #4542
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4544)

Support point color dtype of UInt8

---

.github/ISSUE_TEMPLATE/3-feature-request.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4554)

Feature Request Template Fix

---

examples/cpp/DenseSLAMGUI.cpp
examples/python/t_reconstruction_system/dense_slam_gui.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4540)

Fix cpp slam gui issue

---

examples/cpp/TIntegrateRGBD.cpp

- Upgrade example for #4340
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4503)

Address #4340

---

examples/python/benchmark/benchmark_fgr.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4566)

Fix `benchmark_fgr.py`

---

docs/jupyter/geometry/ray_casting.ipynb

Resolves #3561
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4556)

Add mesh to virtual point cloud to ray casting tutorial

---

cmake/Open3DSetGlobalProperties.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4574)

only strip when DEVELOPER_BUILD=OFF

---

cpp/open3d/t/io/file_format/FilePLY.cpp

Closes #4548 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4553)

T::IO::PointCloud PLY Cleanups Fixes #4548

---

cpp/open3d/data/Download.cpp
cpp/open3d/data/Download.h
cpp/tests/data/Download.cpp
cpp/tests/data/Extract.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4573)

Replace `SHA256` with `MD5` Sum Verification

---

cpp/open3d/core/EigenConverter.h
cpp/tests/core/EigenConverter.cpp

Fixes #4261
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4579)

core::EigenMatrixToTensor: allow convertion for eigen vector

---

cpp/open3d/utility/FileSystem.cpp
cpp/open3d/utility/FileSystem.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4578)

Added `CopyFile`

---

cpp/open3d/t/geometry/kernel/ImageImpl.h
cpp/open3d/t/geometry/kernel/VoxelBlockGridImpl.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4438)

fix nan in normal image

---

cpp/open3d/visualization/gui/NumberEdit.cpp

Fixes #4314
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4588)

FIx typo in GUI NumberEdit widget

---

docs/getting_started.rst.in

Fixes #4614
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4619)

update wheel link to macos 10.15

---

.github/ISSUE_TEMPLATE/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4629)

Fix typo in issues template

---

docs/arm.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4651)

update docs for ARM build

---

cpp/open3d/visualization/gui/NativeMacOS.mm

I was told that FileDialog::Mode::OPEN_DIR is not working in MacOS. After checking the code, I found that MacOS use native file dialog instead, and OPEN_DIR is treated as SAVE.
It's a pitty that although I fixed it, I haven't got the environment to build and test it.
Is there anyone can do that for me? Many thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4511)

fix FileDialog::Mode::OPEN_DIR is treated as SAVE in MacOS using native file dialog

---

cpp/tests/data/Dataset.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4674)

Quick fix for dataset downloader test

---

.github/workflows/ubuntu-cuda.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4682)

Fix for uploading CUDA package to Google cloud for master.

---

python/open3d/visualization/draw.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4681)

Fix misnamed function call

---

cpp/open3d/visualization/visualizer/VisualizerRender.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4680)

Fix Crash With Legacy Visualizer Examples

---

cpp/open3d/visualization/visualizer/O3DVisualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4683)

Fix shadows disappearing after disabling basic mode

---

examples/python/reconstruction_system/colored_icp.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4702)

Fix typo in colored_icp

---

docs/builddocs.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4708)

Add instructions to preview built docs

---

cpp/open3d/visualization/utility/DrawGeometry.cpp
cpp/open3d/visualization/visualizer/Visualizer.cpp
cpp/open3d/visualization/visualizer/VisualizerWithEditing.cpp

Addresses issue #4725
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4728)

Check for invalid geometry input to DrawGeometries

---

cpp/open3d/visualization/gui/MenuImgui.cpp
cpp/open3d/visualization/gui/VectorEdit.cpp

This PR replaces a few obsolete function calls with the updated versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4731)

Update obsolete ImGui function calls

---

cpp/benchmarks/geometry/SamplePoints.cpp
cpp/benchmarks/t/geometry/PointCloud.cpp
cpp/benchmarks/t/io/PointCloudIO.cpp
cpp/benchmarks/t/pipelines/odometry/RGBDOdometry.cpp
cpp/tests/geometry/Octree.cpp
cpp/tests/geometry/PointCloud.cpp
cpp/tests/geometry/RGBDImage.cpp
cpp/tests/io/OctreeIO.cpp
cpp/tests/pipelines/integration/UniformTSDFVolume.cpp
cpp/tests/t/geometry/Image.cpp
cpp/tests/t/io/PointCloudIO.cpp
cpp/tests/t/io/TriangleMeshIO.cpp
cpp/tests/t/pipelines/odometry/RGBDOdometry.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4739)

Add dataset functionality to cpp unit tests and benchmarks

---

README.md
docs/getting_started.in.rst

To include a simple python example and open3d cli command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4754)

update getting started: run python api and cli

---

3rdparty/cmake/FindPytorch.cmake
3rdparty/cmake/FindTensorflow.cmake

More informative error message.
Avoids user confusions such as #4644
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4768)

Don't check CXX11 ABI on macOS, WIN + MSVC

---

docker/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4783)

update readme for runing docker registering scripts

---

examples/python/visualization/vis_gui.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4795)

Update example to load triangle meshes as models

---

cmake/Open3DMakeCudaArchitectures.cmake
cmake/Open3DSetGlobalProperties.cmake
cpp/open3d/ml/tensorflow/CMakeLists.txt
cpp/pybind/make_python_package.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4811)

Reduce wheel size (fewer CUDA arch, stirp TF op, clean test_data)

---

cpp/open3d/visualization/gui/Application.cpp
cpp/open3d/visualization/gui/CMakeLists.txt
cpp/open3d/visualization/gui/RadioButton.cpp
cpp/open3d/visualization/gui/RadioButton.h
cpp/open3d/visualization/gui/Theme.h
cpp/pybind/visualization/gui/gui.cpp
examples/python/visualization/all_widgets.py

support VERT and HORIZ types of radio button group
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4738)

add radio button support

---

docs/tutorial/data/index.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4820)

Typo fix in dataset doc

---

3rdparty/curl/curl.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4838)

Mark `BUILD_CURL_FROM_SOURCE` as advanced option 

---

cpp/open3d/visualization/visualizer/VisualizerWithVertexSelection.h
cpp/pybind/visualization/visualizer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4856)

Added extra VisualizerWithVertexSelection functions to python api

---

3rdparty/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4865)

third-party readme from txt to md

---

.github/workflows/ubuntu.yml
.gitignore
docker/Dockerfile.ci
docker/docker_build.sh
docker/docker_test.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4839)

Ubuntu CPU CI in Docker

---

examples/python/reconstruction_system/slac_integrate.py
examples/python/t_reconstruction_system/integrate.py

Fixes #4851
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4859)

set default device correctly for t-recon examples

---

python/tools/cli.py

fixes #4884
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4887)

remove ununused imports

---

cpp/open3d/utility/FileSystem.cpp
cpp/open3d/utility/FileSystem.h
cpp/tests/data/Dataset.cpp
cpp/tests/io/OctreeIO.cpp
cpp/tests/io/PointCloudIO.cpp
cpp/tests/io/VoxelGridIO.cpp
cpp/tests/io/file_format/FileGLTF.cpp
cpp/tests/io/file_format/FileSTL.cpp
cpp/tests/t/geometry/PointCloud.cpp
cpp/tests/t/io/ImageIO.cpp
cpp/tests/t/io/PointCloudIO.cpp
cpp/tests/t/io/TriangleMeshIO.cpp
python/test/data/test_data.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4920)

Refactoring unit test to use fs::temp_directory

---

docs/jupyter/pipelines/global_registration.ipynb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4974)

(doc) Fix typoed link

---

CMakeLists.txt
cmake/Open3DSetGlobalProperties.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4986)

harderning flags moved to open3d_set_global_properties

---

.github/workflows/style.yml
CMakeLists.txt
cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp
cpp/open3d/visualization/rendering/Material.h
cpp/open3d/visualization/rendering/filament/FilamentRenderer.cpp
docs/contribute/styleguide.rst
util/check_cpp_style.cmake
util/check_style.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5017)

Fix M1 compilation

---

CHANGELOG.md
python/requirements.txt
python/requirements_build.txt

Closes #5019
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5020)

Remove setuptools and wheel as end-user requirements

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5034)

Add news on GSoD application

---

docs/compilation.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5030)

add ccache docs

---

python/open3d/visualization/tensorboard_plugin/summary.py

Fixes #5042
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5043)

Missing `f` prefix on f-strings fix

---

docker/Dockerfile.ci
docker/Dockerfile.wheel
python/open3d/visualization/tensorboard_plugin/summary.py

Example failure cases:
- https://github.com/isl-org/Open3D/runs/6222182591?check_suite_focus=true
- https://github.com/isl-org/Open3D/runs/6222369700?check_suite_focus=true
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5062)

update nvidia repo key

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5085)

remove gsod news

---

3rdparty/find_dependencies.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5104)

link custom targets before system targets

---

cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu

This PR replaces handcrafted cuda kernel reduction for odometry. It keeps the performance while simplifying the code.
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5129)

CUB Reduction for odometry

---

cpp/open3d/geometry/TriangleMesh.cpp
cpp/open3d/geometry/TriangleMeshSubdivide.cpp
cpp/open3d/pipelines/integration/ScalableTSDFVolume.cpp
cpp/open3d/visualization/rendering/Camera.cpp
examples/cpp/MultipleWindows.cpp
examples/cpp/OnlineSLAMUtil.h
examples/cpp/TICP.cpp
examples/cpp/TICPSequential.cpp

Fixed #5132 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5133)

Fixed build Error on Fedora 36 with GCC 12.

---

cmake/Open3DShowAndAbortOnWarning.cmake

Fix by referring [this link](https://github.com/isl-org/Open3D/issues/4296).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5137)

Fix Windows build error

---

cpp/open3d/core/TensorFunction.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5252)

fix doc error for tensor functions

---

cpp/open3d/t/geometry/CMakeLists.txt
cpp/open3d/t/geometry/TriangleMesh.h
cpp/open3d/t/geometry/TriangleMeshFactory.cpp
cpp/pybind/t/geometry/trianglemesh.cpp
cpp/tests/t/geometry/TriangleMesh.cpp
python/test/t/geometry/test_trianglemesh.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5263)

add create_box in tensor-based module

---

examples/python/t_reconstruction_system/integrate.py

This PR fix the issue #5321
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5326)

Fix error in python t_reconstruction example

---

cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5396)

Add support for float and ushort internal formats

---

.github/workflows/ubuntu-cuda.yml
.github/workflows/ubuntu-openblas.yml

An attempt to fix the following issue:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5400)

sleep for 90 secs after VM create

---

cpp/open3d/visualization/gui/Materials/unlitLine.mat
cpp/open3d/visualization/rendering/MaterialRecord.h
cpp/open3d/visualization/rendering/View.h
cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/rendering/filament/FilamentView.cpp
cpp/open3d/visualization/rendering/filament/FilamentView.h
cpp/open3d/visualization/visualizer/GuiSettingsModel.cpp
cpp/open3d/visualization/visualizer/GuiSettingsModel.h
cpp/open3d/visualization/visualizer/GuiSettingsView.cpp
cpp/open3d/visualization/visualizer/GuiSettingsView.h
cpp/open3d/visualization/visualizer/GuiVisualizer.cpp
cpp/pybind/visualization/rendering/rendering.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5498)

Add wireframe mode to visualizer

---

cpp/open3d/visualization/visualizer/O3DVisualizer.cpp
cpp/open3d/visualization/visualizer/O3DVisualizer.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5510)

Add wireframe mode to O3DVisualizer

---

util/install_deps_ubuntu.sh

As the upstream has been fixed.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5530)

revert libudev ubuntu temp fix

---

cpp/open3d/visualization/rendering/Material.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5562)

Fix missing conversions for point size and line width in Material

---

cpp/open3d/t/geometry/PointCloud.cpp
cpp/open3d/t/geometry/PointCloud.h
cpp/tests/t/geometry/PointCloud.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5566)

Make PaintUniformColor return by reference

---

docs/make_docs.py

- delete `*.ipynb` in output folder
- do not execute `draw_plotly.ipynb`, as WebGL widgets does not render well on our docs website yet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5610)

Fix release docs jupyter size issue

---

3rdparty/find_dependencies.cmake
cpp/apps/CMakeLists.txt
cpp/apps/fixup_macosx_bundle.sh
docs/getting_started.in.rst
python/README.rst
python/setup.py
util/ci_utils.sh

- Add macOS instructions to install libomp
- Docs version updates
- manylinux naming for aarch64
- Fix DSO packaging (libomp.dylib) for macOS app
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5663)

Add CI test to check interop with tensorflow / pytorch

---

cpp/open3d/t/geometry/RaycastingScene.cpp

This PR removes the internal headers from the embree repo.
This addresses #5642
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5726)

replace Vectors from internal embree headers with Eigen

---

cpp/open3d/geometry/PointCloud.h

Closing the issue #5700
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5738)

Function CreateFromVoxelGrid is made static.

---

cpp/open3d/core/Tensor.h
cpp/pybind/core/tensor.cpp
cpp/tests/core/Tensor.cpp
python/test/core/test_core.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5778)

unary minus operator

---

cpp/open3d/geometry/TriangleMesh.cpp

This PR addresses #5712
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5789)

fix wrong value for beta in SamplePointsPoissonDisk()

---

cpp/open3d/io/TriangleMeshIO.h
cpp/open3d/t/io/TriangleMeshIO.h
cpp/pybind/t/io/class_io.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5828)

improved t.io.read_triangle_mesh documentation

---

cpp/pybind/pipelines/registration/registration.cpp

This PR aims at solving #5837
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5838)

Release python GIL for generalized icp

---

.github/pull_request_template.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/Open3D/5854)

Pull request template for community contributors.

---

CMakeLists.txt

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #5756
Thanks to @peterzxli for reporting and resolving.
Raspberry Pi4 processor detection fails.
to my code.
`uname -p` -> `uname -m` in CMakeLists.txt for more portable hardware check.
- - - …

More portable ARM detection.

---

3rdparty/find_dependencies.cmake
3rdparty/fmt/fmt.cmake
cpp/benchmarks/core/BinaryEW.cpp
cpp/benchmarks/core/UnaryEW.cpp
cpp/open3d/core/SizeVector.cpp
cpp/open3d/core/hashmap/CUDA/CUDAHashBackendBuffer.cu
cpp/open3d/io/IJsonConvertibleIO.h
cpp/open3d/t/geometry/Geometry.h
cpp/open3d/t/geometry/Image.h
cpp/open3d/t/geometry/VtkUtils.cpp
cpp/open3d/t/geometry/kernel/IPPImage.cpp
cpp/open3d/t/geometry/kernel/NPPImage.cpp
cpp/open3d/utility/IJsonConvertible.cpp
cpp/open3d/utility/IJsonConvertible.h
cpp/open3d/visualization/rendering/RendererHandle.h
cpp/tests/core/CUDAUtils.cpp
cpp/tests/core/Tensor.cpp
cpp/tools/GLInfo.cpp

Adopted from pr #5303 by @roehling 
-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #4360, fixes #5205 
to my code.
-   [ ] For fork PRs, …

 Fix build compatibility with fmtlib 8 [Author: @roehling]

---

cpp/open3d/core/Device.h
cpp/open3d/core/StdAllocator.h
cpp/open3d/core/hashmap/CUDA/StdGPUHashBackend.h

When I add `Device:::description_`:
```diff
diff --git a/cpp/open3d/core/Device.h b/cpp/open3d/core/Device.h
index d3d400de1..b0d6225f5 100644
--- a/cpp/open3d/core/Device.h
+++ b/cpp/open3d/core/Device.h
@@ -130,6 +130,7 @@ protected:
protected:
DeviceType device_type_ = DeviceType::CPU;
int device_id_ = 0;
+    std::string description_;
};
```
It results in this cryptic error:
```
[ 96%] Building CUDA object cpp/open3d/t/geometry/kernel/CMakeFiles/tgeometry_kernel.dir/VoxelBlockGridCUDA.cu.o
/home/yixing/repo/Open3D/cpp/open3d/utility/MiniVec.h(49): error: calling a __host__ function("std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(const ::std::basic_string<char, std::char_traits<char>, std::allocator<char> >&)") from a __host__ __device__ …
```

MiniVec's constructor shall not call Device's constructor/destructor

---

.github/workflows/windows.yml
3rdparty/civetweb/civetweb.cmake
3rdparty/curl/curl.cmake
3rdparty/libjpeg-turbo/libjpeg-turbo.cmake
3rdparty/zlib/zlib.cmake
python/requirements.txt
python/requirements_build.txt
python/requirements_jupyter_build.txt
python/requirements_jupyter_install.txt
python/requirements_style.txt
python/requirements_test.txt
util/ci_utils.sh

**Blackduck:**
- civetweb Fixed in 1.15: CVE-2020-27304 https://groups.google.com/g/civetweb/c/yPBxNXdGgJQ 
- curl 7.88
- zlib 1.2.13 (>=1.2.12):  CVE-2022-37434, CVE-2018-25032 
- libjpeg-turbo 2.1.5.1 (>2.0.90) CVE-2021-46822
**Snyk:**
Upgrade wheel@0.37.1 to wheel@0.38.0 to fix
✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://snyk.devtools.intel.com/vuln/SNYK-PYTHON-WHEEL-3180413] in wheel@0.37.1
introduced by wheel@0.37.1 and 2 other path(s)
Pin certifi@2022.6.15 to certifi@2022.12.7 to fix
✗ Insufficient …

Dependency upgrades for security fixes.

---

.github/workflows/windows.yml
cpp/apps/CMakeLists.txt

Build Windows app in CI

---

examples/python/visualization/to_mitsuba.py
python/open3d/visualization/to_mitsuba.py

-   [X ] New feature (non-breaking change which adds functionality). Resolves #
-   [ X] I have run `python util/check_style.py --apply` to apply Open3D **code style**
to my code. …

Convert normal maps to Mitsuba BSDF normal map adaptor

---

cpp/open3d/t/geometry/PointCloud.cpp
cpp/open3d/t/geometry/PointCloud.h
cpp/open3d/t/geometry/TriangleMesh.cpp
cpp/open3d/t/geometry/TriangleMesh.h
cpp/open3d/t/geometry/VtkUtils.cpp
cpp/open3d/t/geometry/VtkUtils.h
cpp/open3d/t/geometry/kernel/CMakeLists.txt
cpp/open3d/t/geometry/kernel/PCAPartition.cpp
cpp/open3d/t/geometry/kernel/PCAPartition.h
cpp/open3d/t/geometry/kernel/UVUnwrapping.cpp
cpp/open3d/t/geometry/kernel/UVUnwrapping.h
cpp/open3d/utility/Eigen.cpp
cpp/open3d/utility/Eigen.h
cpp/pybind/t/geometry/pointcloud.cpp
cpp/pybind/t/geometry/trianglemesh.cpp

parallel uv unwrap

---

cpp/pybind/t/geometry/trianglemesh.cpp
docs/documented_modules.txt

Add nns module to the documentation

---

python/open3d/__init__.py

This PR updates the error message when an issue occurs while importing the CUDA pybind library to provide more clarity on the underlying issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/Open3D/5997)

Improve CUDA Import Error Message

---

.github/workflows/ubuntu-wheel.yml

Future: Move wheel test to Ubuntu 18.04 docker container.
-   [x] Bug fix (non-breaking change which fixes an issue): 
Ubuntu wheel CI does not run currently, since 18.04 environment is not available on github anymore
to my code.
results** (e.g. screenshots or …

Test Ubuntu wheel on 20.04 in CI

---

cpp/pybind/t/geometry/pointcloud.cpp

The documentation through sphinx had incorrect format for example code of `extrude_linear` function.
to my code.
-   [x] I will follow up and …

Fixed typo in pointcloud.cpp for tensor

---

3rdparty/find_dependencies.cmake
3rdparty/nanoflann/nanoflann.cmake
cpp/open3d/core/nns/NanoFlannImpl.h
cpp/open3d/geometry/KDTreeFlann.cpp

Maintenance of third-party dependencies, in this case nanoflann
to my code.
-   [x] For …

Update nanoflann to version 1.5.0

---

examples/python/reconstruction_system/opencv_pose_estimation.py

Improve 6120

---

.github/workflows/clean-gcloud-profiles.yml
.github/workflows/documentation.yml
.github/workflows/macos.yml
.github/workflows/style.yml
.github/workflows/ubuntu-cuda.yml
.github/workflows/ubuntu-openblas.yml
.github/workflows/ubuntu-sycl.yml
.github/workflows/ubuntu-wheel.yml
.github/workflows/ubuntu.yml
.github/workflows/vtk_packages.yml
.github/workflows/webrtc.yml
.github/workflows/windows.yml
cpp/open3d/t/geometry/TriangleMesh.cpp
cpp/pybind/pipelines/registration/registration.cpp
docker/Dockerfile.ci
docker/Dockerfile.wheel
docker/docker_build.sh
examples/python/reconstruction_system/make_fragments.py

- Remove docker build cache after wheel build to recover disk space.
- Style fix in main
- Fix `RemoveUnreferencedVertices` for CUDA
- Add manual CI run for Ubuntu SYCL
- Update github actions for Node 16 -> Node 20 migration

Misc. CI updates and fixes

---

cpp/open3d/io/file_format/FileASSIMP.cpp
cpp/open3d/t/geometry/TriangleMesh.cpp
cpp/open3d/t/geometry/TriangleMesh.h
cpp/open3d/t/io/file_format/FileASSIMP.cpp
cpp/open3d/visualization/rendering/Material.cpp
cpp/open3d/visualization/rendering/Material.h
cpp/pybind/t/geometry/trianglemesh.cpp
cpp/pybind/visualization/rendering/material.cpp
cpp/tests/t/geometry/TriangleMesh.cpp
docs/getting_started.in.rst

- ToString() for Material and string represtion in Python.
- MaterialRecord to Material conversion - allows converting triangle mesh models to a map of tmeshes, including materials. Limitation: Only one material per tmesh.
- Support for emissive color reading in FileASSIMP (model) and writing for tmesh (tio FIleASSIMP)
Test with:
```py
flight_helmet = o3d.data.FlightHelmetModel()
model = o3d.io.read_triangle_model(flight_helmet.path)
mesh_dict = o3d.t.geometry.TriangleMesh.from_triangle_mesh_model(model)
print(mesh_dict)
o3d.visualization.draw(list({"name": name, "geometry": tmesh} for
(name, tmesh) in mesh_dict.items()))
```
-   [ ] Breaking …

Convert triangle mesh model to tmesh map

---

.github/workflows/documentation.yml
.github/workflows/macos.yml
.github/workflows/style.yml
.github/workflows/ubuntu-cuda.yml
.github/workflows/ubuntu-openblas.yml
.github/workflows/ubuntu-sycl.yml
.github/workflows/ubuntu-wheel.yml
.github/workflows/ubuntu.yml
.github/workflows/update-release.yml
.github/workflows/vtk_packages.yml
.github/workflows/webrtc.yml
.github/workflows/windows.yml

Reolve OpenSSSF scorecard token permission issues.
Run CUDA and  ARM CI for every PR change
Remove old release artifacts regularly [fix]

Job level token permissions for github actions

---

docs/getting_started.in.rst

The links to packages on https://www.open3d.org/docs/latest/getting_started.html are broken. This PR fixes the links.
to my code.
-   [ ] I will …

Fix links to release links of main-devel tag

---

.github/workflows/macos.yml
docs/getting_started.in.rst

pip prefers source distribution links (zip files) over the links to the wheel files.
This adds the "--only-binary" option to the documentation.
to my code.
results** (e.g. screenshots or …

fix pip install statement for latest dev whl on getting started page

---

docker/docker_test.sh
docs/cpp_project.rst
examples/cmake/open3d-cmake-external-project/CMakeLists.txt
examples/cmake/open3d-cmake-external-project/Draw.cpp
examples/cmake/open3d-cmake-external-project/README.md
examples/cmake/open3d-cmake-find-package/CMakeLists.txt
examples/cmake/open3d-cmake-find-package/Draw.cpp
examples/cmake/open3d-cmake-find-package/README.md
util/ci_utils.sh

Earlier example location:
- https://github.com/isl-org/open3d-cmake-find-package
- https://github.com/isl-org/open3d-cmake-external-project
Copying them into the main repo to reduce maintenance overhead and ensure they are up-to-date.
to my code.
-   [ ] I have added or updated …

Copy examples for building user projects with Open3D to Open3D repo

---

cpp/open3d/geometry/TriangleMeshSimplification.cpp

vert2p is not a postion
to my code.
-   [ ] For fork PRs, I have selected **Allow edits …

bug fix at AddPerpPlaneQuadric

---

examples/python/visualization/remote_visualizer.py
python/open3d/visualization/_external_visualizer.py
python/open3d/visualization/draw.py

https://github.com/user-attachments/assets/bbcfa02c-0bbb-45b6-a3ee-4d2d8441b7cf

Add remote visualizer example. Allow changing rpc address in draw.

---

cpp/open3d/visualization/rendering/Renderer.h

Fixed a build issue with Ubuntu 24.04 when cmake is configured with the following arguments:
```
-DBUILD_SHARED_LIBS=ON
-DUSE_SYSTEM_EIGEN3=ON
-DUSE_SYSTEM_FMT=ON
-DUSE_SYSTEM_GOOGLETEST=ON
-DUSE_SYSTEM_JSONCPP=ON
-DUSE_SYSTEM_NANOFLANN=ON
-DUSE_SYSTEM_PYBIND11=ON
-DUSE_SYSTEM_QHULLCPP=ON
-DGLIBCXX_USE_CXX11_ABI=ON
-DBUILD_EXAMPLES=OFF
-DBUILD_UNIT_TESTS=OFF
-DBUILD_BENCHMARKS=OFF
```
The compilor complains that `std::shared_ptr` is not defined in `cpp/open3d/visualization/rendering/Renderer.h`. 
 
-   [x] I have run `python …

Fix build 2404

---

docker/Dockerfile.ci

When I tried to build docker using command `docker/docker_build.sh cpu-static`, it will fail with following log output:
```
> [17/20] RUN mkdir -p /etc/apt/keyrings  && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key  | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg  && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x nodistro main"  | tee /etc/apt/sources.list.d/nodesource.list  && apt-get update  && apt-get install -y nodejs  && rm -rf /var/lib/apt/lists/*  && …
```

fix SSL certificate problem

---

cpp/open3d/t/io/file_format/FileSPLAT.cpp
cpp/pybind/t/geometry/pointcloud.cpp
util/ci_utils.sh

Adding binary mode to the SPLAT read method to allow consistency among the different platforms.
to my code.
-   [x] I will follow up and update …

Fix SPLAT IO tests in Windows

---

README.md
docs/index.rst
docs/poux_book.rst

Add info about new book featuring Open3D

Add info about new book featuring Open3D

---

.github/workflows/update-release.yml

Fix for cleaning main-devel assets

---

.github/workflows/ubuntu-wheel.yml
.github/workflows/windows.yml
3rdparty/webrtc/Dockerfile.webrtc
docker/Dockerfile.ci
docker/Dockerfile.wheel

Minor fixes to ensure CI uploads build artifacts for download.
to my code.
-   [ ] For …

Fix Ubuntu CI
