isl-org/Open3D

src/IO/FileFormat/FilePCD.cpp

Fixed a bug about color decoding for ascii format PCD files.
Related to issue #207 .

Fix for #207

---

src/IO/FileFormat/FilePCD.cpp

Hi Authors,
Similar to #208 , there is a tiny bug for writing point cloud to **PCD** files. When I used `write_point_cloud("./somename.pcd", pcd )` or `write_point_cloud("./somename.pcd", pcd ,write_ascii = True)` , it generated a **PCD** file with flipped color (RGB to BGR).  
So I modified `ConvertRGBToFloat()` function in [Open3D/src/IO/FileFormat/FilePCD.cpp](https://github.com/IntelVCL/Open3D/blob/a51b3fa238f174b43106c8bf3a4970cab28ed6e0/src/IO/FileFormat/FilePCD.cpp#L632) file, and rebuilt it. Now it works good. 
Thanks.

a minor bug about flipped color for writing point cloud to PCD files

---

.appveyor.yml

AppVeyor takes about 40mins for each commit in PR. 
This will exclude VS2017+CPP14 configuration to save some time.
As of today, CI configurations for Windows are following
- VS2015 + CPP14
- VS2017 + CPP newest

Exclude VS2017+CPP14

---

src/Core/Odometry/Odometry.cpp
src/Core/Registration/Registration.cpp

- Information matrix in Odometry.cpp had '2.0' coefficient that came from legacy code used for g2o interface. g2o takes quatanion, so '2.0' were added for that. Removed now.
- Information matrix should be made based on [-q_x | I ] as shown in http://redwood-data.org/indoor/registration.html, but it wasn't configured in that way. Ordering coefficients accordingly.
- I validated this fix using Reconstruction System, and found improved result. Related to #287.

Fix information matrix bug

---

.appveyor.yml

saving open3d.cp36-win_amd64.pyd in appveyor artefacts so that one get the possibility to install the python binding to open3D on windows by simply downloading it from appveyor and copying into his python36/Lib/site-packages folder. Example here https://ci.appveyor.com/project/martinResearch/open3d/build/1.0.13/job/k94ocafr8tn0x4m9/artifacts

saving open3d.cp36-win_amd64.pyd in appveyor artefacts

---

src/CMakeLists.txt

Before (with `make VERBOSE=1`), reproducing #391:
```
[ 68%] Linking CXX executable ../bin/MergeMesh
cd /Users/ylao/repo/Open3D/build/Tools && /usr/local/Cellar/cmake/3.9.1/bin/cmake -E cmake_link_script CMakeFiles/MergeMesh.dir/link.txt --verbose=1
/usr/local/bin/c++   -std=c++11 -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/MergeMesh.dir/MergeMesh.cpp.o  -o ../bin/MergeMesh  -L/usr/local/Cellar/jsoncpp/1.8.4/lib -Wl,-rpath,/usr/local/Cellar/jsoncpp/1.8.4/lib ../lib/libOpen3D.a -framework OpenGL ../lib/libglfw3.a -framework Cocoa -framework IOKit -framework CoreFoundation -framework CoreVideo ../lib/libglew.a ../lib/libjpeg.a -ljsoncpp -lpng16 …
```

Fix MacOS libpng linking issue

---

src/Core/Registration/ColoredICP.cpp
src/Core/Registration/Registration.cpp
src/Core/Registration/TransformationEstimation.h
src/Python/Core/open3d_registration.cpp

This PR related to #411.
Key changes:
- Define TransformationEstimationType
- Adding TransformationEstimationType variable in TransformationEstimation class
- RegistrationICP terminates early with error message like below if there is no normal direction is given
```
Error: TransformationEstimationPointToPlane requires pre-computed normal vectors.
```

Point to plane ICP error message

---

src/Core/Geometry/DownSample.cpp
src/Core/Geometry/TriangleMesh.h
src/Python/Core/open3d_trianglemesh.cpp
src/Tools/CMakeLists.txt
src/Tools/ManuallyCropGeometry.cpp
src/Visualization/Utility/SelectionPolygon.cpp
src/Visualization/Utility/SelectionPolygon.h
src/Visualization/Visualizer/VisualizerWithEditing.cpp

VisualizerWithEditing class supports interactive cropping of meshes. 
- Adding SelectDownSample function for Triangular mesh
Keep a triangle only if all the three corresponding vertices are selected by user.
Preserves vertex ordering
- Generalize Tools/ManuallyCropPointCloud to Tools/ManuallyCropGeometry
Either point cloud and mesh is supported.
**Example of mesh cropping**:
```
./ManuallyCropGeometry --mesh [path_to_mesh_file] 
```
**Example of point cloud cropping**:
```
./ManuallyCropGeometry --pointcloud [path_to_mesh_or_pointcloud_file] 
```

 Supporting interactive cropping of meshes

---

src/Python/Tutorial/Utility/common.py

@syncle This PR is to solve to the issue mentioned in #231 when using the reconstruction tutorial. The added lines will sort the files list in Alphanumeric order compared to the sorted native function in Python.

Sort the file list with Alphanumeric order.

---

src/Test/CMakeLists.txt
src/Test/TestRGBDOdometry.cpp

Resolves #474.
This PR adds Test/TestRGBDOdometry. 
- This program reads two pairs of a color and a depth image, and perform RGBDOdometry. 
- The program also visualizes RGBD image as a point cloud.

adding TestRGBDOdometry

---

.clang-format
docs/contribute.rst

Clang-format is widely used in C++ projects such as [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/.clang-format), [this](https://github.com/pytorch/pytorch/blob/master/.clang-format) and [this](https://github.com/llvm-mirror/llvm/blob/master/.clang-format). Applying Clang-format to the Open3D code base could automatically ensure our code have consistent styling, and avoid manual formatting such as in https://github.com/IntelVCL/Open3D/pull/478. 
Clang format works by first having a `.clang-format` file defining the desired style in the root folder, and then running the `clang-format` command to the targeted files, such as `clang-format -i my_file.cpp`.
To avoid abrupt changes to the code base, we could make incremental changes:
Define and add `.clang-format` in …

Add clang-format file, PR 1

---

src/Python/Core/open3d_colormap.cpp

The `depth_threshold_for_discontinuity_check` and `half_dilation_kernel_size_for_discontinuity_map` from the `ColorMapOptimizationOption` class are now exposed to Python
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/555)

exposing some colormap optimization options to python

---

.clang-format
.gitignore
CMakeLists.txt
util/scripts/apply-style.sh
util/scripts/check-style.sh

Second PR towards automatic format checking: https://github.com/IntelVCL/Open3D/pull/532
For developers before submitting PR
```bash
make apply-style
```
For CI
```bash
make check-style
```
```
➜  ~/repo/Open3D/build (auto-format) make apply-style
...
Applying style in /Users/ylao/repo/Open3D/src
[formatted] src/Visualization/Shader/SimpleShader.h
[formatted] src/Visualization/Shader/PhongShader.cpp
[formatted] src/Visualization/Shader/GeometryRenderer.cpp
[formatted] src/Visualization/Shader/ImageMaskShader.h
...
297 of 304 files were reformatted
Built target apply-style
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/589)

add `make check-style` and `make apply-style`

---

3rdparty/GLFW/CMakeLists.txt
3rdparty/glew/CMakeLists.txt

This fixes #578.
The issue arise when OPEN3D_HEADLESS_RENDERING were renamed as ENABLE_HEADLESS_RENDERING in [this commit](https://github.com/IntelVCL/Open3D/commit/d843712297606acd2ea53b9479b2c59ba814046c).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/579)

fix ENABLE_HEADLESS_RENDERING flag issue

---

src/Python/Visualization/open3d_utility.cpp
src/Visualization/Utility/SelectionPolygonVolume.cpp
src/Visualization/Utility/SelectionPolygonVolume.h

AFAIK there is no dedicated way to crop a TriangleMesh using a SelectionPolygonVolume (as created with the visualizer) via the python bindings. 
This PR would resolves this by adding the equivalent of the crop_point_cloud method for a TriangleMesh to SelectionPolygonVolume and the pybindings.
It seems to do exactly what I want, but I can't tell if this might cause a problem somewhere else. So feel free to see this as a feature request with reference implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/585)

Adding CropTriangleMesh to SelectionPolygonVolume and pybindings

---

examples/Python/ReconstructionSystem/make_fragments.py

Before this change, setting a path_dataset in the config which does not end on '/' leads to a wrong path here, making the fragment writing fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/610)

Use proper path concatenation in make_fragments.py

---

3rdparty/libpng/CMakeLists.txt
3rdparty/libpng/arm/arm_init.c
3rdparty/libpng/arm/filter_neon.S
3rdparty/libpng/arm/filter_neon_intrinsics.c
3rdparty/libpng/contrib/arm-neon/README
3rdparty/libpng/contrib/arm-neon/linux.c

The init purpose is to use open3d on Nvidia Jetson TX2. I found that when using 
```
pip install --user open3d-python 
```
After installing and begin import open3d, it said:
```
ImportError: /home/nvidia/.local/lib/python3.5/site-packages/open3d/linux/open3d.so: cannot open shared object file: No such file or directory
```
While if we use build-from-source, there is png error for its code in 3rdparty has no support for arm. So I added missing files and updated CMakeList.txt. Now everything works well on TX2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/625)

add support for arm(jetson tx2) platform

---

CMakeLists.txt
src/Python/CMakeLists.txt
src/Python/Package/open3d/__init__.py
src/Python/make_python_package.cmake

Before: all based on whether `npm` is detected
Now: only when `ENABLE_JUPYTER=ON`, cmake will try to detect `npm`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/655)

Add option to disable jupyter build

---

src/IO/ClassIO/TriangleMeshIO.cpp
src/Visualization/Utility/SelectionPolygon.cpp
src/Visualization/Utility/SelectionPolygonVolume.cpp

This PR adds the following behavior:
- Emit a warning during reading IO (ReadTriangleMesh), if input PLY is a pointcloud (contains zero/no faces).
- Emit a warning when calling CropTriangleMesh from a SelectionPolygonVolume if TriangleMesh is only a PointCloud
- Emit a warning when calling CropTriangleMesh from a SelectionPolygon  if TriangleMesh is only a PointCloud
Possible problems/short comings of this PR (imo):
- Depending on whether one wants to introduce some terminology like "degenerated TM", then this piece of code `mesh.HasVertices() && !mesh.HasTriangles()` could also be made a member function of TriangleMesh like `isEmpty`.  This raises the questions, what about TriangleMeshes with vertices, triangles, but also N unconnected vertices (e.g., hasUnconnectedVertices() ). How …

Adding warning output for "degenerated" TriangleMeshes

---

src/Python/Visualization/open3d_visualizer.cpp
src/Visualization/Visualizer/VisualizerWithEditing.cpp
src/Visualization/Visualizer/VisualizerWithEditing.h

This PR aims to e xpose the VisualizerWithEdit constructor with arguments through its python bindings. Without one can not define the default filepath which very inconvenient. 
Additionally, this PR adds a counter to the "cropped.ply" file, since most likely one will apply more than one cropping (and requires all to obtain the same final results when loading and applying the crop selections). The counter is only increased if a file is actually saved (although by that point, the point cloud already changed, and the user might start over anyway).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/630)

Expose non-default constructor of VisualizerWithEdit in Python and add counter to automatic filename

---

src/Python/open3d_eigen.cpp

Fixed warning: 
```
c:\users\linux\repo\open3d\src\python\open3d_eigen.cpp(235): note: see reference to function template instantiation 'std::vecto
r<Eigen::Vector3d,std::allocator<_Ty>> pybind11::py_array_to_vectors_double<Eigen::Vector3d>(pybind11::array_t<double,17>)' bei
ng compiled
with
[
_Ty=Eigen::Vector3d
]
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/662)

Fix windows compilation warning with py::ssize_t

---

src/Core/Camera/PinholeCameraIntrinsic.cpp

fixed bug due to PinholeCameraIntrinsic constructor not initializing member data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/684)

Constructor initialization

---

src/Core/Camera/PinholeCameraIntrinsic.cpp
src/UnitTest/Core/Camera/PinholeCameraIntrinsic.cpp

implemented the PinholeCameraIntrinsic test case.
fixed bug in PinholeCameraIntrinsic: uninitialized member data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/689)

PinholeCameraIntrinsic

---

src/UnitTest/Core/Geometry/KDTreeFlann.cpp
src/UnitTest/UnitTest.cpp
src/UnitTest/UnitTest.h

+ using namespace directive in order to reduce code line length.
simplified comparisons using unit_test::ExpectEQ(...).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/693)

KDTreeFlann

---

CMakeLists.txt

Fixes #712 
Previously on CI, there are also a lot of such warnings, see https://travis-ci.org/IntelVCL/Open3D/jobs/460845985#L2675.
This was introduced in a previous commit:
https://github.com/IntelVCL/Open3D/pull/707/files#diff-af3b638bc2a3e6c650974192a53c7291R139
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/722)

remove mac flag -Wno-expansion-to-defined

---

src/IO/FileFormat/FilePLY.cpp

_fix typos in _FilePLY.cpp_: from ply_poincloud_reader to ply_pointcloud_reader_
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/729)

fix typos: ply_poincloud_reader to ply_pointcloud_reader

---

src/Python/check_and_install_conda_deps.cmake

The original code failed on a miniconda3 installation - sys.version did not include the 'conda' substring.
For miniconda2, sys.version reports:
'2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 19:04:19) \n[GCC 7.3.0]'
For miniconda3, sys.version reports:
'3.7.1 (default, Dec 14 2018, 19:28:38) \n[GCC 7.3.0]'
Using 'conda info' we can tell whether a conda environment is active or not:
(base) root@open3d-test-14# conda info | grep "active environment"
active environment : base
(base) root@open3d-test-14# conda deactivate
root@open3d-test-14# conda info | grep "active environment"
active environment : None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/750)

alternate way of detecting conda active environment

---

src/Python/Visualization/open3d_renderoption.cpp
src/Visualization/Shader/SimpleShader.cpp
src/Visualization/Visualizer/RenderOption.cpp
src/Visualization/Visualizer/RenderOption.h
src/Visualization/Visualizer/Visualizer.cpp
src/Visualization/Visualizer/VisualizerCallback.cpp

addresses #734.
- Adding "shift + +/-" key event that can change width of LineSet for the visualization
- Add line_width in RenderOption and corresponding Python binding
- Applies to C++/Python API
Screen shot
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/738)

adjust width of LineSet

---

src/IO/ClassIO/LineSetIO.cpp
src/IO/ClassIO/LineSetIO.h
src/IO/FileFormat/FilePLY.cpp
src/Python/Core/open3d_lineset.cpp
src/Tools/ViewGeometry.cpp

Addresses #705.
- Adding I/O functions for LineSet.
- Currently only PLY format is supported for LineSet. (As suggested by @xuyongzhi, PLY format supports ``edge`` to store line fragments.)
- Add "lineset" option into ViewGeometry application
Example:
```
points = [[0,0,0],[1,0,0],[0,1,0],[1,1,0],
[0,0,1],[1,0,1],[0,1,1],[1,1,1]]
lines = [[0,1],[0,2],[1,3],[2,3],
[4,5],[4,6],[5,7],[6,7],
[0,4],[1,5],[2,6],[3,7]]
colors = [[1, 0, 0] for i in range(len(lines))]
line_set = LineSet()
line_set.points = Vector3dVector(points)
line_set.lines = Vector2iVector(lines)
line_set.colors = Vector3dVector(colors)
write_line_set("test.ply", line_set, write_ascii=True)
```
This will produce the following file (test.ply).
```
ply
format ascii 1.0
comment Created by Open3D
element vertex 8
property double x …
```

IO for LineSet

---

src/Core/Utility/Eigen.cpp

Fixes -Wpessimizing-move warnings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/755)

Remove unneeded std::move calls

---

docs/tutorial/Basic/visualization.rst
src/Visualization/Visualizer/ViewControl.cpp
src/Visualization/Visualizer/ViewControl.h
src/Visualization/Visualizer/Visualizer.cpp
src/Visualization/Visualizer/Visualizer.h
src/Visualization/Visualizer/VisualizerCallback.cpp

Resolves #560, #617, #744.
**Key changes**
- ``Shift + left mouse button + drag`` rotates geometry along z-axis (rolling)
- ``mouse wheel button + drag`` translates the geometry
**Need to check**
Check these additive modes are supported by other Visualization modes, such as ViewControlWithCustomAnimation or ViewControlWithEditing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/745)

Panning by Mouse Wheel Drag & Rolling Option

---

src/Python/Visualization/open3d_renderoption.cpp

This resolves #765.
Key changes
- Expose ``point_color_option``, ``mesh_shade_option``, and ``mesh_color_option``
- Expose enum variables of the ``PointColorOption``, ``MeshShadeOption``, ``MeshColorOption``
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/778)

Expose PointColorOption, MeshShadeOption, MeshColorOption

---

docs/conf.py
src/Python/Core/open3d_voxelgrid.cpp

A quick fix for the release
- Disable "view page source" in the doc html
- Expose additional attributes in the VoxelGrid
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/784)

minor fixes

---

.travis.yml

If switching to xcode 8.3 doesn't help the mac build time, we can consider only keeping the latest version of xcode available on Travis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/792)

only keep xcode10.1 for mac travis

---

src/Core/Camera/PinholeCameraIntrinsic.cpp

cx and cy was replaced with fx, fy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/801)

fixed parameters for depth in Kinect2

---

src/Core/ColorMap/ColorMapOptimizationJacobian.cpp
src/Core/ColorMap/ImageWarpingField.cpp
src/Core/ColorMap/TriangleMeshAndImageUtilities.cpp

Several changes:
1. When computing visibility map `images_mask` is now used, previously it was ignored due to a typo.
2. Index out-of-bound segfaults I: `baseidx < anchor_w_ * anchor_h_ * 2`, cannot be `=`
3. Index out-of-bound segfaults II: Given a pixel location, the base anchor point index `(ii, jj)` must satisfy
```cpp
ii < anchor_w_ - 1;
jj < anchor_h_ - 1;
```
This is because if the base location is `(ii, jj)`, the four anchors are 
```cpp
(ii, jj), (ii + 1, jj), (ii, jj + 1), (ii + 1, jj + 1)
```
and we must have
```cpp
ii + 1 < anchor_w_;
jj + 1 < anchor_h_;
```
4. Divergence: `double anchor_step` shall be used instead of `int anchor_step`, this creates small misalignments when getting pixel values from the image, leading to divergence in the end.
Compared numerical results …

Fix Colomap segfault and divergence issues

---

src/Core/Geometry/TriangleMesh.cpp
src/Core/Geometry/TriangleMesh.h
src/Python/Core/open3d_trianglemesh.cpp
src/UnitTest/Core/Geometry/TriangleMesh.cpp

Adjacency map is useful for implementing some mesh operations. There are some decision made with Jaesik. Please feel free to comment on the datastructure selection. 
1. map vs vector vs set
```cpp
std::vector<std::unordered_set<int>> // selected, to fast check if two nodes are neighbors
std::vector<int, std::vector<int>>
std::unordered_map<int, std::unordered_set<int>>
```
2. size_t vs int
```cpp
std::vector<std::unordered_set<int>> // selected
std::vector<std::unordered_set<size_t>>
```
Tested with python as well
```python
type(mesh.adjacency_list[0])
Out[4]: set
type(mesh.adjacency_list)
Out[5]: list
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/830)

Compute vertex adjacency map

---

README.md
docs/index.rst

- Move links to very front and simplify readme. 
- Move citation to a separate section.
Preview of how it looks:
https://github.com/yxlao/Open3D/blob/readme-reorg/README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intelvcl/open3d/887)

Reorganize readme links

---

.github/ISSUE_TEMPLATE/bug_report.md
examples/Python/Basic/mesh_voxelization.py
src/Open3D/Geometry/HalfEdgeTriangleMesh.h
src/Open3D/Geometry/Image.h
src/Open3D/Geometry/PointCloud.h
src/Open3D/Geometry/RGBDImage.h
src/Open3D/Geometry/TriangleMesh.h
src/Open3D/Geometry/VoxelGrid.h
src/Open3D/Registration/GlobalOptimizationConvergenceCriteria.h
src/Open3D/Registration/PoseGraph.h
src/Open3D/Visualization/Utility/ColorMap.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/908)

remove dummy semicolon after empty functions

---

src/Open3D/Geometry/Octree.cpp
src/Open3D/Geometry/Octree.h
src/UnitTest/Geometry/HalfEdgeTriangleMesh.cpp
src/UnitTest/Geometry/Octree.cpp

- `Octree` class
- Constructor
- Copy constructor
- Node insertion
- Node locate
- Convert from PointCloud
- Traverse function with labmda
- `OctreeNode` class: two sub types
- `OctreeNodeInfo` class.
- Design decision: do not store the origin and size of a node in `OctreeNode`, store in `OctreeNodeInfo`
- `OctreeNodeInfo` is computed then disgraded
- Gain space efficiency with more computes
- Unit tests
Currently `OctreeLeafNode` only takes `color` property. The plan is to expand this to support flexible datatype.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/903)

Initial Octree support

---

examples/Python/Basic/mesh_sampling.py
src/Open3D/Geometry/TriangleMesh.cpp
src/Open3D/Geometry/TriangleMesh.h
src/Python/geometry/trianglemesh.cpp
src/UnitTest/Geometry/TriangleMesh.cpp

Implementation of uniform point cloud sampling from triangle mesh
respecting mesh vertex colors and vertex normals. Added utility
method TriangleArea to TriangleMesh that computes area of a
mesh triangle identified by its index.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/907)

Uniform point sampling from triangle mesh

---

src/Open3D/IO/ClassIO/PinholeCameraTrajectoryIO.cpp
src/Open3D/IO/ClassIO/PinholeCameraTrajectoryIO.h
src/Open3D/IO/FileFormat/FileTUM.cpp

Reader for TUM trajectory files, as described here #951
The clang-format was applied and coding style is as in `FileLOG.cpp`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/953)

Add TUM trajectory format

---

examples/Python/Basic/mesh_simplification.py
src/Open3D/Geometry/TriangleMesh.cpp
src/Open3D/Geometry/TriangleMesh.h
src/Open3D/Geometry/TriangleMeshSimplification.cpp
src/Open3D/Geometry/TriangleMeshSubdivide.cpp
src/Python/geometry/trianglemesh.cpp
src/UnitTest/Geometry/TriangleMesh.cpp

Implemented a vertex cluster mesh simplification (using vertex average and quadric minimization) and "Surface Simplification Using Quadric Error Metrics". For testing, I added also a simple mesh subdivision method (midpoint). The color and normal information is averaged in all implementations and not considered in the error minimization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/945)

Mesh Simplification

---

src/Open3D/Geometry/Octree.cpp
src/Open3D/Geometry/Octree.h
src/Open3D/Geometry/VoxelGrid.cpp
src/Open3D/Geometry/VoxelGrid.h
src/UnitTest/Geometry/Octree.cpp

Input PointCloud (PointCloud to Octree)
VoxelGrid (Octree to VoxelGrid)
The visualization above depends on "VoxelGrid OpenGL 3.1+ visualizer fix" in #918 . Will polish and create another PR. Without the "VoxelGrid OpenGL 3.1+ visualizer fix", VoxelGrid can still be converted from Octree, but VoxelGrid cannot be optimized. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/914)

Octree to VoxelGrid conversion

---

.travis.yml
src/Open3D/Geometry/Octree.cpp
src/Open3D/Geometry/VoxelGrid.cpp
src/Python/geometry/octree.cpp
src/Python/geometry/octree.h
src/UnitTest/Python/test_octree.py

Fixes the Octree python binding and OctreeColorLeafNode merge conflict which breaks the current master build
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/959)

Fix octree merge conflicts

---

examples/Python/ReconstructionSystem/scripts/synchronize_frames.py

There is an edge case this script fails on, and that is the case where there is no associated synchronized depth frame for a given color frame.
I assume that this will only happen on the last color frame of a sequence, where the recording is killed before the associated depth frame is written. If this assumption holds, then the patch will delete the last color file since there is no depth frame to go with it.
This issue can be tested with Redwood class `toilet`, sequence `08597`.
As a side note, I could not find a statement _explicitly_ stating that the raw frames from Redwood need to be run through this script, but clearly they do. I would recommend adding that somewhere prominent in the docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

fixing issue with no associated color-depth sync frame

---

src/Open3D/Geometry/Octree.cpp
src/Open3D/Geometry/Octree.h
src/Open3D/IO/ClassIO/OctreeIO.cpp
src/Open3D/IO/ClassIO/OctreeIO.h
src/Python/geometry/octree.cpp
src/UnitTest/Geometry/Octree.cpp
src/UnitTest/IO/ClassIO/OctreeIO.cpp

Add octree I/O support for json (ascii output). Based on https://github.com/intel-isl/Open3D/pull/903, merge https://github.com/intel-isl/Open3D/pull/903 first.
Example json output
```json
{
"class_name" : "Octree",
"max_depth" : 1,
"nodes" : 
[
{
"children" : [ 1, 2, 3, 4, 5, 6, 7, 8 ],
"class_name" : "OctreeInternalNode",
"id" : 0
},
{
"class_name" : "OctreeLeafNode",
"color" : [ 0.0, 0.0, 0.0 ],
"id" : 1
},
{
"class_name" : "OctreeLeafNode",
"color" : [ 0.25, 0.0, 0.0 ],
"id" : 2
},
{
"class_name" : "OctreeLeafNode",
"color" : [ 0.0, 0.25, 0.0 ],
"id" : 3
},
{
"class_name" : "OctreeLeafNode",
"color" : [ 0.25, 0.25, 0.0 ],
"id" : 4
},
{
"class_name" : "OctreeLeafNode",
"color" : [ 0.0, 0.0, 0.25 ],
"id" : 5
},
{
"class_name" : "OctreeLeafNode",
"color" : [ 0.25, 0.0, 0.25 ],
"id" : 6 …
```

Add octree I/O support for json

---

examples/Cpp/TriangleMesh.cpp
examples/Python/Basic/convex_hull.py
examples/Python/Basic/mesh_filter.py
examples/Python/Basic/mesh_properties.py
examples/Python/Basic/mesh_sampling.py
examples/Python/Basic/mesh_simplification.py
examples/Python/Basic/mesh_subdivision.py
examples/Python/Basic/meshes.py
src/Open3D/Geometry/DownSample.cpp
src/Open3D/Geometry/HalfEdgeTriangleMesh.cpp
src/Open3D/Geometry/HalfEdgeTriangleMesh.h
src/Open3D/Geometry/TriangleMesh.cpp
src/Open3D/Geometry/TriangleMesh.h
src/Open3D/Geometry/TriangleMeshSimplification.cpp
src/Python/geometry/geometry_trampoline.h
src/Python/geometry/trianglemesh.cpp
src/Tools/MergeMesh.cpp
src/UnitTest/Geometry/TriangleMesh.cpp

In this PR I renamed the existing `RemoveNonManifold*` methods in `TriangleMesh` to reflect their actual behavior: `RemoveUnreferencedVertices()` and `RemoveDegenerateTriangles()`. In addition, I moved them to public scope, added doc strings and made them accessible through Python bindings.
The main contribution in this PR is an actual `RemoveNonManifoldEdges()` method. Non manifold edges are edges with more than 2 adjacent triangles. Hence, this method removes the triangle with the smallest surface area from the non-manifold edges until they are manifold.
This method is showcased in the `mesh_properties.py` example. Further, I cleaned up a bit the Python examples by introducing a `meshes.py` file that provides functions to create/load triangle meshes.
--- …

Remove non manifold edges from triangle mesh

---

examples/Python/Basic/mesh_simplification.py
examples/Python/Basic/meshes.py
examples/Python/Basic/transformation.py
src/Open3D/Geometry/Geometry3D.h
src/Open3D/Geometry/LineSet.cpp
src/Open3D/Geometry/LineSet.h
src/Open3D/Geometry/Octree.cpp
src/Open3D/Geometry/Octree.h
src/Open3D/Geometry/PointCloud.cpp
src/Open3D/Geometry/PointCloud.h
src/Open3D/Geometry/TriangleMesh.cpp
src/Open3D/Geometry/TriangleMesh.h
src/Open3D/Geometry/VoxelGrid.cpp
src/Open3D/Geometry/VoxelGrid.h
src/Open3D/Visualization/Utility/PointCloudPicker.cpp
src/Open3D/Visualization/Utility/PointCloudPicker.h
src/Python/geometry/geometry.cpp

I added a `center` parameter to the `Rotate` methods of the `Geometry3D` classes. If it is set to `true`, then the vertices/points are rotated in the centered 3D space.
In addition, I center the points/vertices in the `Scale` methods, otherwise it would do something different as most users might expect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/994)

Added center parameter to rotate method

---

docs/conf.py
docs/make.py
src/Python/docstring.cpp
util/scripts/apply-style.cmake
util/scripts/check-style.cmake

- Handles static class method docs for pybind code, fixes the 3rd issue in https://github.com/intel-isl/Open3D/pull/1003
- Update docs builder to clear `python_api` and `build_` dir each time before build
- Apply style in `docs` folder for `.py` files
Before
After
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1005)

Class static methods docs

---

src/Python/package/open3d/__init__.py

Before: with shortcut
```python
open3d.PointCloud
open3d.geometry.PointCloud
```
After: full module path must be used
```python
open3d.geometry.PointCloud
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1006)

Remove python shortcuts

---

src/Open3D/Geometry/LineSet.cpp
src/Open3D/Geometry/PointCloud.cpp
src/Open3D/Geometry/TriangleMesh.cpp
src/Open3D/Geometry/TriangleMesh.h
src/UnitTest/Geometry/PointCloud.cpp

Improving the `Filter*` methods of `TriangleMesh` by avoiding unnecessary memory copies in each iteration. This should be especially noticeable in `FilterSmoothTaubin`.
Simpler `GetMinBounds` and `GetMaxBounds` in `TriangleMesh`, `LineSet`, and `PointCloud`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1010)

TriangleMesh Filter improvements, GetBounds improvements

---

examples/Python/Basic/pointcloud_estimate_normals.py
src/Open3D/Geometry/EstimateNormals.cpp
src/Open3D/Geometry/PointCloud.h
src/Python/geometry/pointcloud.cpp
src/UnitTest/Geometry/PointCloud.cpp

Reverted the eigenvector computation in `EstimateNormals` in `PointCloud` back to `EigenSolver`. This solves the problem in issue #880, and benchmarking results indicate that it is less than 3ms slower for larger point clouds (1e6 points).
Otherwise the `FastEigen3x3` method needs to handle a few special cases. See https://www.geometrictools.com/Documentation/RobustEigenSymmetric3x3.pdf
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1011)

PointCloud EstimateNormals fix

---

src/Open3D/CMakeLists.txt

This fixes a regression that previously got fixed in https://github.com/intel-isl/Open3D/pull/711.
Include directories in the CMake config file should be relative to the install directory. The current bug makes it absolute paths to the source directory.
Before:
```cmake
set(Open3D_INCLUDE_DIRS "${PACKAGE_PREFIX_DIR}/include;S:/Coding/open3d-win-sandbox/Open3D/3rdparty/Eigen;S:/Coding/open3d-win-sandbox/Open3D/3rdparty/glew/include;S:/Coding/open3d-win-sandbox/Open3D/3rdparty/GLFW/include")
```
After:
```cmake
set(Open3D_INCLUDE_DIRS "${PACKAGE_PREFIX_DIR}/include;${PACKAGE_PREFIX_DIR}/include/Open3D/3rdparty/Eigen;${PACKAGE_PREFIX_DIR}/include/Open3D/3rdparty/glew/include;${PACKAGE_PREFIX_DIR}/include/Open3D/3rdparty/GLFW/include")
```
--- …

Make include directories in Open3DConfig.cmake relative again

---

src/Open3D/Utility/Helper.h

Addressing issue #934 by removing the inheritance from `unary_function` in `hash_eigen`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1023)

Removed unary_function from hash_eigen

---

.gitmodules
3rdparty/CMakeLists.txt
3rdparty/README.txt
docs/tutorial/Basic/file_io.rst
examples/Python/Basic/mesh_io.py
src/Open3D/IO/ClassIO/TriangleMeshIO.cpp
src/Open3D/IO/ClassIO/TriangleMeshIO.h
src/Open3D/IO/FileFormat/FileOBJ.cpp

Added IO support for obj (http://paulbourke.net/dataformats/obj/) file types. This is based on the `tinyobjloader` library added as submodule. Note that we only support vertex, vertex normals and vertex colors at the moment and no textures, or materials. This addresses issue #772 
I further added the supported mesh types for IO to the documentation. This addresses issue #1019
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1021)

FileOBJ for TriangleMesh

---

src/Open3D/IO/FileFormat/FileSTL.cpp

This PR addresses the following bug:
Reading a mesh without normals specified (e.g. "knot.ply" in TestData) and saving to .stl causes a segmentation fault. However, the mesh seems to be correctly saved if either `mesh.compute_vertex_normals()` or `mesh.compute_triangle_normals()` is done first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1041)

Check for mesh normals before saving STL file

---

src/Open3D/Geometry/PointCloud.cpp
src/Open3D/Geometry/PointCloud.h
src/Open3D/IO/ClassIO/PointCloudIO.cpp
src/Open3D/IO/ClassIO/PointCloudIO.h
src/Open3D/IO/FileFormat/FilePCD.cpp
src/Python/geometry/pointcloud.cpp
src/Python/io/io.cpp

This addresses issue #1016. I added a parameter to control if NaNs should be removed after reading a `PointCloud`, or not. The default is set to `true`, such that the function is backwards compatible. 
Note that this fixes also a subtle bug in the `RemoveNaN` function that has so far been unnoticed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1022)

Added option to remove NaN points in ReadPointCloud

---

examples/Python/Basic/clustering.py
examples/Python/Basic/meshes.py
examples/Python/Basic/pointcloud_estimate_normals.py
src/Open3D/Geometry/PointCloud.h
src/Open3D/Geometry/PointCloudCluster.cpp
src/Python/geometry/pointcloud.cpp

Implementation of the DBSCAN clustering algorithm for `PointCloud`. Implementation is not threaded for now, but could be a simple addition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1038)

DBSCAN clustering algorithm

---

docs/builddocs.rst
docs/compilation.rst
docs/index.rst

Created a separate page for documentation on how to build the docs in line with GSoD. I'll add more documentation later on such as editing .rst files and working with the C++ API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1036)

Added Documentation to build docs

---

src/Open3D/Camera/PinholeCameraIntrinsic.h
src/Python/camera/camera.cpp

Updated Python API and C++ docs for open3d.camera.PinholeCameraIntrinsic and fixed a typo present in the website documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1039)

Update Python and C++ docs for Camera PinholeCameraIntrinsic

---

src/Open3D/IO/ClassIO/TriangleMeshIO.cpp
src/Open3D/IO/ClassIO/TriangleMeshIO.h
src/Open3D/IO/FileFormat/FileOBJ.cpp
src/Open3D/IO/FileFormat/FileOFF.cpp
src/Open3D/IO/FileFormat/FilePLY.cpp
src/Open3D/IO/FileFormat/FileSTL.cpp
src/Python/io/io.cpp

Adds an option for the user to specify whether vertex normals and/or vertex colors should be written when saving a mesh. By default, these options are set to `True`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1051)

Add flags to the write triangle mesh methods

---

examples/Python/Basic/mesh_properties.py
src/Open3D/Geometry/TriangleMesh.cpp
src/Open3D/Geometry/TriangleMesh.h
src/Python/geometry/trianglemesh.cpp

Adds a convenience function which replaces
```
watertight = mesh.is_edge_manifold(allow_boundary_edges=False) and mesh.is_vertex_manifold() and not mesh.is_self_intersecting()
```
with
```
watertight = mesh.is_watertight()
```
Some minor typos are also corrected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1053)

Add function is_watertight() to TriangleMesh

---

src/Open3D/IO/ClassIO/TriangleMeshIO.cpp
src/Open3D/IO/ClassIO/TriangleMeshIO.h
src/Open3D/IO/FileFormat/FileOFF.cpp

This PR adds support for loading meshes with non-convex faces.
The implementation is partly based on the ear clipping approach used in the 3rdparty header `tinyobjloader.h` used to load .obj files. The point inclusion in polygon test is acquired from [here](https://stackoverflow.com/a/43896965).
Currently, the triangulation by ear clipping algorithm is only added to the .off-loader. Additionally, it should be added to loading .ply files, but I'm not sure what would be the best approach to do this. .obj-files are handled by `tinyobjloader.h` and .stl-files are triangular representations, per the specifications.
Example triangulations are given in the illustration below:
The chosen ear to base the triangulation on is the first one found in each step (assuming counterclockwise ordering of …

Triangulation by ear clipping

---

.travis.yml
docs/contribute.rst
examples/Python/ReconstructionSystem/sensors/realsense_recorder.py

A new version of yapf was released recently causing master build error. To avoid future issues like this, yapf used by Travis is fixed to `0.28.0`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1071)

Fix master build error, fix yapf==0.28.0

---

src/Open3D/Integration/ScalableTSDFVolume.cpp
src/Open3D/Integration/UniformTSDFVolume.cpp
src/Open3D/Integration/UniformTSDFVolume.h
src/UnitTest/Integration/UniformTSDFVolume.cpp

Fixes #1078 , since it is a dense voxel grid, we can simply use a `vector`.
As discussed, in the future, we will 1) split the voxel grid class to `DenseVoxelGrid` and `SparseVoxelGrid`, 2) use continuous buffers for each property separately, instead of a vector of voxels that contains different properties.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1079)

remove TSDFVoxelGrid class

---

src/Open3D/Visualization/Visualizer/ViewControl.cpp

Set `z_near_` close to `0`.
Before:
Afterwards:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1080)

Set z_near_ close to 0

---

src/Open3D/Geometry/DownSample.cpp

Addressing #1105, using Euclidean distance instead of squared Euclidean distance to compute the mean and std.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1126)

Using correct Euclidean distance in RemoveStatisticalOutliers

---

examples/Python/Basic/meshes.py
src/Open3D/Visualization/Visualizer/ViewControl.cpp
src/Open3D/Visualization/Visualizer/ViewControl.h
src/Python/visualization/viewcontrol.cpp

#1080 introduced problems in the rendering of meshes, see for example #1096. This PR reverts those changes.
In addition, I added a methods to set/unset constant z planes of the visualizer, i.e., that are independent of the zoom and the bounding box size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1122)

Revert #1080 and added method for constant z planes

---

src/Open3D/IO/FileFormat/FileGLTF.cpp

This PR builds upon #1082, and implements the following extensions:
- All meshes given in a glTF file are loaded in the read function, and they are transformed based on any optional translation/rotation/scaling specified. [Test sample](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/OrientationTest)
- Vertex colors are now fully supported (VEC3/VEC4, FLOAT/UNSIGNED BYTE/UNSIGNED SHORT). [Test samples](https://github.com/KhronosGroup/glTF-Asset-Generator/tree/master/Output/Positive/Mesh_PrimitiveVertexColor)
- Minor optimization added to writing indices to file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1100)

Extend functionality of FileGLTF for TriangleMesh

---

3rdparty/CMakeLists.txt
3rdparty/azure_kinect/azure_kinect.cmake
src/Open3D/IO/Sensor/AzureKinect/AzureKinectRecorder.cpp
src/Open3D/IO/Sensor/AzureKinect/AzureKinectRecorder.h
src/Open3D/IO/Sensor/AzureKinect/AzureKinectSensor.cpp
src/Open3D/IO/Sensor/AzureKinect/AzureKinectSensor.h
src/Open3D/IO/Sensor/AzureKinect/AzureKinectSensorConfig.cpp
src/Open3D/IO/Sensor/AzureKinect/K4aPlugin.cpp
src/Open3D/IO/Sensor/AzureKinect/K4aPlugin.h
src/Open3D/IO/Sensor/AzureKinect/MKVMetadata.cpp
src/Open3D/IO/Sensor/AzureKinect/MKVReader.cpp
src/Open3D/IO/Sensor/AzureKinect/MKVReader.h
src/Open3D/IO/Sensor/AzureKinect/MKVWriter.cpp
src/Open3D/IO/Sensor/AzureKinect/PluginMacros.h
src/Python/CMakeLists.txt
src/Python/make_python_package.cmake

- Complete `dlopen` approach
- Stub k4a interface built-in
- Use macros to quickly define k4a functions
- Do not need to link libk4a.so or libk4arecord.so, they will be loaded at runtime
- Python package no longer carry the shared libs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1132)

K4a with dlopen

---

.gitignore
examples/Python/Advanced/surface_reconstruction_ball_pivoting.py
examples/Python/Basic/clustering.py
src/Open3D/Geometry/BoundingVolume.cpp
src/Open3D/Geometry/BoundingVolume.h
src/Open3D/Geometry/Geometry3D.h
src/Open3D/Geometry/HalfEdgeTriangleMesh.cpp
src/Open3D/Geometry/HalfEdgeTriangleMesh.h
src/Open3D/Geometry/LineSet.cpp
src/Open3D/Geometry/LineSet.h
src/Open3D/Geometry/Octree.cpp
src/Open3D/Geometry/Octree.h
src/Open3D/Geometry/PointCloud.cpp
src/Open3D/Geometry/PointCloud.h
src/Open3D/Geometry/PointCloudCluster.cpp
src/Open3D/Geometry/TetraMesh.cpp
src/Open3D/Geometry/TetraMesh.h
src/Open3D/Geometry/TriangleMesh.cpp
src/Open3D/Geometry/TriangleMesh.h
src/Open3D/Geometry/VoxelGrid.cpp
src/Open3D/Geometry/VoxelGrid.h
src/Open3D/Utility/Console.h
src/Open3D/Utility/Helper.cpp
src/Open3D/Utility/Helper.h
src/Open3D/Visualization/Utility/PointCloudPicker.cpp
src/Open3D/Visualization/Utility/PointCloudPicker.h
src/Python/geometry/geometry.cpp
src/Python/geometry/geometry_trampoline.h
src/Python/geometry/pointcloud.cpp

This PR speeds up DBSCAN by pre-computing the neighbors using omp.
I further added a `GetCenter` method to `Geometry3D` and a `relative` parameter to `Translate` to allow to move the center to a specific position.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1147)

DBSCAN speed up

---

docs/tutorial/Basic/azure_kinect.rst
docs/tutorial/Basic/index.rst
examples/Python/ReconstructionSystem/sensors/azure_kinect_viewer.py
src/Open3D/IO/Sensor/AzureKinect/K4aPlugin.cpp
src/Python/package/open3d/__init__.py

MS Azure Kinect on Ubuntu 16.04 is not officially supported on Ubuntu 16.04. This PR is a fix for that.
On ubuntu 16.04, run
```shell
pip install open3d_azure_kinect_ubuntu1604_fix
pip install open3d-python # will be `pip install open3d` in the next release
```
Also see https://pypi.org/project/open3d-azure-kinect-ubuntu1604-fix/, https://github.com/yxlao/open3d_azure_kinect_ubuntu1604_fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1149)

Fixes for Azure Kinect on Ubuntu 16.04

---

src/Open3D/Geometry/BoundingVolume.cpp
src/Open3D/Geometry/Geometry3D.cpp
src/Open3D/Geometry/Geometry3D.h
src/Open3D/Geometry/HalfEdgeTriangleMesh.cpp
src/Open3D/Geometry/LineSet.cpp
src/Open3D/Geometry/LineSet.h
src/Open3D/Geometry/PointCloud.cpp
src/Open3D/Geometry/PointCloud.h
src/Open3D/Geometry/TriangleMesh.cpp
src/Open3D/Geometry/TriangleMesh.h
src/UnitTest/Geometry/LineSet.cpp
src/UnitTest/Geometry/PointCloud.cpp
src/UnitTest/Geometry/TriangleMesh.cpp

I simplified (and removed code duplication) from the `Geometry3D` classes. 
Additionally, I addressed issue #909. If `color` is outside the valid range of `[0, 1]` the method prints a warning and clips the color value to the valid range.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1150)

Geometry Code Simplification and PaintUniformColor Warning

---

3rdparty/azure_kinect/azure_kinect.cmake
docs/tutorial/Basic/azure_kinect.rst
src/Open3D/IO/Sensor/AzureKinect/AzureKinectSensorConfig.cpp
src/Open3D/IO/Sensor/AzureKinect/K4aPlugin.cpp
src/Open3D/IO/Sensor/AzureKinect/PluginMacros.h

- Allow Ubuntu 16.04 to build azure kinect support when `open3d-azure-kinect-ubuntu1604` pip package is installed. This is useful since the released Open3D is built on Ubuntu 16.04 in order to be compatible with both 16.04 and 18.04. 
- Simplify `azure_kinect.cmake`: `k4a_INCLUDE_DIRS` is all we need at build time, no library or lib paths are needed
- Added the option for Windows users to specify `cmake -DK4A_INCLUDE_DIR=...` at at CMake config time
- Added the option for Windows user to specify `K4A_LIB_DIR` environment variable to point to K4a DLLs, e.g.
```
set K4A_LIB_DIR=C:\Program Files\Azure Kinect SDK v1.2.0\sdk\windows-desktop\amd64\release\bin
```
- `std::map` instead dof `std::unorderd_map` for enum to string map, to be compatible with older compilers.
--- …

Azure Kinect build from source on Ubuntu 16.04

---

examples/Python/Basic/convex_hull.py
examples/Python/Basic/hidden_point_removal.py
src/Open3D/Geometry/BoundingVolume.cpp
src/Open3D/Geometry/PointCloud.cpp
src/Open3D/Geometry/PointCloud.h
src/Open3D/Geometry/Qhull.cpp
src/Open3D/Geometry/Qhull.h
src/Open3D/Geometry/TetraMeshFactory.cpp
src/Open3D/Geometry/TriangleMesh.cpp
src/Open3D/Geometry/TriangleMesh.h
src/Python/geometry/pointcloud.cpp

This pull request will add two new features:
1) The call to `point_cloud.compute_convex_hull` can contain an optional argument of an IntVector, which will be filled with the mapping between the point in the mesh (returned) and the points in the original point cloud. One possible application of this is to retain additional information in the mesh:
```
pc = o3d.geometry.PointCloud()
pc.points = points  # a numpy array of  x, y, z values
pc.colors = colors  # a numpy array of r, g, b values
pt_map = o3d.utility.IntVector()
mesh = pc.compute_convex_hull(pt_map=pt_map)
mesh.vertex_colors = colors[np.asarray(pt_map)]
```
2) Implement the Hidden Point Removal operator, discussed in [Katz et. al. 'Direct Visibility of Point Sets', 2007](https://cgm.technion.ac.il/Computer-Graphics-Multimedia/Publi …

Point Mapping in ConvexHull and Hidden Point Removal Operator

---

src/Open3D/Geometry/IntersectionTest.cpp

It seems that the current triangle triangle intersection test has numerical issues (#1171). Therefore, this PR adds a normalization step to this collision test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1177)

Improve numeric stability of TriangleTriangle3d

---

examples/Cpp/EvaluateFeatureMatch.cpp
examples/Cpp/EvaluatePCDMatch.cpp
examples/Cpp/IntegrateRGBD.cpp
examples/Cpp/ViewDistances.cpp
examples/Cpp/ViewPCDMatch.cpp
src/Open3D/IO/FileFormat/FileBIN.cpp
src/Open3D/IO/FileFormat/FileJPG.cpp
src/Open3D/IO/FileFormat/FileLOG.cpp
src/Open3D/IO/FileFormat/FilePCD.cpp
src/Open3D/IO/FileFormat/FilePTS.cpp
src/Open3D/IO/FileFormat/FileSTL.cpp
src/Open3D/IO/FileFormat/FileTUM.cpp
src/Open3D/IO/FileFormat/FileXYZ.cpp
src/Open3D/IO/FileFormat/FileXYZN.cpp
src/Open3D/IO/FileFormat/FileXYZRGB.cpp
src/Open3D/Utility/FileSystem.cpp
src/Open3D/Utility/FileSystem.h
src/Tools/ManuallyAlignPointCloud/ManuallyAlignPointCloud.cpp
src/Tools/ManuallyAlignPointCloud/VisualizerForAlignment.cpp
src/UnitTest/Integration/UniformTSDFVolume.cpp

Addresses #1098. 
Implemenation of an fopen wrapper in `utility::filesystem` that should handle unicode paths in Windows. Note that some file types/extensions might still not work with unicode paths on Windows (ply, png?), because fopen is used within the 3rdparty lib.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1190)

fopen wrapper to enable unicode paths in Windows

---

src/Open3D/Geometry/Image.cpp
src/Open3D/Geometry/Image.h
src/Python/geometry/image.cpp
src/UnitTest/Geometry/Image.cpp

- Rename previous `Flip()` with `Transpose()` according to its semantics;
- Implement `FlipUD()` and `FlipLR()` to flip images. These are useful functions in loading textures.
- Python interface also supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1186)

Implement image flip functions

---

examples/Python/Basic/meshes.py
src/Open3D/Geometry/TriangleMesh.cpp
src/Open3D/Geometry/TriangleMesh.h
src/Python/geometry/trianglemesh.cpp
src/UnitTest/Geometry/TriangleMesh.cpp

Introduces `MergeCloseVertices` that is similar to `RemoveDuplicatedVertices`, but with some tolerance threshold `eps`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1189)

Merge close vertices

---

src/Open3D/Geometry/BoundingVolume.cpp
src/Open3D/Geometry/BoundingVolume.h

This fixes the `operator+` of `AxisAlignedBoundingBox` such that it ignores empty bounding boxes. This should address #1197.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1205)

Fix operator+ of AxisAlignedBoundingBox

---

CMakeLists.txt

Fix linker warning on Mac. Ideally, we shall use `target_link_directories`, but that's only available in newer versions of cmake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1223)

fix link warning

---

src/Open3D/Utility/Console.h
src/Python/utility/console.cpp

Fixes
```
Tensor.cpp:104:1: warning: control may reach end of non-void function [-Wreturn-type]                     
}                                                                                                                                                       
^ 
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1222)

fix control may reach end warning for VFatal

---

docs/tutorial/Basic/visualization.rst
examples/Python/Basic/bounding_volume.py
examples/Python/Basic/mesh_properties.py
examples/Python/Basic/visualization.py
examples/Python/Misc/meshes.py
src/Open3D/Geometry/LineSet.h
src/Open3D/Geometry/MeshBase.h
src/Open3D/Geometry/PointCloud.h
src/Open3D/Geometry/TetraMesh.h
src/Open3D/Geometry/TriangleMesh.h
src/Python/geometry/boundingvolume.cpp
src/Python/geometry/lineset.cpp
src/Python/geometry/pointcloud.cpp
src/Python/geometry/tetramesh.cpp
src/Python/geometry/trianglemesh.cpp

Added some init functions to the geometry classes. E.g., we can now directly create `AxisAlignedBoundingBox` with the parameters in the constructor.
Addresses comment https://reviewable.io/reviews/intel-isl/open3d/1218#-Lq_6SCRC82OKQcD6Y-5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1228)

Add some Python init functions to geometry classes

---

3rdparty/librealsense/src/verify.c
examples/Cpp/RealSense.cpp

RealSense.cpp was not updated when Image PrepareImage() was refactored. See #1276
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1277)

Refactor Image::Prepare() in RealSense.cpp

---

examples/Cpp/AzureKinectMKVReader.cpp
src/Open3D/Utility/Console.h

Same as #1222 but now applies to `VError`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1288)

fix control may reach end warning for VError

---

src/Open3D/Registration/ColoredICP.cpp

This simple patch will fix #1264 #1281 #1286.
Colored ICP will fail due to incorrect color gradients. 
The incorrect color gradients are from outlier points with only 2 neighbors (3-nn including itself). In this rare case, ill-posed linear systems will be built that generate singular gradients. 
Singular gradients look like
```
-24266.6 -69947.5   415081
```
whereas regular gradients have norms < 1.
These singular gradients will be the dominant factor in the global linear system to solve for pose that cancels the existance of other valid points.
The randomness of the problem in the reconstruction system may come from RANSAC: RANSAC may cause minor changes of initial poses for the initialization of colored ICP. During nn search, a minor shift of pose might lead to change of nns.
Simply …

Quick fix to colored icp

---

src/Open3D/Container/Kernel/CPULauncher.h
src/Open3D/Container/Kernel/CUDALauncher.cuh
src/Open3D/Container/Kernel/UnaryEW.cpp
src/Open3D/Container/Kernel/UnaryEWCPU.cpp
src/Open3D/Container/Kernel/UnaryEWCUDA.cu
src/Open3D/Container/Tensor.cpp
src/Open3D/Container/Tensor.h
src/UnitTest/Container/Blob.cpp
src/UnitTest/Container/Tensor.cpp

Supports copy constructor and assignment of the following syntax:
```cpp
Tensor tensor_a(tensor_b);
Tensor tensor_a(tensor_b[0]);
tensor_a = tensor_b;
tensor_a = tensor_b[0];
tensor_a[0] = tensor_b;
tensor_a[0] = tensor_b[0];
tensor_a[0] = 100;  // with automatic casting
```
Notably, we now can assign to a non-contiguous tensor, e.g (in python equivalent).
```python
a = np.ones((10,))
b = np.ones((20,))
a[0:10:2] = b[0:20:4]
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1293)

Assignment operator

---

src/Open3D/IO/FileFormat/FilePLY.cpp

Addressing an issue brought up in #1302. 
Writing a triangle mesh to ply assumes that the color values are in a valid range `[0, 1]`, but fails without proper warning if this assumption is not met.
This PR adds a warning and automatically clamps the color values to a valid range, as done also for  `PointCloud` and `LineSet`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1306)

fix write ply color values clamped

---

src/Open3D/Container/Blob.h
src/Open3D/Container/Broadcast.cpp
src/Open3D/Container/Dtype.h
src/Open3D/Container/Indexing.cpp
src/Open3D/Container/Kernel/CPULauncher.h
src/Open3D/Container/Kernel/CUDALauncher.cuh
src/Open3D/Container/Kernel/Scheduler.h
src/Open3D/Container/SizeVector.h
src/Open3D/Container/Tensor.cpp
src/Open3D/Container/Tensor.h
src/UnitTest/Container/Tensor.cpp

- To support negative stride size and avoid confusion of converting `int`, `size_t`, `int64_t` when doing indexing.
- Unchanged:
- `MemoryManager`'s `malloc` and etc. still uses `size_t`
- `device_id`  still uses `int`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1335)

Use int64_t for all Tensor indexing code

---

src/Python/open3d_pybind/geometry/geometry.cpp

Currently, rotation matrices can be computed via instances of `open3d.geometry.Geometry3D`, or via `open3d.geometry.Geometry3D.get_rotation_matrix_from_*`. This PR exposes these functions directly via the module `open3d.geometry`.
Brought up in #1351.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1355)

Expose get_rotation_matrix_from_* directly in open3d.geometry

---

src/Open3D/Visualization/Visualizer/Visualizer.cpp
src/Open3D/Visualization/Visualizer/Visualizer.h
src/Open3D/Visualization/Visualizer/VisualizerWithEditing.cpp
src/Open3D/Visualization/Visualizer/VisualizerWithEditing.h
src/Python/open3d_pybind/visualization/visualization_trampoline.h
src/Python/open3d_pybind/visualization/visualizer.cpp

Currently, when `open3d.visualization.Visualizer.add_geometry()` and `open3d.visualization.Visualizer.remove_geometry()` is called, the viewpoint is reset based on the new bounding box.
In some situations, it is necessary to keep the viewpoint between adding/removing geometries.
This pull request adds optional `reset_bounding_box` parameter to those methods.
Usage example:
```python
vis.add_geometry(mypcd, reset_bounding_box=False)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1315)

Add geometry without resetting bounding box

---

src/Open3D/Geometry/SurfaceReconstructionBallPivoting.cpp
src/UnitTest/Utility/Eigen.cpp

This PR fixes a memory leak in the BPA surface reconstruction caused by cyclic references in shared pointers.
Addesses #1360.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1363)

Fix BPA memory leak

---

CMakeLists.txt
src/Open3D/Visualization/Visualizer/Visualizer.cpp

Bug with headless rendering fixed, appears that problem was in GLFW_OPENGL_FORWARD_COMPAT set to true - osMesa doesn't support this mode.
So, switched this hint off when building with headless rendering.
Needs tests on MacOS, if we support headless rendering there.
Fix for issue #940
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1358)

osMesa headless rendering fixed

---

src/Python/open3d_pybind/visualization/renderoption.cpp

Currently `visualization.RenderOption` exposes `mesh_show_back_face` but does not expose `mesh_show_wireframe`.
This PR simply adds `mesh_show_wireframe` to the Python API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1388)

Expose RenderOption.mesh_show_wireframe to Python API

---

src/Open3D/Visualization/Shader/GeometryRenderer.h
src/Open3D/Visualization/Visualizer/Visualizer.cpp
src/Open3D/Visualization/Visualizer/Visualizer.h
src/Python/open3d_pybind/visualization/visualization_trampoline.h

This resurrects and improves an old PR #804 
Significant speedups when `AddGeometry` or `RemoveGeometry` is called when there are many other geometries in the scene.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1392)

Only update single geometry in Visualizer::AddGeometry and Visualizer::RemoveGeometry

---

examples/Python/Basic/pointcloud_plane_segmentation.py
src/Open3D/Geometry/PointCloud.h
src/Open3D/Geometry/PointCloudSegmentation.cpp
src/Open3D/Registration/Registration.cpp
src/Python/open3d_pybind/geometry/pointcloud.cpp
src/Python/open3d_pybind/registration/registration.cpp
src/UnitTest/Geometry/PointCloud.cpp

Implementation of plane segmentation for `PointCloud` using the RANSAC algorithm.
It will find the plane with the greatest number of points in the cloud. Therefore, if the cloud has several planes, the model can be rerun multiple times until all planes are found by removing the inliers each time.
Adresses issue #591.
Example segmentation for `fragment.pcd` with 50 iterations is given below:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1287)

Add point cloud plane segmentation

---

.travis.yml

The brew formula for tbb changed and now depends on python which in turn cannot be installed on the travis osx without error.
Install python beforehand as a workaround.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1440)

Fix brew link problem for python/tbb on OSX for CI

---

docs/versions.js

Also the 0.9.0 docs has been pushed manually to the server.
Now http://open3d.org/docs/release/ shall point to 0.9.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1446)

upgrade versions.js for 0.9

---

.appveyor.yml

- Remove duplicated build in `appveyor.yml`. 
- Sometimes, pr and the feature branch are built at the same time. Followed [this](https://help.appveyor.com/discussions/questions/18437-skip_branch_with_pr-setting-doesnt-work) to create branch filter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1473)

Avoid duplicated Appveyor builds

---

CHANGELOG.md
CMakeLists.txt

This PR adds code for detecting and selecting the GPU architecture to the build system.
The default behavior is to automatically detect the architecture.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1478)

Added cache variables and code for selecting the gpu arch

---

src/Open3D/ML/Misc/Detail/FixedRadiusSearch.cuh
src/Open3D/ML/Misc/Detail/FixedRadiusSearch.h
src/Open3D/ML/Misc/Detail/InvertNeighborsList.cuh
src/Open3D/ML/Misc/Detail/InvertNeighborsList.h
src/Open3D/ML/Misc/Detail/RadiusSearch.h
src/Open3D/ML/Misc/Detail/ReduceSubarraysSum.cuh
src/Open3D/ML/Misc/Detail/ReduceSubarraysSum.h
src/Open3D/ML/TensorFlow/Misc/FixedRadiusSearchOpKernel.cpp
src/Open3D/ML/TensorFlow/Misc/FixedRadiusSearchOpKernel.cu
src/Open3D/ML/TensorFlow/Misc/FixedRadiusSearchOpKernel.h
src/Open3D/ML/TensorFlow/Misc/FixedRadiusSearchOps.cpp
src/Open3D/ML/TensorFlow/Misc/InvertNeighborsListOpKernel.cpp
src/Open3D/ML/TensorFlow/Misc/InvertNeighborsListOpKernel.cu
src/Open3D/ML/TensorFlow/Misc/InvertNeighborsListOpKernel.h
src/Open3D/ML/TensorFlow/Misc/InvertNeighborsListOps.cpp
src/Open3D/ML/TensorFlow/Misc/RadiusSearchOpKernel.cpp
src/Open3D/ML/TensorFlow/Misc/RadiusSearchOpKernel.h
src/Open3D/ML/TensorFlow/Misc/RadiusSearchOps.cpp
src/Open3D/ML/TensorFlow/Misc/ReduceSubarraysSumOpKernel.cpp
src/Open3D/ML/TensorFlow/Misc/ReduceSubarraysSumOpKernel.cu
src/Open3D/ML/TensorFlow/Misc/ReduceSubarraysSumOpKernel.h
src/Open3D/ML/TensorFlow/Misc/ReduceSubarraysSumOps.cpp
src/Python/CMakeLists.txt
src/UnitTest/Python/test_tf_op_library.py
src/UnitTest/Python/tf_ops/test_fixed_radius_search.py
src/UnitTest/Python/tf_ops/test_invert_neighbors_list.py
src/UnitTest/Python/tf_ops/test_radius_search.py
src/UnitTest/Python/tf_ops/test_reduce_subarray_sum.py

This PR changes the prefix sum format to row split format to simplify interop with tf.ragged
- var name changes x_prefix_sum -> x_row_splits
- updated unit tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1488)

change of prefix sum format to row splits

---

src/Open3D/Geometry/PointCloud.h
src/Open3D/Geometry/PointCloudFactory.cpp
src/Python/open3d_pybind/geometry/pointcloud.cpp

Related to the following issue https://github.com/intel-isl/Open3D/issues/647
This PR enables an option `keep_organized` to maintain whole point cloud's points.
```
import matplotlib.pyplot as plt
color_raw = o3d.io.read_image(
"../../TestData/RGBD/other_formats/SUN_color.jpg")
depth_raw = o3d.io.read_image(
"../../TestData/RGBD/other_formats/SUN_depth.png")
rgbd_image = o3d.geometry.RGBDImage.create_from_sun_format(
color_raw, depth_raw)
pcd = o3d.geometry.PointCloud.create_from_rgbd_image(
rgbd_image,
o3d.camera.PinholeCameraIntrinsic(
o3d.camera.PinholeCameraIntrinsicParameters.PrimeSenseDefault),
keep_organized=False)
print(len(pcd.points))
pcd = o3d.geometry.PointCloud.create_from_rgbd_image(
rgbd_image,
o3d.camera.PinholeCameraIntrinsic( …
```

[PointCloudFactory/CreatePointCloud] Add project_valid_depth_only option

---

CHANGELOG.md
src/Open3D/Registration/FastGlobalRegistration.cpp
src/Open3D/Registration/Registration.cpp
src/Open3D/Utility/Helper.cpp
src/Open3D/Utility/Helper.h

This PR follows up on https://github.com/intel-isl/Open3D/issues/359 and mostly cherry picks from https://github.com/syncle/open3d/tree/uniform_real_distribution
**What's done here**
Rely on C++11 random generators instead of `std::srand` and `std::rand` in global registration.
**Context**
cstdlib random generators can have severe limitations in some implementations, and are awkward to use in multithreaded code. I have not observed changes in ransac stability related to this change, as suggested instead in the thread mentioned above, but this may well depend on the specific platform I am on.
~On the other hand, I observed an important performance gain by switching to the C++11 random generator, and this is the main reason for opening this PR. The performance gain is probably related to …

Avoid cstdlib random generators in ransac for global registration

---

src/Open3D/Geometry/DownSample.cpp
src/Open3D/Geometry/PointCloud.h

Related to the following issues https://github.com/intel-isl/Open3D/issues/1241 .
This PR adds an option`return_point_references` to keep a full index of an original point cloud.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1406)

[PointCloud/Downsample] Add return_point_references option to VoxelDownSampleAndTrace

---

src/Open3D/Registration/GlobalOptimization.cpp

Simply remove unnecessary code since `0 or x == x`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1509)

Simplify trivial Boolean expression

---

docs/compilation.rst

In this PR,
a17b64f is minor fix.
5efe7f2 removes `BUILD_PYTHON_TUTORIALS` at **Compiling from source** section. Looks like that options is actually not present in any cmake as of now.
Let me know if I am wrong.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1513)

Minor doc fix

---

src/Open3D/Core/Kernel/BinaryEWCUDA.cu
src/Open3D/Core/TensorList.cpp
src/Open3D/Core/TensorList.h
src/Open3D/ML/Misc/Detail/ReduceSubarraysSumCPU.h
src/Python/open3d/__init__.py
src/Python/open3d/core.py
src/Python/open3d_pybind/core/container.cpp
src/Python/open3d_pybind/core/container.h
src/Python/open3d_pybind/core/tensorlist.cpp
src/UnitTest/Python/test_core.py

Initial Python binding for the TensorList class
- Supports construct from (shape, dtype, device, size); from tensors; from an internal tensor.
- Initial tests with various interfaces for concat and push back. 
- TBD: finish indexing when Tensor's indexing is done (for consistency).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1505)

TensorList initial pybind

---

src/Open3D/Visualization/Rendering/Filament/FilamentRenderToBuffer.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentRenderToBuffer.h
src/Open3D/Visualization/Rendering/Filament/FilamentRenderer.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentRenderer.h
src/Open3D/Visualization/Rendering/Filament/FilamentView.cpp
src/Open3D/Visualization/Rendering/RenderToBuffer.h

New interface introduced: `RenderToBuffer`. It allows user to create requests to renderer for rendering next frame into a buffer. User can choose settings for view mode, camera, viewport, etc. In particular View and Camera settings can be manipulated for this rendering mode.
When working with Filament~ classes user also can use `FilamentRenderToBuffer` for headless rendering, without creating `FilamentRender` and its children. **This would not work on headless systems!**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1512)

rendering scenes into a buffer

---

src/Open3D/GUI/Materials/lines.mat
src/Open3D/Visualization/Rendering/Filament/FilamentGeometryBuffersBuilder.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentGeometryBuffersBuilder.h
src/Open3D/Visualization/Rendering/Filament/LineSetBuffers.cpp
src/Open3D/Visualization/Rendering/Filament/PointCloudBuffers.cpp
src/Open3D/Visualization/Rendering/Filament/TriangleMeshBuffers.cpp

Added rendering of LineSet objects and new material for them.
Fixed a bug with algorithm for excluding duplicate vertices in TriangleMesh and LineSet geometries. This fix is located at `TriangleMeshBuffers.cpp:252`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1514)

Lineset rendering

---

src/Open3D/Geometry/TriangleMesh.cpp
src/Open3D/Geometry/TriangleMesh.h
src/Open3D/IO/FileFormat/FileOBJ.cpp
src/Open3D/Visualization/Shader/GeometryRenderer.cpp
src/Open3D/Visualization/Shader/TexturePhongShader.cpp
src/Open3D/Visualization/Shader/TexturePhongShader.h
src/Open3D/Visualization/Shader/TextureSimpleShader.cpp
src/Open3D/Visualization/Shader/TextureSimpleShader.h
src/Open3D/Visualization/Utility/GLHelper.h
src/Python/open3d_pybind/geometry/trianglemesh.cpp

Enhancement of PR #1194.
This PR supports loading multiple textures for one single mesh, addressing #1484. 
Major changes:
- Added property `material_ids` per face in `TriangleMesh` supported by tinyobjloader.
- Supports rendering multiple textures in several passes.
**Note**: due to the general API design in the IO module, an `.obj` containing multiple `shapes` is still not supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1517)

Supports multiple textures in .obj file

---

docs/make_docs.py

This PR adds code for retrieving the modules to be documented from index.rst.
It relies fully on inspect to avoid special treatment for the modules defined with pybind.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1520)

Enable building docs for pure python submodules

---

src/Open3D/Geometry/TriangleMesh.cpp
src/Open3D/Geometry/TriangleMesh.h
src/Python/open3d_pybind/geometry/trianglemesh.cpp
src/UnitTest/Geometry/TriangleMesh.cpp

This PR adds an option to SamplePointsUniformly() and SamplePointsPoissonDisk() for using the triangle normal instead of the interpolated vertex normals.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1539)

Option for using the triangle normal for sampled points

---

src/Python/open3d_pybind/geometry/trianglemesh.cpp

This PR exposes the GetSurfaceArea function from TriangleMesh to python.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1540)

Added get_surface_area to TriangleMesh python interface

---

src/Open3D/GUI/Window.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentRenderer.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentRenderer.h
src/Open3D/Visualization/Rendering/Renderer.h

We need to recreate the swap chain on macOS, or else Filament draws into the wrong rectangle (it's too small when shrinking, and too big when expanding).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1572)

Fix broken resizing on macOS

---

src/Open3D/GUI/Materials/depth.mat
src/Open3D/GUI/Materials/normals.mat
src/Open3D/GUI/SceneWidget.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentResourceManager.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

* Normals mapped to colors in world space
* Applied heatmap mapping to depth visualizer
* Point size now affects 'Normal map' and 'Depth' modes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1586)

Rendering modes fixes

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

German decided that we need to use a lit material for point clouds, because if we use unlit for all-white point clouds they look really terrible, but there isn't a good way of telling the difference between those and point clouds that have real vertex colors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1587)

Fix white point clouds looking nearly invisible

---

src/Open3D/ML/ContinuousConv/Detail/ContinuousConvBackpropFilter.cuh
src/Open3D/ML/ContinuousConv/Detail/ContinuousConvBackpropFilter.h
src/Open3D/ML/TensorFlow/ContinuousConv/ContinuousConvBackpropFilterOpKernel.cpp
src/Open3D/ML/TensorFlow/ContinuousConv/ContinuousConvBackpropFilterOpKernel.cu
src/Open3D/ML/TensorFlow/ContinuousConv/ContinuousConvBackpropFilterOpKernel.h
src/Open3D/ML/TensorFlow/ContinuousConv/ContinuousConvBackpropFilterOps.cpp

This PR adds the filter backprop for the convolution and the tf op.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1575)

cconv filter backprop implementation and tf op

---

src/Open3D/GUI/FileDialog.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentRenderer.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentRenderer.h
src/Open3D/Visualization/Rendering/RenderToBuffer.h
src/Open3D/Visualization/Rendering/Renderer.cpp
src/Open3D/Visualization/Rendering/Renderer.h
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.h

I changed CreateBufferRenderer() to return a shared_ptr rather than unique_ptr because you can't put a unique_ptr in a lambda (it makes it non-copyable), which makes it troublesome to delete it once you're done. It wasn't obvious how to get a shared_ptr in a lambda that was reset()able, either, so I added Renderer::RenderToBuffer() so that other people won't have to discover obscure C++ details like that you can have mutable lambdas.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1616)

Adds render current view to file

---

src/Open3D/Visualization/Rendering/MatrixInteractor.cpp

Fix incorrect camera rotation when camera is dollyed to be in front of center of rotation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1617)

Fix incorrect camera rotation

---

CMakeLists.txt

A minor change in CMakeLists.txt
Looks like building glew/glfw from source always requires the legacy OpenGL library to be linked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1628)

Suppress developer warning for OpenGL library with CMAKE_VERSION >= 3.11

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

Also labelled default light as default
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1635)

Default lighting change for point clouds

---

src/Open3D/Visualization/Visualizer/ViewControl.cpp

Some cameras are flipped (in the z-axis) when the bounding_box center of the scene is not visible (i.e. center is behind the camera). This situation could happen when you are in an indoor scene, for instance, and looking at the walls instead of towards the center of the room.
The fix is simple, basically adding a absolute value to the result of the dot product (projection to the 'front_' vector).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1447)

Some cameras are flipped (in the z-axis) in ViewControl::ConvertFromPinholeCameraParameters

---

src/Open3D/ML/ShapeChecking.h
src/Open3D/ML/TensorFlow/Misc/InvertNeighborsListOpKernel.h
src/Open3D/ML/TensorFlow/Misc/InvertNeighborsListOps.cpp
src/Open3D/ML/TensorFlow/TensorFlowHelper.h
src/UnitTest/ML/ShapeChecking.cpp
src/UnitTest/Python/tf_ops/test_invert_neighbors_list.py

This PR adds 
- helper functions for checking the shape of tensors
- updated shape checking code for invert_neighbors_list
- unit tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1589)

shape checking helpers for op wrappers

---

examples/Python/ReconstructionSystem/make_fragments.py
examples/Python/ReconstructionSystem/opencv_pose_estimation.py

The Python gives the following warnings when using the original code:
```
OpenCV is detected. Using ORB + 5pt algorithm
/home/hzxie/Development/Open3D/examples/Python/ReconstructionSystem/opencv_pose_estimation.py:39: SyntaxWarning: "is" with a literal. Did you mean "=="?
```
with the following command:
```
python run_system.py config/tutorial.json --make
```
Now, the warning is gone.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1664)

Fix SyntaxWarning: replace 'is' with '==' for literals.

---

docs/tutorial/ReconstructionSystem/system_overview.rst

- `redwood.json` is required in `docs/tutorial/ReconstructionSystem/system_overview.rst`, but the correct filename is `tutorial.json`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1699)

Fix incorrect file name in a ReconstructionSystem document

---

src/Open3D/Geometry/TriangleMesh.cpp
src/Open3D/Geometry/TriangleMesh.h
src/Python/open3d_pybind/geometry/trianglemesh.cpp

This MR adds an additional argument to the `TriangleMesh::SamplePoints...` methods that is used to set the seed for the random number generator. The argument defaults to `-1`, which is a magic value that keeps the current functionality (the random number generator seed being set to a random number; thus, producing a new sequence which each trial). Any value besides `-1` will be used as the seed and will produce the same random number sequence for each trail. 
This MR addresses issue #1682 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1683)

Add seed argument to mesh sampling functions (#1682)

---

src/Open3D/Core/Tensor.cpp
src/Open3D/Core/Tensor.h
src/Open3D/Core/TensorKey.cpp
src/Open3D/Core/TensorKey.h
src/Python/open3d/core.py
src/Python/open3d_pybind/core/tensor.cpp
src/Python/open3d_pybind/core/tensor_key.cpp
src/UnitTest/Container/Tensor.cpp
src/UnitTest/Python/test_core.py

Support for mixed indexing, slicing and advanced indexing:
e.g.
```python
o3_dst = o3_src[1, [[1, 2], [2, 1]], 0:4:2, [3, 4]]
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1613)

mixed regular and anvanded indexing, and pybind

---

src/Open3D/Geometry/VoxelGrid.cpp
src/Open3D/Geometry/VoxelGrid.h
src/Python/open3d_pybind/geometry/voxelgrid.cpp

I found a bug that can't use open3d.geometry.VoxelGrid.voxels same as #1535 .
Thanks to @noahstier, I changed to get voxels of unordered_map by function.
Without this PR
```
In [11]: voxel_grid.voxels
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-d7484a89cc11> in <module>()
----> 1 voxel_grid.voxels
TypeError: unhashable type: 'numpy.ndarray'
```
With this PR
```
In [11]:: voxel_grid.voxels()
[geometry::Voxel with grid_index: (16, 25, 12), color: (0.6, 0.654902, 0.623529),                                                                                                                                                     
geometry::Voxel with grid_index: (27, 66, 22), …
```

Fix VoxelGrid.voxels bug #1535

---

src/Apps/CMakeLists.txt
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

The CMake target and source directory name are still Open3DViewer, both to avoid confusion with the name of the library and because you can't have two targets named identically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1726)

Merged some materials, don't revert mouse controls to default, name app Open3D.app

---

src/Open3D/GUI/Window.cpp
src/Open3D/GUI/Window.h

This fixes not being able to type text into a text box, for the main reason that ImGUI does not use key events to enter characters (since that does not work well with much beyond ASCII), and GLFW's character event wasn't hooked up. (Testing: the only text widget currently in the app is the file name when saving an image on Linux)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1754)

Implemented text events with GLFW

---

CMakeLists.txt

Current gui using Filament links against libc++, that causes any thrown exceptions from our library to crash the running python process.  Here's a sample:
$ python
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d as o3d
>>> import numpy as np
>>> a=np.ones((2, 4), dtype=np.int32)
>>> o3d.utility.Vector3dVector(a)
terminating with uncaught exception of type pybind11::cast_error: Unable to cast Python instance to C++ type (compile in debug mode for details)
Aborted (core dumped)
additionally, if you load our library (first), it causes any thrown exception from any other C++ library to crash the running python process.  For example, if you have pytorch:
$ python
Python 3.6.9 (default, …

linux build with Filament: libstdc++ and libc++ and python library

---

src/Open3D/GUI/Window.cpp

To reproduce crash, select "Export Current Image", type in a filename, click "Save" and once the dialog has disappeared press any key before doing anything else.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1761)

Fix crash when using Export Current Image in Open3D

---

src/Open3D/GUI/Window.cpp
src/Open3D/GUI/Window.h

ImGUI uses the delta time parameter when drawing to compute double-click time, but what we were passing had no relationship to the actual time that had passed.
Testing:  double-click on a directory or model in the file dialog box on Linux. Previously it would take three clicks to enter a directory or load a model, now a proper double-click should work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1756)

Fix problems with double-clicking

---

src/Apps/Open3DViewer/Open3DViewer.cpp
src/Open3D/GUI/Application.cpp
src/Open3D/IO/FileFormat/FilePLY.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

On Linux Open3D app crashes if given a bad file on command line. Also, fixed a handful of log outputs that were using the Python-style formatting function instead of printf-style.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1767)

Gui errissa open3d crash on invalid file on Linux

---

src/Open3D/Core/Kernel/BinaryEW.cpp
src/UnitTest/Core/Tensor.cpp

```
// A.shape = (   3, 4)
// B.shape = (2, 3, 4)
// A += B should throw exception.
// B += A is fine.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1777)

fix bug: binary op output must fit in the output tensor

---

src/Apps/CMakeLists.txt
src/Apps/Open3DViewer/postinstall-linux.sh

Installing app for all users requires updating icon cache, also we had the wrong path for the icon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1783)

Fixed integration of app icon with FreeDesktop environments

---

src/Open3D/Visualization/Rendering/Filament/FilamentRenderToBuffer.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentRenderToBuffer.h
src/Open3D/Visualization/Rendering/Renderer.cpp

Keep copy of View in FilamentRenderToBuffer instead of creating an internal version and copying settings from the provided View.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1790)

Workaround Open3DViewer image export issue

---

src/Open3D/Core/Kernel/CUDALauncher.cuh
src/Open3D/Core/Tensor.cpp
src/Open3D/Core/Tensor.h
src/Python/open3d/core.py
src/Python/open3d_pybind/core/tensor.cpp
src/UnitTest/Core/Tensor.cpp
src/UnitTest/Python/test_core.py

```python
a = o3d.Tensor.empty((2 ,3), o3d.Dtype.Float32)
a = o3d.Tensor.ones((2 ,3), o3d.Dtype.Float32)
a = o3d.Tensor.zeros((2 ,3), o3d.Dtype.Float32)
a = o3d.Tensor.full((2 ,3), 100, o3d.Dtype.Float32)
b = a + 1
b = a + True  # auto cast scalar
b = 1 - a
a += 1
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1779)

Tensor creation shortcuts and scalr value op

---

.travis.yml
src/Open3D/ColorMap/ColorMapOptimization.cpp
src/Open3D/ColorMap/ColorMapOptimization.h
src/Open3D/ColorMap/ColorMapOptimizationJacobian.cpp
src/Open3D/ColorMap/ColorMapOptimizationJacobian.h
src/Open3D/ColorMap/TriangleMeshAndImageUtilities.cpp
src/Open3D/ColorMap/TriangleMeshAndImageUtilities.h
src/Python/open3d_pybind/color_map/color_map.cpp
src/UnitTest/ColorMap/ColorMapOptimizationOption.cpp
src/UnitTest/Python/test_color_map.py

Looks like the segfault is mainly due to the `LogDebug` statement inside OpenMP. Here's the stack trace:
```bash
(lldb) up
frame #13: 0x00007ffff374135f open3d_pybind.cpython-37m-x86_64-linux-gnu.so`::.omp_outlined.() at TriangleMeshAndImageUtilities.cpp:105
102                  viscnt++;
103              }
104          }
-> 105          utility::LogDebug("[cam {:d}] {:.5f} percents are visible", c,
106                            double(viscnt) / n_vertex * 100);
107          fflush(stdout);
108      }
```
After the fix, I ran the unit tests for 100 times with prints, no segfault occurred.
Changes:
- Move print outside of OpenMP
- Add color map python test
- Fix spellings
--- …

fix colormap segfault and refactor

---

src/Open3D/GUI/Materials/defaultLit.mat
src/Open3D/Geometry/TriangleMesh.h
src/Open3D/IO/FileFormat/FileOBJ.cpp
src/Open3D/Visualization/Rendering/Filament/FilamentResourceManager.cpp
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

This PR adds support in defaultLit shader for reflectance, clear coat, clear coat roughness, and anisotropy maps. Only reflectance maps (map_Ps) are supported by the OBJ loader.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1817)

Support additional texture maps

---

.gitignore
3rdparty/azure_kinect/azure_kinect.cmake
src/Open3D/IO/Sensor/AzureKinect/AzureKinectSensor.cpp

Fixes #1708 
- Fix Windows compilation warning (as error)
- Update cmake to support k4a 1.4 include path on Windows
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1796)

fix Windows Kinect compile

---

.gitignore
src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

Adds UVs to triangle meshes that don't have any.
NOTE: I also added .clangd/ to .gitignore. This is an unrelated change but anyone using clangd as a language server will end up with a bunch of index files in a .clangd directory in the root of the project. I added .clangd/ to my local copy of .gitignore a while ago and thought others might find it useful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1835)

Filament Warning Fixes

---

src/Open3D/ML/TensorFlow/Misc/BuildSpatialHashTableOps.cpp

Fixes wrong rank in the static shape inference.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1850)

bugfix in shape inference

---

.travis/gcs.lifecycle.json
.travis/readme.md

This has already been applied to our gcs bucket. The PR is for documentation purposes.
Under the extreme case, we can have 36 docs builds a day (since it takes 40 mins to build). Each build produces 0.17GB docs. Under this scenario, the maximum storage size is 36 * 0.17 * 7 = 42.84 GB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1849)

Set gcs bucket lifecycle

---

src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp

Fixes issue of IBL appearing to stop working when you disable IBL, switch IBL maps, then re-enable IBL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1866)

Reset IBL intensity when IBL is re-enabled

---

CMakeLists.txt

before:
```
open3d-0.10.0.0-cp36-cp36m-macosx_10_15_x86_64.whl
```
after:
```
open3d-0.10.0.0-cp36-cp36m-macosx_10_9_x86_64.whl
```
10.9 is selected based on considerations specified in:
- https://github.com/MacPython/wiki/wiki/Spinning-wheels#question-will-pip-give-me-a-broken-wheel
- https://github.com/matthew-brett/multibuild
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1867)

set macos sdk to 10.9

---

src/Open3D/GUI/Button.cpp
src/Open3D/GUI/Button.h
src/Open3D/GUI/ImageLabel.cpp
src/Open3D/GUI/ImageLabel.h
src/Open3D/GUI/ImguiFilamentBridge.cpp
src/Open3D/GUI/ImguiFilamentBridge.h
src/Open3D/GUI/Materials/img_blit.mat
src/Open3D/GUI/UIImage.cpp
src/Open3D/GUI/UIImage.h
src/Open3D/GUI/Widget.h
src/Open3D/GUI/Window.cpp
src/Open3D/Open3D.h.in
src/Open3D/Visualization/Rendering/RendererHandle.h

This PR lets us display images in the UI. Each image costs another draw call. Open3D cannot currently load images with transparency (but in theory should work if it does). The UI does not use any images, so this is currently unused; you can test by adding some variation of the following to GuiVisualizer.cpp:
```
#include “Open3D/GUI/ImageLabel.h”
#include "Open3D/Visualization/Rendering/Filament/FilamentEngine.h"
settings.wgt_base->AddChild(std::make_shared<gui::ImageLabel>(
"path/to/test.png"));
auto &rsrc_mgr = visualization::EngineInstance::GetResourceManager();
auto texture = rsrc_mgr.CreateTexture("path/to/test.png");
settings.wgt_base->AddChild(std::make_shared<gui::ImageLabel>(
texture, 0.25, 0.125, 0.75, 0.625));
```
See attached test.png. 
--- …

GUI: implements image widget

---

examples/Cpp/EvaluateFeatureMatch.cpp

Fixes error on clang 10 (default clang for ubuntu 20.04)
```cpp
/home/yixing/repo/Open3D/examples/Cpp/EvaluateFeatureMatch.cpp:232:21: error: loop variable 'feature' of type 'const std::__cxx11::basic_string<char>' c
reates a copy from type 'const std::__cxx11::basic_string<char>' [-Werror,-Wrange-loop-construct]                                                       
for (const auto feature : features) {                                   
^                 
/home/yixing/repo/Open3D/examples/Cpp/EvaluateFeatureMatch.cpp:232:10: note: use reference type 'const std::__cxx11::basic_string<char> &' to prevent co
pying                                 
for (const auto feature : features) {                                   
^~~~~~~~~~~~~~~~~~~~         
&                 
1 error generated. …
```

fix auto & warning (as error) for clang 10

---

.gitmodules
src/Open3D/Utility/Console.cpp
src/UnitTest/Core/Tensor.cpp

When CUDA is enabled, there are a lot of warnings about:
```shell
warning: #warning "host_defines.h is an internal header file and must not be used 
directly.  This file will be removed in a future CUDA release.  Please use 
cuda_runtime_api.h or cuda_runtime.h instead." [-Wcpp]
```
This PR:
- Bumps Eigen version to d41dc4d
- which is the same as [pytorch's eigen](https://github.com/pytorch/pytorch/commit/f29858ff1450e566205fbb900028dee39222180e)
- Updated EIgen's URL, since they have moved to https://gitlab.com/libeigen/eigen.git.
- Bumps `fmt` to release `6.0.0`, in order to be compatible with the updated Eigen
- Now `fmt` by default formats float differently than int
Note:
Update git submodule with
```shell
git submodule sync --recursive
git submodule update --init --recursive
```
--- …

Fix Eigen warning when using CUDA

---

CMakeLists.txt

This PR fixes a problem if cuda code is compiled for multiple archs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1960)

avoid deduplication of the -gencode option

---

src/Open3D/Geometry/Geometry3D.cpp
src/Open3D/Geometry/Geometry3D.h
src/Python/open3d_pybind/geometry/geometry.cpp

Overload `rotate` method so that center parameter is optional.
Addressing comment https://github.com/intel-isl/Open3D/pull/1774#issuecomment-635206007
@yxlao I think the doc extraction from overloaded pybind methods does not work well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1920)

Rotate Overload

---

CHANGELOG.md
src/Python/open3d_pybind/integration/integration.cpp

Extend Python API to enable the creation of UniformTSDFVolume whose origin is not (0, 0, 0).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1762)

expose UniformTSDFVolume's origin in Python API

---

examples/Python/ReconstructionSystem/make_fragments.py
examples/Python/ReconstructionSystem/refine_registration.py
examples/Python/ReconstructionSystem/register_fragments.py

The condition `if config["python_multi_threading"]:` is true even when `config["python_multi_threading"]` is set `False` or `false` or anything.
This PR fixes that bug present in the reconstruction example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1901)

Fix bug reading multi-threading config

---

.gitfilters
docs/contribute/contribution_recipes.rst
util/scripts/git_enable_ipynb_filter.sh

The output of the filter may differ from the strip output script, which may cause confusion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1982)

remove ipynb git filter

---

README.md
cpp/pybind/core/dtype.cpp
cpp/pybind/core/size_vector.cpp
cpp/pybind/core/tensor_key.cpp
cpp/pybind/pipelines/color_map/color_map.cpp
cpp/pybind/pipelines/integration/integration.cpp
cpp/pybind/pipelines/odometry/odometry.cpp
cpp/pybind/pipelines/registration/registration.cpp
docs/builddocs.rst
docs/conf.py
docs/cpp.rst
docs/documented_modules.txt
docs/getting_started.rst
docs/index.rst
docs/introduction.rst
docs/make_docs.py
docs/tutorial/C++/cplusplus_interface.rst
python/open3d/core.py

- Add option to skip jupyter notebook docs at `make_docs.py` to speed up debugging
- Fix python docs, especially for `open3d.pipelines.*`
- Add standalone page for C++ API docs
- Fix cases and remove duplicated "about" page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1988)

Add option to skip ipynb docs, fix python and cpp docs

---

cpp/open3d/geometry/BoundingVolume.cpp
cpp/open3d/geometry/BoundingVolume.h

Brought up in #1996, the `rotate` and `scale` function of `OrientedBoundingBox` does not conform with the other `rotate` and `scale` functions. This PR fixes this issue, i.e., if you rotate a point cloud that has a OrientedBoundingBox associated, calling rotate on this box with the same parameters will give you the expected result.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/1999)

fix obb rotate and scale

---

cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp
cpp/open3d/visualization/shader/ImageMaskShader.h
cpp/open3d/visualization/shader/ImageShader.h
cpp/open3d/visualization/shader/PhongShader.cpp
cpp/open3d/visualization/shader/PhongShader.h
cpp/open3d/visualization/shader/RGBDImageShader.h
cpp/open3d/visualization/shader/TexturePhongShader.cpp
cpp/open3d/visualization/shader/TexturePhongShader.h
cpp/open3d/visualization/shader/TextureSimpleShader.cpp
cpp/open3d/visualization/utility/GLHelper.cpp
cpp/open3d/visualization/utility/GLHelper.h
cpp/open3d/visualization/utility/SelectionPolygon.cpp
cpp/open3d/visualization/visualizer/ViewControl.cpp
cpp/open3d/visualization/visualizer/ViewControl.h
cpp/open3d/visualization/visualizer/VisualizerRender.cpp
cpp/open3d/visualization/visualizer/VisualizerWithEditing.cpp
cpp/open3d/visualization/visualizer/VisualizerWithVertexSelection.cpp

Also removed the more or less empty and useless texture_loading namespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2024)

Rename GLHelper namespace

---

cpp/apps/Open3DViewer/Open3DViewer.cpp
cpp/apps/Open3DViewer/Open3DViewer.h
cpp/apps/Open3DViewer/Open3DViewer_mac.mm
cpp/open3d/visualization/gui/Menu.cpp
cpp/open3d/visualization/gui/Menu.h
cpp/open3d/visualization/gui/MenuMacOS.mm
cpp/open3d/visualization/gui/Window.cpp
cpp/open3d/visualization/visualizer/GuiVisualizer.cpp
cpp/open3d/visualization/visualizer/GuiVisualizer.h

Also makes macOS menu more Mac-like, and fixes problems with auto-centering windows. Menu option only exists on macOS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2031)

Adds menu option on macOS to make Open3D viewer default for file types

---

.github/workflows/macos.yml
.github/workflows/ubuntu.yml
.travis.yml
util/scripts/install-deps-osx.sh
util/scripts/install-deps-ubuntu.sh
util/scripts/run-ci.sh
util/scripts/setup-linux.sh

- Enable GitHub actions for macOS CI, disable Travis.
- Skip `brew update` for macOS on CI.
- Use `ccache` for Ubuntu and macOS builds
- Prints `ccache` status before and each run. It shows that `cache` is indeed activated. e.g. https://github.com/intel-isl/Open3D/runs/843543441#step:6:24 and https://github.com/intel-isl/Open3D/runs/843543441#step:6:6213
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2045)

Use GitHub actions again for macOS CI

---

cpp/tests/geometry/TriangleMesh.cpp

The `TriangleMesh.CreateFromPointCloudPoisson` could be stuck for hours on macOS CI, occasionally. 
Example failures:
- https://github.com/intel-isl/Open3D/runs/844549493#step:6:3150
- https://github.com/intel-isl/Open3D/runs/741891346#step:5:3146
- https://github.com/intel-isl/Open3D/runs/734021844#step:5:3169
The memory consumption for this test should be low (~30MB). It might be related to threads. Needs to be investigated further.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2054)

disable CreateFromPointCloudPoisson test for macos

---

CMakeLists.txt

Fixes #2040 .
This issue only affects certain versions of CMake: https://gitlab.kitware.com/cmake/cmake/-/issues/20270.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2058)

CUDA header as system header for CMake 3.16

---

cpp/open3d/core/ShapeUtil.cpp
cpp/open3d/core/ShapeUtil.h
cpp/open3d/core/SizeVector.h
cpp/open3d/core/Tensor.cpp
cpp/open3d/core/Tensor.h
cpp/open3d/core/TensorList.cpp
cpp/open3d/core/TensorList.h
cpp/open3d/core/kernel/Reduction.cpp
cpp/open3d/core/kernel/Reduction.h
cpp/open3d/core/kernel/ReductionCPU.cpp
cpp/open3d/core/kernel/ReductionCUDA.cu
cpp/pybind/core/tensor.cpp
cpp/pybind/core/tensorlist.cpp
cpp/tests/core/Tensor.cpp
cpp/tests/core/TensorList.cpp
python/open3d/core.py
python/test/core/core_test_utils.py
python/test/core/test_core.py
python/test/core/test_tensorlist.py

- Refactor `TensorList`
- In-place created tensor list cannot be resized (i.e. cannot do push_back, extend, ...).
- Refined copy behavior: copy constructor, move constructor, copy assignment and move assignment.
- Now unless explicitly copy, everything else is "shallow" copy
- Get device and dtype info from tensor directly
- Do not allow auto broadcasting
- Removed second-layer python wrapper (`core.py`) for TensorList -- it's not needed
- Simplified internal implementations
- `Tensor`
- New op: `Tensor::AllClose`
- New op: `Tensor::IsClose`
- New op: `Tensor::Any`
- New op: `Tensor::All`
- New op: `Tensor::IsSame`: useful to test if teh tensor shares the same memory
- Pybind
- C++ and python tests, also moved some test files
--- …

TensorList refactoring and comparison tensor ops

---

cpp/open3d/utility/Console.h
cpp/tests/utility/Console.cpp

```cpp
utility::LogInfo("{}", "Example shape print {1, 2, 3}");
```
results in
```
C++ exception with description "invalid format string" thrown in the test body.
```
This is related to this fmt library's `{}` escaping issue: https://github.com/fmtlib/fmt/issues/634 . 
Somehow, if we replace the final `fmt::print(msg);` call with `std::cout`, it works properly. Not it can correctly print:
```
[ RUN      ] Logger.LogInfo
[Open3D INFO] Example shape print {1, 2, 3}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2072)

fix utility::LogXX {} escape problem

---

cpp/apps/Open3DViewer/Open3DViewer_mac.mm
cpp/open3d/visualization/gui/Window.cpp
cpp/open3d/visualization/gui/Window.h

To reproduce (prior to this fix): on macOS, launch the viewer app but don't load a model. Now resize the window. Load a model, then move the window. You should see the pre-resized image squeezed (or pulled) into the window. (The fact that we didn't have any model loaded when we resized should be make the problem especially noticeable.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2076)

Fix window showing buffer from last resize when a window is moved on macOS

---

3rdparty/find_dependencies.cmake

Install 3rdparty header in `open3d/3rdparty/...` rather than `Open3D/3rdparty/...`.
**Before**
```
(open3d3) ➜  ~ tree -L 3 open3d_install
open3d_install
├── include
│   ├── open3d                  <=== open3d
│   │   ├── 3rdparty
│   │   ├── camera
│   │   ├── core
│   │   ├── geometry
│   │   ├── io
│   │   ├── Macro.h
│   │   ├── ml
│   │   ├── Open3DConfig.h
│   │   ├── Open3D.h
│   │   ├── pipelines
│   │   ├── utility
│   │   └── visualization
│   └── Open3D                  <=== Open3D
│       └── 3rdparty
└── lib
├── cmake
│   └── Open3D
└── libOpen3D.so
```
**After**
```
(open3d3) ➜  ~ tree -L 3 open3d_install
open3d_install
├── include
│   └── open3d
│       ├── 3rdparty
│       ├── camera
│       ├── core
│       ├── geometry
│       ├── io
│       ├── Macro.h
│       ├── ml …
```

lower case "open3d/3rdparty" intall dir

---

3rdparty/find_dependencies.cmake

This PR 
-fixes a bug in import_3rdparty_library for paths without trailing '/'
-allows to pass multiple include dirs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2084)

fix bug in import_3rdparty_library for paths without trailing '/'

---

cpp/open3d/core/Tensor.h
cpp/open3d/core/TensorKey.h
cpp/pybind/core/tensor.cpp
python/open3d/core.py
python/test/core/test_core.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2093)

scalar support to more binary ops

---

cpp/open3d/visualization/gui/Window.cpp

These bugs are not necessarily Python-specific, just that I found them while creating Python examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2098)

Bugfixes found while integrating with Python

---

cpp/open3d/visualization/gui/Button.cpp
cpp/open3d/visualization/gui/Checkbox.cpp
cpp/open3d/visualization/gui/ColorEdit.cpp
cpp/open3d/visualization/gui/Combobox.cpp
cpp/open3d/visualization/gui/ImageLabel.cpp
cpp/open3d/visualization/gui/Label.cpp
cpp/open3d/visualization/gui/ListView.cpp
cpp/open3d/visualization/gui/NumberEdit.cpp
cpp/open3d/visualization/gui/Slider.cpp
cpp/open3d/visualization/gui/TabControl.cpp
cpp/open3d/visualization/gui/TextEdit.cpp
cpp/open3d/visualization/gui/TreeView.cpp
cpp/open3d/visualization/gui/TreeView.h
cpp/open3d/visualization/gui/VectorEdit.cpp
cpp/open3d/visualization/visualizer/GuiVisualizer.cpp
cpp/pybind/visualization/gui/gui.cpp
examples/python/GUI/all-widgets.py

A Python script testing this is attached below (note that you will need to rename it to .py, as GitHub won't accept a .py file)
[ml-vis.txt](https://github.com/intel-isl/Open3D/files/4974546/ml-vis.txt) (change line 288 to `dataset.visualize(0)` if using the small version of SemanticKITTI linked below
[microkitti.tar.gz](https://github.com/intel-isl/Open3D/files/4983757/microkitti.tar.gz) (very small version of SemanticKITTI)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2105)

gui::TreeView now supports arbitrary widgets for its cells

---

cpp/open3d/pipelines/registration/Registration.cpp

This PR fixes #2075 
https://github.com/intel-isl/Open3D/blob/ae38f286302f1d650e6acd1048178ca28c86af00/cpp/open3d/pipelines/registration/Registration.cpp#L160
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2118)

PointToPlane and ColoedICP should only require target PointCloud to have pre-computed Normals

---

3rdparty/filament/filament_download.cmake
3rdparty/find_dependencies.cmake
3rdparty/mkl/mkl.cmake
CMakeLists.txt

- MKL
- MKL merged lib is provided for linux
- Now we upload to github releases, instead of google cloud bucket
- Filament
- Use external project instead of fetch content to trigger download at build time, instead of config time
- In general
- Allow user to specify `THIRD_PARTY_DOWNLOAD_DIR`, and prepare the downloaded files **manually**
- Added function to accommodate local and remote URL.
- By default, remote URLs is used if `THIRD_PARTY_DOWNLOAD_DIR` is not specified. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2155)

speed up 3rd-party package download

---

CMakeLists.txt

disables the `CUDA_ARCHITECTURES is empty for target "Open3D"` warning on cmake 3.18+.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2175)

disable CMP0104 warning

---

cpp/open3d/io/rpc/Connection.cpp

```
In file included from /home/yixing/repo/Open3D/cpp/open3d/io/rpc/Connection.cpp:27:
/home/yixing/repo/Open3D/cpp/open3d/io/rpc/Connection.h:64:15: error: private field 'connect_timeout_' is not used [-Werror,-Wunused-private-field]
const int connect_timeout_;
^
/home/yixing/repo/Open3D/cpp/open3d/io/rpc/Connection.h:65:15: error: private field 'timeout_' is not used [-Werror,-Wunused-private-field]
const int timeout_;
^
2 errors generated.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2196)

fix unused var error with clang

---

cpp/pybind/io/class_io.cpp

Revert #1936 to remove bugs causing instability in IO, detailed in #2148.
May revisit if the feature is supported without bugs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2225)

Revert #1936

---

3rdparty/find_dependencies.cmake
cpp/open3d/CMakeLists.txt
cpp/open3d/core/Tensor.h
cpp/open3d/ml/CMakeLists.txt
cpp/open3d/ml/contrib/CMakeLists.txt
cpp/open3d/ml/contrib/Cloud.cpp
cpp/open3d/ml/contrib/Cloud.h
cpp/open3d/ml/contrib/GridSubsampling.cpp
cpp/open3d/ml/contrib/GridSubsampling.h
cpp/open3d/utility/Optional.h
cpp/pybind/core/core.cpp
cpp/pybind/core/core.h
cpp/pybind/core/tensor.cpp
cpp/pybind/ml/contrib.cpp
cpp/pybind/ml/ml.cpp
cpp/pybind/ml/ml.h
cpp/pybind/open3d_pybind.h
python/test/ml/test_contrib.py

These are meant for temporary use to support with 3D-ML repo. They should be replaced by Open3D's own PointCloud subsampling methods in the future.
- `cpp/open3d/ml/contrib/*`: 3rdparty code. Need to review CMake and directory structure. In particular, is this a good place to put the 3rdparty ML code?
- `cpp/pybind/ml/contrib.cpp`: main change. Includes our own python wrapper and input sanity checks.
- Related to `optional`: this PR introduces a back-ported C++17 `std::optional` as `open3d::utility::optional` to handle `None` parameter in pybind11.
- Unit tests: unit tests are dummy. @sanskar107 could you provide some unit tests in this PR or a separate PR?
--- …

ml-contrib subsample library

---

cpp/open3d/visualization/visualizer/Visualizer.h
cpp/open3d/visualization/visualizer/VisualizerRender.cpp

This PR fixes #1367 (although the issue has been closed, it is still not fixed). 
In the current version of Open3D (0.10.1.0), the methods `capture_screen_image()` and `capture_screen_float_buffer()` **do not work in offscreen mode**. An image of the desktop is shown instead of the rendered scene. 
You can easily verify this by executing the following script:
```
import matplotlib.pyplot as plt
print('o3d.__version__', o3d.__version__)
ofp = 'some/path/to/file.png'
mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()
vis = o3d.visualization.Visualizer()
vis.create_window(visible=False)
vis.add_geometry(mesh)
vis.poll_events()
vis.update_renderer()
vis.capture_screen_image(ofp, True)
color = vis.capture_screen_float_buffer(True)
depth = …
```

Fix screen rendering in offscreen mode

---

cpp/open3d/ml/PyTorch/CMakeLists.txt

Use torch_cpu target for cpu builds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2292)

fix cpu only builds for torch op library

---

cpp/open3d/visualization/gui/TreeView.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2301)

Fix left side of checkboxes in a treeview not being clickable

---

.dockerignore
.github/workflows/gce-ubuntu-docker.yml
util/ci_utils.sh
util/docker/open3d-gpu/Dockerfile
util/docker/open3d-gpu/scripts/env-setup.sh
util/docker/open3d-gpu/scripts/gce-ubuntu-docker-run.sh

Configuration: 
BUILD_SHARED_LIBS=OFF
BUILD_TORCH_OPS=ON
BUILD_TENSORFLOW_OPS=ON
BUILD_RPC_INTERFACE=ON
BUILD_CUDA_MODULE=ON
CUDA 10.1 on Ubuntu 20.04 needs gcc 8.4 (default is gcc 9.3)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2308)

Enable CI on Ubuntu 20.04 (focal) with CUDA on GCE

---

cpp/open3d/visualization/gui/TreeView.cpp

TreeView was ignoring the draw return value of cells.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2314)

Fix checkboxes in treeview not always redrawing when clicked

---

cpp/pybind/camera/camera.cpp

This version is clearer, in python `camera.camera_parameters` gives an AttributeError.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2312)

Python camera message fix

---

cpp/open3d/core/linalg/LinalgUtils.cpp
python/open3d/__init__.py

Delay cuSOLVER and cuBLAS init so exceptions are transferred to Python.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2319)

Fix for abort on disabled CUDA devices

---

cpp/open3d/io/ImageIO.cpp
cpp/open3d/io/ImageIO.h
cpp/open3d/io/file_format/FileJPG.cpp
cpp/open3d/io/file_format/FilePNG.cpp
cpp/pybind/io/class_io.cpp
util/ci_utils.sh

Enable PNG_IMAGE_FLAG_FAST with quality<=2
Write time: 86ms->19ms
File size: 374KB->596KB
for lena_color (512x512)
Issue #846
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2325)

Fast compression mode for png writing (issue #846)

---

cpp/open3d/core/CUDAUtils.cpp
python/open3d/__init__.py

Loading  cuda pybind, checking cuda availability and then loading cpu pybind causes "symbol already registered"  error. This re-appeared in specific combinations after the CUDA_VISIBLE_DEVICES fix. This uses ctypes to prevent symbol registration.
New `open3d_core_cuda_device_count() `C interface can be called through ctypes. Directly calling C++ interface is not portable due to name mangling.
Tested with these combinations:
GPU + CUDA : ISL workstation
GPU + CUDA + CUDA_VISIBLE_DEVICES=none : ISL workstation
No GPU + no CUDA : docker
GPU + no CUDA : docker
No GPU + CUDA : docker
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2324)

Fix for "symbol already registered"

---

cpp/open3d/core/Tensor.cpp
python/test/core/test_core.py

Consistent with python's slicing semantics:
```python
a = o3c.Tensor([0, 1, 2])
print(a[10:20])  # valid, result = [0]
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2317)

Slice out-of-range

---

3rdparty/filament/filament_build.cmake
CMakeLists.txt

Simplifies filament build-from-source scripts. Added some additional flags.
- `CCACHE_PROGRAM=OFF`: this actually enables ccache for ubuntu
- `FILAMENT_ENABLE_JAVA=OFF`
- `FILAMENT_SUPPORTS_VULKAN=OFF`, the pre-compiled Filament has Vulkan support, but since we're compiling it, we don't need it
- `FILAMENT_SKIP_SAMPLES=ON`
(This was part of the efforts to port Open3D to ARM64, where filament will be compiled from source. However, `bluegl` is not yet supporting ARM: https://github.com/google/filament/issues/1135  and `bluegl` cannot be disabled for Filament.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2303)

simplify filament build-from-source

---

cpp/open3d/core/nns/NanoFlannIndex.h

`NanoFlannIndexHolderBase` does not have a virtual destructor, causing the `unique_ptr` to its children classes not being able to destruct property.
Quick test case that causes memory leak:
```cpp
void RunTest() {
core::Tensor ref = core::Tensor::Ones({100, 3}, core::Dtype::Float64);
core::nns::NanoFlannIndex index(ref);
}
TEST(NearestNeighborSearch, KnnSearch) {
while (true) {
RunTest();
}
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2340)

Fix NanoFlannIndex base class memory leak

---

cpp/pybind/visualization/gui/gui.cpp

`.def("__repr__", ...)` can take a `std::string` return value directly.  Fixes warning:
```cpp
Open3D/cpp/pybind/visualization/gui/gui.cpp:830:29: 
warning: returning address of local temporary object [-Wreturn-stack-address]      
return s.str().c_str(); 
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2336)

fix c_str() temp address warning

---

python/open3d/ml/torch/python/layers/convolutions.py

Uses Module.register_buffer to avoid propagation of the required_gradient flag to the non-trainable offset parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2350)

fix required_gradient propagation in torch conv layers

---

cpp/open3d/ml/pytorch/continuous_conv/ContinuousConvOps.cpp
cpp/open3d/ml/pytorch/continuous_conv/ContinuousConvTransposeOps.cpp
cpp/open3d/ml/pytorch/misc/BuildSpatialHashTableOps.cpp
cpp/open3d/ml/pytorch/misc/FixedRadiusSearchOps.cpp
cpp/open3d/ml/pytorch/misc/InvertNeighborsListOps.cpp
cpp/open3d/ml/pytorch/misc/InvertNeighborsListOps.h
cpp/open3d/ml/pytorch/misc/KnnSearchOps.cpp
cpp/open3d/ml/pytorch/misc/RadiusSearchOps.cpp
cpp/open3d/ml/pytorch/misc/ReduceSubarraysSumOps.cpp
cpp/open3d/ml/pytorch/misc/ReduceSubarraysSumOps.h
cpp/open3d/ml/pytorch/misc/VoxelPoolingOps.cpp

This also fixes problems with noncontiguous tensors in the backward pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2354)

convert noncontiguous tensors instead of throwing an exception.

---

python/open3d/ml/tf/python/layers/convolutions.py
python/open3d/ml/torch/python/layers/convolutions.py

-bugfix for float extents for torch cconv layer
-fixed discrepancy between dense layer initialization between tf and torch
-added parameters for the dense weight initializer to the cconv layer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2361)

bugfixes for torch ContinuousConv layer

---

CMakeLists.txt

The generator expressions CXX_COMPILER_ID in cpp/CMakeLists.txt:13 do not support multiple ids before 3.15.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2392)

set cmake minimum to 3.15

---

cpp/open3d/utility/Eigen.cpp

While looking into the Eigen utilities  I found this small unused variable. Is not a big thing, but better to remove it :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2398)

Remove unused variable from SolveJacobianSystemAndObtainExtrinsicMatrix

---

cpp/tests/geometry/Image.cpp
cpp/tests/geometry/RGBDImage.cpp

Resolving some failing tests in #2343 in ARM simulator:
```
[  FAILED  ] 11 tests, listed below:
[  FAILED  ] Image.CreateFloatImage_3_2_Weighted
[  FAILED  ] Image.CreateFloatImage_3_2_Equal
[  FAILED  ] Image.CreateFloatImage_3_4_Weighted
[  FAILED  ] Image.CreateFloatImage_3_4_Equal
[  FAILED  ] RGBDImage.CreateFromColorAndDepth
[  FAILED  ] RGBDImage.CreateFromRedwoodFormat
[  FAILED  ] RGBDImage.CreateFromTUMFormat
[  FAILED  ] RGBDImage.CreateFromSUNFormat
[  FAILED  ] RGBDImage.CreateFromNYUFormat
[  FAILED  ] RGBDImage.FilterPyramid
[  FAILED  ] RGBDImage.CreatePyramid
```
The tests are failing because we're comparing float as 4 independent bytes. Since this PR is to support #2343, only a subset of the image tests are refactored.
--- …

Refector some image tests failing on arm simulator

---

cpp/open3d/visualization/gui/SceneWidget.cpp
cpp/open3d/visualization/gui/SceneWidget.h
cpp/open3d/visualization/rendering/Open3DScene.cpp
cpp/open3d/visualization/visualizer/GuiVisualizer.cpp
cpp/pybind/visualization/gui/gui.cpp

Note: with this change scene caching is disabled by default and must be enabled explicitly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2409)

Expose caching related functions in Python

---

CHANGELOG.md
cpp/open3d/geometry/TriangleMesh.h
cpp/open3d/geometry/TriangleMeshSimplification.cpp
cpp/pybind/geometry/trianglemesh.cpp

This pull request adds a maximum error threshold to `SimplifyQuadricDecimation`. This allows a user to target a particular quality rather than only targeting a specific triangle count. For example, a user could generate two levels of detail like so:
```python
lq = mesh.simplify_quadric_decimation(2, maximum_error=1e-6)
hq = mesh.simplify_quadric_decimation(2, maximum_error=1e-10)
```
The algorithm will attempt to reduce the mesh to 2 faces, but will exit when it exceeds the specified maximum error.
Closes #1972 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2411)

Added max error threshold

---

util/ci_utils.sh

```
E: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/Packages.gz  File has unexpected size (47871 != 49498). Mirror sync in progress? [IP: 152.195.19.142 443]
Hashes of expected file:
- Filesize:49498 [weak]
- SHA256:332f3ee4e353b8a5e5a2bdd8fdbd47cf140c73822b82b328815f122e09e195a0
- SHA1:4dc8ef9a3ee3c97b3c26d46e07fdd83997e6880b [weak]
- MD5Sum:bbff3b9c3462257479d72521ee78ec29 [weak]
Release file created at: Wed, 23 Sep 2020 22:09:13 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2423)

Fix nvidia download error

---

3rdparty/filament/filament_build.cmake
3rdparty/filament/filament_download.cmake

Note: ignore branch name. This PR updates to build against Filament 1.9.3 which is the current release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2430)

Compile against Filament 1.9.3

---

cpp/pybind/visualization/gui/gui.cpp
docs/versions.js
examples/python/gui/all-widgets.py
examples/python/gui/vis-gui.py

In particular:
```
def main():
gui.Application.instance.inititalize()
w = Window("Crash")
gui.Application.instance.add_window(w)
gui.Application.instance.run()  # C++ cleans up filament, but Python still has a shared_ptr ref in w
if __name__ == "__main__":
main()
```
This also prevents Python users from forgetting to call add_window() which would lead to problems with layouts. And it should have the side-effect of preventing crash-on-exit if the Python script exits prematurely after the window is created due to an exception.
The API has been changed. The above code should be:
```
def main():
gui.Application.instance.inititalize()
w = gui.Application.instance.create_window("No crash")
gui.Application.instance.run()
if __name__ == "__main__":
main()
```
--- …

Rework Python API for creating windows to avoid crash on exit in some simple situations.

---

cpp/open3d/visualization/rendering/filament/TriangleMeshBuffers.cpp

Factory methods like TriangleMesh::CreateSphere() produce warning messages about "missing required attributes" because they are missing texture coordinates. This PR automatically adds them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2514)

Add dummy texture coordinates for triangle meshes with no texture coordinates to avoid error messages.

---

cpp/open3d/visualization/utility/DrawGeometry.cpp

This was added due as a result of a bad merge conflict resolution in d5b95454b
This fixes #2472 and I suspect it also fixes #2157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2523)

Remove O(n^2) adding of geometries in draw_geometries

---

cpp/open3d/visualization/rendering/filament/FilamentGeometryBuffersBuilder.cpp
cpp/open3d/visualization/rendering/filament/TriangleMeshBuffers.cpp

The old `draw_geometries()` would accept bounding boxes. Right now we have to convert them into a LineSet first. See #2448
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2520)

Allow Scene::AddGeometry to accept bounding boxes

---

CHANGELOG.md
python/open3d/__init__.py

Resolves #2518 per @jwnimmer-tri's suggestion
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2527)

Fixes bug for preloading libc++ and libc++abi in Python

---

cpp/open3d/visualization/rendering/Open3DScene.cpp

The bug is that unless you explicitly set the background color, the background is black and the view does not clear on draw, leading to streaking from all the previous draws.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2530)

Fix Open3DScene with no background color set not clearing on draw

---

cpp/open3d/geometry/PointCloud.h

Fixes following bummer on documentation.
Screenshot taken from [here](http://www.open3d.org/docs/latest/cpp_api/classopen3d_1_1geometry_1_1_point_cloud.html#a5ba828b0b6849dc5dafd9ca03a0000ee).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2554)

Minor documentation fix

---

examples/python/reconstruction_system/refine_registration.py

Fixed the function call  TransformationEstimationForColoredICP() in refine_registration.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2562)
Fixes Issue - #2561

Fixed incomplete function call.

---

cpp/open3d/pipelines/odometry/Odometry.cpp
examples/python/reconstruction_system/make_fragments.py
examples/python/reconstruction_system/refine_registration.py
examples/python/reconstruction_system/register_fragments.py

This PR fixed the bug introduced by #2497, intensively discussed in #2107 and #2565. Now the reconstruction system can reproduce the result of the tutorial.
It also addressed minor config issues in the reconstruction system.
While this PR fixes the urgent RGBD odometry bug, we need to keep monitoring potential bugs like in #1787, and introduce better mechanisms to notify user when abnormal memory patterns take place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2567)

Fix reconstruction system

---

CHANGELOG.md
cpp/open3d/io/file_format/FilePCD.cpp

The type float_t can be float, double, or long double, depending on the
architecture and compiler settings. Thus, when reading a "float" value
of size 4 from a PCD file, the code should not use float_t but float.
Fixes #2556 
(edit: fix referenced issue)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2563)

fix reading float from PCD, instead of float_t

---

cpp/open3d/visualization/visualizer/ViewControl.cpp
cpp/open3d/visualization/visualizer/ViewControl.h
cpp/pybind/visualization/viewcontrol.cpp

Function to get view controller from arbitrary pinhole camera parameters. In this function, it is responsibility of the users to
verify the validity of the parameters, in contrast to `ConvertFromPinholeCameraParameters()` function. This can be useful to render images or depthmaps without any restriction in FOV, zoom, etc.
Example of use (python): https://github.com/pablospe/open3D_depthmap_example
(code is already compiled, and can be installed with pip).
This PR is related to the following git issues: #1417, #497, #727, #834, #1389, #2443, #1164, #2036, #2190.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2564)

Allow arbitrary pinhole camera

---

cpp/open3d/io/rpc/RemoteFunctions.cpp

This PR fixes a wrong shape check for the faces and lines tensor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2623)

fixed shape check for faces and lines in SetMeshData

---

cpp/open3d/ml/impl/misc/FixedRadiusSearch.cuh
cpp/open3d/ml/impl/misc/RaggedToDense.cuh
cpp/open3d/ml/impl/misc/RaggedToDense.h
cpp/open3d/ml/impl/misc/Voxelize.cuh
cpp/open3d/ml/impl/misc/Voxelize.h
cpp/open3d/ml/pytorch/CMakeLists.txt
cpp/open3d/ml/pytorch/TorchHelper.h
cpp/open3d/ml/pytorch/misc/RaggedToDenseOpKernel.cpp
cpp/open3d/ml/pytorch/misc/RaggedToDenseOpKernel.cu
cpp/open3d/ml/pytorch/misc/RaggedToDenseOpKernel.h
cpp/open3d/ml/pytorch/misc/RaggedToDenseOps.cpp
cpp/open3d/ml/pytorch/misc/VoxelizeOpKernel.cpp
cpp/open3d/ml/pytorch/misc/VoxelizeOpKernel.cu
cpp/open3d/ml/pytorch/misc/VoxelizeOpKernel.h
cpp/open3d/ml/pytorch/misc/VoxelizeOps.cpp
cpp/open3d/ml/tensorflow/CMakeLists.txt
cpp/open3d/ml/tensorflow/misc/VoxelizeOpKernel.cpp
cpp/open3d/ml/tensorflow/misc/VoxelizeOpKernel.cu
cpp/open3d/ml/tensorflow/misc/VoxelizeOpKernel.h
cpp/open3d/ml/tensorflow/misc/VoxelizeOps.cpp
cpp/open3d/utility/MiniVec.h
python/test/ml_ops/mltest.py
python/test/ml_ops/test_ragged_to_dense.py
python/test/ml_ops/test_voxelize.py

This PR adds 
- an op for voxelization of point clouds
- an op for converting ragged to dense tensors for torch
- unit tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2607)

voxelize op for torch and tensorflow

---

.gitignore
cpp/open3d/ml/Helper.h
cpp/open3d/ml/impl/misc/Nms.cpp
cpp/open3d/ml/impl/misc/Nms.cu
cpp/open3d/ml/impl/misc/Nms.h
cpp/open3d/ml/impl/misc/NmsImpl.h
cpp/open3d/ml/pytorch/CMakeLists.txt
cpp/open3d/ml/pytorch/misc/NmsOps.cpp
cpp/open3d/ml/tensorflow/CMakeLists.txt
cpp/open3d/ml/tensorflow/misc/NmsOpKernel.cpp
cpp/open3d/ml/tensorflow/misc/NmsOpKernel.cu
cpp/open3d/ml/tensorflow/misc/NmsOpKernel.h
cpp/open3d/ml/tensorflow/misc/NmsOps.cpp
cpp/open3d/utility/MiniVec.h
python/test/ml_ops/test_nms.py

Some notes:
1. In the original impl, the op is implemented in Python + CPP. Where the Python part does the sorting in PyTorch. In this implementation, the sorting part is moved to C++ and it is done by thrust. This is required since in TensorFlow we cannot use PyTorch's sorting. 
2. Added CPU implementation.
3. Same as the original impl, the CUDA op requires host + device operations.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2615)

nms op for pytorch and tensorflow

---

.github/workflows/openblas.yml
CMakeLists.txt
docs/compilation.rst

* [Updated] CMake min requirement from 3.15 to 3.17 as required by faiss.
[3.18 is not supported by current CI Tests configuration]
* [Updated] CMake-3.18-aarch64 for arm64-filament-only CI, install wget
* [Modified] "Ubuntu 18.04 and below" to "Ubuntu 18.04" as the package is incompatible with previous versions of Ubuntu, as libc++7-dev required by the package is not available in previous versions of Ubuntu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2665)

cmake-3.17 required

---

cpp/benchmarks/tgeometry/PointCloud.cpp
cpp/open3d/core/EigenConverter.cpp
cpp/open3d/core/EigenConverter.h
cpp/open3d/core/Tensor.cpp
cpp/open3d/core/Tensor.h
cpp/open3d/t/geometry/PointCloud.cpp
cpp/open3d/t/geometry/PointCloud.h
cpp/open3d/t/geometry/TriangleMesh.cpp
cpp/open3d/t/geometry/TriangleMesh.h
cpp/pybind/t/geometry/pointcloud.cpp
cpp/tests/t/geometry/PointCloud.cpp
cpp/tests/t/geometry/TriangleMesh.cpp
cpp/tests/t/io/PointCloudIO.cpp
python/test/t/geometry/test_pointcloud.py

- Add mesh conversion functions
- Constructor of pointcloud and trianglemesh no longer takes dtypes
- Several orders of magnitudes faster conversion to legacy `PointCloud` and `TriangleMesh`.
```
------------------------------------------------------------------
Benchmark                        Time             CPU   Iterations
------------------------------------------------------------------
ToLegacyPointCloud/CPU        21.5 ms         21.5 ms           30
ToLegacyPointCloud/CUDA       4470 ms         4470 ms            1
------------------------------------------------------------------
Benchmark                        Time             CPU   Iterations
------------------------------------------------------------------
ToLegacyPointCloud/CPU       0.030 ms        0.030 ms        20128 …
```

Faster geometry conversion

---

cpp/open3d/visualization/visualizer/GuiSettingsModel.cpp

This PR fixes a link error in debug builds with gcc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2744)

fix undefined reference in Debug build with gcc

---

cpp/open3d/ml/impl/misc/RaggedToDense.cuh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2751)

fix out of bounds memory access in ragged_to_dense op

---

cpp/open3d/visualization/gui/PickPointsInteractor.cpp
cpp/open3d/visualization/visualizer/O3DVisualizerSelections.cpp

Picking examines nearby points and takes the point with the highest score. Point clouds need to have a smaller range than meshes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2746)

Better picking, fixes crash removing last selection set

---

cpp/open3d/visualization/rendering/View.h
cpp/open3d/visualization/rendering/filament/FilamentView.cpp
cpp/open3d/visualization/rendering/filament/FilamentView.h

Exposes AO, shadow map, anti-aliasing, and post process options + removes use of some deprecated Filament API methods
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2755)

Expose Additional Filament features via View class

---

cpp/open3d/visualization/gui/Events.h
cpp/pybind/visualization/gui/events.cpp
cpp/pybind/visualization/gui/gui.cpp
cpp/pybind/visualization/gui/gui.h

Addresses #2610 (which itself collects other issues)
```
#!/usr/bin/env python
def on_mouse(e):
if e.type == gui.MouseEvent.Type.BUTTON_DOWN:
print("[debug] mouse:", (e.x, e.y))
return gui.Widget.EventCallbackResult.IGNORED
def on_key(e):
if e.key == gui.KeyName.SPACE:
if e.type == gui.KeyEvent.UP:  # check UP so we default to DOWN
print("[debug] SPACE released")
else:
print("[debug] SPACE pressed")
return gui.Widget.EventCallbackResult.HANDLED
if e.key == gui.KeyName.W:  # eats W, which is forward in fly mode
print("[debug] Eating W")
return gui.Widget.EventCallbackResult.CONSUMED
return gui.Widget.EventCallbackResult.IGNORED
def main():
gui.Application.instance.initialize()
w = gui.Application.instance.create_window("Open3D …
```

Add ability to add mouse and key callbacks to SceneWidget in Python

---

cpp/open3d/geometry/Octree.cpp

Fixes #1359, #1871
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2788)

Allow creation of octree from point cloud with no color info

---

python/open3d/visualization/_external_visualizer.py

This PR
- fixes the example in the docstring
- adds notes about future functionality in the docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2792)

fix wrong example for external visualizer

---

cpp/open3d/visualization/visualizer/O3DVisualizer.cpp
cpp/open3d/visualization/visualizer/O3DVisualizer.h
cpp/pybind/visualization/o3dvisualizer.cpp

Fixed changing point size while not in standard shader mode resetting to standard shader mode;  non-standard shading mode not keeping point sizes;  added unlit shader mode.
Known bug: lines are not shown in depth mode (and even if they were, they'd only be one pixel GL lines)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2815)

Fixes to O3DVisualizer shading modes, adds unlit mode

---

cpp/open3d/utility/Console.h

Now the more detailed error message looks like this:
```
In function open3d::t::geometry::TSDFVoxelGrid::TSDFVoxelGrid(std::unordered_map<std::__cxx11::basic_string<char>, open3d::core::Dtype>, float, float, int64_t, int64_t, const open3d::core::Device&):
/home/wei/Workspace/code/Open3D/cpp/open3d/t/geometry/TSDFVoxelGrid.cpp:100 [Open3D Error] SDF trunc is too large. Please make sure sdf trunc is smaller than half block size (i.e., block_resolution * voxel_size * 0.5)
```
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2829)

Add __file__ and __line__ for error message

---

cpp/open3d/pipelines/color_map/NonRigidOptimizer.cpp
cpp/open3d/pipelines/color_map/RigidOptimizer.cpp

Since #2408, openmp macro guards are no longer required. This is a quick-fix PR for #2832 to remove macro guards for color map optimization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2835)

remove openmp macro guards for color map optimization

---

cpp/open3d/core/Scalar.h
cpp/open3d/core/Tensor.cpp
cpp/open3d/core/Tensor.h
cpp/pybind/core/tensor.cpp
cpp/tests/core/Scalar.cpp
cpp/tests/core/Tensor.cpp
python/test/core/test_core.py

- Add `core::Scalar` class
- Siimplify `Tensor::Arange`
- Future work: `core::Scalar` can potentially be used for `Tensor::Init`, `Tensor::Fill`, etc, where currently templates are used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2857)

core::Scalar class and refactor arange

---

.github/workflows/openblas.yml
util/ci_utils.sh

This essentially reverts https://github.com/intel-isl/Open3D/pull/2708 and adds minor tweaks, where we first compile the 3rd-party libraries and cache the compilation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2891)

compile 3rd-party library in a separate step for arm64 CI

---

cpp/open3d/visualization/rendering/filament/FilamentGeometryBuffersBuilder.cpp
cpp/open3d/visualization/visualizer/O3DVisualizer.cpp

You can test with:
```
import sys
if len(sys.argv) != 2:
print("Usage:", sys.argv[0], " point_cloud_filename")
exit(1)
filename = sys.argv[1]
cloud = o3d.io.read_point_cloud(filename)
print("VoxelGrid")
voxels = o3d.geometry.VoxelGrid.create_from_point_cloud(cloud, 0.05)
o3d.visualization.draw_geometries([voxels])
o3d.visualization.draw([voxels])
print("Octree")
voxels = o3d.geometry.Octree(3)  # max_depth=3
voxels.convert_from_point_cloud(cloud, 0.05)
o3d.visualization.draw_geometries([voxels])
o3d.visualization.draw([voxels])
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2932)

Add rendering for VoxelGrid and Octree to new renderer

---

3rdparty/librealsense/librealsense.cmake
examples/cpp/RealSenseRecorder.cpp
python/test/t/io/test_realsense.py

- RSUSB backend cannot detect devices correctly on Windows.
- More robust patching command for librealsense repo - succeeds on rebuild.
- Add Python unit test for `RealSenseSensor`
fixes #2861
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2923)

Enable RSUSB backend only on Linux.

---

cpp/open3d/visualization/gui/Window.cpp
cpp/open3d/visualization/gui/Window.h

This fixes the following Python script hanging on Windows:
```
#!/usr/bin/env python
def main():
o3d.visualization.gui.Application.instance.initialize()
w = o3d.visualization.gui.Application.instance.create_window("Crash", 640, 480)
crash
if __name__ == "__main__":
main()
```
On Windows it seems that if the program exits before the first draw message is received, the Filament render (or command?) thread has not started yet. The Window destructor will destroy the Filament renderer, which will clean up some stuff and then hang at filament/src/Renderer.cpp:130 (FRenderer::terminate() at Fence::waitAndDestroy()). It is not clear to me if this is a timing problem or something else. If the script exits shortly after the renderer is created in the draw, the script may still …

Lazy load renderer when creating window in case Python crashes before window becomes visible

---

cpp/open3d/visualization/gui/Events.h
cpp/open3d/visualization/gui/SceneWidget.cpp
cpp/open3d/visualization/gui/Window.cpp
cpp/open3d/visualization/rendering/CameraInteractorLogic.cpp
cpp/open3d/visualization/rendering/CameraInteractorLogic.h
cpp/open3d/visualization/rendering/MatrixInteractorLogic.cpp
cpp/open3d/visualization/rendering/MatrixInteractorLogic.h
cpp/open3d/visualization/rendering/ModelInteractorLogic.cpp
cpp/open3d/visualization/rendering/ModelInteractorLogic.h

To test, two-finger swipe *slowly* to dolly in/out on macOS. You should see it buttery-smooth with this PR, and very discrete (arguably not working) without it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2964)

Fixed trackpad scrolling to be buttery smooth at slow speeds on macOS

---

cpp/open3d/t/geometry/TSDFVoxelGrid.cpp
cpp/open3d/t/geometry/TSDFVoxelGrid.h
cpp/open3d/t/geometry/kernel/GeometryMacros.h
cpp/open3d/t/geometry/kernel/TSDFVoxelGrid.cpp
cpp/open3d/t/geometry/kernel/TSDFVoxelGrid.h
cpp/open3d/t/geometry/kernel/TSDFVoxelGridShared.h
cpp/pybind/t/geometry/tsdf_voxelgrid.cpp

Fixes #2927 by exposing the weight filter ratio to users. By changing the parameter to 0.0 the user can generate relatively noisy mesh from a single frame / multiple frames.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2931)

Expose outlier threshold parameter to users

---

cpp/open3d/visualization/visualizer/GuiVisualizer.cpp
cpp/open3d/visualization/visualizer/O3DVisualizer.cpp
cpp/open3d/visualization/visualizer/Receiver.cpp
cpp/open3d/visualization/visualizer/Receiver.h
cpp/pybind/visualization/o3dvisualizer.cpp
python/open3d/visualization/draw.py

The initial problem was to get RPC add-geometry to redraw the scene in response to an update. However, this is a little troublesome because a) the scene doesn't know about the SceneWidget (which needs to note that it needs to actually redraw the scene for the next redraw and not just copy a bitmap) and the widgets don't know about their owning window (which is what requests a redraw from the OS), and b) different visualizers need to do different things even on adding geometry: O3DVisualizer needs to add to the scene using a lit material if it has normals or unlit otherwise, and to the list of geometries, but GuiVisualizer needs to add to the scene using the current material (or maybe replace the current object). So it seemed like it would be more flexible for the RPC Receiver to have a …

Refactored RPC interface to be more amenable to variation in visualizers (fixes add not updating)

---

cpp/pybind/geometry/boundingvolume.cpp

Typo in __repr__ for OBB in boundingvolume.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2987)

Minor typo in __repr__ for OBB

---

cpp/open3d/visualization/gui/Window.cpp

It fixed the hang on exit when a python exception is generated before the run() happens, but broke normal windows. Essentially a revert of #2819.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/2996)

Undo lazy creation of renderer on Windows

---

.github/workflows/gce-ubuntu-docker.yml
python/open3d/ml/torch/__init__.py
util/ci_utils.sh
util/docker/open3d-gpu/scripts/env-setup.sh
util/docker/open3d-gpu/scripts/gce-ubuntu-docker-run.sh
util/run_ci.sh

Python unit tests were failing in GCE. Issues identified and fixed:
- Change in Nvidia driver version in the host VM image to prepare for upgrade to CUDA-11.0.
- CPU version of PyTorch during Python tests -> CUDA PyTorch.
- Python unit tests now run in virtual env, as in Github.
- The CI config IDs now have meaningful names instead of just numbers.
- Minor formatting fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3063)

GCE CUDA Python tests

---

3rdparty/azure_kinect/azure_kinect.cmake
3rdparty/mkl/mkl.cmake
cpp/open3d/camera/CMakeLists.txt
cpp/open3d/geometry/CMakeLists.txt
cpp/open3d/io/CMakeLists.txt
cpp/open3d/pipelines/CMakeLists.txt
cpp/open3d/utility/CMakeLists.txt
cpp/open3d/visualization/gui/CMakeLists.txt
cpp/pybind/CMakeLists.txt
cpp/tests/CMakeLists.txt
cpp/tools/ManuallyAlignPointCloud/CMakeLists.txt

- Simplifies logic => less chance of errors for conditional compilation.
- Explicitly listing files to be built reduces accidental exclusion of files from the build.
[StackOverflow discussion](https://stackoverflow.com/questions/1027247/is-it-better-to-specify-source-files-with-glob-or-each-file-individually-in-cmak)
GLOBS for macros, GUI resources and style checks are unchanged.
Contributors: Please list unit test files, pybind files, other source files explicitly in CMakeLists.txt from now onwards.
Added URL hashes for MKL and AzureKinect downloads to prevent re-download during rebuild.  Fixes #2989
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3059)

Replace CMake GLOB and GLOB_RECURSE with file listing

---

3rdparty/find_dependencies.cmake

Resolves #3056
- Support USE_SYSTEM_LIBREALSENSE flag.
- If USE_SYSTEM_LIBREALSENSE=ON and BUILD_LIBREALSENSE=ON, build using pre-install librealsense.
- If GLIBCXX_USE_CXX11_ABI=ON, USE_SYSTEM_LIBREALSENSE turn OFF. This is to avoid problems with different ABIs (#2876).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3057)

Support USE_SYSTEM_LIBREALSENSE flag.

---

CMakeLists.txt

Tested with clang-7, ubuntu 18.04
Error during build.
```shell
Linking CXX executable ../../bin/EncodeShader
CMakeFiles/EncodeShader.dir/EncodeShader.cpp.o: In function `MakeString(std::string const&)':
/home/yixing/repo/Open3D/cpp/tools/EncodeShader.cpp:48: undefined reference to `__safestack_unsafe_stack_ptr'
/home/yixing/repo/Open3D/cpp/tools/EncodeShader.cpp:72: undefined reference to `__safestack_unsafe_stack_ptr'
/home/yixing/repo/Open3D/cpp/tools/EncodeShader.cpp:72: undefined reference to `__safestack_unsafe_stack_ptr'
/home/yixing/repo/Open3D/cpp/tools/EncodeShader.cpp:72: undefined reference to `__safestack_unsafe_stack_ptr'
/home/yixing/repo/Open3D/cpp/tools/EncodeShader.cpp:72: undefined reference to `__safestack_unsafe_stack_ptr' …
```

disable incompatible clang flags for now

---

cpp/open3d/io/sensor/azure_kinect/AzureKinectSensor.cpp
cpp/open3d/io/sensor/azure_kinect/AzureKinectSensor.h
cpp/pybind/io/sensor.cpp

This PR add `disconnect` method to AzureKinectSensor class. (required by #3044).
The method give user more flexible control to disconnect sensor.
For the test procedure. I prepared manual test.
For the test, please connect azure kinect to your PC, run this script for the manual test,
and check if all the assertion passed.
```py
config = o3d.io.AzureKinectSensorConfig()
sensor = o3d.io.AzureKinectSensor(config)
assert(sensor.connect(0))
assert(not sensor.connect(0))
sensor.disconnect()
assert(sensor.connect(0))
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3082)

Add disconnection function to AzureKinectSensor (#3044)

---

cpp/open3d/visualization/rendering/filament/FilamentView.cpp
cpp/open3d/visualization/rendering/filament/FilamentView.h

Fixes issue with picking and new render targets based scene caching
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3083)

Set post-processing configuration when copying View settings

---

cpp/open3d/visualization/gui/Application.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3084)

Fix crash if posted Window callback executes after Window is destroyed

---

docs/contribute/contribution_recipes.rst

Reading through the documentation and noticed a small spelling error in the documentation for contributions so I have amended it fo you in an effort to practice with GitHub.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3088)

Spelling error within documentation

---

cpp/tests/t/pipelines/registration/Registration.cpp

In PR #2979, The unit-test for t-registrations that require Faiss were disabled if build with `WITH_FAISS=OFF`. 
However, the updated HybridSearch uses `fixed_radius_search` instead of `knn_search`, so it might not be using FAISS anymore. 
If that's the case we may change the unit test back to run with `RegistrationPermuteDevices` instead of `RegistrationPermuteDevicesWithFaiss`. As for system build with `FAISS=OFF` and `CUDA=ON`, this might be potentially harmful. 
Seeking confirmation from @junha-l.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3095)

Changed t-registration unit-test to use RegistrationPermuteDevices

---

cpp/open3d/visualization/gui/Application.cpp
cpp/open3d/visualization/gui/Application.h
cpp/open3d/visualization/gui/Window.cpp

It's easy to do something like:
```
vis = o3d.visualization.O3DVisualizer()
...
```
You need to initialize the Application instance before creating anything UI-related, so that we can start up GLFW and find the resources. This spits out an error instead of continuing and crashing or getting unrelated-sounding errors like not being able to load images. (See #2995)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3103)

Better error message if you don't initialize gui::Application before creating a window

---

cpp/pybind/visualization/gui/gui.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3106)

Use UnownedPointer so Python doesn't retain a valid shared_ptr

---

cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp
cpp/open3d/visualization/rendering/filament/FilamentView.cpp

Fixes resize bug caused by switch to Render Targets for scene caching
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3107)

Fix window resize when Scene caching is enabled.

---

cpp/open3d/core/CoreUtil.h
cpp/open3d/core/linalg/LU.cpp
cpp/open3d/core/linalg/Tri.cpp
cpp/open3d/t/pipelines/kernel/TransformationConverter.cpp
cpp/open3d/t/pipelines/kernel/TransformationConverter.cu
cpp/open3d/t/pipelines/kernel/TransformationConverterImpl.h
cpp/open3d/utility/Console.h
cpp/tests/t/pipelines/TransformationConverter.cpp

Changes:
-  Float32 and Float64 support added for PoseToTransformation and RtToTransformation.
-  Changed `DTYPE == Dtype...` to `DTYPE == core::Dtype...`  `DISPATCH_FLOAT32_FLOAT64_DTYPE`, in core/CoreUtil.h, as for t:: modules. not inside core namespace, dispatching the code to just Dtype::... throws error. 
-  Modified Unit Tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3098)

TransformConverter supports Float32 and Float64 

---

cpp/open3d/visualization/gui/SceneWidget.cpp
cpp/open3d/visualization/gui/Window.cpp
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3121)

Fix one frame blinking in Open3DViewer when layout changed or dialog box was closed

---

cpp/open3d/visualization/gui/SceneWidget.cpp
cpp/open3d/visualization/gui/Window.cpp
cpp/open3d/visualization/rendering/Renderer.cpp
cpp/open3d/visualization/rendering/Scene.h
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/rendering/filament/FilamentScene.h
cpp/pybind/visualization/gui/gui.cpp
cpp/pybind/visualization/rendering/rendering.cpp

Also:
- makes resulting depth iage range from 0 (near plane) to 1 (far plane) instead of simply returning the raw values from Filament's buffer (which are reversed)
- fixes widgets that aren't SceneWidget or a Layout not working if they are a top-level child. (If you created a window and then called `window->AddChild(a_label)` (and properly sized it) the label would not draw, but if you put it in a layout and made the layout top-level, it worked fine.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3178)

Expose rendering to a depth image to Python

---

cpp/open3d/visualization/gui/BitmapWindowSystem.cpp
cpp/open3d/visualization/gui/BitmapWindowSystem.h
cpp/open3d/visualization/gui/GLFWWindowSystem.cpp
cpp/open3d/visualization/gui/GLFWWindowSystem.h
cpp/open3d/visualization/gui/Window.cpp
cpp/open3d/visualization/gui/WindowSystem.h

On high-DPI monitors, glfwGetWindowContentScale() returns > 1, which triggers problems with the new Window System code. The result is that text is properly sized, but the mouse coordinates are reduced by half, making clicking on UI elements not working (or, rather, mapped to the upper left quarter of the window).
Tested on Linux, macOS, and Windows. (Windows works for 100%, 150%, 200%)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3177)

Fix incorrect coordinates for mouse events on Linux

---

CHANGELOG.md
cpp/open3d/geometry/TriangleMesh.cpp

Add support for textures in TriangleMesh::operator+=
`TriangleMesh::operator+=` previously didn't support adding meshes with textures. This PR fixes that. Note that if either one of the meshes doesn't have texture, the resulting mesh won't have textures.
Tested and verified compliance with `WriteTriangleMeshToOBJ` as well. Let me know if anything.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3170)

Add support for textures in TriangleMesh::operator+=

---

cpp/pybind/visualization/rendering/rendering.cpp
examples/python/gui/line-width.py

It's not obvious that `Material::line_width` requires `shader` to be set to "unlitLine"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3194)

Added an example for line width

---

cpp/open3d/visualization/rendering/filament/FilamentScene.cpp

Prevents panic asserts from Filament when vertex buffers with 0 vertices are created.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3203)

Don't allow empty geometry to be added to scene

---

CHANGELOG.md
cpp/pybind/visualization/rendering/rendering.cpp

Also changes open3d.visualization.rendering.Open3DScene.`get_view` to `view` (it is a property, not a function). This should have minor impact on users, since the only thing that can be done with a view is setting the color grading, but that turns out to be impossible because the enums did not exist. Hence, we should have no users using `get_view`.
Resolves #2918.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3193)

Added pybinds for color grading enums

---

.github/workflows/arm64.yml
cpp/open3d/t/geometry/Image.cpp

Add special case for Image::To when there is no dtype conversion / scaling / offset
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3207)

Fix for CreateFromRGBDImage test

---

cpp/open3d/t/io/sensor/realsense/RSBagReader.cpp
cpp/open3d/t/io/sensor/realsense/RSBagReader.h

Resolves #3141
- Resolves undefined symbol error (`RSBagReader::DEFAULT_BUFFER_SIZE`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3142)

Fix ModuleNotFoundError when build with GCC10.

---

cpp/open3d/geometry/SurfaceReconstructionAlphaShape.cpp

fixes #1829 
Change the handling of "invalid tetra" from error to warning. If the tetra is invalid - do not perform the calculation on the tetra but cycle to the next tetra to continue building the mesh.
This does not prevent the original incorrect Tetra but does mean that the mesh is created although there may be a missing vertex.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3201)

handle the invalid tetra warning - fix #1829

---

cpp/open3d/visualization/gui/Layout.cpp
cpp/open3d/visualization/gui/Layout.h
cpp/open3d/visualization/gui/SceneWidget.cpp
cpp/open3d/visualization/rendering/Open3DScene.cpp
cpp/open3d/visualization/rendering/Open3DScene.h
cpp/open3d/visualization/rendering/filament/FilamentRenderer.cpp
cpp/pybind/visualization/gui/gui.cpp

Moves drawing render targets from Open3DScene into SceneWidget, where they get drawn as an ImGUI image. (There is no overhead for this, ImGUI just takes an opaque ID and the ImguiFilamentBridge needs to make sure that the ID identifies the proper texture; in our case the ID is simply Filament's texture ID.) Because the image is incorporated into the UI, the painting order will be correct and SceneWidgets can now be used in a layout.
```
#!/usr/bin/env python
app = gui.Application.instance
app.initialize()
w = app.create_window("SceneWidget and Layout", 1024, 768)
em = w.theme.font_size
left = gui.VGrid(2, 0.5 * em)
widget3d = gui.SceneWidget()
right = gui.Vert(0.5 * em)
horiz = gui.Horiz()
horiz.add_child(left) …
```

SceneWidget works with layouts

---

cpp/open3d/io/ModelIO.cpp
cpp/open3d/io/ModelIO.h
cpp/open3d/io/TriangleMeshIO.cpp
cpp/open3d/io/TriangleMeshIO.h
cpp/open3d/io/file_format/FileASSIMP.cpp
cpp/open3d/io/file_format/FileGLTF.cpp
cpp/open3d/io/file_format/FileOBJ.cpp
cpp/open3d/io/file_format/FileOFF.cpp
cpp/open3d/io/file_format/FilePLY.cpp
cpp/open3d/utility/Console.h
cpp/open3d/visualization/visualizer/GuiSettingsModel.cpp
cpp/open3d/visualization/visualizer/GuiVisualizer.cpp
cpp/pybind/io/class_io.cpp
cpp/tests/io/file_format/FileGLTF.cpp
cpp/tests/io/file_format/FileSTL.cpp

Progress bar isn't perfect, ASSIMP doesn't quantize internal computations of normals, but it is better than what we had before (the progress bar did not work at all). Progress feedback is also added to ReadTriangleMesh() subfunctions, but most of them did not work with print_progress=True, so not much change there.
Fixed Open3DViewer using unlit material for triangle meshes instead of lit material (regression due to changing the default shader for Material).
Fixed some console warnings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3238)

Improves progress bar in Open3DViewer app, also fixes unlit material instead of lit

---

cpp/open3d/geometry/PointCloudCluster.cpp
cpp/open3d/geometry/SurfaceReconstructionPoisson.cpp
cpp/open3d/utility/Console.cpp
cpp/open3d/utility/Console.h
cpp/pybind/open3d_pybind.cpp
cpp/pybind/utility/console.cpp

In Jupyter (python), the default logging function `std::cout` is replaced by `py::print`, where the logging displays in the Jupyter cell. This PR:
1. Adds `LogInfoConsole`, `LogDebugConsole`, ... to allow logging to console even in Jupyter environment. This is useful for debugging and make the front end appear less verbose.
2. Some tweaks of the `Logger` class, making some variables/functions private.
3. Hide `Logger` class and unnecessary APIs in the `.cpp` (with pimpl). This drastically reduces the binary size of Open3D.
Build with:
```bash
cmake -DCMAKE_BUILD_TYPE=Release ..
```
Current `master`:
```bash
➜  ~/repo/Open3D/build (master) ls -alh lib/Release/libOpen3D.a
-rw-rw-r-- 1 yixing yixing 52M Apr  4 14:23 lib/Release/libOpen3D.a
```
This PR:
```bash
➜  ~/repo/Open3D/build …
```

refactor logging, add option to log to console

---

cpp/open3d/visualization/rendering/filament/FilamentScene.cpp

You can see the warning (without this PR) when you pick points.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3256)

Fix spurious warning if a triangle mesh with no normals uses "defaultUnlit"

---

cpp/pybind/visualization/rendering/rendering.cpp

Fixes #3117. The problem is that the camera functions return Eigen::Transform, but there isn't a conversion for that into Python, so we convert into a full-blown Eigen::Matrix instead.
```
gui.Application.instance.initialize()
w = o3d.visualization.O3DVisualizer("03DVisualizer",640, 480)
w.add_geometry("box", o3d.geometry.TriangleMesh.create_box())
w.reset_camera_to_default()
gui.Application.instance.add_window(w)
open3DScene = w.scene
camera = open3DScene.camera
debug = camera.get_model_matrix()
print("model matrix:\n", debug)
debug = camera.get_view_matrix()
print("view matrix:\n", debug)
debug = camera.get_projection_matrix()
print("proj matrix:\n", debug)
```
--- …

Fix camera matrix getting pybinds not returning something that can be converted to a Python object

---

3rdparty/stdgpu/stdgpu.cmake

Currently, a patched version of stdgpu is used since its CUDA backend automatically detects the machine's GPU and sets the architecture flags accordingly. In case no GPU can be found, an error is thrown. The latest upstream version of stdgpu relaxes this constraint such that the patched version is not needed anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3265)

Update stdgpu dependency to latest upstream

---

cpp/open3d/visualization/rendering/filament/PointCloudBuffers.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3278)

Use more sensible default color for point clouds with no per-vertex color

---

cpp/open3d/core/hashmap/CUDA/StdGPUHashmap.h

The new default hashmap backend based on `stdgpu` can leak memory in its `Rehash` function when re-allocating memory to increase its capacity. Tested internally by intentionally producing a double-free error (calling `Free()` twice) to verify the first call releases the memory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3281)

Fix memory leak in stdgpu hashmap backend

---

cpp/pybind/visualization/o3dvisualizer.cpp

Allows this:
```
import open3d.visualization.rendering as rendering
import time
def make_point_cloud():
npts = 1000
center = (0, 0, 0)
radius = 1.0
pts = np.random.uniform(-radius, radius, size=[npts, 3]) + center
cloud = o3d.geometry.PointCloud()
cloud.points = o3d.utility.Vector3dVector(pts)
cloud.paint_uniform_color((0, 0, 0))
return cloud
def main():
cloud_name = "random"
app = gui.Application.instance
app.initialize()
vis = o3d.visualization.O3DVisualizer("Open3D - non-blocking", 1024, 768)
vis.add_geometry(cloud_name, make_point_cloud())
vis.reset_camera_to_default()
app.add_window(vis)
last_now = time.perf_counter()
while app.run_one_tick():
now = time.perf_counter()
if now - last_now > 0.1: …
```

Add post_redraw() to O3DVisualizer so that it can be used non-blocking

---

CMakeLists.txt

Drop the test for Pytorch_VERSION, which was not defined in the current scope.
Further, the warning can be relevant for older versions of Pytorch too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3355)

fix conditions for showing warning about CUDA 11 and pytorch

---

3rdparty/stdgpu/stdgpu.cmake
cpp/benchmarks/core/Hashmap.cpp
cpp/open3d/core/hashmap/CUDA/CUDAHashmapBufferAccessor.h
cpp/open3d/core/hashmap/CUDA/SlabHashmap.h
cpp/open3d/core/hashmap/CUDA/SlabNodeManager.h
cpp/open3d/core/hashmap/CUDA/StdGPUHashmap.h

- Update to most recent upstream version of `stdgpu` which includes significant performance improvements for `clear()`
- Fix asynchronous `cudaMemset` calls leading to wrong benchmark results
- Increase threads per block in `stdgpu` backend to `128` for better performance
- Fuse erase kernels for better performance which is safe because `stdgpu` only invalidates the iterator in `erase()` that gets removed while keeping all other valid
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3346)

Improve performance of stdgpu hashmap backend

---

cpp/open3d/t/geometry/PointCloud.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3350)

Properly scale UInt8 colors when converting to Legacy Point Cloud

---

3rdparty/jsoncpp/0001-optional-CXX11-ABI-and-MSVC-runtime.patch
3rdparty/jsoncpp/jsoncpp.cmake

This reverts commit 0444bae70cd5776fa8b824e19986cb3c12596cd1.
Server PRs are affected by this, e.g. #3108, #3385 . Merging this to fix master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3386)

Revert "simplify jsoncpp cmake (#3174)"

---

cpp/CMakeLists.txt
cpp/open3d/core/hashmap/CUDA/SlabHashmap.h
cpp/open3d/core/hashmap/CUDA/SlabNodeManager.h
cpp/open3d/geometry/TriangleMesh.cpp
cpp/open3d/visualization/gui/CMakeLists.txt
cpp/open3d/visualization/gui/Events.cpp
cpp/open3d/visualization/gui/Events.h
cpp/open3d/visualization/gui/GLFWWindowSystem.cpp
cpp/open3d/visualization/rendering/filament/FilamentRenderer.cpp
cpp/open3d/visualization/shader/PhongShader.cpp
cpp/open3d/visualization/shader/SimpleShader.cpp
cpp/open3d/visualization/visualizer/O3DVisualizerSelections.cpp
cpp/open3d/visualization/visualizer/VisualizerWithVertexSelection.cpp
cpp/tests/test_utility/Print.h

- Increase warning level for GNU/Clang/Intel compilers by `-Wextra`, but disable noisy `-Wunused-parameter` warning for now
- Make CUDA flags consistent with C++ flags
- Fix newly introduced warnings by the above bump
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3357)

Increase warning level

---

docs/getting_started.rst.in

Add a minimal `Dockerfile` example as requested in #3388. I've decided to leave out the `docker build` and `docker run` commands out intentionally to keep the document short.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3396)

Add Docker minimal example to getting_started docs. Fix #3388

---

cpp/open3d/visualization/gui/SceneWidget.cpp
cpp/open3d/visualization/gui/Window.cpp
cpp/open3d/visualization/gui/Window.h
cpp/open3d/visualization/rendering/Open3DScene.h

* Also cleans up some unused code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3394)

Fix screen turning black on resize in standalone viewer

---

cpp/open3d/ml/tensorflow/misc/NmsOps.cpp
docs/make_docs.py
docs/python_api_in/open3d.ml.tf.ops.rst
docs/python_api_in/open3d.ml.torch.ops.rst

This PR
- adds the nms and voxelize ops to the python api documentation
- fixes some formatting problem with the nms op doc
- adds default values to the help message of make_docs.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3425)

add missing ops to python api doc

---

python/test/core/test_core.py
python/test/ml_ops/mltest.py

Before:
```
...
============================================================================================================= warnings summary ==============================================================================================================
<...>/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py:22
<...>/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py:22: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
import imp
test/core/test_core.py: 22 warnings
<...>/Open3D/python/test/core/test_core.py:206: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is …
```

Suppress warnings in python unit tests

---

docs/builddocs.rst
docs/make_docs.py
examples/python/core/tensor.ipynb
util/ci_utils.sh

1. force `pip install jinja2==2.11.3`, `jinja2` was updated to `3.0.0` on May 11, 2021, causing incompatibilities with `nbsphinx` since then:
```python
Notebook error:
UndefinedError in tutorial/core/tensor.ipynb:
'nbformat.notebooknode.NotebookNode object' has no attribute 'tags'
Traceback (most recent call last):
File "make_docs.py", line 529, in <module>
sdb.run()
File "make_docs.py", line 326, in run
stderr=sys.stderr)
File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/subprocess.py", line 311, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sphinx-build', '-b', 'html', '.', '/home/runner/work/Open3D/Open3D/docs/_out/html']' returned non-zero exit status 2.
Error: Process completed with exit code 1.
```
2. fix the wrong variable …

fix docs build: NotebookNode object has no attribute 'tags'

---

examples/cpp/VoxelHashingGUI.cpp

Now the transformation is at the fixed-width, with or without negative signs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3440)

Fix flickering transformation in the GUI

---

cpp/open3d/core/Tensor.h
cpp/open3d/t/geometry/PointCloud.cpp
cpp/open3d/t/geometry/PointCloud.h
cpp/pybind/core/tensor.cpp
cpp/pybind/t/geometry/pointcloud.cpp
examples/python/gui/online-processing.py

- Copy Tensor C++ docs to Tensor Python docs.
- Add `Tensor.reshape()` pybind.
- `ToString`(), `__repr__` for PointCloud
Sample output:
> PointCloud on CPU:0 [0 points ()] Attributes: None.
> PointCloud on CPU:0 [0 points (Float32)] Attributes: colors (Float32, 3).
> PointCloud on CPU:0 [2 points (Float32)] Attributes: labels (Float32, 3), normals (Float32, 3).
> PointCloud on CUDA:0 [2 points (Float32)] Attributes: labels (Float32, 3), normals (Float32, 3).
> PointCloud on CUDA:0 [4 points (Float32)] Attributes: normals (Float32, 3).
- Correct `Mul_()` -> `MatMul_()` in extrinsic transformation in `CreatePointCloudWithNormals()`
.
--- …

Tensor Python documentation + bugfix

---

python/open3d/ml/torch/__init__.py

This PR adds a warning message when importing ```open3d.ml.torch``` with a torch wheel that may be affected by a compatibility problem with CUDA 11.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3451)

print warning if the torch wheel may have compatibility problems with CUDA 11

---

cpp/open3d/visualization/gui/GLFWWindowSystem.cpp
cpp/open3d/visualization/visualizer/Visualizer.cpp

Fixes #3471
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3475)

Fix changing directory to macOS bundle resource path on GLFW initialization

---

cpp/open3d/pipelines/registration/ColoredICP.cpp

Change:
- Raise error is point cloud is missing colors to avoid seg. fault in `RegistrationColoredICP`. [Fix for Issue #3455].
Pending Issues:
- One might still get a segmentation fault if one is using legacy `RegistrationICP` function directly with `estimation = TransformationEstimationType::ColoredICP`. To fix this, some refactoring is required. It will be done in a future PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3466)

Raise error is required attr. is missing [Fix #3455] 

---

cpp/open3d/visualization/gui/Button.cpp
cpp/open3d/visualization/gui/Checkbox.cpp
cpp/open3d/visualization/gui/ColorEdit.cpp
cpp/open3d/visualization/gui/Combobox.cpp
cpp/open3d/visualization/gui/ImageWidget.cpp
cpp/open3d/visualization/gui/Label.cpp
cpp/open3d/visualization/gui/Layout.cpp
cpp/open3d/visualization/gui/Layout.h
cpp/open3d/visualization/gui/ListView.cpp
cpp/open3d/visualization/gui/ListView.h
cpp/open3d/visualization/gui/NumberEdit.cpp
cpp/open3d/visualization/gui/Slider.cpp
cpp/open3d/visualization/gui/TabControl.cpp
cpp/open3d/visualization/gui/TextEdit.cpp
cpp/open3d/visualization/gui/ToggleSwitch.cpp
cpp/open3d/visualization/gui/TreeView.cpp
cpp/open3d/visualization/gui/TreeView.h
cpp/open3d/visualization/gui/VectorEdit.cpp
cpp/open3d/visualization/gui/Widget.cpp
cpp/open3d/visualization/gui/Widget.h
cpp/open3d/visualization/gui/Window.cpp
cpp/open3d/visualization/visualizer/GuiVisualizer.cpp
cpp/open3d/visualization/visualizer/O3DVisualizer.cpp
cpp/pybind/visualization/gui/gui.cpp

- GUI is scrollable now, which improves usability when the window is too small for the UI. ImGUI automatically creates scrollbars for a top-level widget.
- Added ScrollableVert class, which is useful if you want to (potentially) scroll something like a long legal license, for instance.
- Updated About boxes to have scrollable text for the legal license.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3476)

Fixed GUI to be scrollable

---

README.md

- Travis CI is not used anymore, so remove it from the README file
- Fix minor typo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3469)

Fix minor issues in README file

---

examples/python/utility/downloader.py

Moved redwood dataset used in "examples/python/utility/downloader.py" to open3d_downloads repo:
https://github.com/intel-isl/open3d_downloads/releases/tag/redwood
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3488)

moved downloader.py files to open3d_downloads

---

examples/python/reconstruction_system/scripts/download_redwood_simulated.sh

Moved redwood-simulated dataset used in "examples/python/reconstruction_system/scripts/download_redwood_simulated.sh"
to open3d_downloads.
https://github.com/intel-isl/open3d_downloads/releases/tag/redwood-simulated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3505)

moved redwood simulated dataset to open3d_downloads

---

examples/python/open3d_tutorial.py
python/test/open3d_test.py

Moved open3d_tutorial.py downloads to 
https://github.com/intel-isl/open3d_downloads/releases/tag/open3d_tutorial
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3477)

moved open3d_tutorial.py downloads to open3d_downloads release

---

python/setup.py

The current wheel (since v0.12 or earlier) causes `auditwheel` to crash when tested:
```
$ auditwheel show open3d-0.12.0-cp36-cp36m-manylinux2014_x86_64.whl
....
RuntimeError: Invalid binary wheel, found the following shared library/libraries in purelib folder:
libc++.so.1
libc++abi.so.1
open3d_tf_ops.so
open3d_torch_ops.so
pybind.cpython-36m-x86_64-linux-gnu.so
open3d_tf_ops.so
open3d_torch_ops.so
pybind.cpython-36m-x86_64-linux-gnu.so
The wheel has to be platlib compliant in order to be repaired by auditwheel.
```
This PR updates `setup.py` so that the purelib folder is not used. This produces a wheel that auditwheel can check without crashing (with warnings):
```
$ auditwheel show lib/python_package/pip_package/open3d-0.12.0+90f52cde6-cp36-cp36m-manylinux_2_31_x86_64.whl …
```

Fix wheel folder structure to prevent auditwheel crash

---

cpp/pybind/CMakeLists.txt
cpp/pybind/make_install_pip_package.cmake

This PR ensures that the `install-pip-package` target uses the pip module that matches the python environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3524)

fix using wrong pip module for installing the pip package

---

3rdparty/find_dependencies.cmake
cpp/open3d/utility/ParallelScan.h

- Clang 12 has been released mid of April, so add detection for it in the Filament dependency setup
- Remove library check which is already handled by the `REQUIRED` keyword for CMake 3.18 and newer
- Fix `parallelstl` include if compiler has parallel algorithms support
Fixes #3520
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3522)

Add Clang 12 detection for Filament dependency

---

3rdparty/CMake/FindPytorch.cmake
3rdparty/CMake/FindTensorflow.cmake

Retrieving properties from Tensorflow and Pytorch in our find modules is expensive because calling Python and importing either of them comes with a significant cost. Improve the performance by fetching all required properties in a single pass instead of 1 property per pass:
`time cmake -DCMAKE_INSTALL_PREFIX=../bin -DBUILD_CUDA_MODULE=ON -DBUILD_UNIT_TESTS=ON -DBUILD_BENCHMARKS=ON -DBUILD_PYTORCH_OPS=ON -DBUILD_TENSORFLOW_OPS=ON -DBUNDLE_OPEN3D_ML=ON -DOPEN3D_ML_ROOT=../../Open3D-ML -DOPEN3D_THIRD_PARTY_DOWNLOAD_DIR=~/workspace/open3d-downloads -DBUILD_JUPYTER_EXTENSION=ON -DBUILD_RPC_INTERFACE=ON -DBUILD_LIBREALSENSE=ON -DBUILD_AZURE_KINECT=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..`
real    0m19,039s
user    0m21,909s
sys     0m22,577s
real    0m9,561s
user    0m8,882s
sys     0m6,575s
In …

Improve performance of Tensorflow and PyTorch modules

---

cpp/pybind/CMakeLists.txt
cpp/pybind/core/tensor_accessor.cpp
cpp/pybind/core/tensor_converter.cpp
cpp/pybind/ml/contrib/contrib_subsample.cpp
cpp/pybind/utility/eigen.cpp

We already use the increased warning level for the core library as well as for tests, examples, etc. The `pybind` target should also follow that standard and maintain that high quality level.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3551)

Use same warning level in python bindings

---

python/open3d/ml/tf/python/layers/convolutions.py
python/open3d/ml/tf/python/layers/neighbor_search.py
python/test/ml_ops/test_fixed_radius_search.py
python/test/ml_ops/test_sparseconv.py

1) Added `tf.RaggedTensor` support for Fixed Radius Search, SparseConv and SparseConvTranspose layers.
2) Enabled batching support for same ops in tensorflow.
3) Added unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3553)

Add batch support for fixed_radius_search and SparseConvolution in tensorflow

---

CMakeLists.txt
cpp/pybind/CMakeLists.txt
docs/compilation.rst

- State minimum supported version in documentation to be CUDA 10.1
- Remove workarounds for older CUDA versions
- Add compiler check and abort if too old CUDA version is detected
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3575)

Clarify minimum required CUDA version

---

3rdparty/find_dependencies.cmake

Prevent build failures on older AppleClang compilers where the linker flag is absent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3576)

Test for -load_hidden flag

---

CMakeLists.txt

This PR workarounds a newly introduced compiler bug in Visual Studio 16.10 when building with CUDA and C++14.
References:
- https://github.com/actions/virtual-environments/issues/3485
- https://developercommunity.visualstudio.com/t/VS-16100-isnt-compatible-with-CUDA-11/1433342
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3574)

Workaround Visual Studio 16.10 compiler bug with CUDA and C++14

---

util/docker/open3d-gpu/scripts/gce-ubuntu-docker-run.sh

Remove deleting *all* ssh keys that may cause GCE VM login errors in other runs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3586)

Cleanup ssh key individually for each GCE run when deleting VM

---

.github/workflows/ubuntu.yml

A new version of `ccache` can support CUDA caching.
The `ccache` binary is uploaded to https://github.com/intel-isl/open3d_downloads/releases/tag/ccache . 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3603)

Use ccache 4.3 for CI

---

CMakeLists.txt

Currently, the python build wheel CI job often exceeds github's 6 hour time limit for master, when all CUDA architectures are built. The CUDA pybind is also very large (~420MB).
This PR reduces CUDA build time and CUDA binary size. 
Build with all supported architectures for previous **two** generations (Turing, Ampere) and M0 (minor=0) architectures for previous generations (inluding deprecated). Note that cubin for M0 runs on GPUs with architecture Mx. This is a tradeoff between binary size / build time and runtime older architectures.
See:
- https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#building-for-maximum-compatibility.
- https://docs.nvidia.com/cuda/ampere-compatibility-guide/index.html#application-compatibility-on-ampere
--- …

Reduce CUDA build time and binary size

---

.gitmodules
3rdparty/find_dependencies.cmake
3rdparty/libjpeg-turbo/libjpeg-turbo.cmake

Some git submodules are not really used for :
- Remove unused `google/filament` submodule because we rely on our fork `intel-isl/filament`
- Remove `libjpeg-turbo` submodule and use `ExternalProject_Add` URL downloading instead
- Upgrade `libjpeg-turbo` from commit between versions 2.0.2 and 2.0.3 to release version 2.0.6 (upgrade to 2.1.1 involves major changes and is deferred for future consideration)
In the future, we might port more/all submodules to URL downloading.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3621)

Cleanup git submodules

---

cpp/open3d/core/nns/NanoFlannIndex.cpp

`NanoFlannIndex` always falls back to the default internal sorting flag of `nanoflann::SearchParams`, i.e. `sorted = true`, independent of the user-provided function parameter `NanoFlannIndex::SearchRadius(..., sort = true)`. Respect the provided parameter (`sort`) and always set the internal sort strategy (`sorted`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3624)

Respect sort flag in NanoFlannIndex

---

cpp/open3d/core/Indexer.cpp
cpp/open3d/core/NumpyIO.cpp
cpp/open3d/geometry/SurfaceReconstructionBallPivoting.cpp
cpp/tools/ManuallyAlignPointCloud/VisualizerForAlignment.cpp

n Indexer::SplitLargestDim() I return nullptr if the two error conditions are true (there are two log messages early that do input validation
In NumpyArray::Load I added an assert if fp is null after the fopen
In NumpyArray::Save I return if fp is null after the fopen
in BallPivotingVertexPtr FindCandidateVertex I assert if opp is a nullptr
in io::WritePointCloud I return if fp is null after fopen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3631)

Last batch of fixes from the Klocwork scan

---

cpp/open3d/core/CMakeLists.txt
cpp/open3d/core/Device.h
cpp/open3d/core/MemoryManager.cpp
cpp/open3d/core/MemoryManagerStatistic.cpp
cpp/open3d/core/MemoryManagerStatistic.h

Features:
- Thread-safe `MemoryManagerStatistic` instance implemented as a singleton
- Per `Device` logging of memory allocations and frees
- Configurable print modes: `All`, `Unbalanced`, `None`
- Automatic print at the end of the program, defaults to `Unbalanced` to minimize noise
Detected memory leaks in unit tests:
- Skipped `Free` in LU decomposition when the operation fails
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3639)

Introduce memory manager statistics

---

3rdparty/azure_kinect/azure_kinect.cmake

Every time we build Open3D, we get this as part of the output:
```
x ./usr/
x ./usr/include/
x ./usr/include/k4a/
x ./usr/include/k4a/k4a.h
x ./usr/include/k4a/k4a.hpp
x ./usr/include/k4a/k4a_export.h
x ./usr/include/k4a/k4atypes.h
x ./usr/include/k4a/k4aversion.h
x ./usr/include/k4arecord/
x ./usr/include/k4arecord/k4arecord_export.h
x ./usr/include/k4arecord/playback.h
x ./usr/include/k4arecord/playback.hpp
x ./usr/include/k4arecord/record.h
x ./usr/include/k4arecord/record.hpp
x ./usr/include/k4arecord/types.h
x ./usr/lib/
x ./usr/lib/x86_64-linux-gnu/
x ./usr/lib/x86_64-linux-gnu/cmake/
x ./usr/lib/x86_64-linux-gnu/cmake/k4a/
x ./usr/lib/x86_64-linux-gnu/cmake/k4a/k4aConfig.cmake
x ./usr/lib/x86_64-linux-gnu/cmake/k4a/k4aConfigVersion.cmake
x …
```

Reduce noise of k4a archive extraction

---

cpp/open3d/t/geometry/kernel/GeometryMacros.h
cpp/open3d/t/pipelines/kernel/Reduction6x6Impl.cuh

Changes:
Adding template dtype support in Reduction6x6Impl.
Issue re-solved [by @stotko ]: 
Adding 
```
#if __CUDA_ARCH__ < 600
__device__ double atomicAdd(double *address, double val) {
unsigned long long int *address_as_ull = (unsigned long long int *)address;
unsigned long long int old = *address_as_ull, assumed;
do {
assumed = old;
old = atomicCAS(
address_as_ull, assumed,
__double_as_longlong(val + __longlong_as_double(assumed)));
// Note: uses integer comparison to avoid hang in case of NaN (since NaN
// != NaN)
} while (assumed != old);
return __longlong_as_double(old);
}
#endif
```
throws error 
```
.../Open3D/cpp/open3d/t/geometry/kernel/GeometryMacros.h(35): error: function "atomicAdd(double *, double)" has already been defined
```
Not adding the same, throws an error in some of …

Registration Reduction6x6Impl template datatype support.

---

cpp/pybind/io/class_io.cpp

I noticed that `Octree` didn't have the IO function in python bind yet, but I found the C++ file. 
I made this modification so we could use the `write_octree()` and `read_octree()` function the same way we use `write_voxel_grid()` or `write_point_cloud()`.
Just let me know if tests or docs are additionally necessary.
Some example code:
``` python
pcd = o3d.io.read_point_cloud("some_ply_file.ply")
voxel_grid = getVoxelStructure(pcd)
octree = getOctreeStructure(pcd)
o3d.visualization.draw_geometries([pcd])
o3d.visualization.draw_geometries([voxel_grid])
o3d.visualization.draw_geometries([octree])
o3d.io.write_point_cloud("pointcloud.pcd", pcd)
o3d.io.write_voxel_grid("voxel_grid.ply", voxel_grid)
o3d.io.write_octree("octree.json", octree)
pcd2 = o3d.io.read_point_cloud("pointcloud.pcd") …
```

Add octree IO in python bind

---

util/ci_utils.sh
util/docker/open3d-gpu/Dockerfile

Enabled on 18.04 without TF or Torch Ops only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3662)

Use CUDA 10.1 to test Open3D builds with min supported CUDA version

---

docs/getting_started.rst.in

libusb-1.0-0 is statically linked.
Verified in Ubuntu focal and bionic.
Update docs. 
FYI: @nachovizzo 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3657)

libusb not required for running Open3D in docker

---

cpp/open3d/core/MemoryManager.cpp
cpp/open3d/core/MemoryManagerStatistic.cpp
cpp/open3d/core/MemoryManagerStatistic.h
cpp/pybind/open3d_pybind.cpp

Summary:
- Add `HasLeaks()` function to memory statistics to query current leak status. This simplifies some internal code.
- Add `Reset()` function to discard all recorded statistics. Used to suppress leak warning for objects managed by `pybind11`.
- Filter pointers and sizes to automatically account for previous calls to `Reset()`.
- Print list of leaking pointers to provide more information about their distribution.
- Fix underflow in balance computation by changing `size_t` to `int64_t` .
Manually checked exit code of C++ and Python unit tests with an intentional leak. Works as expected. CI must all pass as Open3D should be leak-free as of this PR.
--- …

Return failure exit code on leaks at program end

---

cpp/open3d/core/EigenConverter.cpp
cpp/open3d/core/kernel/ArangeCPU.cpp
cpp/open3d/core/kernel/ArangeCUDA.cu
cpp/open3d/core/kernel/BinaryEWCPU.cpp
cpp/open3d/core/kernel/BinaryEWCUDA.cu
cpp/open3d/core/kernel/CPULauncher.h
cpp/open3d/core/kernel/CUDALauncher.cuh
cpp/open3d/core/kernel/IndexGetSetCPU.cpp
cpp/open3d/core/kernel/IndexGetSetCUDA.cu
cpp/open3d/core/kernel/UnaryEWCPU.cpp
cpp/open3d/core/kernel/UnaryEWCUDA.cu
cpp/open3d/core/linalg/TriCPU.cpp
cpp/open3d/core/linalg/TriCUDA.cu
cpp/open3d/geometry/PointCloudCluster.cpp
cpp/open3d/pipelines/color_map/ColorMapUtils.cpp
cpp/open3d/pipelines/color_map/NonRigidOptimizer.cpp
cpp/open3d/pipelines/color_map/RigidOptimizer.cpp
cpp/open3d/pipelines/odometry/Odometry.cpp
cpp/open3d/pipelines/registration/Registration.cpp
cpp/open3d/t/geometry/kernel/ImageImpl.h
cpp/open3d/t/geometry/kernel/PointCloudCPU.cpp
cpp/open3d/t/geometry/kernel/PointCloudCUDA.cu
cpp/open3d/t/geometry/kernel/PointCloudImpl.h
cpp/open3d/t/geometry/kernel/TSDFVoxelGridCPU.cpp
cpp/open3d/t/geometry/kernel/TSDFVoxelGridCUDA.cu
cpp/open3d/t/geometry/kernel/TSDFVoxelGridImpl.h
cpp/open3d/t/pipelines/kernel/FillInLinearSystemImpl.h
cpp/open3d/utility/Eigen.cpp

Changes:
- `CPULauncher` and `CUDALauncher` are now be namespaces, not classes
- Rename `LaunchGeneralKernel` to `LaunchParallel`
- Add comments
(This PR is to prepare us for the upcoming "parallel for" PR.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3638)

Refactor cpu_launcher and cuda_launcher as namespaces

---

cpp/open3d/core/nns/FaissIndex.cpp

Running the unit tests with CUDA support enabled on a GPU with 8 GB VRAM (or less) likely fails because `faiss` is unable to allocate memory. Ideally, we would give it access to our cached memory manager, but for the time being, workaround this problem by releasing our CUDA memory cache instead.
Tested on NVIDIA RTX 2070 Max-Q with 8 GB VRAM.
Note that other out-of-memory failures on GPUs with less memory may still occur due to limitations of the cached memory manager (will be addressed separately.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3677)

Release CUDA cache in faiss index initialization

---

.gitmodules
3rdparty/find_dependencies.cmake
3rdparty/googletest/googletest.cmake
3rdparty/imgui/imgui.cmake
3rdparty/qhull/qhull.cmake
cpp/tests/core/Indexer.cpp
cpp/tests/core/TensorObject.cpp
cpp/tests/t/geometry/TriangleMesh.cpp
cpp/tests/t/pipelines/TransformationConverter.cpp
cpp/tests/t/pipelines/odometry/RGBDOdometry.cpp
cpp/tests/t/pipelines/registration/Registration.cpp
cpp/tests/t/pipelines/registration/TransformationEstimation.cpp
cpp/tests/t/pipelines/slac/ControlGrid.cpp
cpp/tests/t/pipelines/slac/SLAC.cpp

This PR ports all manually-built libraries that are currently included as `git submodules` to the `ExternalProject_Add` URL downloading approach:
- `googletest`: Also upgrade from `pre-1.10` version to `1.11`.
- `imgui`: Also upgrade from `pre-1.74` to `1.74`.
- Other ported libraries are kept at their particular version. Upgrading them should be evaluated in a different PR.
Further changes:
- Teach `build_3rdparty_library` to accept absolute paths, e.g. coming from `ExternalProject_Add` and slightly restructure it.
- Remove uninstantiated test suites which become test failures by default in `googletest 1.11`.
The remaining `git submodules` will be ported in a future PR to keep this one simpler.
Issue: #3134
---
This change is [<img src="https://reviewable.io/review_button.svg" …

Port build submodules to URL downloading

---

cpp/open3d/visualization/webrtc_server/CMakeLists.txt

The HTML copy command should update the resource directory on every build. However, the underlying logic is overly complicated and produces some noise, especially when the build is complete. Since `add_custom_target` is always out-dated by default, the simplified logic achieves the same result with less noise for the user.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3696)

Simplify HTML copy command

---

.gitignore
.gitmodules
3rdparty/benchmark/MakeAvailable/CMakeLists.txt
3rdparty/benchmark/benchmark.cmake
3rdparty/find_dependencies.cmake
3rdparty/pybind11/pybind11.cmake
3rdparty/zeromq/zeromq_build.cmake
CMakeLists.txt
cpp/benchmarks/CMakeLists.txt
docs/CMakeLists.txt
docs/conf.py.in

This PR ports all remaining libraries that are currently included as `git submodules` to the `ExternalProject_Add` URL downloading approach:
- `benchmark`: Also upgrade from `pre-1.5.1` version to `1.5.1`.
- `zeromq`: Switch to `ExternalProject_Add` to defer download from configure to build time.
- Other ported libraries are kept at their particular version. Upgrading them should be evaluated in a different PR.
Fixes #3134
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3703)

Port remaining git submodules to URL downloading

---

3rdparty/find_dependencies.cmake
3rdparty/openblas/openblas.cmake

Some readability cleanups:
- Prefix internal functions for 3rdparty dependency handling with `open3d_` for consistency.
- Add `DEPENDS` argument to import and build functions to make them more self-contained.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3702)

Add DEPENDS option to import and build 3rdparty functions

---

cpp/pybind/io/rpc.cpp

This PR
-exposes BufferConnection to python
-enables implicit conversion to Tensor for the rpc functions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3729)

expose BufferConnection to python and enable implicit conversion to Tensor for the RPC functions

---

cpp/open3d/ml/pytorch/sparse_conv/SparseConvOps.cpp
cpp/open3d/ml/pytorch/sparse_conv/SparseConvTransposeOps.cpp

This PR fixes calls to the tensor.index() function for torch 1.8 and later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3740)

fix args to tensor.index() for torch 1.8 and later

---

cpp/open3d/core/Tensor.cpp
cpp/pybind/core/tensor_accessor.cpp
cpp/tests/core/Tensor.cpp
python/test/core/test_core.py
python/test/core/test_hashmap.py
python/test/core/test_linalg.py
python/test/core/test_nn.py
python/test/core/test_torch_integration.py

Fixed IndexSet() for 0-D tensor (Advanced indexing cannot handle 0-D tensor).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3389)

fix index set for 0-D tensor

---

cpp/open3d/core/MemoryManagerCached.cpp

Fixes CUDA error in even some very simple code:
```diff
diff --git a/examples/cpp/CMakeLists.txt b/examples/cpp/CMakeLists.txt
index dbbe5b785..241cb8540 100644
--- a/examples/cpp/CMakeLists.txt
+++ b/examples/cpp/CMakeLists.txt
@@ -27,6 +27,7 @@ macro(open3d_add_example EXAMPLE_CPP_NAME)
list(APPEND EXAMPLE_TARGETS ${EXAMPLE_CPP_NAME})
endmacro()
+open3d_add_example(DebugBenchmark)
open3d_add_example(CameraPoseTrajectory)
open3d_add_example(ColorMapOptimization)
open3d_add_example(DepthCapture)
diff --git a/examples/cpp/DebugBenchmark.cpp b/examples/cpp/DebugBenchmark.cpp
new file mode 100644
index 000000000..fbfb4bc9c
--- /dev/null
+++ b/examples/cpp/DebugBenchmark.cpp
@@ -0,0 +1,13 @@
+// Compile with -DBUILD_CUDA_MODULE=ON
+// This example gives error:
+// …
```

Ensure CUDAState is initialized before Cacher

---

cpp/open3d/io/file_format/FileASSIMP.cpp

Updated Flags:
```
const unsigned int kPostProcessFlags =
aiProcess_GenNormals | aiProcess_RemoveRedundantMaterials |
aiProcess_Triangulate | aiProcess_GenUVCoords | aiProcess_SortByPType |
aiProcess_OptimizeMeshes | aiProcess_PreTransformVertices;
```
Loading Time of Redwood dataset: apartment, bedroom, boardroom mesh:
|               | Open3D (master) | Open3D (This PR) | MeshLab |
| ------------- | --------------- | ---------------- | ------- |
| apartment.ply | 277,932         | 6,000            | 5,300   |
| bedroom.ply   | 154,251         | 3,300            | 3,300   |
| boardroom.ply | 316,495         | 6,000            | 5,500   |
*Time of Open3D is more end to end, as compared to MeshLab (there is some lag between when loading time is displayed and mesh is displayed). Also, with …

Updated ASSIMP processing flags to improve triangle-model loading time

---

cpp/open3d/utility/Logging.h

`fmt 6.0.0` implicitly includes `fmt/ostream.h` in one of its other header files. In (at least) `fmt 8.0.0`, this include has changed such that stream-based support is no longer automatically provided which causes compilation errors. Explicitly include the header file to fix compilation errors with recent versions of `fmt`.
Issue: #3754
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3763)

Add missing include in Logging.h

---

cpp/benchmarks/core/MemoryManager.cpp
cpp/open3d/core/CMakeLists.txt
cpp/open3d/core/CUDAState.cu
cpp/open3d/core/CUDAState.cuh
cpp/open3d/t/geometry/kernel/NPPImage.cpp
cpp/tests/core/CUDAState.cpp

Followup of #3732:
- Stream support for `NPPImage`.
- Additional constructor for `CUDAScopedStream` with automatic stream creation and deletion.
- Updated unit test. The large constant `kIterations = 100000` is used to increase the likelihood of detecting multi-threading bugs as thread creation comes with an initial startup cost. More iterations result in longer execution time and, hence, more attack surface for potential bugs to be detected.
Future changes:
- Unification of `CUDAState.cuh` and `CUDAUtils.h` is deferred to another followup PR. This will include making `cuda::Set{Device,Stream}` an implementation detail.
- Potentially adding python bindings for multi-stream/device functionality will also be considered later based on the result of above unification.
--- …

Cleanup CUDAScopedStream and add stream support to NPPImage

---

cpp/open3d/core/CMakeLists.txt
cpp/open3d/core/Tensor.cpp
cpp/open3d/t/io/CMakeLists.txt
cpp/open3d/t/io/NumpyIO.cpp
cpp/open3d/t/io/NumpyIO.h
cpp/tests/core/Tensor.cpp
cpp/tests/t/io/CMakeLists.txt
cpp/tests/t/io/NumpyIO.cpp

- Move numpy IO to the `t/io` directory. 
- Hide `NumpyArray` class as implementation details. 
- This is a pure refactoring PR to prepare us for future support for `.npz` file format.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/intel-isl/open3d/3752)

Move Numpy I/O to t/io/NumpyIO.h

---

3rdparty/find_dependencies.cmake
CMakeLists.txt
cpp/tools/CMakeLists.txt

Summary:
- Add `PUBLIC` and `HEADER` keywords to `open3d_pkg_config_3rdparty_library` and `open3d_find_package_3rdparty_library`. They are used to control target installation like in the other functions. Note that `HEADER` is internally unused in above functions, but for consistency it must be added nonetheless.
- Add `PACKAGE_VERSION_VAR` option to `open3d_find_package_3rdparty_library` to specify non-standard version variables.
- Make dependency names consistent between `USE_SYSTEM_*` variables and `Open3D::3rdparty_*` targets.
- Fix `filament` dependency not being added to the list of `HEADER` targets.
- Fix `parallelstl` dependency not being added to the list of `PUBLIC` targets.
- Fix `PNG` dependency not being installed when using `USE_SYSTEM_PNG`.
- Fix installation of public …

Fix inconsistencies in 3rdparty dependency handling

---

3rdparty/find_dependencies.cmake
CMakeLists.txt

Preinstalled versions of `googletest` only work with setting the option `GLIBCXX_USE_CXX11_ABI` to `ON`. However, the default is `OFF` and Tensorflow and PyTorch also rely on that different setting. Since `googletest` is only used in our unit tests (which are not installed) and not by the Open3D library itself, building it from source does not affect packaging for repository maintainers or other use cases.
Fixes #3785 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3808)

Remove USE_SYSTEM_GOOGLETEST option

---

cpp/pybind/t/io/class_io.cpp

Loading time are different when the file is saved as ASCII v/s BIN. [Similar results were observed when opened with MeshLab].
|             | points     | file size | Loading Time [ASCII] | Loading Time [BIN] |
| ----------- | ---------- | --------- | -------------------- | -------------------- |
| bedroom.ply | 20,061,457 | 450 MB      | 28,129 ms            | 5,300 ms             |
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3816)

t write_point_cloud pybind default param set to write binary

---

3rdparty/stdgpu/stdgpu.cmake
cpp/benchmarks/core/Hashmap.cpp
cpp/open3d/core/Device.h
cpp/open3d/core/StdAllocator.h
cpp/open3d/core/hashmap/CUDA/StdGPUHashmap.h

- Add `StdAllocator` as conforming `Allocator` interface for containers.
- Add `StdGPUAllocator` which is based on `StdAllocator` and includes additional device checks as well as memory register functionality required by `stdgpu`.
- Change custom default constructor of `Device` to automatically generated one. This implicitly "adds" `OPEN3D_HOST_DEVICE` for CUDA code and is required for `StdGPUAllocator`.
- Add `Rehash` benchmark.
- `Insert`: 7% slower on very small sizes, 10-47% faster for large sizes.
- `Erase`: 7% slower on very small sizes, 10-45% faster for large sizes.
- `Find`: Identical performance.
- `Clear`: 15% slower on very small sizes, 40-50% faster for large sizes.
- `Rehash`: 10-12% faster on very small sizes, 34-67% faster for large sizes.
- `VoxelDownSample`: 15-23% …

Add StdAllocator and apply to stdgpu backend

---

cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp
cpp/open3d/pipelines/registration/FastGlobalRegistration.h
cpp/open3d/pipelines/registration/Registration.cpp
cpp/open3d/pipelines/registration/Registration.h
cpp/open3d/utility/Helper.cpp
cpp/open3d/utility/Helper.h
cpp/pybind/pipelines/registration/registration.cpp
cpp/tests/core/Tensor.cpp
cpp/tests/utility/Helper.cpp

This PR addresses https://github.com/intel-isl/Open3D/issues/1263 for allowing deterministic registration:
- Adds a `seed` optional parameter to `RegistrationRANSACBasedOnCorrespondence` and `RegistrationRANSACBasedOnFeatureMatching`
- Adds a `seed` member to `FastGlobalRegistrationOption`
- Replaces the `UniformRandInt` function with a callable class that accepts an optional seed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3737)

Deterministic registration

---

3rdparty/faiss/faiss_build.cmake
3rdparty/find_dependencies.cmake
python/test/ml_ops/test_cublas.py

The current release version of Python wheel for Linux depends on certain CUDA shared libraries. If the CUDA toolkit version does not match the one in `PATH`, all the CUDA functionalities will not work. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3817)

Full CUDA static linking on Linux

---

CHANGELOG.md
cpp/pybind/generate_torch_ops_wrapper.py
python/test/core/test_core.py

$ `flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics`
```
./Open3D/cpp/pybind/generate_torch_ops_wrapper.py:57:49: F821 undefined name 'docstr'
m = re.search('with schema: open3d::(.*)$', docstr)
^
./Open3D/python/test/core/test_core.py:212:46: F821 undefined name 'VisibleDeprecationWarning'
category=VisibleDeprecationWarning)
^
2     F821 undefined name 'docstr'
2
```
https://github.com/numpy/numpy/blob/main/numpy/_globals.py#L44 change made in #3421
@stotko Your review please.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3844)

Fix undefined names: docstr and VisibleDeprecationWarning

---

cpp/open3d/io/PointCloudIO.h
cpp/pybind/io/class_io.cpp

- Changed default parameter for `ReadPointCloud` to set `remove_nan_points` and `remove_inf_points` as false (as they are not supported in tensor pipeline yet). 
- This also changes the default for legacy.
Discussion:
- ReadParamOptions might be complicated, may we replace it directly with bool?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3879)

ReadPointCloud default parameter changed

---

.github/workflows/Dockerfile.openblas

Also updated the Google cloud cache `open3d-arm64-ci-ccache.tar.gz` manually.
The new limit is ccache's default 5G limit.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3904)

Revert ccache -M 1G for ARM docker build

---

cpp/open3d/t/geometry/LineSet.cpp
cpp/open3d/t/geometry/PointCloud.cpp
cpp/open3d/t/geometry/TriangleMesh.cpp
cpp/open3d/t/geometry/TriangleMesh.h
cpp/pybind/t/geometry/pointcloud.cpp
cpp/pybind/t/geometry/trianglemesh.cpp
cpp/tests/t/geometry/LineSet.cpp
cpp/tests/t/geometry/PointCloud.cpp
cpp/tests/t/geometry/TriangleMesh.cpp

- Default constructor for `Tensor` `PointCloud` and `TriangleMesh` `Pybind`.
- `TriangleMesh::ToString()`
Updated `ToString()` for pointcloud and lineset:
Previously for a `custom` attribute of `shape (4, 3, 2)` and type `Float32`, ToString for `pointcloud` and `lineset` printed: 
`Attribute: custom (Float32, 3)`, now it prints `Attribute: custom (dtype = Float32, shape = {4, 3, 2})`, which might be more clear.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3880)

Default Constructor for Tensor PointCloud and TriangleMesh Pybind

---

cpp/open3d/core/CUDAUtils.cpp
cpp/open3d/core/CUDAUtils.h
cpp/tests/core/Tensor.cpp

Master build failing since #3890. Testing again without #3890.
This reverts commit 617b96ff3f2ca48b073dbb02943c92b678102261.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3907)

Revert "Throw proper error for invalid CUDA device id. (#3890)"

---

.github/workflows/documentation.yml
.github/workflows/ubuntu.yml

Upload docs archive with a prefix initially.
Rename to correct name after Ubuntu wheels are uploaded.
Ubuntu wheels take the longest to build (on master).
~~Upload enabled on all branches for testing.~~ Only master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3919)

Make docs archive available after wheels are ready.

---

docs/getting_started.rst.in
python/open3d/__init__.py

Warnings enabled (if cuda.pybind DSO not found):
```
$ python -W default -c "import open3d as o3d"
/Users/ssheorey/Documents/Open3D/Code/Open3D/build/lib/python_package/open3d/__init__.py:84: ImportWarning: Open3D was built with CUDA support, but Open3D CUDA Python binding library not found! Falling back to the CPU Python binding library.
warnings.warn(
Using external Open3D-ML in /Users/ssheorey/Documents/Open3D/Code/Open3D-ML/
```
Warnings disabled:
```
$ python -c "import open3d as o3d"
Using external Open3D-ML in /Users/ssheorey/Documents/Open3D/Code/Open3D-ML/
```
See: https://github.com/isl-org/Open3D/issues/3827#issuecomment-898672575
--- …

Add warnings to help debug CUDA / pybind issues

---

cpp/open3d/core/CUDAUtils.cpp
cpp/open3d/core/CUDAUtils.h
cpp/tests/core/Tensor.cpp

Changes: Added `AssertCUDADeviceAvailable` to check if the `device_id` is valid.
Context:
- Using `cuda::DeviceCount` in the function `AssertCUDADeviceAvailable` was resulting in GPU CI failure. The CI run was getting killed trying to run the cpp unit tests `./bin/tests`, however, the instance did not get terminated. 
- replacing `cuda::DeviceCount` with `cudaGetDeviceCount(&num_devices)` seems to solve the issue. 
- However, the previous version ran fine on the local system, so the issue might have to do with the CI environment. This is one of my guess : https://github.com/isl-org/Open3D/pull/3915#issuecomment-898823350 
TODO: 
- maybe we can directly use `cudaGetDeviceCount(&num_devices)` in `cuda::DeviceCount`.
This change is [<img src="https://reviewable.io/review_button.svg" …

Assert CUDA Device-ID Available

---

cpp/open3d/core/CUDAUtils.cpp
cpp/open3d/core/CUDAUtils.h
cpp/open3d/core/MemoryManagerCUDA.cpp
cpp/open3d/core/kernel/ReductionCUDA.cu
cpp/tests/Main.cpp
cpp/tests/core/CUDAUtils.cpp
cpp/tests/core/CoreTest.h

Merge #3922 first.
- `CUDAState()` returns instance reference instead of shared ptr
- Rename `num_devices` to `device_count` to be consistent with CUDA API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3925)

Refactor CUDAState()::GetInstance()

---

3rdparty/find_dependencies.cmake
cmake/Open3DLink3rdpartyLibraries.cmake

Header targets are defined as dependencies used in *public headers* but *linked privately*. The latter step is currently implemented by also treating them also as private targets. Instead we should automatically link them privately and do not add them to the list of private targets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3937)

Simplify header target usage

---

cpp/open3d/core/nns/NanoFlannIndex.cpp

Changes:
- Assuming `num_neighbors = min(dataset_size, knn)`, removed checks. 
- Replaced `Filled tensor of {-1} of shape {num_query_points, knn}` with `Empty tensor of shape {num_query_points, num_neighbors}`.
----
Effect on performance of `estimate_noramls`:
```
------------------------------------------------------------------------------------------------
Benchmark                                                      Before             After   
------------------------------------------------------------------------------------------------
EstimateNormals/CPU F32 KNN[0.02 | 30]                      51.8 ms         23.4 ms          
EstimateNormals/CPU F64 KNN[0.02 | 30]                      54.6 ms         24.1 ms          
LegacyEstimateNormals/Legacy KNN[0.02 | 30] …
```

Faster TensorCPU KNN Search.

---

3rdparty/find_dependencies.cmake

Currently, `Open3D_3RDPARTY_EXTERNAL_MODULES` is constructed manually by checking if the corresponding `open3d_find_package_3rdparty_library` call succeeded and appending the relevant find module. Automatically handle this case to simplify the code and make it more robust.
Manually tested with all 4 combinations of `BUILD_SHARED_LIBS` and `USE_SYSTEM_PNG`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3939)

Automatically handle 3rdparty external modules

---

cpp/open3d/core/Indexer.h
cpp/open3d/core/kernel/ReductionCUDA.cu

`MiniVec<T, N>` is a strict superset of `SmallArray<T, N>` and can be used instead. Thus, remove the latter and replace any usages by the former.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3949)

Remove SmallArray<T, N> class

---

cpp/open3d/core/CUDAUtils.cpp
cpp/open3d/core/CUDAUtils.h
cpp/open3d/core/kernel/ReductionCUDA.cu
cpp/tests/core/CUDAUtils.cpp

Changes:
- Move `GetNumDevices()` to standalone `DeviceCount()`.
- Move `GetWarpSize()` to standalone `GetCUDACurrentWarpSize()`.
- Remove superfluous `GetCurrentDeviceID()`.
- Re-enable `CUDAScopedDevice` usage in `CUDAState` constructor.
- Minor fixes for const correctness, copy constructors in singletons, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3946)

Minimize cached CUDA state

---

examples/python/gui/online-processing.py

TensorMap doesn't have "points" key. It has "positions".
https://github.com/isl-org/Open3D/blob/4f70ff19da8f65380a3835c10cbadb1a01c1b80e/cpp/open3d/t/geometry/TensorMap.h#L43
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3969)

Fix typo of online-processing.py

---

cpp/open3d/io/rpc/MessageUtils.cpp
cpp/open3d/io/rpc/Messages.h
cpp/open3d/io/rpc/RemoteFunctions.cpp
cpp/open3d/io/rpc/RemoteFunctions.h
cpp/pybind/io/rpc.cpp
python/test/io/rpc/test_serialization.py

This PR relaxes some of the sanity checks for the serialization/deserialization to allow geometries that have no primary data like vertices or face indices.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3963)

Allow serialization of partial data

---

cpp/open3d/t/pipelines/CMakeLists.txt
cpp/open3d/t/pipelines/kernel/CMakeLists.txt
cpp/open3d/t/pipelines/kernel/Reduction6x6Impl.cuh
cpp/open3d/t/pipelines/kernel/Registration.cpp
cpp/open3d/t/pipelines/kernel/Registration.h
cpp/open3d/t/pipelines/kernel/RegistrationCPU.cpp
cpp/open3d/t/pipelines/kernel/RegistrationCUDA.cu
cpp/open3d/t/pipelines/kernel/RegistrationImpl.h
cpp/open3d/t/pipelines/registration/Registration.cpp
cpp/open3d/t/pipelines/registration/Registration.h
cpp/open3d/t/pipelines/registration/TransformationEstimation.cpp
cpp/pybind/pipelines/registration/registration.cpp
cpp/pybind/t/pipelines/registration/registration.cpp
cpp/tests/t/pipelines/registration/Registration.cpp
python/test/t/registration/test_registration.py

Changes:
- Renamed `ComputeTransform*` kernel codes, to `Registration*` kernel codes, for consistency with other kernel code naming patterns.
- Added `GetInformationMatrixFromPointClouds` function, kernels, unit-tests, pybinds.
The contribution has been derived from https://github.com/theNded/Open3D/blob/cuda/src/Cuda/Registration/RegistrationCuda.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3987)

Tensor Registration - `GetInformationMatrixFromPointClouds`

---

cpp/open3d/visualization/gui/Window.cpp

Pressing ESC will close both Open3DViewer standalone app and Windows created by O3DVisualizer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3992)

Close window on ESC keypress

---

cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/rendering/filament/PointCloudBuffers.cpp

This can be tested with Open3DViewer viewer using the attached file which consists of a single point. It is a PLY file. Change the extension to `.ply`.
[test_one_point.txt](https://github.com/isl-org/Open3D/files/7050965/test_one_point.txt)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3979)

Fix crash when visualizing single point Point Cloud

---

cpp/open3d/CMakeLists.txt
cpp/open3d/t/geometry/CMakeLists.txt
cpp/open3d/t/pipelines/CMakeLists.txt
cpp/open3d/t/pipelines/kernel/CMakeLists.txt

The `tpipelines_kernel` object library is inconsistently handled:
- It is compiled with `HIDDEN` visibility and its object files are added to the `tpipelines` object library.
- `tpipelines` compiles the kernel source files again without `HIDDEN`visibility.
- Only the non-hidden `tpipelines` object files are considered and the hidden `tpipelines_kernel` are implicitly dropped.
Explicitly adding the object files of `tpipelines_kernel`'s to the Open3D library causes linker errors for `BUILD_SHARED_LIBS=ON `.  The non-hidden version is required since the `TransformationConverter` unit test directly calls some kernel functions. Therefore, drop the `HIDDEN` flag and clean up the inconsistent and duplicate behavior.
This is required for ISPC support in #3996.
--- …

Fix inconsistent kernel object library handling

---

cpp/open3d/core/Dtype.cpp

- Fixed #3990 .
- Fixed strncpy compilation error with GCC 11 on Fedora 34.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3991)

Fixed wrong maximum count character in strncpy.

---

cpp/benchmarks/CMakeLists.txt
cpp/benchmarks/t/io/CMakeLists.txt
cpp/benchmarks/t/io/PointCloudIO.cpp
cpp/open3d/t/io/CMakeLists.txt
cpp/open3d/t/io/PointCloudIO.cpp
cpp/open3d/t/io/PointCloudIO.h
cpp/open3d/t/io/file_format/FilePCD.cpp
cpp/tests/t/io/PointCloudIO.cpp

Added :
- Native Tensor IO support for `.pcd` format. [Read Write in ASCII, BINARY, BINARY_COMPRESSED].
- Various data types are supported.
- Supports custom attributes of shape `{num_points, 1}`.
- Added unit-test and benchmark codes.
-----
```
curvature [shape: {196133, 1}, stride: {1, 1}, Float32]
colors [shape: {196133, 3}, stride: {3, 1}, UInt8]
normals [shape: {196133, 3}, stride: {3, 1}, Float32]
positions [shape: {196133, 3}, stride: {3, 1}, Float32]
```
Format : PCD  | IO  | Legacy | Tensor (v0.13.0) | Tensor
-- | -- | -- | -- | --
ASCII | Write | 217 | 235 | 255
  | Read | 297 | 305 | 317
Binary | Write | 10 | 21.1 | 8.78
  | Read | 31.7 | 38.1 | 40.8
Binary Compressed | Write | 21.1 | 31.7 | 21.0
  | Read | 9.29 | 13.9 | 33.7
---- …

t-IO `PCD` Support

---

cpp/open3d/t/io/file_format/FilePCD.cpp

Merging #3998 before rebasing to master after #3978 got merged caused a conflict where one tensor check is not properly updated to the new API. This causes all CI jobs to fail. Port the offending check to unblock all upcoming users of the master branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4001)

Fix Tensor API check in PCD IO

---

cpp/benchmarks/core/HashMap.cpp
cpp/open3d/core/hashmap/CPU/CreateCPUHashBackend.cpp
cpp/open3d/core/hashmap/CPU/TBBHashBackend.h
cpp/open3d/core/hashmap/CUDA/CUDAHashBackendBufferAccessor.h
cpp/open3d/core/hashmap/CUDA/CreateCUDAHashBackend.cu
cpp/open3d/core/hashmap/CUDA/SlabHashBackend.h
cpp/open3d/core/hashmap/CUDA/SlabHashBackendImpl.h
cpp/open3d/core/hashmap/CUDA/StdGPUHashBackend.h
cpp/open3d/core/hashmap/DeviceHashBackend.h
cpp/open3d/core/hashmap/Dispatch.h
cpp/open3d/core/hashmap/HashBackendBuffer.cpp
cpp/open3d/core/hashmap/HashBackendBuffer.h
cpp/open3d/core/hashmap/HashMap.cpp
cpp/open3d/core/hashmap/HashMap.h
cpp/open3d/core/hashmap/HashSet.cpp
cpp/open3d/core/hashmap/HashSet.h
cpp/open3d/t/geometry/kernel/TSDFVoxelGridImpl.h
cpp/open3d/t/pipelines/slac/ControlGrid.cpp
cpp/pybind/core/hashmap.cpp
cpp/tests/core/HashMap.cpp

- Change Block and BlockHash to MiniVec and MiniVecHash
- Remove duplicate functions in DeviceHashBackends and collect shared code snippets in the HashMap caller
- Dispatch value pointers to vectorize copy of value chunks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/3986)

Refactor HashMap and backends

---

3rdparty/find_dependencies.cmake
CMakeLists.txt

The flag to specify that `-pthread` should be preferred over `-lpthread` is inconsistently used:
- Non-CUDA builds: `THREADS_PREFER_PTHREAD_FLAG` is correctly recognized.
- CUDA build: `THREADS_PREFER_PTHREAD_FLAG` is defined too late since the `CUDAToolkit` package internally calls `find_package(Threads)` before the flag is set.
- `CMAKE_THREAD_PREFER_PTHREAD` is no longer recognized by CMake and can be dropped.
Move the definition of the preference flag before enabling CUDA support. Furthermore, disable `-pthread` since the ISPC compiler has problems with it and throws errors.
Required for #3996.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4004)

Consistently specify pthread preference

---

util/ci_utils.sh

I found that the Docker build (which uses `util/ci_utils.sh`'s `build_pip_conda_package`) continues even if there are errors. 
`set -euo pipefail` let the build stop immediately when the error occurs during `build_pip_conda_package`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4010)

CI utils stop on error

---

.dockerignore
.github/workflows/Dockerfile.ubuntu-cuda
.github/workflows/docker_build.sh
.github/workflows/openblas.yml
.github/workflows/ubuntu-cuda.yml
util/ci_utils.sh

`docker_build.sh` is used to build Open3D docker images for all supported scenarios. This can be used in CI and on local machines. The objective is to allow developers to emulate CI environments for debugging or build release artifacts such as Python wheels locally.
```bash
./docker_build.sh openblas_arm64
./docker_build.sh cuda_wheel_py36_dev
```
- Use a flat list of options.
We don't want to have a cartesian product of different combinations of options. E.g., to support Ubuntu {18.04, 20.04} with Python {3.7, 3.8}, we don't specify the OS and Python version separately, instead, we have a flat list of combinations: [u1804_py37, u1804_py38, u2004_py37, u2004_py38].
- No external environment variables.
This script should not make assumptions on external environment variables. This make the …

Build Docker with scripts

---

cpp/open3d/t/io/file_format/FilePLY.cpp

Changes:
- Faster Read.
- More memory efficient (avoiding memory copy).
```
curvature [shape: {196133, 1}, stride: {1, 1}, Float32]
colors [shape: {196133, 3}, stride: {3, 1}, UInt8]
normals [shape: {196133, 3}, stride: {3, 1}, Float32]
positions [shape: {196133, 3}, stride: {3, 1}, Float32]
```
PLY Read | Legacy | Master | This PR
-- | -- | -- | --
ASCII | 115 | 139 | 121
BIN | 22.2 | 41.0 | 22.8
BIN_COMP. | 22.2 | 41.3 | 22.8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4017)

TIO PLY Read Performance Improvement

---

3rdparty/README.txt
3rdparty/eigen/eigen.cmake

`Eigen 3.4` has been released August 18, 2021. In particular, it includes a fix for building on Windows + CUDA which will resolve the build issues observed [here](https://github.com/isl-org/Open3D/pull/4039/checks?check_run_id=3597186732).
Required for #4039
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4046)

Upgrade Eigen dependency

---

cpp/open3d/ml/pytorch/misc/InvertNeighborsListOpKernel.cpp
cpp/open3d/ml/pytorch/misc/InvertNeighborsListOpKernel.cu
cpp/open3d/ml/pytorch/misc/InvertNeighborsListOps.cpp
cpp/open3d/ml/tensorflow/misc/InvertNeighborsListOpKernel.cpp
cpp/open3d/ml/tensorflow/misc/InvertNeighborsListOpKernel.cu
cpp/open3d/ml/tensorflow/misc/InvertNeighborsListOps.cpp
python/test/ml_ops/test_invert_neighbors_list.py

This PR extends the number of types supported by the InvertNeighborsListOp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4048)

add support for more types to InvertNeighborsListOp

---

cpp/pybind/core/hashmap.cpp
cpp/pybind/core/size_vector.cpp
cpp/pybind/core/tensor.cpp
cpp/pybind/core/tensor_converter.cpp
cpp/pybind/core/tensor_converter.h
python/test/core/test_core.py
python/test/core/test_size_vector.py

Full automatic implicit conversion of `SizeVector` class in Python.
E.g.:
```python
o3d.core.Tensor.ones((3, 4))
t.reshape(o3d.core.SizeVector([12]))
t.reshape(o3d.core.SizeVector([4, 3]))
t.reshape(12)
t.reshape((12))
t.reshape((12,))
t.reshape([12])
t.reshape([12,])
t.reshape((4, 3))
t.reshape([4, 3])
```
This also works for other locations where `SizeVector` is used as input. Updated reduction, tensor creation, hash map/set in this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4045)

SizeVector implict conversion in Pybind

---

cmake/Open3DISPC.cmake
cpp/benchmarks/CMakeLists.txt
cpp/benchmarks/core/CMakeLists.txt
cpp/benchmarks/core/ParallelFor.cpp
cpp/benchmarks/core/ParallelFor.ispc
cpp/open3d/Macro.h
cpp/open3d/core/ParallelFor.h
cpp/open3d/core/ParallelFor.isph
cpp/open3d/utility/Helper.isph
cpp/open3d/utility/ISAInfo.isph
cpp/open3d/utility/Overload.h
cpp/open3d/utility/Preprocessor.h
cpp/tests/CMakeLists.txt
cpp/tests/core/CMakeLists.txt
cpp/tests/core/CoreTest.h
cpp/tests/core/ParallelFor.cpp
cpp/tests/core/ParallelFor.cu
cpp/tests/core/ParallelFor.ispc
cpp/tests/t/geometry/Image.cpp
cpp/tests/utility/CMakeLists.txt
cpp/tests/utility/Helper.cpp
cpp/tests/utility/Helper.ispc
cpp/tests/utility/Preprocessor.cpp

- `ParallelFor` with additional argument to call the vectorized code path. Falls back to other `ParallelFor` if `BUILD_ISPC_MODULE` is `OFF`.
- `OPEN3D_VECTORIZED` and `OPEN3D_TEMPLATE_VECTORIZED` macros to automatically create a lambda function calling the specified ISPC kernel. Only work for up to 9 additional parameters.
- `OPEN3D_EXPORT_VECTORIZED` and `OPEN3D_EXPORT_TEMPLATE_VECTORIZED` macros to define the ISPC kernels to be called by `ParallelFor`. Only work for up to 9 additional parameters.
- `OPEN3D_INSTANTIATE_TEMPLATE` and `OPEN3D_INSTANTIATE_TEMPLATE_WITH_BOOL` macros to emulate template functions and their instantiation in ISPC code.
- Unit tests to cover the introduced functions and macros.
Command: `./bin/benchmarks --benchmark_filter=ParallelFor`
```
[Open3D INFO] …
```

Add vectorized ParallelFor function and helper macros

---

cpp/open3d/visualization/CMakeLists.txt

This PR fixes unresolved symbols when linking to the shared libs without gui module by moving MessageProcessor.cpp to the gui source files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4062)

Fix unresolved symbols with BUILD_SHARED_LIBS=ON and BUILD_GUI=OFF

---

3rdparty/find_dependencies.cmake
CMakeLists.txt

This overwrites the default flags for `Threads::Threads`:
https://github.com/Kitware/CMake/blob/efed2f8706b46d2f5c7711a9426b7e23a08b9709/Modules/FindThreads.cmake#L243-L247
Copy and run this script as to the root Open3D directory (as `Open3D/build_and_rebuild.sh`).
```bash
#!/usr/bin/env bash
set -eu
rm -rf build
mkdir build
rm -f build.log
rm -f rebuild.log
pushd build
cmake -DBUILD_BENCHMARKS=ON -DBUILD_UNIT_TESTS=ON .. &> >(tee -a "../build.log")
make VERBOSE=1 Open3D -j$(nproc) &> >(tee -a "../build.log")
popd
touch CMakeLists.txt
pushd build
make VERBOSE=1 Open3D -j$(nproc) &> >(tee -a "../rebuild.log")
popd
```
- On `master` :
- First build: no `-pthread` flag at all.
- Second build:  `-pthread` added for every file, causing recompilations. `-pthread` is also used in ISPC, causing …

Avoid -pthread flag with ISPC compiler

---

CMakeLists.txt
cmake/Open3DISPC.cmake
cpp/benchmarks/core/CMakeLists.txt
cpp/open3d/utility/CMakeLists.txt
cpp/tests/core/CMakeLists.txt
cpp/tests/utility/CMakeLists.txt

This PR simplifies parts of the logic of the ISPC language emulation module and relaxes some limitations:
- Replace `ISPC_FORCE_LEGACY` with `ISPC_USE_LEGACY_EMULATION` to expose precise control to enable and disable (not support by old option) emulation.
- Move the default condition, i.e. checking for Make and Ninja generators, to the top-level CMake file to a single and consistent place. Furthermore, check for `CMAKE_ISPC_COMPILER_LOADED` to not use emulation if first-class support is already enabled.
- Recursively process the target dependency tree rather than only considering first-level dependenciesto capture (almost) all properties. `PROCESSED_TARGET_LIBRARIES` is used to break potential cyclic dependencies.
- Remove `open3d_ispc_target_sources` macro and process the `SOURCES` …

Simplify ISPC language emulation module

---

cpp/benchmarks/pipelines/registration/Registration.cpp
cpp/benchmarks/t/pipelines/registration/Registration.cpp
cpp/open3d/t/pipelines/registration/Registration.cpp
cpp/open3d/t/pipelines/registration/Registration.h
cpp/pybind/t/pipelines/registration/registration.cpp
cpp/tests/t/pipelines/registration/Registration.cpp
examples/cpp/TICPOdometry.cpp
examples/cpp/TICPReconstruction.cpp
python/test/t/registration/test_registration.py

- renamed `RegistrationICP` to `ICP`, `RegistrationMultiScaleICP` to `MultiScaleICP`, `GetInformationMatrixFromPointClouds` to `GetInformationMatrix`, for `t-pipelines`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4072)

Rename tensor-registration functions

---

cpp/open3d/core/Indexer.cpp
cpp/open3d/core/Indexer.h
cpp/open3d/core/kernel/BinaryEWCPU.cpp
cpp/open3d/core/kernel/UnaryEWCPU.cpp
cpp/tests/core/Indexer.cpp

- Add `IsContiguous()` function to `TensorRef` similar to the one in `Tensor`.
- Add `bool` array of contiguous flags to avoid costly computations in `IsContiguous()` during indexing.
- Add fast indexing path based on the contiguous flags.
- Refactor Binary EW ops to prepare for vectorized code path.
Tested on all Binary and Unary EW Operations with consistent performance improvements of ~10x for tensors with sizes of 100k and 100m entries.
The element size `dtype_byte_size_` could be inferred at compile-time, i.e. by making the indexing functions templates, to emit machine code that runs even faster (~10-30% for initial experiments).
--- …

Add fast path for indexing contiguous tensors

---

cpp/open3d/t/geometry/RaycastingScene.cpp
cpp/open3d/t/geometry/RaycastingScene.h
cpp/pybind/t/geometry/raycasting_scene.cpp
python/test/t/geometry/test_raycasting_scene.py

This PR adds an argument to the functions of RaycastingScene to allow the user to control the number of threads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4100)

Add nthreads argument to RaycastingScene

---

cpp/open3d/core/Indexer.h
cpp/open3d/core/Indexer.isph
cpp/open3d/core/kernel/BinaryEWCPU.cpp
cpp/open3d/core/kernel/BinaryEWCPU.ispc
cpp/open3d/core/kernel/BinaryEWCUDA.cu
cpp/open3d/core/kernel/UnaryEWCPU.cpp
cpp/open3d/core/kernel/UnaryEWCPU.ispc
cpp/open3d/core/kernel/UnaryEWCUDA.cu

- Add template overloads for `GetInputPtr`, `GetOutputPtr`, and `GetWorkloadDataPtr` to directly return the dispatched pointer of type `T`.
- Add the same overloads for the ISPC code path.
- Apply these overloads to all `BinaryEW` and `UnaryEW` ops.
Hitting GitHub's character limits. See all results in the comments below.
- General observations:
- Same performance for scalar code path.
- Consistent improvements for vectorized code path of ~1.25x.
Depends on #4107.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4110)

Add template overloads of Tensor indexing functions

---

python/benchmarks/core/test_binary_ew.py
python/benchmarks/core/test_unary_ew.py
python/benchmarks/open3d_benchmark.py

- Introduce common directory structure for Python benchmarks that matches the C++ structure:
```
cpp
|-- benchmarks
|-- open3d
|-- ...
python
|-- benchmarks <-- This PR
|-- open3d
|-- ...
```
- Add benchmark helper functions in `python/benchmarks/open3d_benchmark.py` similar to helpers in `test`.
- Add benchmarks based on `pytest-benchmark` (which is similar to the C++ `google/benchmark` framework) for `BinaryEW` and `UnaryEW` ops of `Tensor`.
- Also add benchmarks for `numpy` to compare performance with `Tensor`.
Whereas tests are executed using
```
pytest ../python/test
```
(here w.r.t the `build` directory), the benchmarks are executed similarly:
```
pytest ../python/benchmarks --benchmark-sort=name
```
Besides sorting options (for a clearer output), further options to control …

Add Python benchmarks for Tensor's Binary and Unary EW ops

---

cpp/open3d/core/EigenConverter.h
cpp/open3d/core/Tensor.cpp
cpp/open3d/core/Tensor.h
cpp/tests/t/geometry/Image.cpp
cpp/tests/t/geometry/LineSet.cpp
cpp/tests/t/geometry/TriangleMesh.cpp
cpp/tests/t/io/ImageIO.cpp
cpp/tests/t/io/PointCloudIO.cpp

- Removed `Assign` op from Tensor.
- Removed `TensorList.h` header from files not using it.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4134)

Remove `Assign` op from Tensor

---

cpp/open3d/io/file_format/FileASSIMP.cpp
cpp/tests/t/io/TriangleMeshIO.cpp

Issue: https://github.com/isl-org/Open3D/issues/3799
`ASSIMP`: Face normals are shared between all points of a single face, so a single point can have multiple normals, which forces the library to duplicate vertices in some cases.
`aiProcess_JoinIdenticalVertices` Identifies and joins identical vertex data sets within all imported meshes.
- `aiProcessPreset_TargetRealtime_Fast` includes the removed flags.
Refactored unit test: In test `TriangleMeshLegecyCompatibility`, using `cube` instead of `monkey`, because of the following issue:
- Reading `monkey` is fine, Writing `monkey` to a file and then reading in `legacy` and `tensor` is giving a slightly different number of vertices. Suspected reason: While `tensor -> eigen` there might be some precision loss, which leads to some vertices …

Join Identical Vertices [Fixing #3799]

---

python/open3d/ml/tf/python/ops/gradients.py

Moved `trilinear_devoxelize` Op gradient from Open3D-ML to `python/open3d/ml/tf/python/ops/gradients.py`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4214)

Add Gradient for Devoxelize Op

---

CMakeLists.txt
docs/compilation.rst

Fixes #4207
@ssheorey , shall we recommend the `Release` build in the documentation. Or, shall make `Release` build the default build type in CMake (currently `RelWithDebInfo` is the default for single-config generators)? 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4221)

:book: recommends release build type for user

---

cpp/open3d/visualization/visualizer/O3DVisualizer.cpp
cpp/open3d/visualization/visualizer/O3DVisualizer.h
cpp/pybind/visualization/o3dvisualizer.cpp
python/open3d/visualization/draw.py

Prior to this PR you could only change the IBL by using the `O3DVisualizers` user interface. It is now possible to specify the IBL and its intensity as part of the `draw` call:
```
vis.draw(sphere, ibl="photo_studio", ibl_intensity=40000.0)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4190)

Add keywords to draw to allow IBL and its intensity to be set

---

cpp/open3d/visualization/visualizer/O3DVisualizer.cpp
cpp/open3d/visualization/visualizer/O3DVisualizer.h
cpp/pybind/visualization/o3dvisualizer.cpp

* Adds `get_geometry_material` and `modify_geometry_material` to help keep script originated material changes and UI synchronized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4236)

Add higher level interfaces to avoid UI issues

---

cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp
cpp/open3d/pipelines/registration/FastGlobalRegistration.h
cpp/pybind/pipelines/registration/registration.cpp
examples/python/pipelines/global_registration.ipynb
examples/python/reconstruction_system/register_fragments.py

- make FGR API more explicit and parallel the RANSAC registration API by:
- renaming in c++ `FastGlobalRegistration` --> `FastGlobalRegistrationBasedOnFeatureMatching`
- adding c++ `FastGlobalRegistrationBasedOnCorrespondence`, python `registration_fgr_based_on_correspondence`
- rename existing python API to be more explicit: `registration_fast_based_on_feature_matching` --> `registration_fgr_based_on_feature_matching`
- add function documentation in c++
- updates in `global_registration.ipynb` and `examples/python/reconstruction_system/register_fragments.py` for renamed `registration_fgr_based_on_feature_matching`
I felt `registration_fgr_*` was more descriptive than `registration_fast_*`, but happy to revert that change if we don't want to change the API
--- …

expose API for Fast Global Registration given correspondences

---

util/check_style.py

% `flake8 . --count --select=E9,F63,F7,F82,Y --show-source --statistics`
```
./Open3D/util/check_style.py:39:41: YTT204 `sys.version_info.minor` compared to integer (python4), compare `sys.version_info` to tuple
if not (sys.version_info.major == 3 and sys.version_info.minor >= 6):
^
./Open3D/examples/python/t_reconstruction_system/common.py:80:38: F821 undefined name 'depth_folder'
len(depth_file_names), depth_folder, color_folder, extensions))
^
./Open3D/python/open3d/ml/tf/python/ops/gradients.py:294:18: F821 undefined name 'ml_ops'
grad_input = ml_ops.trilinear_devoxelize_grad(grad_out, inds, wgts, r)
^
2     F821 undefined name 'depth_folder'
1     YTT204 `sys.version_info.minor` compared to integer (python4), compare `sys.version_info` to tuple
3
``` …

Fix a compare that would be broken on Python 4

---

examples/python/t_reconstruction_system/common.py

% `flake8 . --count --select=E9,F63,F7,F82,Y --show-source --statistics`
```
./Open3D/util/check_style.py:39:41: YTT204 `sys.version_info.minor` compared to integer (python4), compare `sys.version_info` to tuple
if not (sys.version_info.major == 3 and sys.version_info.minor >= 6):
^
./Open3D/examples/python/t_reconstruction_system/common.py:80:38: F821 undefined name 'depth_folder'
len(depth_file_names), depth_folder, color_folder, extensions))
^
./Open3D/python/open3d/ml/tf/python/ops/gradients.py:294:18: F821 undefined name 'ml_ops'
grad_input = ml_ops.trilinear_devoxelize_grad(grad_out, inds, wgts, r)
^
2     F821 undefined name 'depth_folder'
1     YTT204 `sys.version_info.minor` compared to integer (python4), compare `sys.version_info` to tuple
3
```
--- …

Fix undefined name `depth_folder`

---

cpp/open3d/visualization/rendering/Open3DScene.cpp
cpp/open3d/visualization/visualizer/O3DVisualizer.cpp
cpp/open3d/visualization/visualizer/O3DVisualizer.h
cpp/pybind/visualization/o3dvisualizer.cpp
examples/python/gui/demo-scene.py
python/open3d/visualization/draw.py

Settings for built-in lighting profiles updated to make environment lighting more prominent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4263)

Change IBL/Lighting defaults for O3DVisualizer

---

examples/cpp/Draw.cpp
examples/python/gui/draw.py

* Internal change to default bounding volume color caused unexpected colors in example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4274)

Explicitly set line set/bounding volume color

---

cpp/open3d/visualization/rendering/filament/FilamentGeometryBuffersBuilder.h
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/rendering/filament/LineSetBuffers.cpp
cpp/open3d/visualization/visualizer/O3DVisualizer.cpp
python/open3d/visualization/draw.py

Before line sets render as thin, pixel-width lines. Default view:
Default view with this PR:
Colored, wider lines:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4293)

Support Wide Lines For T Geometry Line Sets

---

cpp/open3d/visualization/rendering/filament/FilamentRenderToBuffer.cpp
cpp/open3d/visualization/rendering/filament/FilamentRenderToBuffer.h
cpp/open3d/visualization/rendering/filament/FilamentScene.cpp
cpp/open3d/visualization/rendering/filament/FilamentScene.h

This PR solves crash when trying to double click in `O3DVisualizer` window when there are objects with "defaultLitSSR" materials.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4291)

Hide refracted materials when rendering to depth image

---

cpp/open3d/visualization/gui/Layout.cpp
cpp/open3d/visualization/gui/Layout.h

Ignore invisible children in Layout1D layouting so that the space is not reserved for those widget and seems to be an empty place. SetNeedsLayout shall be called to make it work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4270)

do not count invisible widiget in Layout1D layouting

---

cpp/open3d/visualization/gui/FileDialog.cpp
cpp/open3d/visualization/gui/FileDialog.h
cpp/pybind/visualization/gui/gui.cpp

add OPEN_DIR besides OPEN and SAVE for FileDialog mode definition to select a directory in cpp as long as python.
Currently OPEN and SAVE mode of FileDialog select a file path like /path/to/file.json, there is no way to select a directory path like /path/to/dir/path. OPEN_DIR mode is used to select an existing directory path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4272)

support FileDialog::Mode::OPEN_DIR for selecting a directory

---

cpp/open3d/core/Tensor.cpp
cpp/open3d/core/Tensor.h
cpp/pybind/core/tensor.cpp
cpp/tests/core/Tensor.cpp
python/test/core/test_core.py

The flatten operation is based on flatten from pytorch, as pytorch and numpy had inconsistent flatten functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4305)

Add flatten operation to Tensor

---

cpp/open3d/visualization/gui/TextEdit.cpp

Sometimes text editor will eat last char while being focused like this:
This is caused by insufficient buffer size passing to `ImGui::InputTextEx`
```
// Edit a string of text
// - buf_size account for the zero-terminator, so a buf_size of 6 can hold "Hello" but not "Hello!".
bool ImGui::InputTextEx(const char* label, const char* hint, char* buf, int buf_size, const ImVec2& size_arg, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, void* callback_user_data)
```
Here TextEditor passes `impl_->text_.capacity()` as `buf_size`. Note that `capacity()` does not necessary contain null-terminal of string. That means if string length is 6, the `capacity()` could be 6, but we need a buffer size including null-terminal char, which should be 7. And because `string.capacity() >= …

fix text editor eats last char sometimes due to insufficient buffer size

---

cpp/open3d/visualization/rendering/Renderer.cpp
cpp/open3d/visualization/rendering/filament/FilamentCamera.cpp

The following script should show almost identical z values both when setting up the camera with intrinsics/extrinsics and with fov/camera pose.
```
vis = o3d.visualization.rendering.OffscreenRenderer(800,600,)
sphere = o3d.geometry.TriangleMesh.create_sphere(create_uv_map=True, radius=1.0)
sphere.compute_vertex_normals()
sphere.paint_uniform_color((0, 1, 0))
mat = o3d.visualization.rendering.MaterialRecord()
mat.shader = 'defaultLit'
vis.scene.add_geometry('mysphere', sphere, mat)
w, h = 800, 600
f = 1000
cx, cy = 400, 300
cam_intrinsics = o3d.camera.PinholeCameraIntrinsic(w,h,f,f,cx,cy)
cam_extrinsics = np.eye(4)
cam_extrinsics[0:3,3] = [0,0,3]
vis.setup_camera(cam_intrinsics, cam_extrinsics)
img = vis.render_to_image() …
```

Setup custom (intrinsic) projection matrix with infinite far plane

---

cpp/open3d/visualization/rendering/Open3DScene.cpp
cpp/open3d/visualization/rendering/Open3DScene.h
cpp/pybind/visualization/rendering/rendering.cpp

this PR exposes SetGeometryTransform, GetGeometryTransform and GeometryIsVisible to the python API which allows us to show animations in the open3d.visualization.gui.SceneWidget
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4366)

made set/get geomety transform available in python

---

cpp/open3d/geometry/PointCloudSegmentation.cpp
cpp/tests/geometry/PointCloud.cpp

Fixes #4409.
As the doc say, ransac_n is the inliers to initial plane.
But in current implement, only 3 point used.
So I make this change, and also passed unit test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4418)

fix issue 4409

---

cpp/apps/CMakeLists.txt

On some macOS systems, the Viewer app may fail to link when `-DBUILD_SHARED_LIBS=ON`.
```bash
cmake -DBUILD_SHARED_LIBS=ON ..
make Open3DViewer -j10
```
```
[100%] Linking CXX executable ../../bin/Open3D.app/Contents/MacOS/Open3D
Undefined symbols for architecture x86_64:
"___CFConstantStringClassReference", referenced from:
CFString in Open3DViewer_mac.mm.o
CFString in Open3DViewer_mac.mm.o
CFString in Open3DViewer_mac.mm.o
CFString in Open3DViewer_mac.mm.o
CFString in Open3DViewer_mac.mm.o
CFString in Open3DViewer_mac.mm.o
CFString in Open3DViewer_mac.mm.o
...
"_OBJC_CLASS_$_NSApplication", referenced from:
objc-class-ref in Open3DViewer_mac.mm.o
"_OBJC_METACLASS_$_NSObject", referenced from:
_OBJC_METACLASS_$_AppDelegate in Open3DViewer_mac.mm.o
"_OBJC_CLASS_$_NSObject", referenced …
```

Viewer app links 3rd-party libraires (with apple frameworks)

---

cpp/open3d/geometry/PointCloud.cpp
cpp/open3d/geometry/PointCloud.h
cpp/open3d/geometry/Qhull.cpp
cpp/open3d/geometry/Qhull.h
cpp/pybind/geometry/pointcloud.cpp
cpp/tests/geometry/PointCloud.cpp

This PR adds an option to `ComputeConvexHull()` to work around degenerate inputs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4447)

Add joggle_inputs option to convex hull functions

---

cpp/open3d/io/file_format/FileJPG.cpp
cpp/open3d/t/geometry/kernel/PointCloudCPU.cpp
cpp/open3d/t/geometry/kernel/PointCloudCUDA.cu
cpp/open3d/t/io/file_format/FileJPG.cpp
cpp/pybind/t/geometry/pointcloud.cpp

Provide projection functionality in python.
```python
import matplotlib.pyplot as plt
import argparse
if __name__ == '__main__':
parser = argparse.ArgumentParser()
parser.add_argument('path')
args = parser.parse_args()
depth = o3d.t.io.read_image(args.path)
intrinsic = o3d.core.Tensor([[535.4, 0, 320.1], [0, 539.2, 247.6],
[0, 0, 1]])
pcd = o3d.t.geometry.PointCloud.create_from_depth_image(depth,
intrinsic,
depth_scale=5000.0,
depth_max=10.0)
o3d.visualization.draw([pcd])
depth_reproj = pcd.project_to_depth_image(640,
480,
intrinsic,
depth_scale=5000.0,
depth_max=10.0)
fig, axs = plt.subplots(1, 2)
axs[0].imshow(np.asarray(depth.to_legacy()))
axs[1].imshow(np.asarray(depth_reproj.to_legacy()))
plt.show()
```
```python
import …
```

Fix 3578 and 4439

---

cpp/open3d/geometry/BoundingVolume.cpp
cpp/open3d/geometry/BoundingVolume.h
cpp/open3d/geometry/Geometry3D.h
cpp/open3d/geometry/LineSet.cpp
cpp/open3d/geometry/LineSet.h
cpp/open3d/geometry/MeshBase.cpp
cpp/open3d/geometry/MeshBase.h
cpp/open3d/geometry/Octree.cpp
cpp/open3d/geometry/Octree.h
cpp/open3d/geometry/PointCloud.cpp
cpp/open3d/geometry/PointCloud.h
cpp/open3d/geometry/VoxelGrid.cpp
cpp/open3d/geometry/VoxelGrid.h
cpp/open3d/visualization/utility/PointCloudPicker.cpp
cpp/open3d/visualization/utility/PointCloudPicker.h
cpp/pybind/geometry/boundingvolume.cpp
cpp/pybind/geometry/geometry.cpp
cpp/pybind/geometry/geometry_trampoline.h
cpp/tests/geometry/PointCloud.cpp

This PR
- adds the `robust` parameter to allow computing the OBB for degenerate cases 
- #2571
- #3916 
- fixes a problem with the rotation matrix of the obb containing a reflection 
- #2206
- #4006
- improves docstrings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4452)

Robust oriented bounding box computation and fixed reflection

---

CMakeLists.txt

For now, we don't release 3.10 wheel since PyTorch/TensorFlow does not support 3.10. 
However, we can still enable the 3.10 build-from-source option for users. 
Fixes #4461
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4463)

Enable Python 3.10 (>= Python 3.6)

---

examples/python/gui/render-to-image.py

The `render-to-image.py` example is supposed to render two images from two different points of view. At some point the second view was accidentally changed so it's identical to the first. This PR restores the example to its original state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4440)

Revert example to its original camera setup

---

cpp/open3d/visualization/rendering/filament/FilamentView.cpp
cpp/open3d/visualization/rendering/filament/FilamentView.h
cpp/pybind/visualization/rendering/rendering.cpp

Addresses #2946 . Allows users to disable post-processing effects that may be detrimental to data visualization.
```
rng = np.random.default_rng()
pts1 = rng.random((10000, 3), dtype=np.float32)
t1 = o3d.core.Tensor(pts1)
pcd1 = o3d.t.geometry.PointCloud(t1)
pcd1.point['colors'] = t1
mat = o3d.visualization.rendering.MaterialRecord()
mat.shader = "defaultUnlit"
mat.point_size = 5
render = o3d.visualization.rendering.OffscreenRenderer(800,600)
render.scene.add_geometry("pcd", pcd1, mat)
render.setup_camera(45.0, [0.5, 0.5, 0.5], [0.5, 2, 0.5], [0, 0, 1])
img = render.render_to_image()
o3d.io.write_image("/tmp/default_render.png", img)
render.scene.view.set_post_processing(False)
img = render.render_to_image() …
```

Add missing pybinds for View class

---

cpp/open3d/visualization/gui/SceneWidget.cpp
cpp/open3d/visualization/rendering/Camera.h
cpp/open3d/visualization/rendering/filament/FilamentCamera.cpp

Addresses issues #4244 and #4382. The documentation indicate that inputs to `Camera::Unproject` and `visualization.rendering.Camera.unproject` expect `x,y` in screen coordinates relative to upper-left of screen but the implementation expected lower-right origin.
The following modified version of the `mouse-and-point-coord.py` demo provided by the authors of both referenced issues can be used to test:
```
import open3d.visualization.rendering as rendering
import os
SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))
class ExampleApp:
def __init__(self, cloud):
app = gui.Application.instance
self.window = app.create_window("Open3D - GetCoord Example", 1024, 768)
self.window.set_on_layout(self._on_layout) …
```

Correct unproject behavior to match documentation

---

3rdparty/assimp/assimp.cmake

On Fedora, the installation directory is `lib64`, so the build will fail.  
Use `${Open3D_INSTALL_LIB_DIR}` to fix the build error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4491)

Fixed build error on Fedora(assimp).

---

3rdparty/curl/curl.cmake

The `libdir` for curl is `${CMAKE_INSTALL_PREFIX}/lib`. This will result in a build error on Fedora.
- https://github.com/curl/curl/blob/d4492b6d125d31ef5c74e4deb6786896606b70cc/CMakeLists.txt#L1504
Change `${Open3D_INSTALL_LIB_DIR}` to `lib`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4495)

Fixed build error on Fedora(curl).

---

CMakeLists.txt
README.md
cmake/Open3DSetGlobalProperties.cmake
cpp/open3d/utility/FileSystem.cpp
cpp/tests/utility/FileSystem.cpp
docs/compilation.rst
docs/getting_started.rst.in

- Allow `DeleteDirectory()` to remove directory with its contents.
- Uses `std::experimental::filesystem`, can be changed to `std::filesystem` after C++17 is enabled.
- Requires macOS 10.15+ (Initial release date: October 7, 2019).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4462)

rm -rf folder, std::experimental::filesystem, macOS 10.15+

---

cpp/open3d/visualization/gui/Application.cpp

If PostToMainThread is called inside Posted, the posted_lock_ will cause a deadlock for mutex multiple locking. To avoid this, we should limit the locking range of posted_lock_ to minimum. Here it protects the moving from posted_ to a local variable(which is thread safe), and release the mutex before any Posted is called.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4448)

avoid deadlock while PostToMainThread is called inside a Posted

---

cpp/open3d/geometry/Qhull.cpp
cpp/tests/geometry/PointCloud.cpp

This PR adds code to fix the orientation of the faces generated by qhull.
This fixes the workflow in #3776
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4508)

make faces generated by ComputeConvexHull oriented

---

cpp/open3d/visualization/gui/CMakeLists.txt
cpp/open3d/visualization/gui/Widget.cpp
cpp/open3d/visualization/gui/Widget.h
cpp/open3d/visualization/gui/WidgetProxy.cpp
cpp/open3d/visualization/gui/WidgetProxy.h
cpp/pybind/visualization/gui/gui.cpp
examples/python/gui/all-widgets.py

This PR is to create WidgetProxy as a widget container of dynamic widgets. If no widget is set, WidgetProxy will be disappeared in GUI.
An relayout is required after setting a new widget.
An example could be found in all-widgets.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4498)

Widget proxy

---

cpp/open3d/geometry/TriangleMesh.cpp

This PR
- adds an AABB test before the actual triangle-triangle intersection test to improve the runtime.
- This speeds up dependent functions `GetVolume()` and `IsWatertight()` as used in #2555  (4.6 sec -> 0.8 sec on i9-7960X)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4525)

Improve speed of TriangleMesh::GetSelfIntersectingTriangles

---

cpp/open3d/data/ExtractZIP.cpp

- Fix for the case, when the compressed file has no parent dir.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4571)

ExtractFromZIP Bug Fix

---

cpp/open3d/visualization/gui/Label3D.cpp
cpp/open3d/visualization/gui/Label3D.h
cpp/open3d/visualization/gui/SceneWidget.cpp
cpp/pybind/visualization/gui/gui.cpp
examples/python/gui/text3d.py

The example `examples/python/gui/text3d.py` has been modified to demonstrate both text color and scale.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4558)

Add support for scaling 3D text

---

cpp/open3d/io/TriangleMeshIO.cpp
cpp/tests/io/TriangleMeshIO.cpp

This PR addresses issue #2632 
Not the whole polygon was searched for ears, which lets the algorithm give up too early on the polygon in #2632.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4609)

fix bug in AddTrianglesByEarClipping where not the whole poly was searched for ears

---

cpp/apps/Open3DViewer/Open3DViewer.cpp
cpp/apps/Open3DViewer/Open3DViewer.h
cpp/open3d/utility/Logging.cpp
cpp/open3d/utility/Logging.h
cpp/open3d/visualization/CMakeLists.txt
cpp/open3d/visualization/app/Viewer.cpp
cpp/open3d/visualization/app/Viewer.h
cpp/pybind/make_python_package.cmake
cpp/pybind/visualization/CMakeLists.txt
cpp/pybind/visualization/app/viewer.cpp
cpp/pybind/visualization/app/viewer.h
cpp/pybind/visualization/visualization.cpp
examples/python/gui/vis-gui.py
python/open3d/visualization/app/__init__.py
python/tools/app.py

Python wrapper for the Open3D Viewer can be used like this:
```python
import open3d.app as app
app.main()
```
or by running 
```python
o3d.visualization.app.run_viewer(args)
```
The second way of running viewer is not meant to be used by the user as `args` should be of the format:
```python
args = ["path/to/open3d_python_installation/app.py", "path/to/mesh_or_ptcloud.file"]
```
Mesh or pointcloud files as arguments to the python wrapper for Open3D Viewer will be made available for the user in the command line interface PR #4594.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4586)

Add pybind for Open3D Viewer

---

3rdparty/openblas/openblas.cmake

Advantages:
- We pass `ExternalProject_CMAKE_ARGS`, such that the cache info can be used by OpenBLAS build. According to my local test, all C compilations are cached. Fortran compilations are not cached, but they compile relatively fast. 
- Potential cross-platform support for Windows (not verified).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4621)

build openblas with cmake instead of gnu make

---

cpp/open3d/visualization/gui/Events.h
cpp/pybind/visualization/gui/events.cpp

Add F1 ~ F12 definition so that it could be processed by python key callbacks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4666)

support F1~F12 keys definitions

---

cpp/open3d/visualization/gui/PickPointsInteractor.cpp

1. remove invalid checking and LogError while picking the last geometry
2. add a safety object in lookup so that invalid index(out of range) could be detected
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4615)

fix bug: terminate while picking points from last geometry

---

cpp/open3d/visualization/gui/SceneWidget.cpp

While points are picked by SceneWidget mouse interactors and reported to UI, their coordinates are based on the frame's topleft. But when SceneWidget draws those lines by imgui, the points coordinates are  based on Window's topleft.
In Mac, it works because menu bar is not integrated by Window, but in other systems the lines are drawn above the correct position because the menu bar height is not considered.
This video shows the problem:
https://user-images.githubusercontent.com/18083216/149350936-4d60972c-385e-47a2-b112-c69ccb73b3b7.mp4
and this video shows what this PR does:
https://user-images.githubusercontent.com/18083216/149351025-f3f43738-f888-4dde-9064-122b5a6bd27f.mp4
--- …

fix selection lines are drawn without offset of frame topleft in SceneWidget on non-Mac system

---

cpp/open3d/core/FunctionTraits.h
cpp/open3d/core/Tensor.h
cpp/open3d/core/nns/FaissIndex.h
cpp/open3d/core/nns/FixedRadiusIndex.h
cpp/open3d/pipelines/registration/GeneralizedICP.h
cpp/tests/core/Tensor.cpp

This simplifies interfacing between T APIs and legacy APIs, as well as between Open3D and other libraries such as OpenCV (e.g.: #2645).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4672)

Tensor wrapper ctor for externally managed data

---

.github/workflows/documentation.yml
.github/workflows/macos.yml
.github/workflows/style.yml
.github/workflows/ubuntu-cuda.yml
.github/workflows/ubuntu-openblas.yml
.github/workflows/ubuntu-wheel.yml
.github/workflows/ubuntu.yml
.github/workflows/webrtc.yml
.github/workflows/windows.yml

- This works on PR
- This shall also work on master, as `github.event.pull_request.number` is undefined, and we'll fall back to `github.ref`
- `github.workflow` is needed since we have multiple workflows PR
Ref:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
https://github.com/TeamAmaze/AmazeFileManager/blob/release/3.7/.github/workflows/android-feature.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4684)

automatically cancel concurrent workflows

---

CHANGELOG.md
cpp/pybind/t/geometry/lineset.cpp
cpp/pybind/t/geometry/pointcloud.cpp
cpp/pybind/t/geometry/trianglemesh.cpp

- The examples in o3d.t.geometry [PointCloud](http://www.open3d.org/docs/release/python_api/open3d.t.geometry.PointCloud.html#open3d.t.geometry.PointCloud), [LineSet](http://www.open3d.org/docs/release/python_api/open3d.t.geometry.LineSet.html#open3d.t.geometry.LineSet), [TriangleMesh](http://www.open3d.org/docs/release/python_api/open3d.t.geometry.TriangleMesh.html#open3d.t.geometry.TriangleMesh) wrote `o3c.core` instead of `o3d.core`.
- Also it seems that in the example in PointCloud the comment seems to suggest:
```python
pcd.point["normals"] = o3d.core.Tensor([[0, 0, 1],
[0, 1, 0],
[1, 0, 0]], dtype, device)
pcd.point["colors"] = o3d.core.Tensor([[0.0, 0.0, 0.0],
[0.1, 0.1, 0.1],
[0.2, 0.2, 0.2]], dtype, device)
```
instead of:
```python
pcd.point["normals"] = o3d.core.Tensor([[0, 0, …
```

Fix sample code in docstring for tensor pc, mesh, & lineset

---

cpp/open3d/visualization/gui/ListView.cpp

while Vert contains too long content and scroll bar is triggered, a ListView child will be drawn in incorrect y position:
https://user-images.githubusercontent.com/18083216/152144815-bae6718d-ee89-41d6-8da2-b927c1c16d17.mov
And this is the correct behavior:
https://user-images.githubusercontent.com/18083216/152144932-1244a362-f6d5-451d-9a9b-d674d6e6de1a.mov
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4686)

fix list view draws in incorrect position while scroll is triggered

---

cpp/open3d/data/Dataset.cpp
cpp/open3d/utility/FileSystem.cpp
cpp/open3d/utility/FileSystem.h

Windows 11 + VS 2019
```
C:\Users\yixing\repo\Open3D\cpp\open3d\data\Dataset.cpp(87,34): error C2039:
'CopyFileA': is not a member of 'open3d::utility::filesystem' [C:\Users\yixin
g\repo\Open3D\build\cpp\open3d\data\data.vcxproj]
C:\Users\yixing\repo\Open3D\cpp\open3d/utility/FileSystem.h(35): message : se
e declaration of 'open3d::utility::filesystem' [C:\Users\yixing\repo\Open3D\b
uild\cpp\open3d\data\data.vcxproj]
C:\Users\yixing\repo\Open3D\cpp\open3d\data\Dataset.cpp(87,42): error C2660:
'CopyFileA': function does not take 2 arguments [C:\Users\yixing\repo\Open3D\
build\cpp\open3d\data\data.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(5546
,1): message : see declaration of 'CopyFileA' [C:\Users\yixing\repo\Open3D\bu …
```

rename CopyFile to Copy to avoid conflict with windows headers

---

3rdparty/eigen/eigen.cmake

Under Windows + CUDA 11, when compiling unit tests, I got this error:
```
...
2.pdb /FS   /MT /GR" -o tests.dir\Release\/core/ParallelFor.cu.obj "C:\Users\yixing\repo\Open3D\cpp\tests\core\ParallelFor.cu"
C:\Users\yixing\repo\Open3D\build\eigen\src\ext_eigen\Eigen\src/Core/util/DisableStupidWarnings.h(77): error #20236-D: pragma "diag_suppress" is deprecated
, use "nv_diag_suppress" instead [C:\Users\yixing\repo\Open3D\build\cpp\tests\tests.vcxproj]
C:\Users\yixing\repo\Open3D\build\eigen\src\ext_eigen\Eigen\src/Core/util/DisableStupidWarnings.h(79): error #20236-D: pragma "diag_suppress" is deprecated
, use "nv_diag_suppress" instead [C:\Users\yixing\repo\Open3D\build\cpp\tests\tests.vcxproj]
```
This was fixed in https://gitlab.com/libeigen/eigen/-/merge_requests/716. Upgrading to the …

upgrade eigen: fix nv_diag error on windows + cuda 11

---

cpp/benchmarks/Main.cpp
cpp/open3d/Open3D.h.in
cpp/open3d/utility/CMakeLists.txt
cpp/open3d/utility/CompilerInfo.cpp
cpp/open3d/utility/CompilerInfo.cu
cpp/open3d/utility/CompilerInfo.h
cpp/tests/core/CUDAUtils.cpp

This is printed every time we run unit tests or benchmarks:
```
make tests -j && ./bin/tests --gtest_filter=""
[Open3D INFO] CompilerInfo: C++14, clang 10.0.0, nvcc 11.6.55.
[Open3D INFO] CPUInfo: 18 cores, 36 threads.
[Open3D INFO] ISAInfo: DISABLED instruction set used in ISPC code.
```
This is needed to verify https://github.com/isl-org/Open3D/pull/4698. In the future, it could also be helpful for detecting DPC++.
BTW, after the Faiss removal, clang-10 + cuda-11 works under ubuntu. This is the first time that we can compile Open3D with Clang and CUDA. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4700)

CompilerInfo to print cxx standard and compiler name/version

---

docs/contribute/contribution_recipes.rst

Fix new tutorial paths.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4705)

Add info about including code examples and Math in doxygen docs

---

cpp/open3d/geometry/SurfaceReconstructionPoisson.cpp
cpp/open3d/geometry/TriangleMesh.h

In relation to issue #3008
Seems like the width parameter ought to be a float.
```
/// \param depth Maximum depth of the tree that will be used for surface
/// reconstruction. Running at depth d corresponds to solving on a grid
/// whose resolution is no larger than 2^d x 2^d x 2^d. Note that since the
/// reconstructor adapts the octree to the sampling density, the specified
/// reconstruction depth is only an upper bound.
/// \param width Specifies the
/// target width of the finest level octree cells. This parameter is ignored
/// if depth is specified.
```
If our point cloud is in 1m units, a target width of less than 1m seems desirable.
Builds for Ubuntu 20.04, testing for our intended use continues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

TriangleMesh::CreateFromPointCloudPoisson width parameter as float

---

cpp/open3d/utility/ISAInfo.cpp

This PR fixes a build failure I ran into after Debian upgraded its libfmt to version 8.1. It should be backwards-compatible with earlier libfmt versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4730)

Fix libfmt 8.x build issue

---

cpp/open3d/visualization/gui/FileDialog.cpp

While select an item in dir tree of FileDialog, the dir tree is not refreshed, which is not the expected behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4717)

fix bug: file dialog not updated after new selection

---

cpp/open3d/visualization/gui/MenuImgui.cpp

ImGui started verifying that widgets have no empty ID by assertion, which triggers when the empty placeholder menu item is drawn:
```
Open3D: imgui.cpp:7793: bool ImGui::ItemAdd(const ImRect&, ImGuiID, const ImRect*, ImGuiItemFlags): Assertion `id != window->ID && "Cannot have an empty ID at the root of a window. If you need an empty label, use ## and read the FAQ about how the ID Stack works!"' failed.
```
This PR works around the problem by drawing a menu item with a single space instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4746)

Fix ImGui assertion about empty IDs on menu draw

---

docs/getting_started.in.rst

Steps:
1. This PR: remove conda from instructions.
2. Tag 0.15. Upload to PyPI as usual.
3. Create a new branch `conda-warning`: print warning message while `import open3d`.
4. Build conda package from the `conda-warning` branch, upload to conda. 
5. Another PR: remove conda CI build and other conda infrastructures from the code base.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4755)

remove conda from getting started instructions

---

cpp/open3d/core/Dispatch.h
cpp/open3d/t/geometry/Image.cpp
cpp/open3d/t/geometry/kernel/Image.cpp
cpp/open3d/t/geometry/kernel/Image.h
cpp/open3d/t/geometry/kernel/ImageImpl.h
cpp/tests/t/geometry/Image.cpp

CUDA support without NPP.
Enables support for all data types and on ARM (no IPP).
Fixes: #4714
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4753)

t::Image::LinearTransform(), To() kernel implementation

---

cpp/open3d/visualization/gui/SceneWidget.cpp

Addresses issue #4662 
To test add the following two lines to line 782 of the `DenseSLAMGUI.cpp` example. This will add a 3D label for each point of the trajectory.
```
Eigen::Vector3f tpos(traj->points_.back().cast<float>());
this->widget3d_->AddLabel(tpos, "traj tex");
```
Without this PR the label will be offset to the left from the rendered trajectory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4775)

Fix 3D text position when SceneWidget is offset from window frame

---

3rdparty/find_dependencies.cmake

This issue was introduced in #4692.
```bash
➜  ~ tree open3d_install/include/open3d/3rdparty/fmt  
open3d_install/include/open3d/3rdparty/fmt
├── chrono.h
├── color.h
├── compile.h
├── core.h
├── format.h
├── format-inl.h
├── locale.h
├── ostream.h
├── posix.h
├── printf.h
├── ranges.h
└── safe-duration-cast.h
0 directories, 12 files
➜  ~ tree open3d_install/lib                        
open3d_install/lib
├── cmake
│   └── Open3D
│       ├── Open3DConfig.cmake
│       ├── Open3DConfigVersion.cmake
│       ├── Open3DTargets.cmake
│       └── Open3DTargets-relwithdebinfo.cmake
└── libOpen3D.so
2 directories, 5 files
```
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4779)

privately link fmt, but propagate its header

---

docs/versions.js

Special release for PyPI Linux only. To get around wheel size limit of 400 MB.
The docs are not updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4815)

bump version to 0.15.2

---

cpp/open3d/visualization/gui/Window.cpp
cpp/open3d/visualization/gui/Window.h
cpp/pybind/visualization/gui/gui.cpp

Alllow callback to intercept Window key event before it is dispatched to focused widget. The similar callback is provided by SceneWidget, but it is not enough. The whole window system must has the capability to capture the key event, and Window would be the better target to deliver it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4734)

add window key interceptor callback

---

cpp/pybind/visualization/gui/events.cpp
cpp/pybind/visualization/gui/gui.cpp

Looks like the KeyEvent was copy/pasted from MouseEvent and the doc string wasn't changed.  I believe I've fixed that issue with this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4819)

Corrected documentation for KeyEvent

---

cpp/open3d/io/file_format/FileASSIMP.cpp
examples/test_data/sword/UV.mtl

The version of ASSIMP we now use added support for a Khronos glTF extension (see [here](https://github.com/KhronosGroup/glTF/pull/1620)) related to quad geometry. This PR makes sure Open3D IO handles the new flag correctly.
Resolves #4821
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4841)

Fix model load regression when loading through ASSIMP

---

cpp/open3d/visualization/rendering/Camera.cpp

Fixes #4831 Can be tested using the the model provided by issue author.
Computation of dynamic far plane implicitly assumed the point cloud is near the origin. If it is sufficiently far from the origin then the point cloud get prematurely/unexpectedly culled out at certain view angles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4842)

Fix Point Clouds Getting Culled Prematurely

---

cpp/open3d/visualization/gui/Window.cpp

fix issue #4843 
once a menu is activated, that area will never be processed by Window's child widget any more. 
Using `ImGui::IsPopupOpen()` instead of `w->Hidden` to judge if popup window is closed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4844)

fix mouse event filter issue in popup menu covered area

---

cpp/open3d/visualization/visualizer/O3DVisualizer.cpp

`O3DVisualizer` was creating an unlit default material for triangle meshes with triangle normals. This PR fixes that so such meshes will show lit with flat shading. The following script can be used to test:
```
sphere = o3d.geometry.TriangleMesh.create_sphere(2.0)
sphere.compute_triangle_normals()
o3d.visualization.draw(sphere)
```
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4867)

Set correct default material for triangle mesh with triangle normals

---

cpp/open3d/visualization/webrtc_server/html/webrtcstreamer.js

mainly used to change center of scene in ROTATE_CAMERA view
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4903)

support double click mouse event in webrtc

---

cmake/Open3DSetGlobalProperties.cmake
cpp/open3d/utility/Parallel.cpp

We observed some minor compilation issues on Windows with OpenMP disabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4914)

Windows build fixups for disabled OpenMP

---

cpp/open3d/geometry/PointCloud.h
cpp/open3d/geometry/PointCloudSegmentation.cpp
cpp/pybind/geometry/pointcloud.cpp
cpp/tests/geometry/PointCloud.cpp

I implement a multi-thread version of `SegmentPlane` function in `PointCloud`. I also compare the time cost with original implementation using the python example `point_cloud_plane_segmentation.py`, and the results are as follow:
cpu info: intel@core i7-1165G7 2.8Gz 8 threads 
point size: 113662
original time cost: 0.95s
multi-thread version: 0.16s
**Update**:
I use this equation: `iter = log(1 - probability) / log(1 - fitness ^ minimal_sample)` to update the number of iteration, such that the best result can be found without taken up to `num_iterations`. Then the time cost is reduced to about 0.03-0.05s.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4863)

Multithread Plane Segmentation

---

cpp/benchmarks/t/geometry/PointCloud.cpp
cpp/open3d/t/geometry/PointCloud.cpp
cpp/open3d/t/geometry/PointCloud.h
cpp/pybind/t/geometry/pointcloud.cpp
cpp/tests/t/geometry/PointCloud.cpp

Python Example:
```python
sample_pcd_data = o3d.data.PCDPointCloud()
tpcd = o3d.t.io.read_point_cloud(sample_pcd_data.path).voxel_down_sample(0.02)
o3d.visualization.draw(tpcd)
tpcd_filtered, indices = tpcd.remove_radius_outliers(nb_points=20, search_radius=0.05)
o3d.visualization.draw(tpcd_filtered)
print(len(tpcd.point["positions"]))
print(len(tpcd_filtered.point["positions"]))
```
Performance Comparision (for `o3d.data.PLYPointCloud`)
```
---------------------------------------------------------------------------------------
Benchmark                                             Time             CPU 
---------------------------------------------------------------------------------------
RemoveRadiusOutliers/CPU[50 | 0.05]                46.5 ms         46.0 ms …
```

Radius Outlier Filter for Tensor PointCloud 

---

cpp/open3d/pipelines/registration/ColoredICP.cpp
cpp/tests/pipelines/registration/ColoredICP.cpp

I made a few changes to improve the readability of the code and make it consistent with the paper: Colored Point Cloud Registration Revisited, ICCV 2017.
Specifically, changes are the following: 
- Rename `is0_proj` to `is_proj`
- Remove the minus sign before `dit.transpose() * M;` for Jacobian and swap `is` and `is_proj` accordingly for residual. (Note that adding/removing a minus sign for Jacobian and residual at the same time will not affect the optimization.) After this change it is now consistent with the math derived in the paper. The gradient derived herein should not include the minus sign, which was confusing to me.
- Rewrite matrix M in its matrix form, which is more concise and readable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

Refactor math for ColoredICP

---

cpp/open3d/pipelines/registration/CorrespondenceChecker.h

Remove incorrect doc comment from CorrespondenceChecker
The initial version of correspondence checker was committed with a requirement that the input point clouds had the same length.  However this ceased to be required when the class was updated to only check correspondence at specified points rather than scanning all points in both inputs.  The docs were never updated with the removal of that requirement, fixing the docs here to reduce confusion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5005)

Remove incorrect doc comment from CorrespondenceChecker

---

3rdparty/openblas/openblas.cmake

Previously there was an issue with openblas paths that caused an error when building openplas from source (which is required on ARM platforms) using `-DUSE_BLAS=ON -DUSE_SYSTEM_BLAS=OFF`:
```
...
-- OPENBLAS_INCLUDE_DIR: /home/[REDACTED]/Open3D/build/openblas/include/openblas/
-- OPENBLAS_LIB_DIR /home/[REDACTED]/Open3D/build/openblas/lib
-- OPENBLAS_LIBRARIES: openblas
...
-- Third-Party Dependencies:
...
--   BLAS .................................... yes (build from source)
...
```
Resulted in this error:
```
make[2]: *** No rule to make target 'openblas/lib/libopenblas.a', needed by 'bin/GLInfo'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target 'openblas/lib/libopenblas.a', needed by 'bin/ConvertPointCloud'.  Stop.
make[2]: *** Waiting for …
```

Updated OpenBLAS to v0.3.20 and fixed build from source.

---

docs/arm.rst
docs/builddocs.rst
docs/compilation.rst
docs/contribute/contribution_recipes.rst
docs/contribute/styleguide.rst
docs/docker.in.rst
docs/getting_started.in.rst
docs/index.rst
docs/make_docs.py
docs/python_api_in/open3d.io.rpc.rst
docs/python_api_in/open3d.ml.tf.layers.rst
docs/python_api_in/open3d.ml.tf.ops.rst
docs/python_api_in/open3d.ml.torch.layers.rst
docs/python_api_in/open3d.ml.torch.ops.rst
docs/python_api_in/open3d.visualization.rst
docs/tutorial/reconstruction_system/capture_your_own_dataset.rst
docs/tutorial/reconstruction_system/integrate_scene.rst
docs/tutorial/reconstruction_system/make_fragments.rst
docs/tutorial/reconstruction_system/refine_registration.rst
docs/tutorial/reconstruction_system/register_fragments.rst
docs/tutorial/reconstruction_system/system_overview.rst
docs/tutorial/sensor/azure_kinect.rst
docs/tutorial/t_reconstruction_system/dense_slam.rst
docs/tutorial/t_reconstruction_system/integration.rst
docs/tutorial/visualization/customized_visualization.rst
docs/tutorial/visualization/headless_rendering.rst
docs/tutorial/visualization/non_blocking_visualization.rst
docs/tutorial/visualization/web_visualizer.rst

This PR:
- Adds `--parallel` option to `make_docs.py`
- Standardizes empty lines in docs:`\n\n\n` -> `\n\n`
Example usage:
```bash
python make_docs.py --parallel --clean_notebooks --execute_notebooks=never --sphinx
```
Merge this PR before merging https://github.com/isl-org/Open3D/pull/4898. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5029)

add `--parallel` option to `make_docs.py`

---

3rdparty/assimp/assimp.cmake

Fixed linking error for Visual Studio 2022 compile.  #4788
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5115)

Bugfix for Visual Studio 2022 compile #4788

---

docs/tutorial/visualization/web_visualizer.rst

I have checked in release [0.15](https://github.com/isl-org/Open3D/tree/ed30e3b61fbe031e106fa64030bec3f698b316b4/examples/python), **gui** folder has already been renamed to **visualization**. But In the documentation, the path to the example file hasn't been updated simultaneously and causing dead link.
For example [this one](http://www.open3d.org/docs/0.15.1/tutorial/visualization/web_visualizer.html#python-server).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5119)

fix: dead link in documentation

---

cpp/open3d/pipelines/odometry/Odometry.cpp
cpp/open3d/pipelines/odometry/OdometryOption.h
cpp/pybind/pipelines/odometry/odometry.cpp
cpp/tests/t/pipelines/slac/SLAC.cpp
docs/jupyter/pipelines/rgbd_odometry.ipynb
docs/tutorial/sensor/realsense.rst
examples/cpp/AzureKinectMKVReader.cpp
examples/cpp/OfflineSLAM.cpp
examples/cpp/RealSenseBagReader.cpp
examples/cpp/SLACIntegrate.cpp
examples/python/open3d_example.py
examples/python/reconstruction_system/color_map_optimization_for_reconstruction_system.py
examples/python/reconstruction_system/config/realsense.json
examples/python/reconstruction_system/config/tutorial.json
examples/python/reconstruction_system/data_loader.py
examples/python/reconstruction_system/initialize_config.py
examples/python/reconstruction_system/make_fragments.py
examples/python/reconstruction_system/optimize_posegraph.py
examples/python/reconstruction_system/slac_integrate.py

1. Change `depth_max` -> `max_depth`.
2. Add `--vis` to control whether to visualize the result.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5167)

Offline SLAM Small Bug Fix

---

cpp/benchmarks/core/HashMap.cpp
cpp/benchmarks/core/ParallelFor.cpp
cpp/benchmarks/t/geometry/PointCloud.cpp
cpp/open3d/core/Tensor.cpp
cpp/open3d/core/Tensor.h
cpp/open3d/core/kernel/IndexGetSetCPU.cpp
cpp/open3d/core/kernel/IndexGetSetCUDA.cu
cpp/open3d/t/geometry/PointCloud.cpp
cpp/open3d/t/geometry/PointCloud.h
cpp/pybind/t/geometry/pointcloud.cpp
cpp/tests/t/geometry/PointCloud.cpp

1. Change SelectPoints -> SelectByMask in tensor based PointCloud.
2. Remove tensor clone inside SelectByMask.
3. Add SelectByIndex (both unit test and pybind) in tensor based PointCloud.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5150)

Add SelectByIndex and improve minor of SelectByMask

---

cpp/open3d/t/geometry/TriangleMesh.cpp
cpp/open3d/t/geometry/TriangleMesh.h
cpp/pybind/t/geometry/trianglemesh.cpp
python/test/t/geometry/test_trianglemesh.py

This PR adds a new function for quadric decimation to the tensor TriangleMesh.
The function does not produce duplicate vertices for the mesh described here #2581 and does not produce the hole in #4083 .
Note that the function arguments are different from the legacy function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5199)

add SimplifyQuadricDecimation to tensor TriangleMesh

---

cpp/open3d/t/geometry/TriangleMesh.cpp
cpp/open3d/t/geometry/TriangleMesh.h
cpp/pybind/t/geometry/trianglemesh.cpp
python/test/t/geometry/test_trianglemesh.py

This PR adds 3 new functions to t::geometry::TriangleMesh for computing the boolean union, intersection, and difference
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5257)

add boolean mesh operations to Tensor TriangleMesh

---

cpp/open3d/t/geometry/TriangleMesh.cpp
cpp/open3d/t/geometry/TriangleMesh.h
cpp/pybind/t/geometry/trianglemesh.cpp
python/test/t/geometry/test_trianglemesh.py

This PR adds a wrapper for the FillHoles filter from vtk to the Tensor TriangleMesh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5285)

Add FillHoles() to Tensor TriangleMesh

---

docs/jupyter/visualization/visualization.ipynb

Fix documentation typo in geometry primitives section, which related to issue #5322.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5323)

fix doc typo 

---

3rdparty/find_dependencies.cmake
docker/Dockerfile.openblas
docker/docker_build.sh
docs/arm.rst
python/requirements.txt
util/install_deps_ubuntu.sh

Ubuntu 22.04 does not have `clang-7` in the default repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5302)

fix ubuntu 22.04 dependency installation

---

cpp/open3d/t/geometry/PointCloud.h
cpp/open3d/t/geometry/TensorMap.h
cpp/open3d/t/geometry/TriangleMesh.cpp
cpp/open3d/t/geometry/TriangleMesh.h
cpp/open3d/t/geometry/VtkUtils.cpp
cpp/open3d/t/geometry/VtkUtils.h
cpp/tests/t/geometry/VtkUtils.cpp

This PR
- enables attributes in vtk wrapper functions allowing to preserve (interpolate) vertex and triangle attributes
- fixes a segfault when converting empty vtkPolyData to a TriangleMesh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5347)

Enable attributes in vtk wrapper functions

---

CHANGELOG.md
cpp/open3d/t/geometry/RaycastingScene.cpp
cpp/open3d/t/geometry/RaycastingScene.h
cpp/pybind/t/geometry/raycasting_scene.cpp

This PR adds an argument to the constructor of RaycastingScene to allow the user to control the number of threads that are used for building a RaycastingScene. It completes the intention of PR #4100, where the user was enabled to control the number of threads for doing computations in a RaycastingScene.
Currently all hardware threads are used for building a RaycastingScene, since a `RTCDevice` is created using this: `rtcNewDevice(NULL)`. This is unwanted behavior and can lead to problems, e.g. if many cores are present (>=16), and the scene is not huge, using all hardware threads results actually in a slowdown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5384)

Fix raycasting scene: Allow setting of number of threads that are used for building a raycasting scene

---

CHANGELOG.md
cpp/pybind/core/cuda_utils.cpp
cpp/pybind/t/geometry/voxel_block_grid.cpp

Hi!
I was having some trouble with these bindings, which had the helptext and argument definitions accidentally combined.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5425)

(minor) Fix Python bindings for CUDA device synchronization, voxel grid save

---

cpp/open3d/visualization/utility/SelectionPolygonVolume.cpp
cpp/open3d/visualization/utility/SelectionPolygonVolume.h
cpp/pybind/visualization/utility.cpp

Following issue created at https://github.com/isl-org/Open3D/issues/3713, in some circumstance it would be really great to have the indices of the cropped point clouds in SelectionVolume.CropInPolygon() function, for example, when the point cloud size is very large, and it's expensive to make a copy of the cropped point clouds. 
This PR proposes to make the SelectionVolume.CropInPolygon() a public method, which directly returns the indices for the cropped point cloud. Python bindings function is added to make it callable from python.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5354)

Make SelectPolygonVolume.CropInPolygon return indices

---

cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp

The following script should visualize a box with random colors on it:
```
tex = np.random.rand(128,128,3).astype(np.float32)
box = o3d.geometry.TriangleMesh.create_box(create_uv_map=True)
box = o3d.t.geometry.TriangleMesh.from_legacy(box)
box.material.set_default_properties()
box.material.texture_maps['albedo'] = o3d.t.geometry.Image(tex)
o3d.visualization.draw([box])
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5438)

Fix floating point texture usage

---

cpp/open3d/core/Dispatch.h

Using `DISPATCH_XXX` in external project will result  in the following issue:
This can be fixed by adding `open3d` namespcae before `utility`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5490)

Fix issue when using Dispatch in external project

---

cpp/open3d/t/geometry/LineSet.cpp
cpp/open3d/t/geometry/PointCloud.cpp
cpp/open3d/t/geometry/TriangleMesh.cpp
cpp/tests/t/geometry/PointCloud.cpp
cpp/tests/t/geometry/TriangleMesh.cpp

- Always return the long description that includes attributes for Tensor PointCloud and TriangleMesh to make debugging easier.
- Fix wrong counts if there are only vertices or triangles
- Fix exception if there is an attribute but no primary key
```python
mesh = o3d.t.geometry.TriangleMesh()
mesh.vertex.positions = np.random.rand(123,3)
print(mesh, '\n')
mesh = o3d.t.geometry.TriangleMesh(np.random.rand(10,3), np.random.randint(0,10, size=(8,3)))
print(mesh, '\n')
mesh = o3d.t.geometry.TriangleMesh()
mesh.vertex.positions = np.random.rand(123,3)
mesh.triangle.bla = np.random.rand(12,3,4)
print(mesh, '\n')
```
Before
```
TriangleMesh on CPU:0 [1 vertices and 0 triangles].
TriangleMesh on CPU:0 [10 vertices (Float64) and 8 triangles (Int64)].
Vertex …
```

Always return long description in ToString() for t.geometry classes

---

python/requirements.txt

`nbformat` `5.6.0` was released on Sept 21, 2022, and it has a bug of reporting the version to be `0.0.0`. `nbformat` is required by `dash`.
```
➜  pip install nbformat==5.6.0
➜  python -c "import nbformat; print(nbformat.__version__)"
0.0.0
➜  pip install nbformat==5.5.0
➜  python -c "import nbformat; print(nbformat.__version__)"
5.5.0
```
Master CI is failing due to the following reason:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5544)

add nbformat==5.5.0 as global deps

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5614)
3.10 wheels are included for 0.16.0:
- https://pypi.org/project/open3d/0.16.0/#files

Document support for Python 3.10 wheels

---

3rdparty/find_dependencies.cmake
3rdparty/imgui/imgui.cmake
cpp/open3d/visualization/gui/Layout.cpp
cpp/open3d/visualization/gui/Window.cpp

Open3D is mostly compatible with the latest ImGui release, except for a very small change.
**EDIT**: *two* small changes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5644)

Update imgui to latest version

---

3rdparty/assimp/assimp.cmake

Fixes two issues:
1. MacOS 13.0 SDK deprecates `vsprintf` and `sprintf` which causes warnings/errors building ASSIMP. This PR pulls a version of ASSIMP that uses the recommended `vsnprintf` and `snprintf` alternatives.
2. Changes glTF importer to use normal flow control instead of exceptions for flow control. On Apple Silicon the exception was not being caught starting with `clang` 14.0 and loading glTF 2.0 models always caused a crash.
Note: No ASSIMP release currently incorporates these two changes therefore this PR clones a specific commit. Once ASSIMP produces a stable release incorporating these changes a new PR will be necessary to reference the release.
- - - …

Fix Mac build issue with ASSIMP

---

.github/workflows/macos.yml

In Github actions macOS runner, libomp is installed with brew, but not linked. cmake does not find it, though clang is able to find and use it when building. The PR #5663 set WITH_OPENMP=OFF if cmake is not able to find OpenMP, and hence macOS is built without OpenMP on Github. This PR links libomp, so that both cmake and clang can find it.
GHA run with this branch: 
https://github.com/isl-org/Open3D/actions/runs/3430223624/jobs/5716910302#step:6:12210
libomp location: 
https://github.com/isl-org/Open3D/actions/runs/3430223624/jobs/5716910302#step:6:12210
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5668)

Github Actions: link libomp so that cmake finds it

---

3rdparty/filament/filament_build.cmake

System info:
```bash
(open3d) ➜  ~/repo/Open3D/build (master) clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
(open3d) ➜  ~/repo/Open3D/build (master) pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 14.1.0.0.1.1666437224
volume: /
location: /
install-time: 1667393287
groups: com.apple.FindSystemFiles.pkg-group 
(open3d) ➜  ~/repo/Open3D/build (master) sw_vers
ProductName:            macOS
ProductVersion:         13.0
BuildVersion:           22A380
```
Fixes the following error on M1 Macs:
```bash
In file included from …
```

ignore filament compilation warning (macos)

---

cpp/open3d/t/io/file_format/FileASSIMP.cpp

Adds loading of colors and uvs when using tgeometry IO function `read_triangle_mesh` with file types loaded by ASSIMP (obj, stl, off, gltf/glb, fbx). Test with following script:
```
dataset = o3d.data.MonkeyModel()
mesh = o3d.t.io.read_triangle_mesh(dataset.path)
mesh.material.material_name = 'defaultLit'
mesh.material.texture_maps['albedo'] = o3d.t.io.read_image(dataset.path_map['albedo'])
print(mesh)
o3d.visualization.draw(mesh)
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5632)

Add loading colors and uvs in tgeometry TriangleMesh IO

---

cpp/pybind/t/geometry/boundingvolume.cpp
cpp/pybind/t/geometry/image.cpp
cpp/pybind/t/geometry/lineset.cpp
cpp/pybind/t/geometry/pointcloud.cpp
cpp/pybind/t/geometry/trianglemesh.cpp

Use case:
```python
import copy
Class Foo:
def __init__(self, name='foo', pcd=None):
self.name = name
self.pcd = pcd
a = Foo('test', pcd=o3d.t.geometry.PointCloud())
b = copy.deepcopy(b)
```
Error will occur if no adding `bind_copy_functions` in pybind:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5709)

Enable python copy&deepcopy for tensor geometry

---

python/tools/cli.py

```$ open3d draw_web -h
***************************************************
* Open3D: A Modern Library for 3D Data Processing *
*                                                 *
* Version 0.16.0+7862ccd51                        *
* Docs    http://www.open3d.org/docs              *
* Code    https://github.com/isl-org/Open3D       *
***************************************************
usage: open3d draw_web [--bind_all] [-h] [filename]
Load and visualize a 3D model in a browser with WebRTC. Optionally, you can
customize the serving IP address and port with WEBRTC_IP and WEBRTC_PORT
environment variables. Example usage:
open3d draw_web path/to/model_file            # Visualize at http://localhost:8888
open3d draw_web --bind_all path/to/model_file # Serve to the entire local network …
```

Add draw_web to CLI for remote visualization.

---

CHANGELOG.md
cpp/open3d/pipelines/odometry/Odometry.cpp
cpp/open3d/pipelines/odometry/Odometry.h
cpp/pybind/pipelines/odometry/odometry.cpp

The use case for this is to be better able to tune the various odometery options as well as integrate the cost function(s) into different minimization frameworks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5611)

Added additional python bindings for RGBD odometry functionality

---

cpp/open3d/t/geometry/RaycastingScene.cpp
cpp/open3d/t/geometry/RaycastingScene.h
cpp/pybind/t/geometry/raycasting_scene.cpp
python/test/t/geometry/test_raycasting_scene.py

This PR addresses #5669
Functions like ComputeOccupancy and ComputeSignedDistance have a new argument `samples` for using multiple rays to determine the inside/outside.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5797)

add voting and ray jitter to compute the inside outside

---

cpp/open3d/t/pipelines/kernel/RGBDOdometry.cpp
cpp/open3d/t/pipelines/kernel/RGBDOdometry.h
cpp/open3d/t/pipelines/kernel/RGBDOdometryCPU.cpp
cpp/open3d/t/pipelines/kernel/RGBDOdometryCUDA.cu
cpp/open3d/t/pipelines/kernel/RGBDOdometryImpl.h
cpp/open3d/t/pipelines/kernel/RGBDOdometryJacobianImpl.h
cpp/open3d/t/pipelines/odometry/RGBDOdometry.cpp
cpp/open3d/t/pipelines/odometry/RGBDOdometry.h
cpp/pybind/t/pipelines/odometry/odometry.cpp
examples/python/t_reconstruction_system/config.py
examples/python/t_reconstruction_system/default_config.yml
examples/python/t_reconstruction_system/integrate.py
examples/python/t_reconstruction_system/pose_graph_optim.py
examples/python/t_reconstruction_system/ray_casting.py
examples/python/t_reconstruction_system/rgbd_odometry.py
examples/python/t_reconstruction_system/run_system.py
examples/python/t_reconstruction_system/split_fragments.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5181)
This PR implements 
- Information matrix computation for RGB-D odometry
- Easier-to-use pose graph wrapper in t-reconstruction system
- Explicit Long sequence splitter (into fragments)
- Module: RGB-D odometry, pose graph construction, and optimization
- Module: RGB-D integration
For the copyroom scene (5490 frames), on RTX 3060 & i7-11700 @ 2.5Hz
- Pose graph generation and optimization takes 107.961s for 55 fragments. (~ avg 50 FPS)
- TSDF integration takes 47.590s for 55 fragments. (~ avg 120 FPS)
- Example fragments:
To run the system, call
```
python examples/python/t_reconstruction_system/run_system.py …
```

Tensor reconstruction system upgrade: make fragments

---

3rdparty/find_dependencies.cmake
cpp/open3d/core/hashmap/CUDA/CUDAHashBackendBuffer.cu

Fix #5827.
Fix the build error below.
1. error: namespace "thrust" has no member "device"
2. *** No rule to make target '/usr/local/cuda/lib64/liblapack_static.a'
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5833)

Support CUDA 12.0 build.

---

cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp

the `FastGlobalRegisrationBasedOnCorrespondence` function from https://github.com/isl-org/Open3D/pull/4188 has a bug in it (does not affect the original `FastGlobalRegistrationBasedOnFeatureMatching`)
the check on if `source` or `target` has more points (which was copied from `FastGlobalRegistrationBasedOnFeatureMatching`)  is useful so that the smaller set of points is used as the query in `InitialMatching`. This check was copied into the new `FastGlobalRegisrationBasedOnCorrespondence` function, but does not use `InitialMatching` -- i.e., the initial matches come from  the user. In this case, it does not make sense to swap the source/target based on number of points and in fact by swapping them but not swapping the "columns" of `corresvec` results in incorrect initial matches.
---
This …

fix call to AdvancedMatching in FGR

---

cpp/open3d/geometry/VoxelGridFactory.cpp

The box_center calculation was wrong. it gave the corner of a voxel, instead of the center of the box. shifting by half box  size should fix it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/5759)

fixed a bug in CreateFromTriangleMeshWithinBounds

---

cpp/open3d/geometry/BoundingVolume.cpp
cpp/open3d/geometry/BoundingVolume.h
cpp/open3d/geometry/Geometry3D.h
cpp/open3d/geometry/LineSet.cpp
cpp/open3d/geometry/LineSet.h
cpp/open3d/geometry/MeshBase.cpp
cpp/open3d/geometry/MeshBase.h
cpp/open3d/geometry/Octree.cpp
cpp/open3d/geometry/Octree.h
cpp/open3d/geometry/PointCloud.cpp
cpp/open3d/geometry/PointCloud.h
cpp/open3d/geometry/VoxelGrid.cpp
cpp/open3d/geometry/VoxelGrid.h
cpp/open3d/visualization/utility/PointCloudPicker.cpp
cpp/open3d/visualization/utility/PointCloudPicker.h
cpp/pybind/geometry/geometry.cpp
cpp/pybind/geometry/geometry_trampoline.h
cpp/tests/geometry/PointCloud.cpp

Introduced new function that calculates the minimal bounding box for a given point cloud. So far, only the minimal axis aligned and the object-oriented bounding box are implemented.
I have created a feature request here: [https://github.com/isl-org/Open3D/issues/5856](https://github.com/isl-org/Open3D/issues/5856).
I used the same algorithm as the library 'compas' [https://github.com/compas-dev/compas/blob/main/src/compas/geometry/bbox/bbox_numpy.py](https://github.com/compas-dev/compas/blob/main/src/compas/geometry/bbox/bbox_numpy.py)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/Open3D/5857)

New feature: minimal bounding box for a given point cloud

---

cpp/pybind/t/geometry/image.cpp
python/test/t/geometry/test_image.py

Added Python unit test for t.image.to/linear_transform
Fixes #5830
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/Open3D/5873)

Fix issue 5830 (pybind Image::To argument order)

---

python/open3d/visualization/tensorboard_plugin/util.py

Prevent slow loading when a lot of non-3D data is present.
-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #4787
In the case that tensorboard logdir has a lot of data, the Open3D plugin currently parses all the data to check for any 3D data to display. This can slow down tensorboard start to an hour, especially on Windows.
to my code.
updated …

Fast check for 3D tensorboard data

---

.github/workflows/README.md
.github/workflows/clean-gcloud-profiles.yml
.github/workflows/documentation.yml
.github/workflows/gcs.lifecycle.json
.github/workflows/macos.yml
.github/workflows/style.yml
.github/workflows/ubuntu-cuda.yml
.github/workflows/ubuntu-openblas.yml
.github/workflows/ubuntu-sycl.yml
.github/workflows/ubuntu-wheel.yml
.github/workflows/ubuntu.yml
.github/workflows/vtk_packages.yml
.github/workflows/webrtc.yml
.github/workflows/windows.yml

Prevent deprecation warnings that will turn into errors later.
**Future**: Github cache allowance is now 10GB (up from 5GB earlier). We can add caching to Windows builds, but cmake + ccache doesn't work with msbuild, ninja is needed.
- Github actions: Checkout, cache, setup python
- Others: Gcloud SDK, Windows SDK version.
- Update OS: ubuntu-latest for docker and aux (e.g. artifact upload) actions, oldest supported for others.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/Open3D/5890)

Update github actions CI workflow versions

---

cpp/open3d/visualization/gui/TextEdit.cpp

As discussed in #5095, the `TextEdit` control is moving into the opposite direction when added to a scrollable widget. This is due the addition of the `ImGui::GetScrollY()` value, instead of the subtraction as any other widget ([gui/NumberEdit.cpp](https://github.com/isl-org/Open3D/blob/ad1c3ade70dc52e7972db85670ff07a9bb31d2e2/cpp/open3d/visualization/gui/NumberEdit.cpp#L138-L139), [gui/Label.cpp](https://github.com/isl-org/Open3D/blob/ad1c3ade70dc52e7972db85670ff07a9bb31d2e2/cpp/open3d/visualization/gui/Label.cpp#L136-L137)).
This behaviour was added with the following commit: https://github.com/isl-org/Open3D/commit/14363b9f3f19f0550db94a92963e17e7c67e75a9
-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #5095
-   [ ] New feature (non-breaking change which adds …

Fix scrolling direction bug for TextEdit

---

cpp/open3d/visualization/visualizer/O3DVisualizer.cpp

Add ability to select points from a `TriangleMeshModel` in O3D Visualizer (e.g., draw.py). Previously, attempting to do so caused a crash with a cryptic message.
The following script demonstrates the new capability:
```py
monkey = o3d.data.MonkeyModel()
m = o3d.io.read_triangle_model(monkey.path)
o3d.visualization.draw(m, show_ui=True, actions=[["Print selection", lambda o3dvis: print(o3dvis.get_selection_sets())]])
```
Output:
```py
[Open3D WARNING] Geometry Object 1 has already been added to scene graph.
[{'Object 1': {{ index: 47335, order: 5, point: (5.42036, -0.955666, -2.12278) }, { index: 49813, order: 3, point: (-1.15616, -0.0953989, -1.86053) }, { index: 53731, order: 4, point: (-0.625896, -0.964231, -6.8371) }, { index: 40037, order: 1, point: (-4.25987, …
```

Enable picking points from TriangleMeshModels in O3D Visualizer

---

docs/docker.in.rst
docs/tutorial/visualization/cpu_rendering.rst
docs/versions.js
examples/python/visualization/mitsuba_material_estimation.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/Open3D/5991)

Add new Mitsuba Python example + update CPU rendering docs

---

cpp/open3d/t/io/TriangleMeshIO.cpp
cpp/open3d/t/io/TriangleMeshIO.h
cpp/tests/t/io/TriangleMeshIO.cpp

The following script tests the basic functionality:
```
d = o3d.data.MonkeyModel()
mesh = o3d.t.io.read_triangle_mesh(d.path)
print(mesh)
o3d.visualization.draw(mesh)
o3d.t.io.write_triangle_mesh('monkey.npz', mesh)
mesh_npz = o3d.t.io.read_triangle_mesh('monkey.npz')
print(mesh_npz)
o3d.visualization.draw(mesh_npz)
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/Open3D/6019)

Add IO for NPZ files for Tensor-based TriangleMeshes

---

CHANGELOG.md
docs/tutorial/visualization/customized_visualization.rst

Fixes the start and end point of code snippets in the identified documentation
-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6077 
The current code snippets are displayed incorrectly
to my code.
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.
This PR brings tutorial code snippets back in-sync with latest …

Bring tutorial code snippets in-sync with latest source #6077

---

cpp/pybind/CMakeLists.txt

GCC runs LTO on a single core by default, making the final build step for the Python module needlessly long.
to my code.
-   [x] I will follow up …

Enable multi-core link time optimization

---

cpp/open3d/ml/tensorflow/continuous_conv/ContinuousConvBackpropFilterOps.cpp
cpp/open3d/ml/tensorflow/continuous_conv/ContinuousConvOps.cpp
cpp/open3d/ml/tensorflow/continuous_conv/ContinuousConvTransposeBackpropFilterOps.cpp
cpp/open3d/ml/tensorflow/continuous_conv/ContinuousConvTransposeOps.cpp
cpp/open3d/ml/tensorflow/misc/BuildSpatialHashTableOps.cpp
cpp/open3d/ml/tensorflow/misc/FixedRadiusSearchOps.cpp
cpp/open3d/ml/tensorflow/misc/InvertNeighborsListOps.cpp
cpp/open3d/ml/tensorflow/misc/KnnSearchOps.cpp
cpp/open3d/ml/tensorflow/misc/NmsOps.cpp
cpp/open3d/ml/tensorflow/misc/RadiusSearchOps.cpp
cpp/open3d/ml/tensorflow/misc/ReduceSubarraysSumOps.cpp
cpp/open3d/ml/tensorflow/misc/VoxelPoolingOps.cpp
cpp/open3d/ml/tensorflow/misc/VoxelizeOps.cpp
cpp/open3d/ml/tensorflow/pointnet/BallQueryOps.cpp
cpp/open3d/ml/tensorflow/pointnet/InterpolateOps.cpp
cpp/open3d/ml/tensorflow/pointnet/RoiPoolOps.cpp
cpp/open3d/ml/tensorflow/pointnet/SamplingOps.cpp
cpp/open3d/ml/tensorflow/pvcnn/TrilinearDevoxelizeOps.cpp
cpp/open3d/ml/tensorflow/sparse_conv/SparseConvBackpropFilterOps.cpp
cpp/open3d/ml/tensorflow/sparse_conv/SparseConvOps.cpp
cpp/open3d/ml/tensorflow/sparse_conv/SparseConvTransposeBackpropFilterOps.cpp
cpp/open3d/ml/tensorflow/sparse_conv/SparseConvTransposeOps.cpp
cpp/open3d/ml/tensorflow/tf_subsampling/tf_batch_subsampling.cpp
cpp/open3d/ml/tensorflow/tf_subsampling/tf_subsampling.cpp
cpp/open3d/t/geometry/TensorMap.cpp

In TensorFlow 2.11 and later, `tsensorflow::Status::OK()` has been removed.
This causes build errors.
Changing to `tensorflow::Status()` will maintain compatibility with previous versions and fix build errors.
to my code.
-   [ ] I have added or updated C++ and / or Python …

Changed usage of TensorFlow Status API

---

cpp/open3d/visualization/visualizer/Visualizer.h
cpp/pybind/visualization/visualizer.cpp

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6009 
Resolves the issue reported in #6009  that `Visualizer.get_view_control()` is expected to return a reference but it actually returns a copy, this problem does not exist in older versions of Open3D.
to my code.
-   [ ] I have added or updated C++ and / or Python **unit …

Fix the pybind reference bug of get_view_control()

---

cpp/open3d/visualization/gui/Font.h
cpp/open3d/visualization/gui/Util.h

-   [x] Bug fix (non-breaking change which fixes an issue)
Building with gcc 13 exposed the usage of cstdint types without explicitly including them first.
to my code.
-   [x] I will follow up and update the code …

Fix build with gcc-13

---

cpp/apps/OfflineReconstruction/LegacyReconstructionUtil.h

Fix issue #6213.
to my code.
-   [ ] For fork PRs, I have selected **Allow edits from …

Fix typo in reconstruction c++ app

---

python/requirements.txt

the `nbformat` is the only hard pin dependency which is a bit strange (I don't see a reason, but there is pls correct me), which makes a third to find an intersection with other packages
also one of the reasons in the past for pin was resolved already in 5.6.1, see: https://github.com/jupyter/nbformat/issues/306#issuecomment-1271705253
to my code.
-   [ ] Both C++ (Doxygen) and …

relax nbformat

---

cpp/open3d/geometry/ISSKeypoints.cpp

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #4847
During my usage of the ISS Keypoint functionality I encountered some random crashes, which I tried to find the reason for. I explained it here: https://github.com/isl-org/Open3D/issues/4847#issuecomment-1508390527
Secondly there seems to be a more subtile issue in ``ComputeModelResolution``, as the original code only checks for "more than 0" neighbors, but as the query point itself will always be present, this condition will never fail. I adjusted the condition here to ``>= 2``.
Eventually I applied some std algorithms instead …

Fix and improve ISS keypoint

---

CHANGELOG.md
docs/tutorial/t_reconstruction_system/integration.rst
examples/python/t_reconstruction_system/config.py
examples/python/t_reconstruction_system/default_config.yml
examples/python/t_reconstruction_system/integrate.py
examples/python/t_reconstruction_system/run_system.py

The `integrate.py`  in `examples/python/t_reconstruction` did not work. I am using open3d v0.17.0 with python 3.10.10 on ubuntu 22.04.
1. ~~`store_true` no longer works, see [here](https://github.com/isl-org/Open3D/blob/master/examples/python/t_reconstruction_system/integrate.py#L86). ~~ MY BAD - This is not a bug.
2. Config file has `integration_mode` which can be removed in favor of `integrate_color` which is IMO easy to understand.
3. Documentation is no longer synced - …

Fix tensor reconstruction example

---

util/ci_utils.sh

Ubuntu wheel CI is failing due to lack of disk space.
to my code.
-   [ ] For fork PRs, …

Increase Ubuntu wheel CI build space.

---

cpp/open3d/visualization/visualizer/Visualizer.h
cpp/open3d/visualization/visualizer/VisualizerRender.cpp
cpp/pybind/visualization/visualizer.cpp

This PR allows setting view status from a json string. This allows setting the visualizer to the exact same view points.
Example usage:
1. Launch the Open3D visualizer (legacy)
2. Press ctrl+c to copy the view status as a json string
3. As an example, in a new visualizer, you can use the following code to set the view status
```python
vis = o3d.visualization.Visualizer()
vis.create_window()
vis.add_geometry(mesh)
vis.update_geometry(mesh)
vis.set_view_status(view_status_str)  # view_status_str is the json string
vis.poll_events()
vis.update_renderer()
buffer = vis.capture_screen_float_buffer()
vis.destroy_window()
```
Changes:
- `Visualizer::CopyViewStatusToClipboard()`: unchanged
- `Visualizer::CopyViewStatusFromClipboard()`: unchanged
- `Visualizer::GetViewStatus()`: added
- …

Allow setting view status from json string

---

cpp/open3d/visualization/webrtc_server/PeerConnectionManager.cpp
cpp/open3d/visualization/webrtc_server/PeerConnectionManager.h
cpp/open3d/visualization/webrtc_server/WebRTCWindowSystem.cpp
cpp/pybind/make_install_pip_package.cmake
python/js/amd-public-path.js
python/js/lib/embed.js
python/js/lib/extension.js
python/js/lib/labplugin.js
python/js/lib/web_visualizer.js
python/js/package.json
python/js/webpack.config.js
python/pyproject.toml
python/requirements_jupyter_build.txt
python/setup.py

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6030, #5605, #5522   
API change in ipywidgets 8
to my code.
-   [ ] For fork PRs, I have …

Update jupyter web_visualizer for ipywidgets 8

---

.github/workflows/windows.yml
cpp/open3d/geometry/TriangleMesh.cpp
docs/tutorial/visualization/cpu_rendering.rst

Windows CI (CUDA, Debug) is failing due to "out of disk space". This bypasses this check and updates the docs, allowing devel Python wheels and C++ binaries to be available.
**Misc:**
- Style fix.
- CPU rendering tutorial (for Nvidia/ AMD drivers)
to my code.
-   [ ] I have …

Windows CI out of disk space workaround

---

cpp/pybind/data/dataset.cpp

I've met the same issues report in #6273, #5803, while building from source. 
After comparing the pybind.cp37-win_amd64.pyd in binary, I found that some symbols describing the directory structure in cpp/pybind/data/dataset.cpp may escape unproperly while building on windows in some cases.
to my code.
-   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** …

Fix python UnicodeDecodeError on windows

---

3rdparty/find_dependencies.cmake

msgpack 6.0 changed the cmake config. This PR adds that support.
to my code.
-   [x] For …

support msgpack 6.0

---

cpp/benchmarks/t/geometry/PointCloud.cpp
cpp/open3d/core/CMakeLists.txt
cpp/open3d/core/Tensor.cpp
cpp/open3d/core/Tensor.h
cpp/open3d/core/kernel/IndexReduction.cpp
cpp/open3d/core/kernel/IndexReduction.h
cpp/open3d/core/kernel/IndexReductionCPU.cpp
cpp/open3d/core/kernel/IndexReductionCUDA.cu
cpp/open3d/t/geometry/PointCloud.cpp
cpp/open3d/t/geometry/PointCloud.h
cpp/pybind/t/geometry/pointcloud.cpp
cpp/tests/core/Tensor.cpp
cpp/tests/t/geometry/PointCloud.cpp
python/test/t/geometry/test_pointcloud.py

This PR addresses #6172 #5519 and allows averaging properties in voxel downsample. Previously, points are simply put at grid corners.
To achieve this, the operation `IndexAdd_` (similar for [pytorch](https://pytorch.org/docs/stable/generated/torch.Tensor.index_add_.html)) for tensors is introduced.
An alternative would be reusing Benjamin's Voxel Pooling. We may revisit this later.
Now the behavior is the same as legacy, but there is a slight voxel coordinate offset due to implementation discrepancies. The legacy version computes a bound that slightly shifts the voxels.
<table>
<tr>
<td><img src="https://github.com/isl-org/Open3D/assets/6127282/deb7c895-477d-4b0e-9270-b294ad70c416" width="480"/></td>
<td><img src="https://github.com/isl-org/Open3D/assets/6127282/6a07ea2f-04b5-48b9-92f3-870 …

Voxel Downsample for Tensor interface

---

cpp/open3d/geometry/PointCloudSegmentation.cpp
cpp/tests/geometry/PointCloud.cpp

This PR fix issue #5647 and add a unit test for deterministic check of `SegmentPlane`. 
The reason why the function is non deterministic is that, the `RandomSampler` is not guarded by the mutex, which may result in the order of the sampled indices mismatch among multithreading workload.
to my code. …

Fix segment plane non deterministic issue 

---

CHANGELOG.md
cpp/open3d/geometry/TriangleMeshSimplification.cpp

to my code.
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.
The …

SimplifyQuadricDecimation fixes

---

cpp/open3d/data/Dataset.h
cpp/pybind/data/dataset.cpp
docs/conf.in.py
docs/contribute/contribution_recipes.rst
docs/cpp_project.rst
docs/getting_started.in.rst
docs/index.rst
docs/jupyter/t_pipelines/t_icp_registration.ipynb
docs/jupyter/visualization/visualization.ipynb
docs/make_docs.py
docs/tutorial/geometry/index.rst
docs/tutorial/geometry/uvmaps.rst
docs/tutorial/t_geometry/index.rst
docs/tutorial/t_pipelines/index.rst
docs/tutorial/t_reconstruction_system/index.rst

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes build warnings, missing docs, mostly cleanup.
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected) - The items order in documentation layout changes slightly. I will comment wherever these changes are made today. #
Reviewing documentation and required cleanup. This PR only address some of the issues. __Each issue is fixed in single commit, so should be easier to review commit-wise.__ More changes will follow along in a separate PR.
P.S. My end goal is to later on address issues like [architecture documentation request](https://github.com/isl-org/Open3D/discussions/6130), fix existing …

Improve documentation

---

cpp/open3d/utility/FileSystem.cpp

Fixes compilation error on Mac OS with clang 14.0+.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/Open3D/6320)

Fix compile error on Mac OS with latest Clang

---

cpp/open3d/geometry/VoxelGridFactory.cpp

Set all the relevant voxels, since a triangle can span across multiple ones
Currently, we break after the first voxel in the depth axis for some reason, but a single triangle can be relevant to multiple voxels.
Is there any option to release a version including this PR, since I really want to integrate this into a solution I'm building.
-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6324
The current voxel grid generated is wrong and contains only the first voxel in the depth axis.
to my code. …

Fix incomplete VoxelGrid creation from triangles intersecting multiple voxels

---

cpp/open3d/geometry/VoxelGrid.cpp
cpp/open3d/geometry/VoxelGrid.h
cpp/pybind/geometry/voxelgrid.cpp

I hope this update doesn't make any conflict with other features.
Regarding issues https://github.com/isl-org/Open3D/issues/2660, https://github.com/isl-org/Open3D/issues/1101, and https://github.com/isl-org/Open3D/issues/3133, there are needs for people to manually control voxels in VoxelGrid. Although it is already implemented in c++, there are no corresponding lines in pybind.
```import numpy as np
print('input')
N = 2000
armadillo = o3d.data.ArmadilloMesh()
mesh = o3d.io.read_triangle_mesh(armadillo.path)
pcd = mesh.sample_points_poisson_disk(N)
pcd.scale(1 / np.max(pcd.get_max_bound() - pcd.get_min_bound()),
center=pcd.get_center())
pcd.colors = o3d.utility.Vector3dVector(np.random.uniform(0, 1, size=(N, 3)))
print('voxelization')
voxel_grid = …
```

add add_voxel in pybind for VoxelGrid::AddVoxel

---

docs/getting_started.in.rst

The[ Getting Started](http://www.open3d.org/docs/release/getting_started.html) page currently has a list (supported Python versions) that is not rendered properly.
to my code.
results** (e.g. …

Fix rendering of Python versions table in docs

---

examples/python/io/realsense_io.py

-   [x] New feature (non-breaking change which adds functionality). Resolves #6335
Updated RealSense IO example to be more comprehensive and show point cloud video, either from recorded RGB-D frames or from a live camera.
to my code.
results** (e.g. screenshots or …

Display RGBD frames as a point cloud video

---

cpp/open3d/geometry/EstimateNormals.cpp
cpp/open3d/geometry/PointCloud.h
cpp/open3d/t/geometry/PointCloud.cpp
cpp/open3d/t/geometry/PointCloud.h
cpp/pybind/geometry/pointcloud.cpp
cpp/pybind/t/geometry/pointcloud.cpp

While exploring existing algorithms for creating meshes from point clouds, we came across Open3D. We noticed that one of the test point clouds we had available failed to reconstruct the mesh using the normal estimation method. We investigated and studied the library regarding the methods we used, and consequently identified some weaknesses in the algorithm.
Our work is documented in [this report](https://eugeniovaretti.github.io/meshreco/Piazza_Valentini_Varetti_MeshReconstructionFromPointCloud_2023.pdf).
Given an input point …

Normal orientation issues in complex geometries

---

cpp/open3d/geometry/PointCloud.cpp
cpp/open3d/geometry/PointCloud.h
cpp/pybind/geometry/pointcloud.cpp
cpp/tests/geometry/PointCloud.cpp

Tensor Pointcloud have the invert option in cropping but not the basic Pointcloud. Even though SelectbyIndex allows it.Needed it for a project and thought it was missing. The boolean is optional so this is minimal change.
to my code.
-   [x] I have added or updated C++ and / or …

Added optional invert parameter in Pointcloud cropping (similar to tensor pointcloud)

---

cpp/pybind/geometry/image.cpp

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6403
Cropped images (e.g. from OpenCV) provided to Open3D Image ctor are not supported. In tensor API, an error is thrown, while in Eigen API they are silently accepted with errorneous results. This PR raises an error in the Eigen API. See https://github.com/isl-org/Open3D/issues/6403 for a test script and details.
Thanks to @myalos for reporting and debugging. Also thanks to @saurabheights for help
to my code.
-   [ ] This PR changes Open3D …

Throw error on non-contiguous Python buffer provided to Image ctor.

---

examples/cpp/IntegrateRGBD.cpp

Compilation of Open3D failed for gcc-12 with:
```
examples/cpp/IntegrateRGBD.cpp:71:15: error: argument 1 null where non-null expected [-Werror=nonnull]
71 |         fclose(file);
```
Since `file` is already `NULL`, we shouldn't try to `fclose()` it.
-   [x] Bug fix (non-breaking change which fixes an issue)
to my code.
-   [x] For fork PRs, I have …

Fix IntegrateRGBD example compilation

---

CHANGELOG.md
cpp/open3d/core/CUDAUtils.cpp
cpp/open3d/core/CUDAUtils.h
cpp/open3d/core/MemoryManagerCUDA.cpp

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #4679
Some CUDA GPUs, like the Quadro M3000M don't support Memory Pools operations like `cudaMallocAsync`/`cudaFreeAsync` even on driver versions newer than 11020, and this can result in errors like:
```
CUDA runtime error: operation not supported
```
So check for support at runtime instead of compile time.
to my code.
-   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) …

Check for support of CUDA Memory Pools at runtime (#4679)

---

cpp/open3d/t/geometry/RaycastingScene.cpp
cpp/open3d/t/geometry/RaycastingScene.h
cpp/pybind/t/geometry/raycasting_scene.cpp
python/test/t/geometry/test_raycasting_scene.py
util/check_style.py

Add "ListIntersections" (C++) / "list_intersections" (python) function that returns a dictionary for all ray intersections present in a raycasting scene.
Flexibility in ray inclusion / exclusion.
to my code.
-   [x] I have added or updated C++ and / or Python **unit tests** OR …

List intersections

---

cpp/open3d/core/Dispatch.h
cpp/open3d/t/geometry/TriangleMesh.cpp
cpp/open3d/t/geometry/TriangleMesh.h
cpp/pybind/t/geometry/trianglemesh.cpp
cpp/tests/t/geometry/TriangleMesh.cpp
python/test/t/geometry/test_trianglemesh.py

The method uses tensor API. It takes a list of indices and returns a new mesh built with the selected vertices and triangles formed by these vertices.
The method is available with the `open3d::geometry::TriangleMesh` but not in `open3d::t::geometry::TriangleMesh`.
to my code.
-   [?] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is …

Implement open3d::t::geometry::TriangleMesh::SelectByIndex

---

README.md
cpp/open3d/t/geometry/TriangleMesh.h
docs/getting_started.in.rst

Add Open3D architecture diagram

---

docs/_static/css/furo_overrides.css

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6502 
See #6502 
to my code.
-   [x] For fork PRs, I have selected **Allow edits from …

Keep output of cell blocks in jupyter in scrollable area

---

docs/make_docs.py
util/ci_utils.sh

Speeds up building C++ documentation during development of C++ code.
Additionally, printing output path allows quick checking from local system. P.S. Will it be ok to print file uri instead of file path, i.e.
`file:///home/sk/workspace/open3d_prs/Open3D/docs/_out/html/index.html` instead of `/home/sk/workspace/open3d_prs/Open3D/docs/_out/html/index.html`. The former will be clickable on bash.
to my code.
-   [ ] This PR changes Open3D behavior …

Remove extra documentation build for python examples 

---

cpp/open3d/pipelines/registration/Feature.cpp
cpp/open3d/t/pipelines/registration/Feature.cpp

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6514
```
error: unused variable 'kInnerThreads' [-Werror,-Wunused-variable]
```
type of errors occur when building without OpenMP on macOS Sonoma.
to my code.
results** (e.g. screenshots or …

Fix unused variable error when OpenMP is disabled

---

CHANGELOG.md
cpp/pybind/visualization/rendering/rendering.cpp
docs/make.bat

Add optional args to set the NearClip and FarClip of the camera in the Offscreen Renderer.
Open3D Python doesn't currently expose a method for the `OffscreenRenderer` to convert depth units to absolute units, since all camera setting methods automatically normalize to the scene bounding box (without exposing those normalized values anywhere).  This simple PR optionally exposes those options to enable depth to be output in absolute units.
to my …

Expose Near Clip and Far Clip parameters to the Python Bindings

---

cpp/pybind/visualization/o3dvisualizer.cpp
cpp/pybind/visualization/rendering/material.cpp
cpp/pybind/visualization/visualizer.cpp

I was using the python visualization API, and I noticed that some of the keyword arguments in the python bindings show up as "arg0" "arg1" etc. This made it confusing, because I had to keep switching between the python API and the source code to see what the arguments really meant. This adds the missing argument names.
to my code.
-   [x] Both C++ (Doxygen) and Python (Sphinx / …

Add missing keyword arg names to visualization bindings

---

docs/tutorial/visualization/web_visualizer.rst
python/open3d/__init__.py

Add checking `DISABLE_OPEN3D_WEB_VISUALIZER` environment variable to disable automatically enabling web visualizer when in a Jupyter environment.
The problem is that when using the Jupyter extension in Visual Studio Code then the web visualizer does not function. This change allows to set an environment variable so that the web visualizer would not automatically be enabled.
to my code.
-   [x] This PR changes Open3D behavior or adds new …

Add env var to disable automatic WebVisualizer use in Jupyter environment

---

cpp/open3d/core/kernel/UnaryEWCPU.cpp

Fix the compile error.
UnaryEWCPU.cpp(100): error C4146: unary minus operator applied to unsigned type, result still unsigned
to my code.
-   [x] …

Fix for C4146 Error in CPUNegElementKernel with Unsigned Types

---

examples/python/visualization/tensorboard_pytorch.py
examples/python/visualization/tensorboard_tensorflow.py

Fix tensorboard examples with MonkeyModel path

---

cpp/open3d/geometry/PointCloudSegmentation.cpp

This change makes the results deterministic when a random seed is set.
to my code.
-   [ …

Make plane segmentation from point cloud deterministic

---

CHANGELOG.md
cpp/pybind/io/class_io.cpp
cpp/pybind/open3d_pybind.h
cpp/pybind/pybind_filesystem.h
cpp/pybind/t/io/class_io.cpp
cpp/pybind/t/io/sensor.cpp
cpp/pybind/visualization/renderoption.cpp
cpp/pybind/visualization/utility.cpp
cpp/pybind/visualization/visualizer.cpp
examples/python/visualization/mitsuba_material_estimation.py
python/test/io/test_pathlib.py

Adds support for `pathlib.Path`/`os.PathLike` type arguments to IO functions. E.g:
```python
from pathlib import Path
folder = Path('.')
mesh = o3d.io.read_triangle_mesh(folder / 'test.ply')
o3d.io. write_triangle_mesh(folder / 'test.ply', mesh)
```
is now supported in addition to `str`-type arguments.
-   [x] New feature (non-breaking change which adds functionality). Resolves #6344
Currently, only string-type filenames are supported in all IO functions. Python's `pathlib` is quite popular and should be supported. This commit adds support for all libraries which are compatible with …

Add Python pathlib support for file IO

---

cpp/pybind/geometry/voxelgrid.cpp

Fix typo
fix typo
to my code.
-   [x] For fork PRs, I have selected **Allow edits from …

fixed typo

---

cpp/open3d/t/geometry/TriangleMesh.cpp

Current behavior of `FromLegacy` on a legacy `TriangleMesh` with more than one material is to warn the user that Tensor-based meshes don't support multiple materials and not convert _any_ materials. Annoyingly, sometimes our importers (mostly ASSIMP) import or create dummy materials so converting those to Tensor-based `TriangleMesh` result in meshes with no materials. With this PR those cases will convert to a Tensor-based `TriangleMesh` with the first material converted as well. In most cases this should produce a mesh with a …

Update behavior of FromLegacy to make more flexible with materials

---

.github/workflows/ubuntu-cuda.yml
.github/workflows/ubuntu-openblas.yml
CMakeLists.txt

- Run paid CI on GCP for main, when review is requested and manually only to reduce Google Cloud CI costs.
- Change Open3D project email to open3d@intel.com

Reduce Google cloud CI costs, update Open3D project email

---

cpp/open3d/t/geometry/TriangleMesh.cpp
cpp/open3d/t/geometry/TriangleMesh.h
cpp/pybind/t/geometry/trianglemesh.cpp
cpp/tests/t/geometry/TriangleMesh.cpp
python/test/t/geometry/test_trianglemesh.py

The algorithm mimics the one in
geometry::TriangleMesh::RemoveUnreferencedVertices. We first build a mask of vertices and then update all vertex attributes by that mask. Triangles are left untouched.
Implement missing method t::geometry::TriangleMesh::RemoveUnreferencedVertices. The method is defined in the legacy API.
to my code.
-   [x] Both C++ (Doxygen) and Python (Sphinx / …

Implement t::geometry::TriangleMesh::RemoveUnreferencedVertices

---

cpp/open3d/geometry/PointCloudPlanarPatchDetection.cpp

fix #6550 
to my code.
-   [x] For fork PRs, I have selected **Allow edits from …

[Fix] threthold tolerance error (#6550)

---

cpp/open3d/core/nns/NNSIndex.h
cpp/open3d/core/nns/NanoFlannIndex.h
cpp/open3d/core/nns/NearestNeighborSearch.h

to my code.
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.
Fix …

Fix typos in NearestNeighborSearch.h

---

3rdparty/find_dependencies.cmake
3rdparty/googletest/googletest.cmake
3rdparty/imgui/imgui.cmake
3rdparty/qhull/qhull.cmake

Changed the CMake scripts for 3rdparty dependencies to not mark files in the Open3D git repo as generated. This is because the `clean` target would delete them and break the build.
-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6644
When running the clean target on some generators, source files not fetched by `ExternalProject` would be deleted. This would prevent rebuilding without using git to reset those files. See issue #6644 for details. 
-  [ ] I have run `python util/check_style.py --apply` to apply Open3D **code style**
to my code.
-   [ ] This PR changes Open3D behavior …

Switched QHull ImGUI and GoogleTest to use FetchContent

---

cpp/open3d/visualization/gui/PickPointsInteractor.cpp
cpp/open3d/visualization/visualizer/O3DVisualizer.cpp

Fixes and improvements:
- make points removable by correctly forwarding the key modifier to the already implemented function
- fix bounding box calculation for picked point size selection (manual bbox extend calculation was wrong)
- fix crash occurring when trying to make selection and non-pickable geometries where in scene
-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6725 
-   [ ] New feature (non-breaking change which adds functionality). 
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
See issue
to my code.
-   [ ] Both C++ (Doxygen) and Python (Sphinx / …

Fixes and improvements for point selection in O3DVisualizer (fixes #6725)

---

cpp/open3d/visualization/visualizer/VisualizerWithKeyCallback.cpp
cpp/open3d/visualization/visualizer/VisualizerWithKeyCallback.h
cpp/pybind/visualization/visualizer.cpp
examples/python/visualization/customized_visualization_key_action.py

Current Open3D Visualizer provides excellent 3D manipulation capabilities, but there are cases where developers may want to override its behavior. By introducing three additional callback functions for mouse events, developers will be able to handle mouse operations on their side only when necessary. 
The addition of mouse operations has also been discussed in some issues: #2610  #4286 
to my code.
-   [x] This PR changes Open3D behavior or adds …

Add Mouse Callback to VisualizerWithKeyCallback

---

cpp/open3d/core/CMakeLists.txt
cpp/open3d/core/Device.h
cpp/open3d/core/Tensor.cpp
cpp/open3d/core/kernel/UnaryEW.cpp
cpp/open3d/core/kernel/UnaryEW.h
cpp/open3d/core/kernel/UnaryEWSYCL.cpp
cpp/tests/core/Tensor.cpp
docker/Dockerfile.ci

Add a basic copy support for those tensor that needs to have their data in a SYCL device.
to my code.
-   [x] I will follow up and update the code …

Add SYCL copy support to tensor

---

CHANGELOG.md
cpp/open3d/pipelines/registration/Registration.cpp

The update of the iteration number is forced to be non-negative (was negative if corres_inlier_ratio = 0.0)
-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6709 
Issue [6709](https://github.com/isl-org/Open3D/issues/6709): RANSAC incorrectly exits early if `corres_inlier_ratio` is 0.0 during a RANSAC iteration.
to my code.
- …

Fix ransac update of the iteration number

---

.github/workflows/clean-gcloud-profiles.yml
.github/workflows/documentation.yml
.github/workflows/macos.yml
.github/workflows/style.yml
.github/workflows/ubuntu-cuda.yml
.github/workflows/ubuntu-openblas.yml
.github/workflows/ubuntu-sycl.yml
.github/workflows/ubuntu-wheel.yml
.github/workflows/ubuntu.yml
.github/workflows/vtk_packages.yml
.github/workflows/webrtc.yml
.github/workflows/windows.yml
SECURITY.md

```yaml
permissions:
contents: write   # to upload artifacts and update github release packages
actions: write     # to allow cancelling concurrent CI runs (concurrency key)
```

Add security policy, GITHUB_TOKEN access restrictions.

---

CHANGELOG.md
cpp/open3d/utility/ProgressBar.h
cpp/open3d/visualization/visualizer/VisualizerWithCustomAnimation.cpp

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6589
Fixing segmentation fault when running an animation (clicking CTRL+P) with `draw_geometries_with_custom_animation`.
to my code.
-   [x] I have added or updated C++ and / or Python **unit tests** OR included **test
-   [x] I will …

Fix segfault (lambda reference capture) of VisualizerWithCustomAnimation::Play

---

cpp/open3d/t/geometry/TriangleMesh.cpp
cpp/open3d/t/geometry/TriangleMesh.h
cpp/pybind/t/geometry/trianglemesh.cpp
cpp/tests/t/geometry/TriangleMesh.cpp
python/test/t/geometry/test_trianglemesh.py

Implement a few methods which are available with the geometry::TriangleMesh API.
to my code.
-   [x] I have added or updated C++ and / or Python **unit tests** OR included **test
-   [x] I will follow up and update the code if CI …

Implement ComputeTriangleAreas, GetNonManifoldEdges and RemoveNonManifoldEdges in t::geometry::TriangleMesh

---

3rdparty/find_dependencies.cmake

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes compilation on ubuntu 24
libc++-dev is at 18.0-59~exp2 with latest Ubuntu 24
to my code.
- …

cmake: add llvm version deps for c++

---

cpp/tests/test_utility/Raw.h

-   [X] Bug fix (non-breaking change which fixes an issue): Fixes #
to my code.
Add …

add cstdint header to fix missing uint8_t type on ubuntu 24.04

---

cpp/open3d/geometry/TriangleMesh.cpp

Fixes #6848 which describes a bug if computing vertex normals that are already initialized.
to my code.
-   [ ] I will follow up and update the …

add missing initialization for compute_vertex_normals()

---

3rdparty/pybind11/pybind11.cmake

Pybind11 2.12 added numpy 2 support. We update to the latest 2.13.1.
Other dependent packages (e.g. tensorboard) also need update, so keeping the numpy<2 in requirements.txt for now.
-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6845, #6856, #6839, #6840
to my code.
-   [ ] I have added or updated C++ and / or Python **unit …

Support numpy v2.

---

docs/getting_started.in.rst

Release of `numpy==2.0.0` causes many Open3D features to segfault, which I saw will be fixed with the `pybind` update in #6874 .
Due to only requiring `numpy>=1.18.0` in the `Open3D<=0.18.0` releases, new Open3D installs will also install `numpy==2.0.0`, and thus break a large part of the functionality.
I think it's important to communicate this to users, although I'm unsure if this is the right place and way to do so, especially since this documentation will also only update for the next release of Open3D.
I hope this feedback is helpful, thank you!
Add warning about `numpy` versions  to the "Getting Started" documentation.

add numpy version warning to documentation

---

CHANGELOG.md
cpp/open3d/visualization/gui/Layout.cpp
cpp/open3d/visualization/gui/Layout.h
cpp/open3d/visualization/visualizer/O3DVisualizer.cpp
cpp/open3d/visualization/visualizer/O3DVisualizer.h
cpp/pybind/visualization/gui/gui.cpp
cpp/pybind/visualization/o3dvisualizer.cpp

Add API SetCollapsableVertOpen to control the toggling of the verts in the side panel
When we have start the viewer with side panel ("show settings"), the default toggle vert (pane) in the side panel defaults to ON for the "Mouse Controls" and "Scene", but no "Lighting". These default on panels took a lot of space and I find myself always collapsing the settings since I mostly want to control the visibility of objects in "Geometries". This becomes quite annoying very soon.
-   [x] I have run `python util/check_style.py --apply` to …

Add O3DVisualizer API to enable collapse control of verts in the side panel

---

cpp/open3d/visualization/rendering/filament/FilamentScene.cpp

There was a typo, `UpdateGeometry` called `GetPointPositions` instead of `GetPointColors` for the color data when updating the colors of a pointcloud in a gpu.
to my code.
results** (e.g. …

Fix color update in gpu

---

CHANGELOG.md
cpp/open3d/geometry/MeshBase.cpp
cpp/tests/geometry/TetraMesh.cpp
cpp/tests/geometry/TriangleMesh.cpp

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6866
Fixing the [`MeshBase::GetMinimalOrientedBoundingBox`](https://github.com/isl-org/Open3D/blob/v0.18.0/cpp/open3d/geometry/MeshBase.cpp#L53-L55) method, which did not return the minimal oriented bounding box. Also adding new unit tests for the derived classes `TriangleMesh` and `TetraMesh` for the different bounding box generation algorithms, since they were not covered.
to my code.
-   [x] This PR changes Open3D behavior or adds new …

Fix minimal oriented bounding box of MeshBase derived classes and add new unit tests

---

3rdparty/embree/embree.cmake
cpp/open3d/t/geometry/RaycastingScene.cpp

This pull request fixes the following build error:
```
Open3D/cpp/open3d/t/geometry/RaycastingScene.cpp:1184:9: error: enumeration value ‘RTC_ERROR_LEVEL_ZERO_RAYTRACING_SUPPORT_MISSING’ not handled in switch [-Werror=switch]
1184 |         switch (c) {
|         ^~~~~~
cc1plus: all warnings being treated as errors
```

upgrade embree to v4.3.3 and fix fmt formatter for RTCError

---

CHANGELOG.md
cpp/open3d/geometry/TriangleMesh.cpp

Adds color to point cloud sampled from mesh
(https://github.com/isl-org/Open3D/issues/2483)
-   [x ] New feature (non-breaking change which adds functionality). Resolves #2483
to my code.
-   [x] I have added or updated C++ and / or Python **unit tests** OR included **test
-   [x] I will follow up and update …

Add color for sampling from mesh 

---

CHANGELOG.md
cpp/open3d/io/file_format/FilePCD.cpp
cpp/open3d/t/io/file_format/FilePCD.cpp

-   [x] New feature (non-breaking change which adds functionality). Resolves #6925 
Other libraries, like PCL, support both lowercase types (`i`, `u`, `f`) and their uppercase "official" counterpart (`I`, `U`, `F`) when loading PCD files. Currently, Open3D raises an error for lowercase types when using `open3d.t.io`, or loads a 0.0 value when using `open3d.io`, without any warning/error.
to my code.
-   [ ] Both C++ (Doxygen) and Python (Sphinx / Google …

Support lowercase types (i, u, f) when reading PCD files

---

.github/workflows/macos.yml

Updated delocate-fuse to delocate-merge (got removed in delocate>=0.12.0).
The following error occurs in the [Fuse universal2 wheel (3.11, false)](https://github.com/isl-org/Open3D/actions/runs/10644695980/job/29510365691?pr=6896) CI workflow:
```bash
'delocate-fuse' is no longer available.
To fuse two wheels together use 'delocate-merge'.
NOTE: 'delocate-merge' does not overwrite the first wheel.
It creates a new wheel with an automatically determined name.
If the old behavior is needed (not recommended), pin the version to …
```

Updated delocate-fuse to delocate-merge.

---

cpp/pybind/geometry/boundingvolume.cpp
cpp/pybind/t/geometry/boundingvolume.cpp

This PR exposes the minimal volume bounding box function to the python API.
-   [X] New feature (non-breaking change which adds functionality). Resolves #
Only the static function `create_from_points` is currently exposed to the Python API.
However, in the CPP API, another option exists which is to create a bounding box with a minimal volume that is not exposed.
-   [X] I have run `python util/check_style.py --apply` to apply Open3D **code style**
to my code.
-   [X] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is …

Expose minimal oriented bounding box to python api

---

cpp/open3d/io/TriangleMeshIO.h
cpp/open3d/io/file_format/FileASSIMP.cpp
cpp/open3d/t/io/file_format/FileASSIMP.cpp

While reading glb files with bone transforms (especially scaling) and a single mesh, the transform is ignored if post_process is not enabled. This can cause reading a mesh with incorrect scale factor. 
e.g.: 03d693e178e54766af2905e90cbc1f03.glb file from Objaverse
to my code.
- …

Always pre-transform vertices while reading with Assimp.

---

cpp/open3d/t/geometry/RaycastingScene.cpp
cpp/open3d/utility/IJsonConvertible.h
cpp/open3d/visualization/rendering/RendererHandle.h

`fmt v11` requires that `format` function of user-defined formatter should be `const`.

fix build with fmt-v11

---

CHANGELOG.md
examples/python/visualization/draw.py

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6887 
A minor issue, but the ICP example in `examples/python/visualization/draw.py` requires the user to select point correspondences for a preliminary rough transformation before ICP registration, but users may not be aware of this. Currently, if no point correspondences are selected, the application crashes with an IndexError.
to my code.
-   [ ] Both C++ (Doxygen) and Python …

fix visualization/draw ICP example and add warnings

---

3rdparty/find_dependencies.cmake
cpp/open3d/core/nns/NanoFlannImpl.h
cpp/pybind/CMakeLists.txt
cpp/tests/t/geometry/TensorMap.cpp
docker/Dockerfile.ci
docker/docker_test.sh
python/open3d/__init__.py
util/install_deps_ubuntu.sh

CUDA jammy CI (python tests) fail since pytest causes the conda libstdc++ library to be loaded instead of the system libstdc++ library. This is older and prevents Open3D cuda pybind lib from loading.
to my code.
-   [ ] I have added or updated C++ and / or Python **unit tests** …

Replace conda with pyenv to fix incorrect libstdc++ use in jammy CI.

---

cpp/pybind/t/geometry/boundingvolume.cpp
docs/make_docs.py
docs/requirements.txt

Jinja2 CVE: https://github.com/isl-org/Open3D/security/dependabot/6
to my code.
-   [ ] …

jinja2 CVE fix

---

cpp/open3d/core/kernel/ReductionCPU.cpp

This pull request aims to speed up Reductions and ArgReductions with single outputs on the CPU.
For Reductions (e.g. sum), the problem of the current code is the access of multiple threads to a shared array in each loop iteration, which can be fixed using a single local variable.
Argreductions for single outputs (e.g. points.argmax()) run with the current code on a single CPU core, although the operation can be sped up in the same way as the reduction.
This PR fixes both problems and has a 400% speedup for these reductions (4x …

Faster CPU (Arg-)Reductions

---

cpp/open3d/t/geometry/PointCloud.cpp

This PR adds a FarthestPointDownSample implementation for tensor-based point clouds. This enables GPU-acceleration for a performance increase of up to 8x. Before, point clouds were copied to the legacy format and then being downsampled on the CPU before being copied back.
FarthestPointDownSample is an important downsampling method, however it's performance render this implementation inapplicable for certain scenarios. This PR is trying to increase the performance
-   [x] I have run `python util/check_style.py --apply` to apply …

Add Tensor-based implementation of FarthestPointDownSample

---

CHANGELOG.md
cpp/open3d/geometry/SurfaceReconstructionAlphaShape.cpp

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6086 
Surface reconstruction with alpha shapes by calling `create_from_point_cloud_alpha_shape` fails if the alpha value is too small for the internal constraint to become true.
https://github.com/isl-org/Open3D/blob/db00e339c1645440dea6951c2971ffa759934112/cpp/open3d/geometry/SurfaceReconstructionAlphaShape.cpp#L105-L110
There is currently no check if the reconstructed mesh is empty, thus the following call to 
https://github.com/isl-org/Open3D/blob/db00e339c1645440dea6951c2971ffa759934112/cpp/open3d/geometry/SurfaceReconstructionA …

fix alpha shape reconstruction if alpha too small for point scale

---

CHANGELOG.md
cpp/open3d/visualization/rendering/filament/FilamentRenderToBuffer.cpp

-   [X] Bug fix (non-breaking change which fixes an issue): Fixes #6999 , #6270 , (probably also fixes #4978 , #5980 )
Many users have encountered the issue that an active high resolution Retina display, e.g. an open MacBook screen, causes`render_to_depth_image` to only save the lower left quarter of the depth image.
This also happens if an external monitor is connected. The only workaround is to close the MacBook display, i.e. not having an active retina display, and having an external monitor as the primary monitor.
Example:
Here is a small example to recreate the issue (credit to …

fix render to depth image on Apple Retina displays

---

CHANGELOG.md
cpp/open3d/t/geometry/kernel/PointCloudImpl.h

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6967 
Very short PR. In the tensor module, [EstimatePointWiseNormalsWithFastEigen3x3](https://github.com/isl-org/Open3D/blob/v0.18.0/cpp/open3d/t/geometry/kernel/PointCloudImpl.h#L839) has a small bug in computing the normal when the covariance norm is 0, setting a normal to `(0,0,1)` instead of the correct `(0,1,0)` value.
to my code.
-   [ ] Both C++ (Doxygen) and Python (Sphinx …

Fix tensor EstimatePointWiseNormalsWithFastEigen3x3

---

CHANGELOG.md
cpp/open3d/geometry/PointCloudSegmentation.cpp

-   [X] Bug fix (non-breaking change which fixes an issue): Fixes #
Just a small fix, but if the number of points in the pointcloud is smaller than `ransac_n`, `segment_plane` is caught in an infinite loop and does not terminate.
It's a bit of an unlikely scenario, but I did stumble across it because I was fitting planes on clustering results, and one of those point clusters only had two points.
The reason for the infinite loop is because `RandomSampler` is called with `num_points`
https://github.com/isl-org/Open3D/blob/fcc396e494dd3f1204e53571f37400cac50976ef/cpp/open3d/geometry/PointCloudSegmenta …

fix infinite loop in segment_plane if num_points < ransac_n

---

cpp/open3d/geometry/PointCloud.cpp
cpp/open3d/geometry/PointCloud.h
cpp/open3d/t/geometry/PointCloud.cpp
cpp/open3d/t/geometry/PointCloud.h
cpp/pybind/geometry/pointcloud.cpp
cpp/pybind/t/geometry/pointcloud.cpp
cpp/tests/geometry/PointCloud.cpp
cpp/tests/t/geometry/PointCloud.cpp

Closes #7049.
The function `PointCloud::FarthestPointDownSample()` is overloaded to accept a `start_index` in addition to the existing `num_samples`.
See ticket linked above.
to my code.
-   [x] I have added or updated C++ and / or Python **unit tests** OR included **test …

FarthestPointDownSample: arg to specify start index to start downsampling from

---

cpp/pybind/camera/camera.cpp
cpp/pybind/core/dtype.cpp
cpp/pybind/core/tensor.cpp
cpp/pybind/docstring.cpp
cpp/pybind/geometry/geometry.cpp
cpp/pybind/geometry/kdtreeflann.cpp
cpp/pybind/geometry/trianglemesh.cpp
cpp/pybind/pipelines/odometry/odometry.cpp
cpp/pybind/pipelines/registration/feature.cpp
cpp/pybind/pipelines/registration/registration.cpp
cpp/pybind/t/geometry/image.cpp
cpp/pybind/t/geometry/lineset.cpp
cpp/pybind/t/geometry/pointcloud.cpp
cpp/pybind/t/pipelines/odometry/odometry.cpp
cpp/pybind/t/pipelines/registration/robust_kernel.cpp
cpp/pybind/t/pipelines/slac/slac.cpp
cpp/pybind/t/pipelines/slam/slam.cpp
cpp/pybind/visualization/gui/gui.cpp
cpp/pybind/visualization/rendering/rendering.cpp

This pull request is a follow up for/based on #6869 and contains more fixes for documentation and typing generation.
Related issues are #3052 and #6867.
to my code.
results** (e.g. screenshots …

Fixes for pybind11-stubgen errors

---

.github/workflows/macos.yml
.github/workflows/ubuntu-cuda.yml
CMakeLists.txt
cpp/open3d/CMakeLists.txt
cpp/open3d/core/CMakeLists.txt
cpp/open3d/core/SYCLContext.cpp
cpp/open3d/core/SYCLUtils.cpp
cpp/open3d/geometry/SurfaceReconstructionBallPivoting.cpp
cpp/open3d/geometry/SurfaceReconstructionPoisson.cpp
cpp/open3d/visualization/CMakeLists.txt
cpp/pybind/core/sycl_utils.cpp
cpp/tests/core/CoreTest.cpp
docker/Dockerfile.ci
docker/Dockerfile.wheel
docker/docker_build.sh
python/test/open3d_test.py
python/test/t/geometry/test_raycasting_scene.py
util/ci_utils.sh

CI errors.
to my code.
-   [ ] For fork PRs, I have selected **Allow edits from …

Fix CI tests - macOS, Ubuntu, SYCL

---

cpp/open3d/visualization/utility/DrawGeometry.cpp
cpp/pybind/visualization/utility.cpp

Currently, `o3d.visualization.draw_geometries` uses overloading to provide default values for `lookat`, `up`, `front`, and `zoom`. 
This causes two problems:
* It defines a function with default arguments before non-default arguments (forbidden by [The Python Language Reference](https://docs.python.org/3/reference/compound_stmts.html#function-definitions))
* It clutters the documentation with redundancy (see [docs/0.18.0/python_api/open3d.visualization.draw_geometries](https://www.open3d.org/docs/0.18.0/python_api/open3d.visualizat …

Changed draw_geometries to use default args instead of overload

---

CHANGELOG.md
cpp/open3d/visualization/rendering/filament/FilamentView.cpp

If that function doesn't copy the sample count, the copied view will not be an exact copy - it'll contain the default sample count (=4), and not the sample count of the view it's copying from.
-   [x] Bug fix (non-breaking change which fixes an issue): Fixes - separate issue not created, just see above problem & fix
See above.
to my code.
-   [x] …

Copy SampleCount when making a copy of FilamentView

---

cpp/pybind/docstring.cpp
docs/conf.py

Open3D uses namespaces `open3d.cpu.pybind.` and `open3d.cuda.pybind.` to differentiate between both device builds.
This adds a lot of clutter to the documentation (see screenshots below).
There is already a partial fix for functions documented using `docstring::ClassMethodDocInject` and `docstring::FunctionDocInject`.
However, a big part of Open3D does not use those functions for documentation and #7081 removed those from the contribute docs (so they should probably be avoided in the future).
-   [x] I have run `python …

Changed namespace fix to use Sphinx autodoc-process-* events

---

cpp/tests/t/pipelines/registration/Registration.cpp

increase voxel size to improve ICP test reliability

---

.github/workflows/documentation.yml
.github/workflows/style.yml
.github/workflows/windows.yml
docker/Dockerfile.wheel
python/pyproject.toml
util/ci_utils.sh

Documentation CI is failing due to missing dependency for cmake.
The issue is that the dependency install script assumes Ubuntu 20.04 (Focal) is used and tries to install CMake from the Kitware APT Repository for Focal.
The github runner uses `ubuntu-latest` thought, which is currently ~~Ubuntu 22.04 (Jammy)~~ (actually just changed to 24.04 which produces more issues).
(See edit at bottom for a description of the general CI cleanups)
to my …

Fix Documentation CI + General CI Cleanup

---

.github/workflows/windows.yml

maturin>1.7.8 breaks dependency y-py (Python 3.12) and pywinpty (Python 3.8) wheel building
https://github.com/MichaIng/DietPi/issues/7329#issuecomment-2565130837
to my code.
results** (e.g. …

Pin maturin to 1.7.8 to fix Windows CI for Python 3.8, 3.12

---

CHANGELOG.md
python/open3d/__init__.py

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #7104 
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected) -> see below for description
[This PR](https://github.com/isl-org/Open3D/pull/5259) introduced `winmode=0` for loading DLLs during import. This however leads to directories added via `os.add_dll_directory` not being considered, when loading DLLs (see [here](https://github.com/isl-org/Open3D/issues/7104#issuecomment-2556557535) or [here](https://stackoverflow.com/questions/59330863/cant-import-dll-module-in-python/59333711#59333711)). In particular this leads to `open3d/tbb12.dll` not being found.
Fix this by going back to the default …

Fix packaged dlls not found

---

cpp/open3d/utility/Random.h

Fix the UniformIntGenerator  output range error. According to the function description, the output range should be [low, high), but the actual output range is [low, high].
refer to: [uniform_int_distribution](https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution)
Fix the UniformIntGenerator  output range error.
to my code.
-   [ ] Both C++ (Doxygen) and Python …

Fix: UniformIntGenerator range error

---

docs/jupyter/core/tensor.ipynb

In Copy & device transfer
#Device -> another Device.
a_gpu_0 = o3c.Tensor([0, 1, 2], device=o3c.Device("CUDA:0")) a_gpu_1 = a_gpu_0.cuda(0)
print(a_gpu_1)
here a_gpu_0.cuda(0) should be a_gpu_0.cuda(1) to match the variable
to my code.
-   [ ] I have added or updated C++ and / …

fixed a typo in doc tensor.ipynb

---

cpp/pybind/t/geometry/trianglemesh.cpp

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #7135
to my code. …

Fix for #7135 (error with named argument "width")

---

cpp/open3d/core/Device.cpp
cpp/pybind/core/device.cpp
cpp/pybind/geometry/voxelgrid.cpp
cpp/pybind/t/geometry/trianglemesh.cpp

-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #7147
Devices in default values cause corrupted rendering in the documentation as shown in #7147.
The reason is that `o3d.core.Device.__repr__` returns a string like this: `CPU:0`.
Sphinx docs generation seems to misinterpret `:` in default values.
Also, I found a similar problem with the enum VoxelPoolingMode.
The raw enum value also contains a `:` and causes faulty documentation.
I found a similar issue here: sphinx-doc/sphinx#9266
to my code.
- …

Fixed corrupted default values in documentation

---

docs/jupyter/pipelines/icp_registration.ipynb

Fixes discrepancy betweeen:
https://www.open3d.org/docs/latest/tutorial/Basic/icp_registration.html
and 
https://github.com/isl-org/Open3D/blob/main/cpp/open3d/pipelines/registration/Registration.cpp#L65
This commit updates the documentation to align with the implementation details.
to my code. …

Fix ICP registration pipeline documentation

---

cpp/open3d/io/file_format/FilePLY.cpp

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #5994
It seems that `open3d.io.read_point_cloud` assumes that the color properties end with the blue channel:
> https://github.com/isl-org/Open3D/blob/c6d474b3fa0b47adbcff51219f5928855c3bb806/cpp/open3d/io/file_format/FilePLY.cpp#L88-L90
If a PLY [file](https://drive.google.com/file/d/1OuFkeUZotm34VkbQvb0sb_wYE9pCnby_/view?usp=share_link) defines colors in other orders, e.g., GBR, the `color_index` is incorrectly incremented after reading the blue channel, causing all red values to be placed at the wrong positions.
However, …

Fix the reading error when PLY files use non-RGB color orders.

---

cpp/open3d/visualization/gui/CMakeLists.txt
cpp/open3d/visualization/gui/Materials/gaussianSplat.mat
cpp/open3d/visualization/shader/glsl/ShCoeffsToColorFast.glsl

add gaussianSplat mat file for shader

---

CHANGELOG.md
cpp/benchmarks/t/pipelines/registration/Feature.cpp
cpp/open3d/pipelines/registration/Feature.cpp
cpp/open3d/pipelines/registration/Feature.h
cpp/open3d/t/pipelines/kernel/Feature.cpp
cpp/open3d/t/pipelines/kernel/Feature.h
cpp/open3d/t/pipelines/kernel/FeatureImpl.h
cpp/open3d/t/pipelines/registration/Feature.cpp
cpp/open3d/t/pipelines/registration/Feature.h
cpp/pybind/pipelines/registration/feature.cpp
cpp/pybind/t/pipelines/registration/feature.cpp
cpp/tests/t/pipelines/registration/Feature.cpp

-   [x] New feature (non-breaking change which adds functionality). Resolves #7089
Allows optional selection of specific points when computing FPFH features for a point cloud. Previously, if you only needed FPFH features from a small subset of points (e.g., ISS keypoints), you had to compute the features for the entire point cloud (which was slow and unnecessary) and then select the relevant features. Now, you can directly compute the FPFH features for just the selected points, resulting in faster performance.
Unrelated, also fixed a bug in #7039 when calling SelectByIndex with `invert=true`.
-   [x] I have …

Add optional indices arg for fast computation of a small subset of FPFH features

---

3rdparty/ipp/ipp.cmake

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #7152
`cmake -E copy_directory` copies the directory unconditionally without keeping timestamp. Then make thinks that libippc*_tl_tbb.a is updated and needs relinking libOpen3D.so.
In this MR we will use `rsync -rut` to avoid unnecessary updating.
to my code.
-   [ ] I have added …

Use cp -rp to copy tbb libs to avoid relinking every time running make

---

docs/jupyter/visualization/3d_gaussian_splatting.ipynb
examples/cpp/CMakeLists.txt
examples/cpp/GaussianSplat.cpp

add gaussianSplat application

---

cpp/open3d/t/geometry/kernel/MinimumOBB.cpp

Fix failing test OrientedBoundingBox/OrientedBoundingBoxPermuteDevices.CreateFromPoints
to my code.
-   [ ] I will follow up and update the code …

Return OBB on same device as input points

---

cpp/open3d/visualization/gui/NativeLinux.cpp
cpp/open3d/visualization/visualizer/VisualizerRender.cpp

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #7162
On Wayland, Open3D still calls X11 specific functions and dereferences NULL pointers. See #7162. This PR fixes this by checking the platform (X11 / Wayland) via `glfwGetPlatform()` and avoid using X11 specific functions.
to my code.
-   [ ] I have added or updated C++ and / …

fix X11 access on wayland

---

CHANGELOG.md
python/open3d/visualization/__init__.py
python/open3d/visualization/draw_plotly.py

-   [X] New feature (non-breaking change which adds functionality).
When trying to use `draw_plotly` in Colab, it's impossible to modify things like the aspect ratio, and other aspects of the layout, since they aren't parameters to `draw_plotly`. It's also not possible to modify them *before* it is shown.
-   [X] I have run `python util/check_style.py --apply` to apply Open3D **code style**
to my code.
-   [X] This PR changes Open3D behavior or adds new functionality.
-   [X] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
-   [] I have added or updated C++ and / or Python **unit tests** OR included **test
-   [X] I will follow up and update the code if CI fails.
-   [X] For fork PRs, I have …

Expose the `get_plotly_fig` function, return fig from `draw_plotly` and `draw_plotly_server`

---

CHANGELOG.md
cpp/open3d/core/Tensor.h
cpp/open3d/ml/contrib/Cloud.cpp
cpp/tests/core/TensorObject.cpp

Replace usage of `std::is_pod` with `std::is_standard_layout && std::is_trivial`.
-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #5405
std::is_pod` is deprecated in C++20, hence this replacement is necessary to make usage of open3d possible when client code is compiled with C++20.
Fixes part of https://github.com/isl-org/Open3D/issues/5405
to my code.
-   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) …

Replace usage of `std::is_pod` with `std::is_standard_layout && std::is_trivial`.
